### ISSUE TITLE
Incorporate RBF-NEAT and Cascade-NEAT mutations

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#100]
As described in this paper: http://nn.cs.utexas.edu/downloads/papers/kohl.gdns09.pdf

**Comment by evolvingfridge** [comment]
I might be wrong here, but it will be very interesting adding SNAP-NEAT described in [dissertation](http://nn.cs.utexas.edu/?kohl:phd09).
Is Adaptive Pursuit algorithm implemented in MM-NEAT ?

**Comment by schrum2** [comment]
None of it is currently. RBF-NEAT and Cascade-NEAT are the building blocks of SNAP-NEAT, so they are a logical intermediate step.

**Comment by schrum2** [comment]
Will not pursue.
