### ISSUE TITLE
SparCraft

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#108]
Using the resources from this site:
http://www.starcraftai.com/wiki/Main_Page
Try getting a running example of SparCraft in action, both in pure C++ and using Java.

Eventually, once #95 is complete and we can run StarCraft from Java, we should also get SparCraft from Java working.

**Comment by Squillyprice01** [comment]
This seems to be the place to go for information on SparCraft:
https://code.google.com/archive/p/sparcraft/

This URL contains a zip of a standalone executable SparCraft file:
https://code.google.com/archive/p/sparcraft/downloads

I have to note that, while SparCraft is the best combat simulator available, it has some large limitations. For one, there are no collisions. This is intentional, but the example battle given in the above download plays out very differently than it would with collisions (I say as a intermediate StarCraft Player).

**Comment by schrum2** [comment]
Ideally we can make a full StarCraft bot for the competition, but there could be an interesting research paper in SparCraft alone ... or we could at least evolve combat behavior in SparCraft and then deploy in a full bot.

Because of this, I want you to make a SparCraftTask in MM-NEAT so we can evolve in it. This will require incorporating the Java code into MM-NEAT. This will be a complicated issue requiring a lot of work. You should create a new dev_starcraft branch before starting on it. We can put our heads together so I can show you how to get started.

**Comment by schrum2** [comment]
Try to make your own simplistic agent for SparCraft in either C++ or Java, whatever works (can you use an existing BWAPI bot? This seems necessary ... otherwise, what is the use?)

If you try a C++ bot first, then move on to a Java bot. Once you have a standalone Java bot that can play SparCraft, incorporate that bot into the MM-NEAT code and close the issue.

**Comment by Squillyprice01** [comment]
At this point, I can build and run C++ bots on my machine (Admin rights are an absolute requirement). I can get JNIBWAPI (java BWAPI wrapper) to interface with an older version of BWAPI (v. 3.7.4 or something similar, the current version is 4.2.0). The built in bot doesn't work as intended, but it runs. I cannot get JNIBWAPI to interface with the new version of BWAPI and I don't think it will be possible.  The Java version of SparCraft has zero (and I mean zero ) useful documentation and I do not believe that we will get it to work. All said, I don't believe that we will be able to develop this stuff in Java. Relevant in #95

**Comment by schrum2** [comment]
Since this issue is going nowhere, I'm closing it. Working with StarCraft in Java simply seems like more trouble than its worth.
