### ISSUE TITLE
UT2004 server batch files should allow GBDebugging options

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#118]
Need to enable the GBHUDMutator in the server launch batch files so we can see the nav mesh and other convenient troubleshooting tools

**Comment by schrum2** [comment]
I wasn't able to figure this issue out, but since you now have issue #131 you should keep this one in mind too. I suspect they might be related.

**Comment by friedmaa** [comment]
looking at the GameBots2004.ini file as a possibility

**Comment by schrum2** [comment]
This does seem to depend on which version of GameBots we are using, so I'm closing this issue.
