### ISSUE TITLE
Have the dimensions of convolutionally connected layers depend on the dimensions of the receptive field

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#122]
This is in contrast to hardcoding the dimensions of each layer. A varying size of the receptive field could be implemented per layer connection.

**Comment by schrum2** [comment]
Why was this closed? Was any work done, or did you simply decide not to do it. Don't close issues without explaining what happened. In general, just because you no longer plan to do something doesn't mean you close the issue ... perhaps someone else will in the future.

**Comment by DevonFulcher** [comment]
We are going in a different direction with network architecture and this would probably make implementation less general not more general.
