### ISSUE TITLE
Test UT^2 bot

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#125]
Although the UT^2 bot now runs in MM-NEAT, I had to change a bit of code to make it work. This issue involves interacting with the version of the bot in MM-NEAT to test that it works properly. You can launch the bot by running edu.utexas.cs.nn.UT2. 

This class could also use some commenting, though making sense of it might be difficult ... ask me questions, but don't comment anything you feel uncomfortable commenting on.

One important thing you should experiment with:
Search for the final constant UNSTUCK in the code. Around this constant you will see several other constants like OBSERVE, BATTLE, and PATH. These options let you activate and deactivate various modules of the agent. They are described in Figure 1 of this paper: http://nn.cs.utexas.edu/?schrum:botprize2011

See what happens when you turn certain modules on and off.

@friedmaa Don't start on this issue until next week. In fact, I think that this is something that Joe can help you with when he joins us.

**Comment by friedmaa** [comment]
see notes in google doc
