### ISSUE TITLE
Fully Test MirrorBot

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#130]
Now that MirrorBot is in the code, I want you to test it out too. Specifically, compare the version of MirrorBot launched from the jar file to the one in our code. See if you can spot any problematic differences. We don't want our version to have any problems that weren't present in the original bot. This comparison will be a bit subjective, but take notes on anything that looks suspicious. Also, keep in mind that even the original bot will likely have some problems.

Any commenting you can do on the MirrorBot code while analyzing it could also be helpful, but don't feel too strong of an obligation here ... we want top preserve MirrorBot as is, and it's not entirely our job to understand it. However, we may want to steal bits of code here and there into new bots we make.

**Comment by friedmaa** [comment]
See notes on google doc
