### ISSUE TITLE
Applying Behavioral Diversity to Tetris

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#132]
Attempt to apply BD to Tetris using batch files. However, BD might not be general enough to be applied to Tetris in its current form, especially since HyperNEAT is involved. Make it work.

**Comment by schrum2** [comment]
batch\Pinball\Pinball-MOBDHard.bat shows an example of how to use BD

**Comment by schrum2** [comment]
By the way, if you just use BDNSGA2, then you will use the default behavior characterization. For Tetris, this is defined as the getBehaviorVector method in the org.rlcommunity.environments.tetris.Tetris class. However, this may not be the best characterization.

To use general behavior characterizations, you have to change the behaviorCharacterization parameter.
batch\Match\Match-Image-sunset1-BD.bat has an example using the GeneralNetworkCharacterization.

**Comment by DevonFulcher** [comment]
Seems to be working fine with those specifications: batch\RLGlue-Tetris-Experiments\testRLGlue-Tetris-PlainFeaturesBehavioralDiversity.bat

**Comment by DevonFulcher** [comment]
Coding implementation is done. Testing here #157
