### ISSUE TITLE
Fix smallerGenotypes setting in TWEANNGenotype

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#137]
You may recall that in HybrIDUtil there is a commented out line referring to TWEANNGenotype.smallerGenotypes. The line was commented out because it was causing errors. This setting is meant to create genotype representations that do not store superfluous information, which is very important after the HybrID switch, because you end up storing a population full of large substrate networks instead of the population of comparatively small CPPNs. So, fixing TWEANNGenotype.smallerGenotypes would be useful.

When TWEANNGenotype.smallerGenotypes is on, then TWEANNGenotypes consist of LinkGene and NodeGene classes instead of FullLinkGene and FullNodeGene (both inner classes of TWEANNGenotype). I think that FullLinkGene is fine (even if you change it for issue #70 ). However, the node genes are a problem. The bias field in FullNodeGene actually needs to be moved to regular NodeGene, along with the associated methods.

And this is why we have unit tests. Try the following: Uncomment the line in HybrIDUtil about smallerGenotypes first, and run the unit test you made for HybrID. It will almost certainly fail (if not, then we need to talk). However, if you move where the bias field lives, then the unit test should pass again (once again, if not, we will need to talk).

**Comment by schrum2** [comment]
This is hopefully an easy issue to resolve. If all of the steps I lay out work as expected, then you can close it fairly quickly, so please look to this one soon.

**Comment by DevonFulcher** [comment]
Even when smallerGenotypes is false, the substrate networks all have bias values of 0 in their neurons, which is incorrect. The bias values should be set by the CPPN, so it makes no sense for all of them to be 0.

**Comment by schrum2** [comment]
This is fixed now, right?

**Comment by DevonFulcher** [comment]
Yes. Killed 2 birds with one stone.
