### ISSUE TITLE
PO PacMan InputOutput mediator

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#142]
After all of the errors from PO pacman sensors are fixed by assigning reasonable default values, make a new input-output mediator in a new package: edu.southwestern.tasks.mspacman.sensors.mediators.po

You can think of the new mediator as a PO version of IICheckEachDirectionMediator. In fact, you can start by copying IICheckEachDirectionMediator and calling it something else .. POCheckEachDirectionMediator. Note that you still need to extend VariableDirectionBlockLoadedInputOutputMediator.

Start by pruning sensors that simply do not make sense in the context of a PO world. Then add new sensors unique to a PO world (for example, how long since you have seen a ghost?). 

You will also eventually want to add sensor blocks that have some kind of memory, so that pacman is not just using its immediate senses, but also using memory, or making reasonable inferences.

**Comment by schrum2** [comment]
Please put into this issue a list of the sensors currently used. This could simply be a screen shot from a post eval of the game, since this includes sensor visualization

**Comment by Squillyprice01** [comment]
I had to do a test run to get my new sensors to be added, but I will add the others back in. See pictures below:

**Comment by Squillyprice01** [comment]
![ghostsaroundcorner](https://user-images.githubusercontent.com/15305479/41168686-53d10100-6b0c-11e8-9bb6-16bfd2b82222.png)

**Comment by Squillyprice01** [comment]
You can see here that there are two ghost around the corner. The distance to them is closer in the left direction, leading to a negative preference. The distance to them in the right direction is greater, so we have a positive preference for that direction. There probabilities are also at one. This is because when a ghost goes down that hall way, they cannot turn around. They have no other direction to go, so because we saw them in that hall, we know that they must be in it.

**Comment by Squillyprice01** [comment]
![50 ghosts](https://user-images.githubusercontent.com/15305479/41168821-ab4e3948-6b0c-11e8-9d37-ed734f700413.png)

**Comment by Squillyprice01** [comment]
Here, we witnessed a ghost right before it reached that junction. We know there are only two ways that ghost could have gone. As you can see by examining direction 0 panel (UP), there is a closet possible ghost with probability 50%, a second closest possible ghost which has a larger distance with probability 50%, and a third and forth possible ghost with probability 0% and distance infinity. this is exactly what we want to see!

**Comment by Squillyprice01** [comment]
Those are all of the new sensors added so far. @schrum2

**Comment by schrum2** [comment]
This technically exists. I think that future improvements to it should be other issues. Closing.
