### ISSUE TITLE
Add support in MsPacMan Sensors to handle partial observability conditions

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#143]
#21 With this done, we can hopefully evolve agents that work under partially observable conditions.

**Comment by Squillyprice01** [comment]
this issue seems synonymous to #142

**Comment by schrum2** [comment]
The package popacman.prediction seems to have some code for tracking and making predictions about the locations of objects in the world. It is very poorly documented, though there might be a description of it on the PO Pacman competition site. See if there is a way to incorporate some of these classes in the GameFacade to infer where objects are and act accordingly. @Squillyprice01

**Comment by Squillyprice01** [comment]
Closing this issue and migrating to #142
