### ISSUE TITLE
BD General Network Characterization with Syllabus from experience

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#144]
After my 2010 paper using BD ( http://hdl.handle.net/11214/150 ) I did some additional experiments where I made the syllabus in a more intelligent way (not just random). Specifically, instead of generating random syllabus vectors, I randomly sampled from the experiences of agents during evaluation and saves some of the network inputs into the syllabus. A new syllabus would be generated each generation from experiences of agents in that generation. These results were never published, and were only presented in the slides from the presentation: http://nn.cs.utexas.edu/downloads/slides/schrum.gecco2010.ppt . They are labelled as BDObs in the slides.

Granted, the results from "real" observations did not prove better than random inputs in this particular domain, but it seems that this approach could have benefits, especially in a high dimensional input space like Tetris where many random inputs are invalid. Implementing this intelligent syllabus could improve BD, at least in Tetris. This approach would need to be coded from scratch though ... that 2010 GECCO paper used a different programming language.

**Comment by DevonFulcher** [comment]
Tested with a post watch and everything seems to be working fine.

**Comment by schrum2** [comment]
Open a separate issue for making a unit test of this. Use Tetris as the
task, and simply confirm that all syllabus states are valid Tetris states.
Specifically, every value is 0 or 1 in the first 200 inputs and 0 or -1 in
the next 200. Then, confirm that there are no complete lines since they
would be cleared. Finally, confirm that the block inputs correspond to the
hole inputs.
