### ISSUE TITLE
Create batch files for SZ Tetris with Behavioral Diversity and TUG

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#145]
Hi @JoeRoybal ,
@DevonFulcher is investigating Tetris, and trying to find ways to get better performance in this domain. Two possible means to achieve better performance are the algorithms TUG and BD. Devon knows what these are, and is looking to apply them to Tetris. However, there is also a harder variant of Tetris called SZ Tetris. We need a way to run experiments in this domain.

Whenever we want to run experiments, we have to Maven compile/install the code (Devon will show you how to do this), and then execute a batch file from the command line (Devon will show you this too). Once Devon shows you how to set these up, you can run them on your machine while working with him on other tasks.

Some details for @DevonFulcher :
1) Use CNN D1W1 MSS Threshold as the baseline starting point.
1) TUG should use 4 objectives: one for each number of lines cleared at a time
2) Do BD with domain-specific characterization: 4 numbers, count of each number of lines cleared at a time.
3) Do BD with the General Network Characterization (try setting syllabusSize to 5, 10, 20)

If you complete issue #144 then you can also make batch files for that.

**Comment by DevonFulcher** [comment]
All of these batch files have been created. Testing here #157
