### ISSUE TITLE
Configure PacMan so that we display only what PacMan sees.

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#152]
I'm not entirely sure where this configuration is. I might have to read some code.

**Comment by schrum2** [comment]
Figuring out how to do this should become a high priority. The best way to understand the behavior we are seeing is to see the world the way pacman does.

**Comment by Squillyprice01** [comment]
There is now a parameter called observePacManPO in Parameters.java that determines whether or now we observe pacman in PO conditions (completely independent of what the agent can observe).
