### ISSUE TITLE
Implement PacMan OtherScores for PO conditions

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#153]
#21 This would allow us to track other information about the game besides the raw game score.

**Comment by Squillyprice01** [comment]
To implement PillScore, I need to finish #166.

**Comment by Squillyprice01** [comment]
This is unnecessary for now.

**Comment by schrum2** [comment]
I still want to keep this open as an issue, even if we don't get around to it this summer.

**Comment by schrum2** [comment]
Not worth keeping around.
