### ISSUE TITLE
Use split sensors instead of conflict sensors in popacman

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#155]
You told me about doing this tomorrow Dr. Schrum. Easy reminder.

**Comment by schrum2** [comment]
Batch files in the Experiments-2016-TCIAIG-MsPacMan directory that have "Split" in the name are the ones to look at (not "Conflict"). MsPacMan-OneLifeSplit-TwoModules.bat and MsPacMan-OneLifeSplit-ThreeModules.bat in particular are probably the best places to start. The relevant paper is also stored there: schrum.tciaig16.pdf

**Comment by Squillyprice01** [comment]
MsPacMan-OneLifeSplit-TwoModules.bat now works. Need to update the MsPacManTask a bit in order to support MsPacMan-OneLifeSplit-ThreeModules.bat.

**Comment by Squillyprice01** [comment]
As long as the batch files use rawScorePacMan as the fitness measure, they work. Once #153 is complete, we can move on to implementing other measures of fitness for pacman.
