### ISSUE TITLE
Make all useful debugging parameters from GameBots.ini into command line Parameters in MM-NEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#156]
Make all useful configuration settings in GameBots.ini into commandline parameters that affect the server launch string in UT2004Task. At a minimum, we should have the ability to turn on/off the navmesh, debug text on the bots, nav point visibility as boxes, and maybe more. For example, can we turn ray trace viewing on/off? 

These debug setting should be off by default, but make a new batch file in batch\UT2004 that is basically a copy of UT2004-Dummy.bat but with all the debug settings on  (call it UT2004-DummyDebug.bat). Remember that you will have to Maven install/compile before being able to launch this batch file. Make sure all of the settings are evident when you log in.

It would also be nice if we could turn on the GBHUD mutator for users that log into the server, but this is related to issue #118 

One more note: If you are having trouble enabling any of these settings, then you might need to use a different version of GameBots.u in the UT2004/System directory. The special BotPrize version of the mod might not allow certain settings to be changed. Be sure to note any discoveries in this regard within this issue.

**Comment by friedmaa** [comment]
tried to put nav grid in, but it didn't work

**Comment by schrum2** [comment]
Annoyingly, it does not seem possible to configure the GameBots.ini settings directly from the command line. All we are able to successfully do is set mutators.

I think the botprize mod and the PathMarker mods are already available as mutators. Add the GBHUDMutator as the final one (add to Parameters.java and to UT2004Task.java). Once this is added, you can close this issue.

**Comment by schrum2** [comment]
In email communication with Michal Bída, who formerly worked on Pogamut, I had it confirmed that arbitrary settings from GameBots.ini cannot be set from the command line to ucc.

**Comment by friedmaa** [comment]
That's inconvenient, to say the least. But at least we can get the hud to display regardless of what the server is.

**Comment by kwg** [comment]
However you can specify which ini file to load from the command line. While not as simple as a command line option, it does offer a work around... even if it is one that produces a ton of ini files. Alternatively, batch scripting a wrapper may work as well if you want to write one up that alters, selects, or creates the ini file based on parameters passed into the script from the CLI.

**Comment by schrum2** [comment]
It's possible but not worth the effort.
