### ISSUE TITLE
Benchmarking UT2004 evolution time

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#163]
You are currently doing this now. The goal is to find out roughly how long it takes to evolve good behavior. In particular, we want to try making the number of threads as large as possible (without overwhelming the system) and the population size (mu) as small as possible without sacrificing performance or quality of results. Making mu smaller will definitely make us progress through the generations faster, but if we make the population too small then we won't be able to have a diverse and varied population, which could cause us to get stuck evolving fairly crappy agents.

So, for this issue, make comments tracking roughly how long it takes to complete a generation and several generations with different settings. Besides threads and population size, another parameter we might be able to tweak is the number of trials per individual, and the number of minutes that each agent is evaluated for. Fewer trials is faster, but makes agents vulnerable to bad luck (evaluation is noisy) and also might reward bad agents that get lucky. Similarly, longer evaluations give a better, more accurate evaluation of an agent, but take longer.

Start doing this with the Dummy agent (as you are) but quickly move on to evolving against the built-in native bots as soon as the evolved agents demonstrate an ability to trash the Dummy agent.

**Comment by friedmaa** [comment]
**trials:1  mu:10  threads:10**
each gen takes about 10 mins
by gen 3 it was able to kill the dummy bot easily
let it evolve to gen 5, where it was doing well. then killed it

**Comment by friedmaa** [comment]
![image](https://user-images.githubusercontent.com/31463347/40852052-d6a3b1aa-658e-11e8-8932-087f2ba062f9.png)
![image](https://user-images.githubusercontent.com/31463347/40852069-e7572c34-658e-11e8-81c3-d1235f0ae48a.png)
![image](https://user-images.githubusercontent.com/31463347/40852087-eed49f50-658e-11e8-8368-9d4064467a28.png)

**Comment by friedmaa** [comment]
**against native bots
trials:1 mu:10 threads:10**
gens took about 8 mins

**Comment by friedmaa** [comment]
![image](https://user-images.githubusercontent.com/31463347/40855186-6c8bfb50-6599-11e8-9558-1481e2988df9.png)
![image](https://user-images.githubusercontent.com/31463347/40855197-77802e50-6599-11e8-92ac-06bd477c1f6c.png)
![image](https://user-images.githubusercontent.com/31463347/40855220-938770b8-6599-11e8-9b22-9d7d0760f1c1.png)

**Comment by schrum2** [comment]
See how changing the level affects the ability of the bots to evolve. DM-TrainingDay is small, so it is easy to rack up kills, but that also means that many other skills are not developed/trained.

Also, as you complete #107 and  #168 , conduct similar tests with those bots

**Comment by friedmaa** [comment]
**Threads: 10  mu: 10  map: Idoma against dummy bot** (all previous tests were on trainingDay map, **utEvalminutes for all of these trials is 1**)
each gen took about 4 minutes, but it crashed midway through gen 4
will try again

**Comment by friedmaa** [comment]
same as above, crashed in gen 1, then tested on normal DummyDebug with Training day, which seemed to work fine up to the point where idoma crashed

**Comment by friedmaa** [comment]
**Threads: 10 mu: 10 map: Idoma against dummy bot (attempt 3)**
gens take about 5 mins

**Comment by friedmaa** [comment]
![image](https://user-images.githubusercontent.com/31463347/40928287-8c6e8db2-67e6-11e8-9127-2484fe98d842.png)
![image](https://user-images.githubusercontent.com/31463347/40928301-94e0d6a8-67e6-11e8-8e28-c6fc68c3adff.png)
![image](https://user-images.githubusercontent.com/31463347/40928319-9dd928aa-67e6-11e8-802c-0706812b2ef8.png)

**Comment by friedmaa** [comment]
**Threads: 10 mu: 10 map: Idoma against dummy bot**
It seemed to take a bit longer for the bot to change behaviour, because it had less interaction on the bigger map. it also seemed to get stuck on the nav points on ramps, staring at the ceiling
gens took about 6 mins
![image](https://user-images.githubusercontent.com/31463347/40929731-404d6d5e-67eb-11e8-8bba-060991dabbce.png)
![image](https://user-images.githubusercontent.com/31463347/40929751-4aa9d3b4-67eb-11e8-9653-e4b7b4848133.png)
![image](https://user-images.githubusercontent.com/31463347/40929767-55720e4c-67eb-11e8-87a0-47ff6a751072.png)

**Comment by friedmaa** [comment]
Seemed to only have ramp trouble on idoma, so I will find a new map

**Comment by friedmaa** [comment]
**against dummy bots
trials:1 mu:10 threads:10  2 mins long tests**
gens took 6 mins
by 4th gen seemed to be doing well
![image](https://user-images.githubusercontent.com/31463347/40931941-776837d6-67f2-11e8-989e-87aaadacae71.png)
![image](https://user-images.githubusercontent.com/31463347/40932015-aeacdc88-67f2-11e8-99ea-eeaed940065b.png)
![image](https://user-images.githubusercontent.com/31463347/40932027-bbb3fbb4-67f2-11e8-80a5-35c45a61bde8.png)

**Comment by friedmaa** [comment]
**against native bots
trials:1 mu:10 threads:10 2 mins long tests**
kept getting stuck on walls
gens took 8 mins
![image](https://user-images.githubusercontent.com/31463347/40935088-9b21e55a-67fc-11e8-95b3-0c0ea96929b0.png)
![image](https://user-images.githubusercontent.com/31463347/40935099-a0eb003e-67fc-11e8-8a93-96d7d8414e20.png)
![image](https://user-images.githubusercontent.com/31463347/40935115-b2301140-67fc-11e8-90b1-1f1d8fdf8d19.png)

**Comment by friedmaa** [comment]
Will start working on other bots now.
