### ISSUE TITLE
Launch multiple bots of different types with one command

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#164]
DifferentBotLaunchTest is a file I made that currently just launches multiple HunterBots. You should be able to modify this to launch ray trace bots and the other simple Pogamut bots. With some extra effort, you could even launch UT2, but there are some access issues with the UT2Parameters that would make this non-trivial.

However, what I really want is a way to simultaneously launch multiple bots of DIFFERENT types. Start simple: a HunterBot and a NavigationBot. The problem is that Pogamut doesn't really seem to provide a way to do this. The point of this issue is to explore work around solutions.

I think it might be possible (though a huge hassle) to modify all bots so that they extend some kind of general super class of UniversalBot so that we could determine which one we are instantiating via bot parameters, but that is complicated and we will need to discuss it before you try it.

**Comment by friedmaa** [comment]
Possible when using the MultiBotLauncher file
