### ISSUE TITLE
Add support for PillModel in GameFacade.java

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#166]
A step in the direction of  --> #165.

**Comment by Squillyprice01** [comment]
I have code that needs testing unpushed on my machine. However, in order to test it, I need to find an entry point for the new methods added in GameFacade.java, specifically updateHiddenState(). @schrum2

**Comment by Squillyprice01** [comment]
I think that it is up and running. Now all we need to do is run a few generations and compare the results with other agents that didn't have the pill model.

**Comment by Squillyprice01** [comment]
![pillmodel_is_bad](https://user-images.githubusercontent.com/15305479/40864370-2cb5db2a-65b9-11e8-937c-4b9ad28fe015.png)

As it stands, using the pill model both slows down the evaluation speed and decreases performance of agents. Guess which is which!

I think that this will be improved if we have a model of the ghosts as well.

**Comment by Squillyprice01** [comment]
I believe that this is done. Everything could always use testing but I think this is running.

**Comment by schrum2** [comment]
Reopen this in light of the bug you found.
