### ISSUE TITLE
Normalized Characterization

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#170]
First, run a set of intelligent/random vectors through a set of nn. 
Second, characterize each nn by normalizing the magnitude of each of these vectors.
The list of these normalized magnitudes are the network's characterization.

**Comment by DevonFulcher** [comment]
Currently supports normalization by dividing the greatest value of each vector across the vector. Support for other normalization techniques could be added later. It may be worth adding a NormalizationUtil with various forms of normalization since we are doing batch normalization. Although it may not be worth the effort if different normalization techniques only add a marginal increase in performance.

**Comment by schrum2** [comment]
Add links to the relevant commits to this and all issues you worked on so that I know what needs reviewing

**Comment by schrum2** [comment]
You should have received many emails because I just tagged you in discussions about this commit:
https://github.com/schrum2/MM-NEAT/commit/28622f365204b997233748845e26f10053f94fd5#diff-6413b33addcb2873bcf5fb46c8fcac46

Much of your changed need to be rolled back and fixed.

**Comment by schrum2** [comment]
To clarify, normalizing across the entire population would server no purpose, because then the scale of outputs by different networks would still maintain the same relative order. The purpose of the normalization across a single network's outputs is to assure that a network that consistently has small outputs can be properly compared to one that consistently makes large outputs. It is the range and order of the individual network's outputs that matter more than the scale with respect to the whole population.

**Comment by DevonFulcher** [comment]
This works now.

**Comment by schrum2** [comment]
This has errors that I've pointed out here:
https://github.com/schrum2/MM-NEAT/commit/8e80c7ec2e0a10a95c797f59dce3e8746f4d102d
Fix the errors, and also create JUnit tests for this class that verify its behavior.

**Comment by DevonFulcher** [comment]
In the future normalizing across the outputs separately could be explored for domains with more than one output.

**Comment by schrum2** [comment]
What actually remains TODO for this issue? I don't remember what you mean by "normalizing across the outputs separately". This issue either needs to be further clarified, or closed.

**Comment by DevonFulcher** [comment]
I am not really sure that idea I had was well defined

**Comment by DevonFulcher** [comment]
Oh, I remember! Currently, the normalized behavior vector is defined by normalizing across a vector that is created by concatenating multiple output vectors from a syllabus. In Tetris, an output vector would contain one real number because of the one output of the NEAT/HyperNEAT network. However, in domains with multiple outputs each output could be normalized across the syllabus with respect to only the same output from different syllabus vectors. For instance, a domain has 3 outputs a, b, c. The syllabus has 5 vectors. So, there are 5 different versions of a a1, a2, a3, a4, a5. To me, it makes sense to normalize this vector (a1, a2, a3, a4, a5) then place it within the overall behavior vector for the network instead of how is currently down where the behavior vector is normalized after values are placed within it. This is not worth exploring in Tetris but perhaps in other domains.

**Comment by schrum2** [comment]
Closing. If the initial normalized approach had shown some success, it would be worth putting in more effort, but this does not seem to be a useful approach.
