### ISSUE TITLE
Experimenting with different activation functions in deep CNNs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#173]
My previous HyperNEAT results in Tetris rely on using the tanh activation function for all neurons in the substrate CNN, which is fairly unusual, but potentially also part of the reason that deeper networks are not functioning correctly.

In traditional networks, the input neurons have the identity function as their activation function. In CNNs and deep networks, it is now common for all hidden layer neurons to use the ReLU function. The output activation function is still generally a tanh or a sigmoid.

We should experiment with different activation functions, especially in deeper networks. The ftype parameter can be used to change the activation function used by default in the substrate network. The parameter inputsUseID can be used to make all input neurons use the identity activation function. Finally, there is a parameter heterogeneousSubstrateActivations (false by default) that allows various different activation functions in substrate networks. If this final parameter is true, then the activation function used by all neurons in a substrate is in fact determined by the Substrate class (see the getHiddenSubstrateInformation method of HyperNEATUtil.

Clearly, I've done some preliminary testing with these features, but not thorough. I think they need to be revisited. In particular, try some experiments with networks that have HNProcessDepth of both 1 and 2, just to see if we can successfully add a little bit of depth to the networks.

**Comment by schrum2** [comment]
Any progress to report on this?

**Comment by DevonFulcher** [comment]
I have not tried anything independently yet. We tried ReLU on the cluster with very poor performance. I am not sure which activation functions would be effective. UberAI used a activation function composed with ReLU in this paper: https://arxiv.org/pdf/1712.06567.pdf. Maybe, we can try composing tanh with ReLU

**Comment by schrum2** [comment]
I'm not certain that we fully explored this properly. Maybe we could combine ReLU with some of the new approaches, like custom architectures (10 by 1 at the end), more depth (2 or more), normalized nodes, and cascade expansion (force inclusion of 7 links to each new output to strongly encourage usage)

**Comment by schrum2** [comment]
This issue is pretty open-ended. I feel like there is still some exploration that could be done, but the issue is fairly vague as it is, so I'm going to close it.
