### ISSUE TITLE
Fixing how holes are sensed in Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#174]
Regarding the new issue #173 , I mentioned in my recent Tetris paper that using ReLU was not noticeably better than tanh, which is why I stuck with tanh in my experiments. However, I since realized that because I was using ReLU even for the input neurons, this change made the inputs from the "holes" substrate invisible, because holes are detected as -1 and ReLU maps all such values to 0 ... the same as no hole.

However, we could easily sense the holes at "1" instead, and evolve equivalent networks ... just make the link weights leaving those neurons negative, and the behavior would be identical. Still, I want to maintain full backwards compatibility with my previous results, so I want you to fix this, but with a command line parameter.

The parameter should be "senseTetrisHolesAsPositive" and should be false by default. If it is true, then in RawTetrisStateExtractor, the values of -1 assigned to the inputs should instead be +1 (lines 53 and 55)

It could be important to make this change before exploring #173

**Comment by DevonFulcher** [comment]
How do I make the change to "make the link weights leaving those neurons negative"?

**Comment by DevonFulcher** [comment]
![screenshot 2](https://user-images.githubusercontent.com/24593113/40935120-b833b48e-67fc-11e8-92e4-96d1b3b315cb.png)
 seems to be working

**Comment by DevonFulcher** [comment]
Should I turn this parameter on for all future tests?
