### ISSUE TITLE
Make PO PacMan use the existing parameter for pacman number of lives

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#178]
The default is 1, and this is what should be used in evolution too.

**Comment by Squillyprice01** [comment]
This is set in pacman.game.Constants package, which I cannot edit at this time.

**Comment by schrum2** [comment]
Leave this issue, but ignore it for now. It is low priority.

**Comment by Squillyprice01** [comment]
see #226
