### ISSUE TITLE
Throw an exception if the log name doesn't match the saveTo name. 

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#179]
Or, maybe it would be better to allow for only one name in the batch file and the other would be generated automatically.

**Comment by schrum2** [comment]
Possibly, but for now just print a clear error message and exit. Specifically, the saveTo has to match the portion of the log that follows the hyphen.

**Comment by DevonFulcher** [comment]
Is this in MMNEAT.java somewhere?

**Comment by schrum2** [comment]
It should probably be checked in Parameters instead.

Also, do this change on the dev branch instead of dev_tetris

**Comment by DevonFulcher** [comment]
This has been implemented. Hopefully it will save us from some headaches.

**Comment by schrum2** [comment]
I can't find the commit for this. TAG YOUR COMMITS! Which branch? @DevonFulcher

**Comment by DevonFulcher** [comment]
Should be able to find it now. It is two commits because i messed up the first time

**Comment by DevonFulcher** [comment]
I think I forgot to sync that is why my first commit didn't show up until now.

**Comment by DevonFulcher** [comment]
should work now
