### ISSUE TITLE
HybrID plus Convolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#18]
From MM-NEATv2: https://github.com/schrum2/MM-NEATv2/issues/459

**Comment by schrum2** [comment]
I'm attaching some example plots to show what the problem looks like.

This first file is from using raw features with fully connected networks and HybrID. The switch point is 100 generations, but you'll notice that although performance does not noticeably improve after 100 generations, it does not get worse either. In fact, scores stay consistent. This seems to indicate that HybrID is working as expected, though it apparently doesn't help much with fully connected networks using raw features.
[Tetris-HybrIDRaw0_parents-Game Score.pdf](https://github.com/schrum2/MM-NEAT/files/1539675/Tetris-HybrIDRaw0_parents-Game.Score.pdf)

This next file shows how using convolutional networks clearly breaks HybrID. The switch point is 100 generations again, and the fitness completely tanks at this point. If HybrID is working, then there should be no drop. Hopefully, once we get HybrID working here, we can see if it gives any benefit with convolutional networks.
[Tetris-HybrIDConvolution3WideRaw0_parents-Game Score.pdf](https://github.com/schrum2/MM-NEAT/files/1539685/Tetris-HybrIDConvolution3WideRaw0_parents-Game.Score.pdf)

HybrID might also offer a benefit to networks using hand-designed features, but that is a whole other set of experiments to run.

**Comment by schrum2** [comment]
Make some SZ Tetris batch files using HybrID as well to see if we can at least run the code. Since there is a bug with HybrID and CNNs, you should see a sudden fitness drop at the switch point.

**Comment by schrum2** [comment]
We may want to explore convolutionWeightSharing with HybrID too, but that is for later. For now, just make the HybrID batch files for SZ Tetris.

**Comment by leg2015** [comment]
Should I go ahead and set CleanOldNetworks to false so we can compare network architectures across the switch point?

**Comment by schrum2** [comment]
Yes. Until we are certain HybrID works with CNNs, we should look at all networks to track what is going on.

**Comment by leg2015** [comment]
Added two batch files - one for hybrid with hneat and one for hybrid with cnns. I used the cnn batch file ConvDepth1Width1ExtraSZ to make the hybrid files and I modified the old hybrIDRaw batch file to gett the hybrid functionality. I also have cleanOldNetworks set to true currently to better check how hybrid might be failing. I can't actually run experiments though until I have a jar to run them with as I still have Maven bugs on my laptop and the jar on the tower of power is too old to run this code. Hope to get some experiments running soon though once the jar has been exported.

**Comment by schrum2** [comment]
Regarding HybrID with SZ Tetris and CNNs:
Here is the plot of game score you sent me.
[Tetris-HybrIDSZConvolutionDepth1Width1Extra0_parents-Game Score.pdf](https://github.com/schrum2/MM-NEAT/files/1772550/Tetris-HybrIDSZConvolutionDepth1Width1Extra0_parents-Game.Score.pdf)
As we expected, the score drops in an unusual way at generation 100, though it does not tank as badly as I might have feared. This does still indicate that there is a problem though ... there is no reason for the sudden drop. This plot also indicates that for the sake of our testing in the future, you can probably set the HybrID switch point to just 50 generations ... the score is high enough at this point that we will notice if it drops, but we will be able to run tests quicker if we evolve for fewer generations.

In order to try to fix this problem, I recommend taking a close look at HyperNEATCPPNGenotype:
https://github.com/schrum2/MM-NEAT/blob/master/src/main/java/edu/southwestern/evolution/genotypes/HyperNEATCPPNGenotype.java
Specifically, look at the createNodeLinks method, and then look at the convolutionalLoopThroughLinks and loopThroughLinks methods. We believe that HybrID with Full networks works, but that code uses loopThroughLinks. So, presumably, the reason that HybrID plus CNNs fails has to do with convolutionalLoopThroughLinks. 

First you need to understand how this code works (or is supposed to), and then we can figure out how to fix it.

**Comment by schrum2** [comment]
To @DevonFulcher : If you resolve #98 then you can move on to this. I will need to explain CNNs a bit more to you first though.

**Comment by DevonFulcher** [comment]
CNN test works. Batch file is running. Leaving open until confirmed resolution.

**Comment by DevonFulcher** [comment]
Everything seems to be fine after the switch point. Added JUnit tests.
