### ISSUE TITLE
JUnit tests for Behavioral Diversity Intelligent Vector Network Characterization

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#180]
Following #144. Use Tetris as the task, and simply confirm that all syllabus states are valid Tetris states. Specifically, every value is 0 or 1 in the first 200 inputs and 0 or -1 in the next 200. Then, confirm that there are no complete lines since they would be cleared. Finally, confirm that the block inputs correspond to the
hole inputs.

**Comment by schrum2** [comment]
Behavioral Diversity is no longer an interesting quality diversity method
