### ISSUE TITLE
GVG-AI LevelBreederTask.Java compatibility

### ISSUE THREAD

**Issue by JoeRoybal** [schrum2/MM-NEAT#183]
Some files (for example bomber.txt, catapults.txt, and portals.txt) conflict with the general assumed floor in the LevelBreederTask.Java. They usually are mapped to a different key.

**Comment by schrum2** [comment]
Once you add game specific floor tiles to each game, you can close this issue. Be sure to tag the commit with this issue number (you can tag multiple issues with one commit)

**Comment by JoeRoybal** [comment]
https://github.com/schrum2/MM-NEAT/commit/8248e7b5bedf396d14866213d163e11d2c4d3029?diff=split 
This is the link to the code that created the custom floor and wall variables
