### ISSUE TITLE
GVG-AI placement constraints

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#186]
Somewhat related to #185 

Certain objects in certain games really need to be placed in particular locations in order to make sense. For example, in aliens, the ship really needs to be at the bottom of the screen, or it can't be played. There are other examples of games with issues like this.

@JoeRoybal  please comment on this issue and describe which games have specific placement issues, so we can think about a general way of adding such constraints.

**Comment by JoeRoybal** [comment]
Aliens, Ikaruga, Frogs, and Plants are the ones off the top of my head. Aliens should spawn the avatar at the bottom and the aliens somewhere near the top. Ikaruga is the same issue as Aliens and plants is as well. Frogs is more about keeping the avatar from spawning right next to the goal and this is similar to a few more games that just spawn the character near the goal.

**Comment by schrum2** [comment]
Don't waste effort on the old version of GVG-AI
