### ISSUE TITLE
Evolve Architecture and CPPN in tandem

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#188]
We could evolve network architecture as well as weights needs some more consideration.

**Comment by DevonFulcher** [comment]
I think HyperNEATCPPNAndSubstrateArchitectureGenotype and cascade expansion will make this easier. Perhaps we could have a neuron on the cppn that tells HyperNEAT when to expand. Although I find it difficult to image that the cppn will learn both link weights and when to expand on its own. Maybe we could introduce a third nn (a cppn) that takes in substrate locations and neuron locations from the original cppn and output when to expand. However, cascade expansion is still unproven so maybe this is not the correct route. Just some thoughts.

**Comment by schrum2** [comment]
Having the CPPN decide when to expand imwould not work. However, cascade expansion could be made into a mutation operation. In general, we can define mutation operations on the substrate list (add/remove layers/substrates) and the connectivity list

**Comment by DevonFulcher** [comment]
Sounds awesome! Could these be the same mutations as in NEAT such as splice node and add connection because they have been proven successful? Also, maybe these mutations should be on a single neuron/connection instead of a whole substrate to have a smoother gradient. Maybe we could think of a way to implement crossover?

**Comment by schrum2** [comment]
Make Cascade Expansion a mutation operation with its own associated mutation rate parameter (default value of 0.0). Try evolving with a very small value (maybe 0.01).

Note that this should be done after #261

**Comment by DevonFulcher** [comment]
Given that cascade expansion was unsuccessful, I do not know if this is the correct next step. It may be worth rethinking how phenotypes may be evolved.

**Comment by schrum2** [comment]
This is no longer something we can reasonably complete by the end of SCOPE, but might be interesting to pursue later.

Our basic idea was to simply use cascade expansion as a mutation operation, but since that approach didn't seem to provide any benefit, it likely would not help as a mutation either. However, exploring other means of changing the architecture could be useful in the future.

**Comment by schrum2** [comment]
HyperNEAT is no longer a priority, and this approach in particular is probably too complicated anyway.
