### ISSUE TITLE
Reduce UT2004 logging output

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#191]
Whenever we run a UT2004 server with lots of bots, the amount of output is ridiculous. This log output is somewhat useful when watching a single bot, but not when there are multiple.

Make a command line parameter in Parameters.java called utBotLogOutput with a default value of false. Then, go into all bots and find places where System.out.println sends output to the console, and put that code inside of if statements controlled by the new parameter. Reducing the amount of log output should make it easier to track issues with the server and also evolution.

**Comment by schrum2** [comment]
Note: We still want to be able to launch bots like UT^2 in isolation without doing a complicated evolution setup. For example, by right-clicking UT2 and choosing run-as. If you try to run a bot this way, then Parameters.parameters will be null. To avoid the NullPointerException, check this first ... if Parameters.parameters is null, then log output should be printed (since the bot is presumably being run in isolation). Only if Parameters.parameters is not null should you check this new command line parameter.

**Comment by friedmaa** [comment]
Saving MirrotBot changes for issue #184 , because I will be commenting, and thus going through it anyway, so I will look for printlns there.

**Comment by schrum2** [comment]
MirrorBot and UT^2 still seem to produce a lot of log output

**Comment by friedmaa** [comment]
Closed it with only mirror bot output gone
