### ISSUE TITLE
Maven build failure. probably only in the dev_tetris branch

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#200]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:34 min
[INFO] Finished at: 2018-06-07T16:04:17-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project MM-NEAT: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\fulcherd\eclipse-workspace\MM-NEAT\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by schrum2** [comment]
I wish you hand mentioned the specific tests that were failing. They get listed before this.

I wonder if their failure is related to this issue:
https://github.com/schrum2/MM-NEAT/issues/137

**Comment by schrum2** [comment]
Solved
