### ISSUE TITLE
Evolution in Team DeathMatch

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#201]
It's time to start looking into evolving agents for team deathmatch. I'm not sure what all needs to be done to accomplish this, but you should start by creating a new task UT2004ManyVsNativeBotsTeamDeathMatchTask that extends UT2004Task. You will need to override oneEval so that instead of creating an array with a single genotype in it, you create multiple copies of the genotype. The idea is that the whole team will be composed of copies of the same genotype, and they will all be on the same team against a team of native bots.

The team size should probably be a command line parameter. I do not know how to assign bots to specific teams, so you will need to investigate that (I'm sure Pogamut offers a way). You will also need to configure the server config string to launch a team death match game.

**Comment by friedmaa** [comment]
from(http://pogamut.cuni.cz/pogamut_files/latest/doc/gamebots/ch06.html)
**Team (int)
What team the player is on. 255 is no team. 0-3 are red, blue, green, gold in that order.**

 **MaxTeamSize (int)
Max number of players per side (BotTeamGame, BotCTFGame, BotDoubleDomination).**

**MaxTeams (int)
Max number of teams. Valid team range will be 0 to (MaxTeams - 1) (BotTeamGame, BotCTFGame, BotDoubleDomination). Usually there will be two teams - 0 and 1.**

**Comment by friedmaa** [comment]
from: https://artemis.ms.mff.cuni.cz/pogamut_files/documentation-project/Pogamut-User_Manual.pdf

UT2004 server with Gamebots needs to be run from the console. We will use the ucc utility that can be
found in the /System/ subdirectory of your UT2004 installation.
To run the server, start console and cd into the UT2004/System/ directory. Then use following syntax:
ucc server mapname?game=BotAPI.gametype
MapName: Name of the map you want to run. It's the same as name of the map file, without the .ut2
suffix. You can see all the map files in UT2004/Maps/ directory.

GameType: Type of the game started. Select one of the following:
- BotDeathMatch
- BotTeamGame
- BotCTFGame
- BotDoubleDomGame
- BotBombingRunGame
For example, to start the server with game BotDeathMatch on the map DM-Junkyard, the command will
look like this:
ucc server DM-Junkyard?game=BotAPI.BotDeathMatch

**Comment by friedmaa** [comment]
Score
Scores of all players are accessible by following methods (the actual score value may have different
interpretation depending on the game type). Not all of them make sense in every game type (for example,TeamScores are not present in games that don't have teams ).
- **getAgentScore()** Score of the agent.
- **getAgentTeamScore()** Score of the agent's team.
- allPlayersScores()** Scores of all players, in HashMap indexed by ID
- getOpposingTeamScore()** Score of the opposing team.
- opposingTeamScores()** Scores of opposing teams, in HashMap indexed by ID
- getPlayerScore(int ID)** Score of the player with given ID

**Comment by friedmaa** [comment]
**2 teams, 2 players per team, natrive bots vs evolving bots
mu:10   threads:10   evalMinutes:2**
gens took 22 mins
bots don't seem to notice teammates
native bots tend to move together

**Comment by friedmaa** [comment]
**2 teams, 2 players per team, natrive bots vs evolving bots
mu:10   threads:10   evalMinutes:1** used insidious map
gens took 11 mins

**Comment by friedmaa** [comment]
Yes, it is possible.
