### ISSUE TITLE
Evolution in Team CTF

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#203]
Once #201 is completed, generalize the code further and create a task for Capture The Flag. This will definitely require some new stats tracking to define new fitness functions, but will probably also require additions to the sensor models and output models. We may need BotActions associated with CTF actions.

Here are some references:
http://pogamut.cuni.cz/pogamut_files/latest/doc/tutorials/ch11s03.html
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.580.6158&rep=rep1&type=pdf
https://github.com/qwertzdenek/MyAlterEgo

**Comment by friedmaa** [comment]
Did not get to this, as the goal was to evolve for team deathmatch.

**Comment by schrum2** [comment]
This still seems like the best test of team play, but we clearly won't get around to it soon. This issue would be complicated, in that many new sensors and fitness functions would need to be developed.

**Comment by schrum2** [comment]
Too complicated to be worth doing, especially since this Pogamut/UT2004 domain has lots of limitations by modern standards
