### ISSUE TITLE
Once Evolution in CTF works, try including CTFbot

### ISSUE THREAD

**Issue by friedmaa** [schrum2/MM-NEAT#204]

**Comment by friedmaa** [comment]
Did not get to this, as the goal was to evolve for team deathmatch.

**Comment by schrum2** [comment]
This should be easy to do, but doesn't make sense until we can launch CTF matches.

**Comment by schrum2** [comment]
I'm not going to bother keeping this around. If someone else is interested in UT2004 CTF, then resurrecting this issue will be an obvious TODO item.
