### ISSUE TITLE
Allow Bots to sense teammates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#209]
We need to make sure that bots can sense teammates, and that they do not sense them as enemies. Your observations so far seem to indicate that bots do not sense each other as enemies in a team death match. You should confirm this with a test in which there are multiple evolving bots but zero other bots. In this setting, the bots should not attack each other.

More importantly, we want them to be able to sense each other, for the sake of cooperation. We will do this by generalizing some of the existing sensor blocks. For example, refactor/rename NearestOpponentDistanceBlock to NearestAgentDistanceBlock and add a constructor that takes a boolean: true for sensing opponents, false for sensing teammates. Note that by adding this, you will also need to change code that uses this class, such as OpponentRelativeSensorModel. Once there is a boolean that tracks whether we are sensing friends or foes, you can use it to determine which Player the bot is sensing.

Specifically, make it so that
Player opponent = bot.getPlayers().getNearestEnemy(MEMORY_TIME);
will either sense an enemy, or a teammate, depending on the value of the boolean.

You will need to generalize PieSliceOpponentSensorBlock and EnemyBehaviorBlock in similar ways (change the parts of the name that say "enemy" or "opponent" to agent).

Once all of this is done, you can create a new sensor model called OpponentAndTeammateRelativeSensorModel. It will basically be the same as OpponentRelativeSensorModel, except that for every sensor block that senses enemies, there will also be a corresponding block that senses teammates. As a result, the agent will have several more sensors.

**Comment by friedmaa** [comment]
Tried creating a team server with only evolving bots, more than one would get stuck in the same place, but they were not shooting at each other. The fact that they would get stuck in the exact same place indicated that they did not seem to see the bots that were already stuck in the location.

**Comment by friedmaa** [comment]
resumed running, but this is a problem, I need to be able to just let it evolve without constantly reloading it
![image](https://user-images.githubusercontent.com/31463347/41476987-ab8de422-7088-11e8-97c3-c1265cac79bb.png)
![image](https://user-images.githubusercontent.com/31463347/41476998-b3b759e4-7088-11e8-9803-158d9de1d66d.png)
![image](https://user-images.githubusercontent.com/31463347/41477006-bafabe12-7088-11e8-9bc4-dc41d6e746c6.png)

**Comment by friedmaa** [comment]
run with 2 minute evals (previous was 1 minute) 2 teams, 2 per team, still had issues with crashes
![image](https://user-images.githubusercontent.com/31463347/41489513-e3ec7310-70b5-11e8-947c-2badd79b932c.png)
![image](https://user-images.githubusercontent.com/31463347/41489521-eba3d6f2-70b5-11e8-9d1f-00e6800de714.png)
![image](https://user-images.githubusercontent.com/31463347/41489527-f09c8384-70b5-11e8-9148-1f43c0c2146a.png)
![image](https://user-images.githubusercontent.com/31463347/41489547-fc32df9a-70b5-11e8-818d-e06fa7bd9d63.png)

**Comment by friedmaa** [comment]
I am closing this issue, as the sensors are now implemented.
