### ISSUE TITLE
Integrate new Partially Observable Pac-Man Code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#21]
This is the code used in the new Ms. Pac-Man vs Ghosts competition:
http://www.pacmanvghosts.co.uk/download.html

**Comment by schrum2** [comment]
Although my code has extensive support for Ms. Pac-Man, the current version of the Ms. Pac-Man vs Ghosts competition is actually a different code base. In fact, the "partially observable" aspect of the new competition makes it a harder problem. Still, we should be able to adapt my code to work with the new version of the domain.

The new version of the domain is Maven based, so it should actually be pretty easy to import it into MM-NEAT. However, before doing that, I recommend making a simplistic stand-alone bot based on the tutorial here: http://www.pacmanvghosts.co.uk/guide_eclipse.html

Which is part of this larger guide: http://www.pacmanvghosts.co.uk/guide_home.html

Try following their guide to make a simpler starter bot, make comments here updating your progress, and let me know when you're done so I can help you integrate this code into MM-NEAT.

**Comment by Squillyprice01** [comment]
We have working bots for both Mrs. Pacman and the Ghosts! I think this code is ready to import into MM-NEAT. @schrum2

**Comment by schrum2** [comment]
Keep track of problems going on with your issues. For example, you should have made a comment here explaining how we were having trouble importing the new pacman code because there were some package name conflicts with the old pacman code. Tracking this kind of information in your issues will be especially important later in SCOPE when I am not spending the whole day with the team.

**Comment by schrum2** [comment]
I refactor/renamed all existing pacman packages to make way for the new versions. We should be able to incorporate that code now.

**Comment by Squillyprice01** [comment]
All of the PO Pacman code is now neatly ( 💯 ) in the MM-NEAT repository. Now it is time to evolve an agent!

**Comment by schrum2** [comment]
Besides the GameFacade and the Ghost team, the other major class that needs to access the PO code is the ExecutorFacade.

**Comment by schrum2** [comment]
Since we can technically evolve an agent, I'm actually going to say that this issue is closed, and that all remaining work should be handled by separate, more specific issues going forward.
