### ISSUE TITLE
Thoroughly comment the edu.southwestern.tasks.ut2004.sensors package

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#210]
You may want to do this before #209 since this will familiarize you with the relevant code first.

**Comment by friedmaa** [comment]
I think this has been done, but please check @schrum2

**Comment by schrum2** [comment]
Tidy up the edu.southwestern.tasks.ut2004.sensors.blocks package too. Suppress warnings as well (I've already done this in some of these files ... see my commit)

**Comment by schrum2** [comment]
Note that Eclipse gives suggestions of how to suppress the warnings for you. You do not need to type in the actual suppress commands
