### ISSUE TITLE
Directly Encoded CNNs in Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#212]
When Lauren did the Tetris research, we also did a baseline (unpublished) in which we evolved using plain NEAT and raw features, but we initialized the networks to have the same structure defined by the HyperNEAT substrates. This was done be defining a HyperNEAT seed task (look in Parameters.java and MMNEAT.java to see how this is set up ... there may also be a batch file somewhere).

This approach did not work well with fully connected networks, but perhaps it would work well using CNNs (haven't tried this yet). In fact, some similar work by Uber AI indicates that an approach like this should be successful: https://arxiv.org/abs/1712.06567
I'd like to think we could do at least as well as the previous results, since the benefits seem to come from using CNNs

**Comment by DevonFulcher** [comment]
JUnit test confirms correct behavior
