### ISSUE TITLE
PO Pacman text warnings

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#214]
I saw this message when evolving PO Pacman:

How should we handle this situation? NodeCollection.addExtraNodes()

This either means that we still are not handling some sensor correctly, or that you are printing a warning message even though the sensor works fine now. Figure out what the issue is and fix it.

**Comment by schrum2** [comment]
Similarly, I saw the following output:
```
New Maze
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
```

etc.
This should be removed

**Comment by Squillyprice01** [comment]
The problem was that, although the pill model was finally working, the GetActivePillsIndices method in gameFacade was not using it. When pacman couldn't see any pills, it was causing errors. The getActivePillsIndices method now uses the pill model.
