### ISSUE TITLE
Improving the ghost model

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#216]
Here are some ideas for improving the ghost model.

Based on the visualization, it looked to me as though after Pac man ate a ghost, her ghost model was trying to find where the ghost had gone still but this doesn't make sense.

We should also try to sense the ghosts as they leave the lair at the start

**Comment by schrum2** [comment]
Other improvements: if an edible ghost enters the field of view and then leaves it, then Ms. Pac-Man needs to remember that the ghost was edible and keep chasing it.

**Comment by schrum2** [comment]
Please provide an update on the state of this issue. What can Pac-Man currently sense about the ghosts? Is there anything left that we would still like to sense?

**Comment by Squillyprice01** [comment]
I am going to try to add a way of approximating a sense that the ghosts have left the lair. Another thing that would be good to add would be if pacman senses a threat ghost but eats a pill, that threat should turn into an edible ghost

**Comment by Squillyprice01** [comment]
There are some bugs in the ghost model right now. Sometimes ghosts suddenly seem to become edible in the model when they shouldn't be...

**Comment by Squillyprice01** [comment]
The Ghost model now works correctly without the bug causing ghosts to randomly become edible. Ghost predictions also dynamically update when a pill is eaten even if the ghost is not visible.

**Comment by Squillyprice01** [comment]
At this time, there is only one thing to improve for future SCOPE participants and/or me in the future. Edible ghost predictions move at the speed of threat ghosts even though the edible ghosts themselves move at a reduced speed.

**Comment by schrum2** [comment]
This last part of the issue has been moved to #272 so that this issue can remain closed.
