### ISSUE TITLE
Competative Coevolution in PO Pac-Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#22]
After completing #21 try to co-evolve Ms. Pac-Man vs the Ghosts

**Comment by schrum2** [comment]
This issue has actually been in the system for a while, but now that you've integrated the PO code, we could actually pursue it. The idea is to have multiple evolving populations. One for Ms Pac-Man, and one for each ghost (or one population representing the ghost team ... there are a lot of options). Of course, this approach would require us to think up a lot of sensors for the ghosts as well. We probably want to focus on Pac-Man alone first.

**Comment by Squillyprice01** [comment]
The Ms. Pac-Man agent is ready to go. See #248 to see the state of the ghost team development.

**Comment by schrum2** [comment]
No longer interested in evolving the ghosts.
