### ISSUE TITLE
Create a sensor that measures time remaining

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#221]
What type of block should this extend?

**Comment by Squillyprice01** [comment]
Sensor TimeLeftblock in edu.southwestern.tasks.mspacman.sensors.blocks.time does this. Added it to POChechEachDirectionMediator

**Comment by schrum2** [comment]
Give some indication that this works by describing how it behaves in a post watch.

**Comment by Squillyprice01** [comment]
I observed a post watch. It works by having the sensor staring at 1, and slowly decreasing to zero as time progresses through the match. A sensor reading of zero indicates the end of the game.
