### ISSUE TITLE
Refactor Substrate Connectivity to use a custom SubstrateConnectivity class

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#223]
Currently, substrate connectivity is defined by a list of ``Triple<String, String, Boolean>``. I want you to refactor the code to replace all such occurrences with a custom class named SubstrateConnectivity (put in the same package where Substrate is located). This will required changing details in lots of places, but will make future changes easier, and hopefully make the code easier to read.

The SubstrateConnectivity class should have different constructors corresponding to different types of connectivity. An int should designate the connectivity type as either CONNECTION_TYPE_FULL or CONNECTION_TYPE_CONVOLUTION (these will be static final constants with arbitrary values), and there should be Strings for the sourceSubstrateName and targetSubstrateName. You can make all of these fields public, but make them final so that they can't be changed after construction.

Be sure to define a toString method for troubleshooting as well.

Replacing all of the Triples with this new class will likely be a massive refactoring task, but I think it needs to be done before moving on.

**Comment by DevonFulcher** [comment]
This is done. Tomorrow, I will test with a batch file and post watch

**Comment by DevonFulcher** [comment]
Everything seems to be working fine.
