### ISSUE TITLE
Refactoring how HyperNEATTasks provide substrate information

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#225]
After #223 (but not necessarily before #224 ) refactor the HyperNEATTask by REPLACING the getSubstrateInformation method with three distinct methods: getInputSubstrateInformation, getHiddenSubstrateInformation, and getOutputSubstrateInformation. To keep it easy to access the original list of all substrates, you can add a static getSubstrateInformation method to HyperNEATUtil that takes a HyperNEATTask and then simply calls each of these three methods, adding the results to a single list.

This will require you to modify pretty much every domain that is a HyperNEATTask, so feel free to ask me about how to do this if you run into challenges.

However, the main benefit of having these three distinct methods is that a lot of the complex manipulations in your FlexibleSubstrateArchitecture can be avoided. In fact, methods that are unnecessary as a result of these changes should be removed.

**Comment by DevonFulcher** [comment]
This will be done in dev_vizdoom after dev_tetris is merged with dev then pull requested into dev

**Comment by schrum2** [comment]
Delay this task in favor of work on the Infinite Art Gallery

**Comment by schrum2** [comment]
HyperNEAT is pretty irrelevant at this point, so it makes sense to just close this issue
