### ISSUE TITLE
Visualize module usage in PO PacMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#229]
You basically want to copy the visualization that is already available in the old pacman code to PO pacman. The results should look like the movies here:
http://nn.cs.utexas.edu/?ol-pm

From what I recall, there are different options. Either you can assign a color to each module, or you can have a color path only show up when a particular module is used.

Note that this visualization is an option both with multitask modules and with preference modules.

**Comment by Squillyprice01** [comment]
Using the parameter modePheremone:true makes this work, even with the new code!
