### ISSUE TITLE
Create more BotActions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#238]
Before making the team controller #227 you should work on some individual BotActions that might be useful. Basically, for any low level behavior you think of in your brainstorming, make an individual BotAction that carries it out. Things like FOLLOW TEAMMATE, SHIELD TEAMMATE, ATTACK ENEMY, etc.

**Comment by schrum2** [comment]
Regarding this. The utopia.agentmodel.actions package has all of the Actions that UT^2 uses. These actions are not compatible with the BotActions used by our evolved agents, but they are a good collection of basic actions. Start by converting each of these Actions into a BotAction in the same package as the other BotActions. Do not change anything in the utopia packages for now.

**Comment by schrum2** [comment]
Look carefully at the OldActionWrapper class in the latest commit. It should allow you to use any of the old actions in your controllers. You no longer need to translate the old utopia actions into new BotActions now.

**Comment by friedmaa** [comment]
given the fact that I am able to use the old actions, and have not found a need to make specific new ones, I think this issue can be closed.
