### ISSUE TITLE
Team sensors: communicate agent locations on client side

### ISSUE THREAD

**Issue by friedmaa** [schrum2/MM-NEAT#242]
The idea behind this is to allow teammates to share location data outside of simply making visual contact with eachother. This is meant to be comparable to the way humans on a team together will communicate outside the game to coordinate their movements, ie "where are you?" "I'm on the bridge"

**Comment by schrum2** [comment]
These need to go in a new subpackage:
edu.southwestern.tasks.ut2004.sensors.blocks.team

Start with something simple, like NearestTeammateBlock, but only add one sensor: distance to the nearest teammate.

However, the trick with this sensor block is that it needs to store some data structure that is shared by all members of a team. This can be passed into the class when it is constructed. Then, whenever incorporateSensors is called, each team member will update their location information within the shared data structure.
