### ISSUE TITLE
Convolution using substrate x/y inputs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#243]
It came up in the presentation that I'm using coordinates relative to the receptive field instead of relative to the whole substrate when making CNNs. However, we could choose to encode NNs the same way that Full HyperNEAT does, but simply not query links that would not be part of a CNN architecture.

Add this as a boolean command line parameter.

**Comment by schrum2** [comment]
The place to implement this is in convolutionalLoopThroughLinks.

Specifically, there is currently code that has two options:
```
if(convolutionDeltas) {
   ...
} else{
   ...
}
```

You need to add a third option that defines the CPPN inputs using a different scaling approach. In fact, in the convolutionDeltas approach, ILocated2D scaledSourceCoordinates is calculated ... you can use these values directly rather than do additional arithmetic, as is currently done.

**Comment by DevonFulcher** [comment]
I don't quite understand how to implement this one. I added parameter convolutionCoordinates and some code in HyperNEATCPPNGenotype but i need some guidance.

**Comment by schrum2** [comment]
What is the status of this?

**Comment by DevonFulcher** [comment]
I was going to run a batch file on Friday but I already had a lot running. I will start one on Monday and post watch to ensure that everything is okay. Then I will close this issue.

**Comment by DevonFulcher** [comment]
Post watched and everything seems ok. I will update you on the performance once it is done training.
