### ISSUE TITLE
Ability to evaluate agents across multiple maps in sequence

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#247]
In UT2004Task, make a new method evaluateMultipleGenotypesAcrossMultipleMaps that takes the same parameters as evaluateMultipleGenotypes except that the String map is replaced with a ``String[]`` of several map names. The method should have a loop that calls evaluateMultipleGenotypes with each map.

Then, the trick is to take the ``Pair<double[], double[]>`` that is returned by each individual call, and combine them all into a single ``Pair<double[], double[]>``. There is a static method aggregateResults in NoisyLonerTask that can do this for you. The aggregation statistic to use should be Average.

Once this method exists, talk to me about when/where/how to use it.

**Comment by schrum2** [comment]
This method can indeed run agents in one map, and then another. Here are the next steps.

Make a new package: edu.southwestern.tasks.ut2004.maps

Put an interface called MapList and give it a single method: String[] getMapList()

Then, define a single example that implements this interface and returns a list of maps that you find useful to evolve agents on. For example, SmallMapSequence could return a short list (about 3) of several small maps.

Once an example exists, you can define a class parameter in the Parameters class called "utMapList" and give it a default value of null.

Then, in the oneEval method of UT2004Task, if the mapList param is null, then we just do what we are already doing. Else, we would call evaluateMultipleGenotypesAcrossMultupleMaps instead and return the result it produces.

Be sure to commit between all intermediate steps in this todo list

**Comment by friedmaa** [comment]
@schrum2 can you please take a look at this?

**Comment by schrum2** [comment]
Evaluating in multiple maps clearly works from BotPrizeServer, but we want to be able to evolve across several maps in sequence. Does this work? Why or why not?

**Comment by schrum2** [comment]
Close this one if testing indicates that it is stable

**Comment by friedmaa** [comment]
Needs to be tested more on monday, I know it works with single maps, but will test will minute long matches on a bunch of different maps to make sure it changes over.

**Comment by friedmaa** [comment]
see issue #275

**Comment by schrum2** [comment]
With #275 solved this issue can be closed again.
