### ISSUE TITLE
Create OldToNewGhostIntermediaryController

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#249]
It will be a MASController consisting of four of the agent ghosts we design.

**Comment by Squillyprice01** [comment]
As can be read in the description of the last push:

Created OldToNewGhostIntermediaryController. As of right now, it takes a SharedNNGhosts<T> as its constructor. This is given to it in the only place it is constructed, MsPacManTask. The idea behind this class is that all of the decision making logic will be performed in this class. It contains four ZombieControllers and a MASController  made up of those four ZombieControllers. This class will set the moves of each of the zombies (one per ghost). When the MASController calls the getMove method, it will return those moves given to the Zombies by this class.

**Comment by Squillyprice01** [comment]
This is the class to work on to create a ghost team. There is work to be done still.

**Comment by schrum2** [comment]
Since this is not complete, the issue will stay open.

**Comment by schrum2** [comment]
No longer interested in evolving the ghosts.
