### ISSUE TITLE
Create a mediator for the ghost team called POGhostsCheckEachDirectionMediator

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#251]

**Comment by Squillyprice01** [comment]
As can be read in the description of the last push:

Created POGhostsCheckEachDirectionMediator

**Comment by schrum2** [comment]
Turns out that GhostControllerInputOutputMediator already exists. Are you making use of it?

**Comment by Squillyprice01** [comment]
POGhostsCheckEachDirectionMediator is a carbon copy of GhostControllerInputOutMediator as of right now. I want to get evolution under the new conditions up and running before I start tweaking POGhostsCheckEachDirectionMediator .

**Comment by Squillyprice01** [comment]
POGhostsCheckEachDirectionMediator will fill the same role as POPacManCheckEachdirectionMediator when complete. This requires building sensors for the ghosts. This class is where those sensors would be added.

**Comment by schrum2** [comment]
This will remain open for someone else to handle in the future.

**Comment by schrum2** [comment]
I don't think anyone will be handling this in the future.
