### ISSUE TITLE
Create "Zombie" Individual Ghost Controller Class 

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#252]

**Comment by Squillyprice01** [comment]
As can be read in the description of the last push:

Created ZombieGhost.java. These are the ghosts that return moves set by the OldToNewGhostIntermediaryController. I am not sure how this code will ever interface with Piers competition code but this is the only way I could interface with our code.

**Comment by schrum2** [comment]
What is the state of this one?

**Comment by Squillyprice01** [comment]
This class exists and is used in OldToNewGhostIntermediaryController.
