### ISSUE TITLE
Add handling for evolving a ghost team with the new PO code

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#253]

**Comment by Squillyprice01** [comment]
As can be read in the description of the last push:

Added a classOption in Parameters.java called staticPacManPO. It builds a starter pacman to evolve against.

Altered MMNEAT to not crash when trying to evolve ghosts.

Added a constructor to GhostControllerFacade that takes an OldToNewGhostInterMediaryController.

Added methods getAction and getMove to NewGhostController in a similar fashion to NewPacManController. Because many classes extend NewGhostController, I added the unimplemented methods to each. getAction and getMove will never be called except by my new code, so this addition is backwards compatible. The files affect are:

AggressiveGhosts.java
BetterLegacy.java
SharedNNCheckEachDirectionGhostsController.java
ChaseFleeGhosts.java
DeterministicLegacy.java
RandomGhost.java
StarterGhosts.java
VeryRandomLegacy.java

**Comment by schrum2** [comment]
SharedNNCheckEachDirectionGhostsController.java

Being reminded of the existence of this file makes me think that I maybe did actually have some code in place for evolving the ghosts. Investigate this and try to avoid duplicating code. See if you can evolve a ghost in the old version of pacman. If so, then try to integrate your code with this code if possible.

Sorry for not remembering that this existed.

There is even a GhostControllerInputOutputMediator class. Specifically, GhostsCheckEachDirectionMediator looks like it might even collect relevant sensors.

**Comment by Squillyprice01** [comment]
I managed to run the old code and there was definitely some evolution happening. However, when I try to run a post eval watch, I get the following error:

![screenshot 29](https://user-images.githubusercontent.com/15305479/41782393-bab20614-75ff-11e8-9afd-57aa01254dc0.png)

**Comment by schrum2** [comment]
No longer interested in evolving the ghosts.
