### ISSUE TITLE
Ability to define the threshold in SubstrateConnectivity

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#254]
This would allow for more possible custom architectures.

**Comment by DevonFulcher** [comment]
Although lately, I have been thinking that defining very specific custom architectures is antithetical to the goal of machine learning. We should work on ways to improve performance without human intervention. With that being said, our foremost goal should be getting better results no matter the method.

**Comment by schrum2** [comment]
We are manually looking for architectures so we can figure out how to search the space of architectures via evolution. This early discovery phase will hopefully lead to better techniques later.

**Comment by DevonFulcher** [comment]
Perhaps the stride could be a data member of SubstrateConnectivity as well.

**Comment by schrum2** [comment]
Having a custom link threshold for each evolved network doesn't seem like a very productive option to pursue. Same goes for the stride. I'm simply going to close this issue ... it's possible that at a later date, an idea to do something similar will re-emerge, but I won't count on it.
