### ISSUE TITLE
Unit test cascade expansion behavior against hidden skips hidden

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#260]

**Comment by schrum2** [comment]
Generalize the behavior as per my comment first: https://github.com/schrum2/MM-NEAT/commit/575c005acb6ccb3d87d1fddb41b9e4761f0813a2

**Comment by DevonFulcher** [comment]
The behavior of a cascaded network has been fully tested without using custom architecture hidden skips hidden.
