### ISSUE TITLE
Connecting the Cascade Neurons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#261]
I've run several cascade expansion tests with switch points of both 50 and 100. The performance is nearly identical to that of standard D1W1, and when you look at the champion networks the reason is obvious: No complete links are going through the new hidden substrate to the output. Sometimes there are links into the new substrate, and sometimes there are links out, and in very rare circumstances you have a bit of both, though most of the substrate is still grey (disabled).

This isn't too surprising. It relates to your concern about being stuck in a local optimum. The cascade neurons are not connected to start, so it is easy to avoid creating any links. In fact, new links will likely be detrimental at first. However, if you forcibly connect the neurons, then evolution could be forced to use them.

Here is the issue: Add a new command line parameter numIncomingLinksForCascadeExpansion. The default value should be 0, which corresponds to our current behavior. However, if this number is non-zero, it means that for each new cascade output neuron, there will be that many incoming link connections from randomly chosen neuron sources.

If these new neurons affect the network behavior, then evolution will have to find a way to use them. I would actually recommend testing a numIncomingLinksForCascadeExpansion value of 1 just to see what happens. Note that this change probably will result in fitness drops at the cascade switch point, but evolution will hopefully recover afterward.

**Comment by DevonFulcher** [comment]
This has been implemented, but untested. Maybe when we figure out how to evolved cppns and phenotypes in tandem numIncomingLinksForCascadeExpansion would be better served as a probability than a discrete number?

**Comment by schrum2** [comment]
Some comments on the commit:
https://github.com/schrum2/MM-NEAT/commit/a991bf744f82862a040374416182321c040471e5#diff-9cf4198bf0528b635074b8ddad75c008R1330

Maybe, but we can probably get away with a value of 1 or 2, so let's just try that first. We will eventually add a mutation probability for cascade expansion, but that is part of issue #188

**Comment by DevonFulcher** [comment]
This has been implemented and visually tested.
