### ISSUE TITLE
Pac-Man batch files for PO Pac-Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#264]
The batch\MsPacMan subdir contains some batch files specifically for post evolution analysis of Ms. Pac-Man results. I don't know if these work for PO Pac-Man, but I want you to check and document which ones work and which ones don't. Then, if any don't work, try to make them work.

This file explains what they are supposed to do:
https://github.com/schrum2/MM-NEAT/blob/master/TUTORIAL.md

**Comment by schrum2** [comment]
Is this task complete?

**Comment by Squillyprice01** [comment]
postBestEval.bat works
postBestObjectiveEval.bat works
postBestObjectiveWatch.bat works
postBestWatch.bat works

More to come

**Comment by schrum2** [comment]
I'm mainly interested in knowing if the record and replay options still work ... I would not be surprised if they didn't, but want to know.

**Comment by Squillyprice01** [comment]
just kidding its in the MsPacMan batch files

**Comment by Squillyprice01** [comment]
postReplay did not work on either of the agents I am evolving. I will try running a recording batch file.

**Comment by schrum2** [comment]
Indeed ... I don't remember the details, but you have to record a game before you can replay it. I am certain that the new PO PacMan code supports this option, but we may not be activating it in the current MM-NEAT code (we almost certainly aren't). However, you should be able to figure out how to record and replay a game.

**Comment by schrum2** [comment]
This is no longer vital to complete before SCOPE ends. However, the outstanding piece of work is to be able to record a game play, and then replay those recordings.

**Comment by schrum2** [comment]
This issue is no longer relevant enough to keep on the list.
