### ISSUE TITLE
Batch files for thorough PO Pacman experiments

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#265]
In the base batch dir, make a subdir called Experiments-2018-POMsPacMan. Create several batch files here. I may need some guidance from you on what all the appropriate experimental conditions should be. Some of these batch files may be copies of ones you have elsewhere, but renamed. Here is what I think we want (feel free to comment on this issue with recommended changes)

- POMsPacMan-OneLifeConflict-1M.bat
- POMsPacMan-OneLifeConflict-2MPref.bat
- POMsPacMan-OneLifeConflict-3MPref.bat
- POMsPacMan-OneLifeConflict-3MMultitask.bat
- POMsPacMan-OneLifeConflict-MMD.bat
- POMsPacMan-OneLifeSplit-1M.bat
- POMsPacMan-OneLifeSplit-2MPref.bat
- POMsPacMan-OneLifeSplit-3MPref.bat
- POMsPacMan-OneLifeSplit-3MMultitask.bat
- POMsPacMan-OneLifeSplit-MMD.bat

Split vs conflict refers to the sensors (can PO even use conflict sensors?).

All of these should be against ghosts will full observability, but in post evals we can also see how we do against PO ghosts (we just won't evolve against them, unless you really think we should).

What do you think of this list?

**Comment by Squillyprice01** [comment]
We have refined the list to be:

- POMsPacMan-POGhosts-1M.bat
- POMsPacMan-POGhosts-2MPref.bat
- POMsPacMan-POGhosts-3MPref.bat
- POMsPacMan-POGhosts-3MMultitask.bat
- POMsPacMan-POGhosts-MMD.bat
- POMsPacMan-COGhosts-1M.bat
- POMsPacMan-COGhosts-2MPref.bat
- POMsPacMan-COGhosts-3MPref.bat
- POMsPacMan-COGhosts-3MMultitask.bat
- POMsPacMan-COGhosts-MMD.bat

They will all be using split sensors.

**Comment by Squillyprice01** [comment]
I've double checked these files but it never hurts to triple check.
