### ISSUE TITLE
Fix split sensors for PO sensor mediator

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#268]
Split sensors are much more powerful, so we definitely want to use them. The trick is to take your existing ghost sensor blocks and add options that filter ghost locations out from the initial set of possibilities based on whether they are edible or not (looking at the stored edible time prediction)

**Comment by Squillyprice01** [comment]
I added support for the split sensors. I am running a batch file with them overnight to validate that they work correctly.
