### ISSUE TITLE
Saturated outputs in low level features Pacman

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#270]
The output layers of low level Pacman become incredibly saturated with many important inputs turned on. This should be fixed. Node normalization shows promise. Differing activation functions will be tried. This is the answer to issue #4

**Comment by schrum2** [comment]
This issue doesn't seem to be 100% solved, but I am removing the complete before SCOPE ends tag. As far as I can tell, we have some candidate solutions. Using ReLU or ID activation functions seems to prevent the saturation, Nod Normalization also prevents saturation, but might be hurting performance (though we can't be certain this is the fault of Node Normalization ... nothing we do in full screen Ms Pac-Man earns high scores).

There was also some discussion of adding dampening factors on a per layer basis. I don't like this approach, but it is something to keep in mind for the future.

**Comment by schrum2** [comment]
Low-level Ms. Pac-Man doesn't seem like a worthwhile domain to focus attention on any more, especially given that we were applying HyperNEAT to it. The oversaturation is an interesting problem to be aware of if anyone ever works with pacman or HyperNEAT again, but I'm closing this issue anyway.
