### ISSUE TITLE
Failing unit tests for Maven install on Linux

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#273]
```
Results :

Failed tests:   test(edu.southwestern.evolution.mutation.tweann.MeltThenFreezePolicyMutationTest): expected:<false> but was:<true>
  test(edu.southwestern.evolution.mutation.tweann.MeltThenFreezePreferenceMutationTest): expected:<false> but was:<true>

Tests in error:
  test_substrateVisualization(edu.southwestern.networks.hyperneat.HyperNEATVisualizationUtilTest): Can't connect to X11 window server using 'localhost:13.0' as the value of the DISPLAY variable.

Tests run: 232, Failures: 2, Errors: 1, Skipped: 0

```

**Comment by schrum2** [comment]
I've fixed the test_substrateVisualization error by disabling the visualization, but haven't looking at MeltThenFreezePolicyMutationTest yet

**Comment by evolvingfridge** [comment]
After building lasted version, only issue on Debian that caused build failure was MeltThenFreezePreferenceMutationTest, had to disable test in pom.xml.

**Comment by schrum2** [comment]
Thanks for letting me know. This test has been problematic in the past, but it tests a feature that is almost never used. I believe that it only fails probabilistically, but simply disabling it is certainly a reasonable decision.

**Comment by schrum2** [comment]
Closing this. If tests are a problem, then don't Maven compile with them:
mvn -U install -DskipTests=true
