### ISSUE TITLE
Inexplicable crashes when trying to evolve across multiple maps

### ISSUE THREAD

**Issue by friedmaa** [schrum2/MM-NEAT#275]
Usually able to launch, but they will either be stuck in a loop, or will crash after 1 generation.

**Comment by schrum2** [comment]
Wait ... didn't we fix this null pointer? Did you not commit that? @friedmaa

**Comment by schrum2** [comment]
Evolution with a mapList seems to work fine when evolving in a team game with parallel threads turned off. As I said, I think that fixing the null pointer exceptions makes the difference. However, we should also try with parallel threads before claiming the issue is fixed.
@friedmaa

**Comment by schrum2** [comment]
I'm reasonably confident this issue is solved now. I've had some success evolving teams with a map list using parallel threads for a few generations (with reduced population size and eval time). Closing this issue.
