### ISSUE TITLE
CoordConv

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#276]
This intriguing new idea from Uber could be worth implementing, even though we are doing evolution and now backprop:
https://arxiv.org/pdf/1807.03247.pdf
https://eng.uber.com/coordconv/

The idea seems pretty simple. For every layer, add two additional channels that have hard-coded outputs (the weights are still trained though). Specifically, one channel is the x-coordinate for each position, and another is the y-coordinate.

This should be useful for Ms. Pac-Man (Uber applied it to Atari Pac-Man using RL) and maybe also for Tetris.

**Comment by DevonFulcher** [comment]
Our implementation will only work with MSS for now. To make it work with global coordinates, the new coord conv substrates must be put in an intelligent location in vector space. For now, they are just put adjacent to the inputs.

**Comment by DevonFulcher** [comment]
Could you review line 469 of HyperNEATUtil in my recent commit?

**Comment by DevonFulcher** [comment]
CoordConv passes the D1W1 test in Tetris. However, while using the same initial conditions and changing the architecture to D1W2, getSubstrateGenotype in HyperNEATCPPNGenotype is not even called even when coord conv is turned off. I do not know why this is the case. The substrates and connectivities did not appear in the post watch of D1W1 in SZ-Tetris even though the JUnit test passed. I am not sure if this is a problem with the visualization or not.

**Comment by DevonFulcher** [comment]
I am still working on this. Hopefully, I will be able to finish it today or tomorrow.

**Comment by DevonFulcher** [comment]
Tryed to post watch. Got this error. I will finish tomorrow.
Exception in thread "main" java.lang.IllegalArgumentException: node array is out of order!
	at edu.southwestern.networks.TWEANN.getNodesToDraw(TWEANN.java:1202)
	at edu.southwestern.networks.TWEANN.createLayers(TWEANN.java:1029)
	at edu.southwestern.networks.TWEANN.draw(TWEANN.java:978)
	at edu.southwestern.networks.TWEANN.draw(TWEANN.java:849)
	at edu.southwestern.networks.TWEANN.draw(TWEANN.java:845)
	at edu.southwestern.tasks.CommonTaskUtil.getDrawingPanels(CommonTaskUtil.java:45)
	at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:83)
	at edu.southwestern.tasks.LonerTask.evaluateOne(LonerTask.java:151)
	at edu.southwestern.experiment.post.ObjectiveBestNetworksExperiment.run(ObjectiveBestNetworksExperiment.java:54)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:861)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1029)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:989)

**Comment by DevonFulcher** [comment]
I am not sure the best way to fix this issue so I am just going to add a new type of node coordConvNode

**Comment by DevonFulcher** [comment]
Everything seems to be working correctly now. I visually confirmed with Tetris D1W1. Then I tried visually confirming with Tetris D2W2. Everything seemed correct but with so many windows it was hard to tell for sure. With the visualizations and the JUnit tests I am very confident that everything is working correctly.

**Comment by DevonFulcher** [comment]
Here is a picture of Tetris D1W1:
![screenshot 16](https://user-images.githubusercontent.com/24593113/42785652-f0049954-8918-11e8-921c-9b791c795beb.png)

**Comment by DevonFulcher** [comment]
Here is Tetris D2W2:
![screenshot 13](https://user-images.githubusercontent.com/24593113/42785692-0ea8473e-8919-11e8-95b0-d3dbe13e2d9c.png)
![screenshot 15](https://user-images.githubusercontent.com/24593113/42785700-13fd53b4-8919-11e8-8893-93b1f9b7cd7f.png)

**Comment by DevonFulcher** [comment]
I will now focus on testing this in SZ-Tetris and Ms. Pacman as well as many other techniques in Ms. Pacman.

**Comment by schrum2** [comment]
Just based on looking at the images, I can say that jCoordConv is upside down. This probably doesn't really matter, but it should still be fixed.

I look forward to seeing how this runs. If you send me command line parameters I can launch something on the cluster.

**Comment by DevonFulcher** [comment]
The only command line parameter that you need is useConvCoord:true

**Comment by schrum2** [comment]
I guess it doesn't really matter, but from the visualization it is clear that the top has an activation of 0 and the bottom has an activation of 1. Makes one wonder if the coordinate from actually used by HyperNEAT is upside down too, but ultimately it shouldn't matter. Mirroring the coordinate frame shouldn't make the problem any harder for evolution, even though it is the opposite of what we thought we were doing.
