### ISSUE TITLE
Null Pointer Exception in Low Level Ms. Pacman 

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#278]
This exception is not game breaking. The exception is simply caught and the last move is replayed by Ms. Pacman.

**Comment by schrum2** [comment]
Low-level Ms. Pac-Man doesn't seem like a worthwhile domain to focus attention on any more, especially given that we were applying HyperNEAT to it. Not even sure this exception still happens ... there isn't much information on this particular bug.
