### ISSUE TITLE
Halted or Slow Evaluation in Low Level Ms Pacman

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#279]
Many of my tests have seemed to halt mid evaluation around generation 70-100. This doesn't make sense since our Ms. Pacman agent sucks right now and evaluations should happen quickly. This seems to only happen with full screen output but more testing will need to be done to confirm this.

**Comment by DevonFulcher** [comment]
print fitness to debug this issue

**Comment by schrum2** [comment]
Low-level Ms. Pac-Man doesn't seem like a worthwhile domain to focus attention on any more, especially given that we were applying HyperNEAT to it. Guess we'll never figure out why it was running so slow, but there are many inefficiencies in this code.
