### ISSUE TITLE
Save text levels in interactive MarioGAN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#288]
In MarioGANLevelBreederTask the save method is currently unsupported. This is supposed to save a text file version of the Mario level. A similar method in MarioLevelBreederTask (which uses CPPNs) works, but the GAN based encoding is slightly different, and a little bit more work is required in order to save these levels.

Note that this is a left over issue from #283

**Comment by jakeryang** [comment]
Improved save function and it can now differentiate between the two encodings. For the new encoding it uses the tile object in LevelParser. The old encoding still uses the array in GANUtil as OldLevelParser does not provide an easy way to parse from integers to characters.

**Comment by schrum2** [comment]
Could you move that array over to the OldLevelParser to make things more uniform? I don't think a Mario-specific tile representation belongs in GANUtil

**Comment by jakeryang** [comment]
Moved mappings from GANUtil to OldLevelParser
