### ISSUE TITLE
ZeldaGAN: Fitness function for pre-specified paths

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#304]
Provide the user with a way of pre-specifying a chosen path through the maze, then evolve GAN levels that keep this path free, but also maximize other content. Is this a constraint of a fitness function, or both? How to score levels that violate the constraint? How to avoid boring empty levels?

**Comment by jakeryang** [comment]
We're able to implement a way to evolve levels using breadth-first search. However, we need a better way to view the evolved levels.

**Comment by schrum2** [comment]
I think that if we add a check to the task for if CommonConstants.watch is true, then we can make it load and render the level for a human to play in that case. This will allow us to view the final result using the post-watch batch files.

**Comment by schrum2** [comment]
Experience in the CPPN2GAN paper makes me believe that this is not a worthwhile idea to pursue. Maximizing the length of the solution path is more interesting.
