### ISSUE TITLE
Random Zelda GAN Dungeons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#307]
Issue #306 proposes making Zelda GAN dungeons using WFC, which is definitely an awesome long term idea. However, a group from my AI class did something simpler that we might want to import into this code and use as a starting point. They simply take the currently selected rooms and combine them into a random dungeon. The specific code I'm referencing is here:
https://github.com/Sanfordm/MM-NEAT/tree/AI-Zelda/src/main/java/edu/southwestern/tasks/interactive/gvgai
There was supposed to be some posthoc editing of the rooms to make them more traversable as well, but I'm not seeing evidence of that.

We should be careful about what we import from this repo. The code was written quickly on a short deadline, but I want to make sure that the code in my repo stays clean and organized as much as possible. Still, it would be cool to have a "Dungeonize" button that combines several selected rooms into a dungeon.

**Comment by jakeryang** [comment]
We'll have an abstract class to be able to re-use code to be able to make different "dungeonizing" techniques (such as random and WFC). 
We need to have a way of taking different forms of levels, such as latent vectors or 2D arrays of ints or characters, and be able to generate a dungeon out of that representation.

**Comment by jakeryang** [comment]
Ended up using a graph to represent Zelda dungeons (more details in #332). Finally able to go from room to room by making new games. Had to use an "enhanced" Zelda of the original GVG-AI Zelda that added an open door tile that kills the player when touched. When the player is killed the position of the player is taken and used to figure out where to go to next. We still need to incorporate other "dungeonizing" techniques such as WFC, which is another issue #306.
