### ISSUE TITLE
Comment LevelParser and OldLevelParser

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#316]
As we just saw, these files could use some better comments. Provide the necessary javadoc where needed, and try to explain weird issues that you notice. However, if there are confusing magic numbers, etc, it is ok to pose the comments as questions: "Does this correspond to this tile?", "What is this?"

**Comment by jakeryang** [comment]
Added comments and Javadoc as well as improved 'uniformity' code
