### ISSUE TITLE
Add objective for maximizing the number of branch points in ZeldaGAN

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#324]

**Comment by schrum2** [comment]
Though this is no longer a priority, I am going to elaborate on the issue a bit in case someone takes it up in the future. The idea is to evolve real vectors to create individual rooms with the ZeldaGAN, and to have an objective that favors rooms with lots of branching points. 

So, if the maze were searched with breadth first search, we would try to maximize the number of nodes in the search tree with more than two edges.

**Comment by schrum2** [comment]
Evolving dungeons more interesting than the individual rooms. Closing this issue
