### ISSUE TITLE
Incorporate more Zelda features

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#330]
Zelda is a rich and complicated game, and the GVGAI version of it is simplistic in comparison. In order to properly model dungeons in the game, more features are needed. This issue involves enhancing the GVGAI version of Zelda to incorporate more features from the original game.

First, note that the current version of Zelda should not be changed in any way. This issue would involve making a new, enhanced version of Zelda that starts off as a copy of the original version, but incorporates more and more features. Specifically, new features, rules, and sprites would need to be added. The rules for the original game are located in 
https://github.com/schrum2/MM-NEAT/blob/master/data/gvgai/examples/gridphysics/zelda.txt

Rules for other games in this directory can give you an idea of how to enable different types of sprite interactions. For example, in certain Zelda rooms, certain blocks can be pushed (in a particular direction, just one step) in order to open a door, or make an item appear. There are also bombs that can be placed, which will blow up passages through certain tiles (these tiles look like regular wall tiles, but are semantically different). Starting with these mechanics is probably a good idea, since they still take place inside the scope of a single room.

However, the main missing feature of GVGAI Zelda is the ability to move between multiple rooms. To get the experience of a whole dungeon, you need to be able to move from room to room and back again. I don't think that GVGAI can really support this. However, you can define some special game rules for your enhanced Zelda so that whenever you exit a room you "beat" the level, but depending on how you beat the level, you may end up immediately starting to play a new instantiation of the game in a new level. It should be possible to make the transitions fairly seamless to give the illusion of continuous play within a single dungeon.

**Comment by jakeryang** [comment]
Able to copy Zelda ruleset (along with levels) and play the copy fine without having to change much of the code (besides adding it to the string array in Test).

**Comment by schrum2** [comment]
The modified zeldacopy.txt file that you made is not in the repo. The repo does not track text files, so you need to forcibly add it. Go to the directory where it is located and open a Git bash shell, then use ``git add -f `` to force add it

**Comment by jakeryang** [comment]
Added zeldacopy.txt along with level files. Features of zeldacopy so far include : the open door will "kill" the player resulting in a level change, the weapon is now a bomb, but you can fire multiple at a time.

**Comment by schrum2** [comment]
Since working in GVG-AI is rough, I agree that your alternate game interface is better. So, continued work on this issue can take place in the new game interface.

However, definitely keep all work that you did with the GVG-AI version. It should be easy to switch back to the old version by simply changing some global final variable value. Even though the work you've done is incomplete, I don't want to lose it.

**Comment by jakeryang** [comment]
Zelda Features still need to be added:

- Bomb-able walls leading to adjacent rooms
- Movable block tiles
- Key + Locked door system

**Comment by jakeryang** [comment]
Now there's a key + door and bomb-able door system, now we need to generate dungeons + levels in a way that respect the placement of the locked/bomb-able doors.

**Comment by jakeryang** [comment]
More features to consider:

- Enemies can move over water tiles (P)
- Player can attack across water the length of a water tile

**Comment by schrum2** [comment]
Specifically, some kinds of enemies can move over water tiles and others can't. Distinguish between two types of enemies.

**Comment by jakeryang** [comment]
Additional feature to add...

- A ladder item that is automatically placed down over a water tile (tile: 'P') of length 1, allowing the player to cross when they have it

**Comment by jakeryang** [comment]
Ladder tile (represented by a blue '#') is now implemented in the rouge-like version which you can test by running LoadOriginalDungeon (the file name of the dungeon is 'a_test_1'). Still need to implement in A*.

**Comment by jakeryang** [comment]
A* search can now "use" the ladder. You can test comparing the output from LoadOriginalDungeon or run the ZeldaStateTest tests
