### ISSUE TITLE
Zelda Data Cleanup, Manual Fixes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#331]
All level/dungeon data associated with Zelda is in:
https://github.com/schrum2/MM-NEAT/tree/master/data/VGLC/Zelda

This data comes from https://github.com/TheVGLC/TheVGLC

Unfortunately, the level data that the GAN models were trained on has some problems:
https://github.com/schrum2/MM-NEAT/tree/master/data/VGLC/Zelda/Processed
You can compare the data to the images they were derived from to see what I mean:
https://github.com/schrum2/MM-NEAT/tree/master/data/VGLC/Zelda/Original

This data portrays the dungeons as being completely empty with no enemies. However, mistakenly, levels that have statues that look like monsters interpret those tiles as monsters in the data, which is why some GAN generated levels actually do have enemies in them.

The other thing missing from the raw dungeons is information about how you transition between rooms and interact with the environment (push blocks, bomb walls, etc). This information is actually available in these two directories:
https://github.com/schrum2/MM-NEAT/tree/master/data/VGLC/Zelda/Graph%20PreProcessing (Human consumption)
https://github.com/schrum2/MM-NEAT/tree/master/data/VGLC/Zelda/Graph%20Processed (Machine consumption)

These directories provide graphs describing how level rooms are connected, and indicate something about how you transition between rooms.

For this issue, you would NOT change any of the existing Zelda level data, but you would make a copy that you would then clean up and change. Specifically, some of the graph level information needs to be incorporated into the raw tile representation. Essentially, there are tiles in certain Zelda levels that look like normal, generic floor/wall/block tiles, but that have special semantics.

You also need to populate the rooms with enemies according to how they are actually populated, but that information is not available in this data, but it is easy to find:
https://www.google.com/search?safe=off&rlz=1C1GCEA_enUS850US850&q=zelda+level+map+enemies&tbm=isch&source=univ&sa=X&ved=2ahUKEwiGisHo96ziAhUHPK0KHdVmDTIQsAR6BAgIEAE&biw=1920&bih=937
Don't worry about the specifics of enemy type ... just associate different enemy types with different tiles in the data.

**Comment by schrum2** [comment]
I guess this is the issue most associated with your work re-training the GAN on the modified level data. Related to this: Make sure the Dungeonize option works for the GAN rooms trained on the new data. Currently, the code crashes when you try.

**Comment by jakeryang** [comment]
The Dungeonize works for me on the GAN rooms. I suppose the GAN model you're trying has an incorrect number of tiles, there are several that have different tiles and not all of them are supported. Currently, the only one that works (for me at least) is 'ZeldaFixedDungeonsAll_5000_10.pth'

**Comment by schrum2** [comment]
Hmmm, it works for me now too. I'm not sure why I was having problems before. However, I will say that if there are any GAN models left over that are crappy or buggy, then we don't need to keep them. Just keep the good ones.

**Comment by jakeryang** [comment]
Just converted dungeon 5 from the original Zelda. From this point on, Link now has the step ladder at all times. I placed a step ladder in the corner of the first level. Additionally, dungeons 5 and up (including dungeons from quest 2) now have adjacencies that go across the dungeon (like from one corner to the other). There are some parts of the dungeon that are unreachable and won't show on the final map in the rouge-like game. These unreachable parts weren't a problem in dungeon 5 and the Zelda A* was able to complete the dungeon. However, these unreachable parts might be an issue in later dungeons.

**Comment by jakeryang** [comment]
In Dungeon 6, there's an "across" the dungeon adjacency where there the triforce is and you can't go there without the adjacency. So I implemented a way to use that adjacency as if the two rooms were together by adding new keywords to use in the .DOT file and how to use them in the code. Now the adjacencies works and you can complete the level. However, not all of the levels show up on the overall dungeon map even though the .DOT file is correct.

**Comment by jakeryang** [comment]
The generated dungeon map correctly places all of the levels where they need to be according to the original map.

**Comment by jakeryang** [comment]
The A* Star agent on Dungeon 6 takes a while to complete, even though it has an average path length compared to the other dungeons.

**Comment by schrum2** [comment]
Please update this issue regarding the progress I know you've made

**Comment by jakeryang** [comment]
Zelda Dungeons 1 through 7 (from Quest 1) have been finished, still need to do 8 and 9 from Quest 1.

**Comment by jakeryang** [comment]
Dungeon 8 has been completed. Only dungeon remaining from Quest 1 is Dungeon 9.

**Comment by jakeryang** [comment]
Dungeon 9 has been completed. This was the last dungeon in Quest 1 which is fine for now. Closing.
