### ISSUE TITLE
Zelda Dungeon with a Graph

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#332]
We already discussed setting up Zelda to support dungeons represented as graphs. As mentioned in #331 , the Zelda level corpus data already has graph representations for all of the original dungeons.

Therefore, a good starting point to see how well this approach works is to have a way of loading a specific Zelda Dungeon graph from VGLC and playing it. This will probably require you to do a bit of issue #331 first in order to have access to all the data that is actually necessary to construct a functioning dungeon. For example, in the first dungeon, the graph information indicates that you can push a block in one of the rooms to open up a passage, but the actual tile representation of the level doesn't indicate which block this is.

Refer to YouTube videos and other online resources to figure out how to encode this data.

**Comment by jakeryang** [comment]
Have a hashmap of string and nodes, with nodes being the level representation, the name and another hashmap of strings (the exit point) and a pair representing where to go to the next level and starting point of that level.

**Comment by jakeryang** [comment]
Able to represent Zelda dungeons as graphs. Still need to incorporate original Zelda features and need to be able to load original Zelda dungeons.

**Comment by jakeryang** [comment]
Representing Zelda dungeons as a graph is accomplished, the other things that still need to be addressed are other issues (#336) (#330)
