### ISSUE TITLE
Moving enemies for Rogue-like Dungeons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#334]
Allow for enemies in the rogue-like dungeon version of Zelda. These need to wander the levels randomly and kill (or damage?) the player on impact

**Comment by jakeryang** [comment]
The enemies so far wander randomly making it hard to test whether or not they damage the player. Will add a way for the enemy to approach the player once they get into range.

**Comment by jakeryang** [comment]
Monsters now wander randomly until the player is 4 spaces away. Monsters move and attack diagonally which is unfair for the player, so that needs to be fixed.

**Comment by jakeryang** [comment]
Monsters wander randomly in 3x3 square, monsters move left or right when attacking a player, but there's a 20% chance that it will attack diagonally. This is better than before and will be good enough for now. I would like to have more intelligent and more challenging enemies in the future, but I will be closing this issue for now.
