### ISSUE TITLE
Better Zentangle when "stark" not used

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#335]
The original zentangle code assumed only black and white images. My color enhancement still relies of the presence of pure black for the sake of combining two image patterns. However, this should be based on a brightness scale instead of pure black, so that full color images can at least produce output that is a combo of two sources.

**Comment by schrum2** [comment]
To understand what this issue is talking about, run `PicbreederTask`. Select three images and then press the big Z button. Eventually, an interesting amalgamation of several images will pop up. Next, uncheck the "stark" option and click the big Z again. The result that pops up this time will be less interesting and more uniform. That is what needs to be fixed.

Look at the `zentangle` method in the `PicbreederTask`, and then at the `saveSingle` method. Basically, when saving the image that has "background" in the title, the image produced by the CPPN needs to use the "stark" setting, even if that is not currently checked. A way to handle this is a boolean parameter for `saveSingle` called `isBackground`. If this parameter is true, then in the `saveSingle` method you can set the "stark" parameter to true right before `imageFromCPPN` is called, but be sure to set it back to whatever it was immediately afterward so it does not affect how the other images are rendered.

Note that this is probably an easier place to start understanding the Zentangle code than #611

**Comment by annazwicker** [comment]
The code has been modified to include the new parameter, isBackground in the saveSingle method.  If isBackground is true, then the boolean parameter starkPicbreeder is set to true as well, and then set to the originalValue after imageFromCPPN is called.  The output from PicbreederTask now shows an image similar to when the stark checkbox is checked.
