### ISSUE TITLE
Saving and Loading Zelda Dungeons

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#336]
Have a way of saving and loading Zelda Dungeons in various formats. This can be the GAN created dungeons or the original dungeons. However, this needs to be implemented in a way that it can accept numerous ways of sending in the dungeon and representing it via graph.

**Comment by jakeryang** [comment]
Added way to save and load dungeons as JSON files. The entirety of the Dungeon is saved in this one file. Would like to add more formats in the future.

**Comment by schrum2** [comment]
Is this the same mechanism for loading dungeons from the original game, or can this mechanism only load dungeons saved from this program? Please put some instructions for both of these options into this Issue thread.

**Comment by jakeryang** [comment]
This mechanism can only be used to load the dungeons saved from the program. To use it you go to the Dungeonizing window and use the buttons Load or Save Dungeon.

To load original dungeons, go to edu\southwestern\tasks\gvgai\zelda\level\LoadOriginalDungeon.java and edit the `ORIGINAL_FILE` variable to specify the dungeon name. The dungeon must have a .dot file of the same name in the VGLC's Graph Processed folder. And the dungeon must have a folder of the same name in VGLC's Processed folder. The contents of the folder are txt files named after the number which the level corresponds to in the .dot file. The only two dungeons are supported are named `tloz1_1_flip` and `tloz2_1_flip`.

**Comment by schrum2** [comment]
Is this done?

**Comment by jakeryang** [comment]
This is only usable for JSON formats for now. If that is satisfactory then you can close this issue, otherwise specify what other formats you would like to see.
