### ISSUE TITLE
Respect the original Zelda doorways

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#338]
I interacted with some of the dungeons, and it is weird and unnecessary that you create artificial tunnels through closed doorways that were present in the original levels in order to make open doorways on the edges. In the original game, those doorways actually were the connectors between adjacent rooms. Instead of creating new artificial open doorways (green arches in the rogue-like), adapt the existing doorways (blue T's in rogue-like) so that they actually are the transition points between rooms.

In fact, ideally, when the dungeon is generated you would not add extra doorways at all, but instead only put rooms next to each other if the pre-existing layout already had doors in the appropriate spot ... but I'll make another issue about this.

**Comment by jakeryang** [comment]
Added more edges to the dungeon rooms to be able to go through multiple doors. There is still an artificial means of connecting the dungeons by placing doors if there's an adjacent room. But this a step closer to be able to respect the original doorways.
