### ISSUE TITLE
Add Message system for Zelda rouge-like

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#340]
A Message system would be nice to keep track of what is going on in the rouge-like and if we want to have enemies with a lot of health, the user needs to be able to have an idea of the damage they're doing. This will also help with debugging.

**Comment by schrum2** [comment]
Definitely a good idea for debugging purposes, but remember that the main focus of what we're doing is on AI for level design, so some enhancements for playability might not be necessary.

**Comment by jakeryang** [comment]
A log system has been added and is good enough for debugging. Right now, messages are sent if a creature (including the player) attacks another creature, deaths of creatures, and bombs doing damage. More messages will be sent in the future if features need to be debugged.
