### ISSUE TITLE
Make Zelda GAN support additional tiles

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#343]
Make Zelda GAN support additional tiles from zeldacopy in a way that's backwards compatible.

**Comment by schrum2** [comment]
So, I think we actually went the other way on this. We simplified the tile set to only the aspects that would make for an interesting layout, but we made all tiles associated with functional progress through the level (doors, keys, etc.) but added as part of the dungeon generation process.

If you agree with me, then close this issue.
