### ISSUE TITLE
Consider Minecraft for GAN Generation

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#344]
With Minecraft's voxel-based engine and the multitude of user-generated content, Minecraft is prime ground for GAN generation. Using [MCEdit](http://www.mcedit.net/), we can create a plugin for the program written in Python to get world data, train a GAN, and then place the output of the GAN into a Minecraft world. We can also use '.schematic' files, which is like a part of a Minecraft world which can be read in Java or Python.

We can start with 2D parkour maps (by training them or building our own) and work our way up to 3D parkour maps. Once we implement that we can use other types of structures such as houses and sculptures.

**Comment by jakeryang** [comment]
Here's some more information on 3D GAN creation: https://github.com/nashory/gans-awesome-applications#3d-object-generation

**Comment by jakeryang** [comment]
MCEdit is too painful to setup, will be using '.schematic' files to get parts of maps. The server plugin WorldEdit seemed to have the easiest way to make a schematic file as well as having the simplest schematic format, making it easier to convert the GAN output to a schematic file loadable by WorldEdit. So far I've made a way to convert schematic files to JSON (with the level being represented by a 2D array of ints). Hopefully we can use the existing GAN program created for Mario and Zelda without much change to it.

**Comment by schrum2** [comment]
The existing GAN is generalized for any 2D input, and then it outputs a 3D volume that gets collapsed into 2D. You can think of the 3D output as being a one-hot encoded vector across all of the tile types, and the way that the 3D collapses into 2D is by picking the maximum value in the vector to be the representative tile at those 2D coordinates.

I'm not sure how well this would generalize to 3D. You may need to make a completely new file, but it can probably start as a copy of the original that just gets tweaked slightly.

**Comment by jakeryang** [comment]
Don't have enough time to do this, could do this on my personal time. Closing.
