### ISSUE TITLE
Check if Dungeonize results are beatable

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#347]
Some results from Dungeonize are not beatable, and this is not simply an issue of adding extra doors on the edges of the room. There could be a dividing wall in the middle of a room, but the dungeon could still be beatable if, for example, you leave the problem room and are able to re-enter it via another door.

The solution is to do A* search on the level to see if it is beatable. This has to account not just for position in the room, but for the whole game state across several rooms. However, the key to making this work in a generalized way is to have some kind of State or Node class and a method called getSuccessors that returns a list of all States/Nodes adjacent to the current state. Once this exists, then the A* algorithm is easy to write, but you have to deal with the details of Zelda dungeons in the getSuccessors method (basically, this should be an abstract method that is overridden by ZeldaState or some other similarly named class).

In addition to simply indicating if a level is beatable, we might want to return how far the agent is able to progress before losing. This could eventually be useful as a fitness function for evolving whole dungeons.

**Comment by schrum2** [comment]
Either update the issue thread as you work or tag your commits with the issue number. Just put #347 somewhere in the body.

**Comment by jakeryang** [comment]
So far, I've implanted A* for Zelda Dungeons that finishes with decent results. However, there is a glitch where the agent will dance when it picks up a key.

**Comment by jakeryang** [comment]
A* is now working on randomized dungeons, there is some bug where the name associated with the level isn't really there in the 2D representation of the level, but I haven't but running into that as much anymore

**Comment by schrum2** [comment]
Do we still have bugs here? I think that A* pretty reliably indicates whether or not the level is beat-able. This is why we are currently focused on how to modify levels that cannot be beaten.

Close this issue, unless there are still bugs that need to be addressed.
