### ISSUE TITLE
Playability of randomly generated dungeon

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#355]
To address the _scope_ of the problem. Randomly use the levels from the original game to generate the dungeon to see if the dungeons generated are playable most of the time.

**Comment by schrum2** [comment]
We're able to generate dungeons using either original Zelda rooms of GAN rooms, correct? Indicate how this is done (via some command line parameter I hope) and then close the issue.

**Comment by jakeryang** [comment]
There is a function in DungeonUtil called `convertToDungeon()` that takes a graph with a ZeldaGrammar as it's type and converts it to a dungeon. It also takes a Loader that specifies where the function gets its levels from. Ex: `convertToDungeon(graph, new GANLoader())` to use GAN generated levels as it's levels and `convertToDungeon(graph, new OriginalLoader())` to use random levels from the original data.

I would like to make this as a command line parameter.

**Comment by jakeryang** [comment]
Add command line parameter for the LevelLoader, closing.
