### ISSUE TITLE
Original Zelda Feature: Move Block Puzzles

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#356]
In the original game, the player was able to get to different parts of the level by accessing a door that needs to be moved by a block.

**Comment by jakeryang** [comment]
Need to have block puzzles correlate to a specific event that occurs when you push the block. One event could be unlocking a door when pushed.

**Comment by schrum2** [comment]
So, I know that at least one level has a movable block. Do any others? This issue needs a progress update.

A related issue (which can be dealt with in this thread, or you can make a new one) is the ability of the graph grammar to generate a dungeon that puts a block-push puzzle in the player's way (pushing the block is the only way to open a door)

**Comment by jakeryang** [comment]
Add moveable blocks along with grammar. The graph grammar needs to be fixed to respect the placement in between nodes

**Comment by jakeryang** [comment]
There are working puzzles now that open doors. Currently, the movable blocks are colored "cyan", which work on seed number 15. We need to test for multiple seeds.

**Comment by jakeryang** [comment]
The general idea described from the issue has been implemented with plenty of fixes, closing for now.
