### ISSUE TITLE
Remove all doors from Zelda GAN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#363]
I got a room like this in a dungeon that was created:
![image](https://user-images.githubusercontent.com/8397236/60066359-7c097480-96cc-11e9-93a6-833ce3563774.png)
It looks cool, but that door in the center is non-functional. We need to make it so that the GAN stops producing such content. In fact, I thought you already removed all of the doors from the training data. This is not enough though ... you need to actually change the encoding scheme of the GAN ... it should no longer even be possible to interpret a certain GAN output as a door.

This kind of change runs a risk of breaking certain older GAN models. At the very least, the Java code will need a parameter that allows for a different number of tile types. I know that we already have a "new" and "old" ZeldaGAN encoding. I still want to keep the old one, but if you want to completely replace the new one after making this change (so that there is not a parameter for a newNewGANEncoding) you can ... just be sure to delete any models that use the encoding that no longer works.

Since this seems like a dangerous step to take, you may want to make yet another branch to do it in rather than directly edit dev_zelda.

**Comment by jakeryang** [comment]
The GAN model has been retrained to address this issue. Closing.
