### ISSUE TITLE
Zelda Experiment Launcher

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#367]
I think your progress on Zelda is far enough along to start thinking forward to doing a human subject study as we have discussed. In particular, we need a way to launch the game from the command line for the study.

This was done with Adina's previous UT2004 study. Look at the class HumanSubjectStudy2018TeammateServer and look at how it is launched on line 1030 of MMNEAT.java.

I think we want to be able to launch the code from the command line with parameters for the following (some we probably already have, others may need to be added):
1) Human Subject ID (will also be used as random seed)
2) Specifying whether an original level is played, or a generated dungeon with original game rooms, or a generated dungeon with GAN rooms.

You should also look at the batch files in batch\Experiments-2019-CoG-UT2004 for comparison. Make a subdirectory called Experiments-2019-ZeldaGAN to store new files. The main batch file here is UT2004-Study.bat, which launches portions of an experiment in different orders depending on the subject's ID number, and also sets up ffmpeg to record the screen via UT2004-Record.bat. The file also opens up browsers with survey questions.

Clearly you can't get around to all of that now, but I want you to have a road map for what eventually needs to be done.

**Comment by jakeryang** [comment]
I've done some work on this. Is there still more work that needs to be done on the batch files or can we close this?

**Comment by schrum2** [comment]
For the sake of the study, we don't want the users to know what type of level they are playing. Additionally, different users should not be playing in the same order. Finally, we need to have a way of recording the sessions and logging the data.

The UT2004 study files should give guidance on this. We used ffmpeg to record the screen. Whenever the main batch file was launched, the experimenter provided an ID number. This number was used to determine the order in which the user played the levels (we don't want to have some systematic effect where users always like the last one the most because they are the most experienced by that point, so some should see a GAN level first). We also don't want to give any indication in the text prompts what kind of level is being played.

Eventually, we will also make the script boot up Google Form surveys at appropriate points, but we need to decide exactly what we are going to ask first.

**Comment by schrum2** [comment]
Surveys launch. I think the only thing still needed is recording of the sessions.

**Comment by schrum2** [comment]
I need to see if the recording program can auto-quit when the level is over. Otherwise, it will be the job of the experimenter.

**Comment by schrum2** [comment]
This is annoying. I found this command that kills the ffmpeg process:
`taskkill /F /IM ffmpeg.exe /T`
However, killing the process like this seems to make the video feed lose the last bit of the recording. It generally cuts off in the second to last room before the triforce.

**Comment by schrum2** [comment]
Found a way to successfully close the recording using VPScript. It offers a way to send a key press to a running window, so I send Q to quit and that terminates ffmpeg gracefully.
