### ISSUE TITLE
ZeldaGraphGrammarTest fails

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#371]
This one ran for a while before failing, which I think means that many dungeons were successful. Still, we want all tests to pass.

In general, we're at a point where I want you to go back to doing Maven compiles confirm that everything works. The study we eventually run will be launched from the Maven compiled jar file, so this needs to work.

However, the 100 dungeon test does take a long time. I would say that on the last day after the final commit, we should switch the number of dungeon tests from 100 to 10 so that people won't have to deal with this on every Maven compile.

**Comment by jakeryang** [comment]
Even though it takes a while to get to that point, it's actually seed 6 that crashed. I think this is taking so long is because of the graphs (graph of seed 6 is at the end). This might be due to the way we changed how the graph copies nodes when a rule is being applied.

![Screen Shot 2019-07-04 at 11 12 32](https://user-images.githubusercontent.com/6686189/60679371-fc5a7300-9e4c-11e9-9d4c-ab58d6a13762.png)

**Comment by jakeryang** [comment]
Recent commit fixed the error and all tests now pass within a reasonable time for seeds 1-100. However, we're still getting really wacky graphs (shown below). This doesn't make any sense as the nodes' adjacencies are supposed to be a set with the equality just the id. When looking at the nodes' adjacencies, it shows multiple of the same node.

![Screen Shot 2019-07-04 at 11 55 52](https://user-images.githubusercontent.com/6686189/60680878-b2748b80-9e52-11e9-98c3-48bc177cb10c.png)

**Comment by schrum2** [comment]
Seems like there is definitely an issue with the equals method and/or the copy method. Make some unit tests that artificially instantiate and test individual Node instances to see if you can get to the bottom of it. All of those extra edges shouldn't be there.

**Comment by jakeryang** [comment]
While the issue with nodes is still determined whether it's fixed. The test now passes so you can mvn compile. Closing.
