### ISSUE TITLE
Zelda Enemies disappearing

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#374]
Enemies are randomly disappearing at points causing the a key to not appear

**Comment by schrum2** [comment]
Disappearing during dungeon creation or during actual play?

If it is during dungeon creation, then you should check to see if the V-UV algorithm or breadth-first search (which places those grey X marks) might be overwriting enemy locations.

**Comment by jakeryang** [comment]
This is during actual play.

**Comment by schrum2** [comment]
As I mentioned in #375 the disappearance only seems to happen when I attack an enemy right next to the avatar. Do you ever see them disappear under different circumstances?

**Comment by jakeryang** [comment]
I thought I've seen enemies disappear when they're a block away from me.

**Comment by jakeryang** [comment]
Fixed, and discussed in #375. Closing.
