### ISSUE TITLE
Zelda soft lock error

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#375]
In the first dungeon from the actual game, I entered a room with a soft lock, but then exited it without killing any enemies. When I returned to the room, the enemy was still there and I killed it, but this did NOT open the soft lock. This is a problem that could make levels unbeatable.

**Comment by jakeryang** [comment]
I have trouble recreating this issue. Where was was the soft lock? Can you recreate this issue again?

**Comment by jakeryang** [comment]
I feel like #374 is a related issue. The enemy disappears and the soft-lock doesn't unlock as the room still has the creature in the room.

**Comment by schrum2** [comment]
I'm able to recreate this by using your batch files to play the first dungeon (Eagle). I go left for a key, then go up until the soft lock room, immediately exit, then go back in.

I think you are correct though ... when I am trying to attack an enemy, it sometimes suddenly disappears. I mistakenly thought I was killing it, but it really is just disappearing. This is indeed the cause of the soft lock error.

Is it possible that the enemy is trying to move into the spot occupied by the avatar, but the avatar's presence is overwriting the enemy out of existence?

**Comment by jakeryang** [comment]
When an enemy moves into a player's spot, that's registered as an attack by the enemy towards the player. In the console output, I see that there's still an enemy being updated in the same room when it's not appearing.

**Comment by jakeryang** [comment]
I believe I found the bug. While the enemy creatures had knowledge of the player's current location, whenever it would try to move on to the player, it didn't know the player was there and it moved there anyway causing the enemy to disappear. This has been fixed.
