### ISSUE TITLE
Zelda Enemy Respawn

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#376]
In general, I think that enemies should respawn every time you leave and re-enter a room. I believe this is how the original game worked, but I could be mis-remembering. Any comments @jakeryang? 

In addition to making the game slightly harder, this change could also be necessary if for example the player uses up all bombs, and needs to kill enemies to get more (we should make the player not start with ANY bombs by the way).

**Comment by schrum2** [comment]
Actually, now that I am watching all of these playthroughs it looks like enemies generally don't respawn in rooms.

However, I still want to have some kind of need to get extra bombs. Here is a simple rule: When ever you enter an enemy room with no bombs, enemies spawn there, even if you killed the enemies before.

**Comment by jakeryang** [comment]
Add ability for enemies to respawn when player goes back to room if they have no bombs. Will this be a good enough method to ensure that players have bombs? When playing through it seemed to be enough as there are plenty of enemy rooms.

**Comment by schrum2** [comment]
This should assure they don't get stuck. We have to consider what it will be like now that the wall etchings are gone. Some people could really struggle and waste bombs in a lot of places. However, having new enemies pop up should be enough to assure they have the resources they need.

I feel that we could also have a small random percentage of enemies respawning in any room. There are definitely some rooms (or perhaps certain types of enemies) that respawn, but others that don't.

**Comment by jakeryang** [comment]
> I feel that we could also have a small random percentage of enemies respawning in any room

I don't know how I feel about this. While I get the point, enemies may spawn in rooms like the Triforce room. I think there are plenty of enemy rooms so that they get enough bombs. Enemies still respawn if you don't have any bombs.

**Comment by schrum2** [comment]
I agree that this would be problematic. Can we at least have it so that rooms designated as enemy rooms have a chance of respawning enemies? Either that, or some small percentage of enemy rooms are chosen to be enemy respawn rooms at the start of the dungeon creation.

I think this is sort of how it works in the original game ... from watching playthroughs, it seems that rooms containing certain types of enemies (like bats) always respawn. We don't have enemy types, but we could simply designate certain rooms as having the respawnable type.

**Comment by schrum2** [comment]
I feel like this was implemented before you left ... can we close this?

When I last played, what seemed to happen was that all enemy rooms had a small chance of spawning a bunch of extra enemies, either in an empty room (which would be a respawn) or the first time it was entered (which meant it had twice as many enemies as usual, which was actually kind of cool).

**Comment by jakeryang** [comment]
This has been implemented, I didn't close to wait for you to check it out. It seems fine so I'm closing.
