### ISSUE TITLE
Remove bomb wall etching, and allow bombing everywhere

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#378]
For the sake of the study at least, we don't want the bombable walls to be obvious. They should look like regular walls. Perhaps we need a regular mode and a debugging mode, and the bombable walls are only visible in the debugging mode.

However, if we are going to make the bombable walls indistinguishable from the regular walls, this means we need to have a way to place bombs on any walls, not only the bombable walls. This is currently not allowed, but what should happen is that the bomb is placed on the regular wall and goes through its detonation, but the wall remains afterward.

**Comment by jakeryang** [comment]
This issue has been addressed in a commit, closing.
