### ISSUE TITLE
Extra inputs for 3D shape evolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#38]
For all tasks that evolve 3D shapes (3D object evolver, 3D object animator, and shape innovation) I can add some additional CPPN inputs. Currently, the distance to a voxel from the center of the figure is a CPPN input. However, reading a recent paper that extends EndlessForms indicated that one extension to this standard scheme is to have inputs for distance from the center within 2D slices.

In other words, there should be a distance from center of xy-plane, distance from center of xz-plane, and distance from center of yz-plane.

**Comment by schrum2** [comment]
Still haven't done this, but Bryan did it in the Infinite Art Gallery project, and it seemed to be really cool and worthwhile.

**Comment by schrum2** [comment]
Run `ThreeDimensionalObjectBreederTask` first to get a sense for how it works and what it looks like. Then we can talk about changing it.

**Comment by schrum2** [comment]
We should return to this next week. This should be completed before you work on the newly made #756

**Comment by alejmedinajr** [comment]
I have added the distance calculations for XY, YZ, and XZ using a vertex with 0, 0, 0 coordinates and the distance method. I still need to add these parameters to the methods that need them elsewhere.

**Comment by schrum2** [comment]
See my latest commit message. When you calculate the new planar distance inputs, you need to apply `CartesianGeometricUtilities.centerAndScale` as is done earlier in that same method.

**Comment by alejmedinajr** [comment]
Just fixed this in last commit. The `CartesianGeometricUtilities.centerAndScale` has been applied to the new planar distance inputs.
