### ISSUE TITLE
Zelda Map

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#383]
Have a map item. The overhead map is not visible until the player has picked up the map (or at least, rooms that have not been visited are not visible).

For the original dungeon, the text data will have to specify where the maps are located.

For randomly generated dungeons, simply place the map in a room that is not the triforce room, and is at least 2 (or maybe just 1?) rooms away from the start room.

**Comment by jakeryang** [comment]
Should we have a requirement for the A* to have the map before going to the goal? If we don't have a way to visit it programmatically then the V-UV algorithm won't pick up on it and may leave the map item unable to be accessed.

**Comment by schrum2** [comment]
Good point. I agree that we need to assure it is reachable.

**Comment by schrum2** [comment]
It might still be cool to add a map item, but if we do, it should be handled by the graph grammar. That makes this issue related to #445 but fairly low priority. This addition isn't really enhancing the research, though it could make the levels a bit more interesting.

**Comment by schrum2** [comment]
Since this is just a gameplay change and not really relevant to research, I'm closing it without completing it.
