### ISSUE TITLE
Puzzle Blocks always tied to doors

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#384]
I played a randomly generated dungeon (using original rooms) and there was a puzzle block, but it didn't affect a door. Is a puzzle block a tile type? Basically, I'm wondering if the block was a puzzle block because any instance of that particular room would have the puzzle block. In any case, these should only be present when they actually do something.

**Comment by schrum2** [comment]
Related to this. I was in a dungeon that was graph generated, but using rooms from the original game. This room had a block puzzle. However, it also happened to be a room from the original game that contained a block puzzle. I pushed the block that is pushable in the original game, and the puzzle door unlocked. Then I moved and was also able to push the other pushable block, though nothing happened when this was pushed.

We want a one-to-one correspondence between puzzle blocks and locked doors. There are two solutions. One is to not allow blocks in original rooms to be pushable ... the only pushable blocks are ones we explicitly add afterward (randomly). However, I think a better approach which is a bit more true to the idea of using the original rooms is to use any existing puzzle blocks if the room needs one, and to only add a new puzzle block if the room does not have one.

And, as was the original point of this issue, puzzle blocks in rooms with no puzzle door should just become regular blocks.

**Comment by jakeryang** [comment]
The way it works currently is that when a puzzle locked door is placed, a puzzle block is placed. So I just remove all of the puzzle blocks when the original levels are loaded. I can fix this to if the room has a puzzle block, then don't place one.

**Comment by schrum2** [comment]
I think our generated dungeons deal with puzzle blocks just fine. The problem here is how the levels from the original game are loaded, but that issue is no longer worth pursuing.
