### ISSUE TITLE
Do puzzle rooms never have enemies?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#386]
It seems as though the randomly generated puzzle rooms never have enemies in them. I think it would be more interesting if there were enemies in these rooms. Otherwise, it's a bit more obvious that you need to find a puzzle block, but if enemies are distracting you, you may not think to look for a push block right away.

Of course, we could have separate symbols for puzzle rooms with and without enemies, but I think the easy solution which should require minimal code change is to just put enemies in all puzzle block rooms.

**Comment by jakeryang** [comment]
This has been implemented and works well. I was too focused on the enemies to realize that it was a puzzle room
