### ISSUE TITLE
Allow for different width and height of receptive field

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#39]
This seems like it could be particularly beneficial in Tetris, which is taller than it is wide.

**Comment by DevonFulcher** [comment]
Where can this be found? It is difficult for me to find specific items within all of the packages without a specific path or a name of the package.

**Comment by schrum2** [comment]
There is a parameter receptiveFieldSize in Parameters. This needs to be replaced with two separate parameters. When doing this, you will also have to replace all batch files that use this parameter.

Both the Java source files and the batch files that use this parameter can be found using the Search functionality of Eclipse. Specifically, use "File Search"

**Comment by schrum2** [comment]
This actually seems like a comparatively simple issue that I would like you to look in before exploring some of the more complicated convolutional architecture issues @DevonFulcher

**Comment by DevonFulcher** [comment]
This is done. Did a post watch to test and it seems to work fine.

**Comment by schrum2** [comment]
Indeed, I did a test with a height 5 and a width 3 and the convolutional receptive fields were clearly rectangular. Good:
![image](https://user-images.githubusercontent.com/8397236/41170194-e5e154ba-6b10-11e8-80ca-a06354d9af2c.png)
