### ISSUE TITLE
Explore Novelty of GAN Levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#393]
This paper: http://ieee-cog.org/papers/paper_128.pdf

Measures the Novelty of several levels created with a GAN in a similar style to the Mario GAN approach. We need a way to measure the novelty of levels produced by the Mario and Zelda GAN approaches. Might also want to measure KL Divergence.

**Comment by schrum2** [comment]
@jakeryang has put some work into this: ef1c76941b1bbfcfab28aaa86a3d204f07a84c55

Future work on this issue should tag it.

As for the current work, I think there is a misunderstanding concerning the ``calcNeighbor`` method. Is this calculating the neighbor based on proximity in the dungeon? The k-nearest neighbors are meant to be the k rooms whose distance in novelty space (novelty distance) is smallest.

In other words, you need to calculate ``oneRoomNovelty`` between all pairs of rooms, and the k-nearest neighbors are the rooms whose ``oneRoomNovelty`` distances are the smallest. In fact, this method should probably be renamed to reflect this. 

It would also be nice to have a method like ``dungeonNovelty`` but whose input is a set or list of rooms, but not necessarily a dungeon.

Also, make some unit tests. In particular, verify that a room always has a distance of 0 from itself, and calculate distances between some known rooms. Verify that exiting doors do not matter by comparing rooms with different door configs but identical inner portions.

**Comment by jakeryang** [comment]
> As for the current work, I think there is a misunderstanding concerning the `calcNeighbor` method. Is this calculating the neighbor based on proximity in the dungeon? The k-nearest neighbors are meant to be the k rooms whose distance in novelty space (novelty distance) is smallest.

It's calculating its neighbor based on its position in the list of rooms, I'll change it so it's by novelty.

**Comment by schrum2** [comment]
I fixed the "neighbor" issue, but encountered another problem.

If you run the code in DungeonNovelty now, then it prints out the novelty value of each room before printing the average across the dungeon. However, the values change slightly each time.

Some random aspect of the dungeon generation must be influencing the roomDistance calculation. Note that the randomly placed enemies, and the placement of the player avatar should not be part of the roomDistance comparison calculation. This calculation should be completely deterministic.

Can you fix this Jake? @jakeryang

**Comment by jakeryang** [comment]
It seems like you were messing with an entire different codebase, because that issue was fixed and the fix is gone in the latest commit. I'll commit another fix.

**Comment by jakeryang** [comment]
> If you run the code in DungeonNovelty now, then it prints out the novelty value of each room before printing the average across the dungeon. However, the values change slightly each time.

This is fixed.

**Comment by schrum2** [comment]
Now that this works, we need to apply it to the data from the study. Do the following and save the data:

1. Apply the novelty calculation to every original Zelda level (even though we only used one, let's get numbers for them all). I think that even for levels that haven't been extensively tweaked to assure correct functioning during play, we should be able to load the data and get a calculation, but let me know if I'm wrong ... even just calculating scores for the ones that we know are playable would be good.

2. Apply the novelty calculation to every graph grammar (no GAN) level actually generated in the study. When we match these up with participant responses, we will be able to see if their subjective assessments correspond to an objective measurement.

3. Do the same thing with the graph/GAN levels.

We might do more calculations down the line ... like an aggregate across all GAN levels ... but I want to see these numbers first.

**Comment by schrum2** [comment]
We took care of this today. Now that the novelty calculation is consistent, I can use this code to run some stats comparing things.
