### ISSUE TITLE
Apply GAN to Lode runner 

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#394]
Try applying the GAN to the Lode Runner data in VGLC: https://github.com/TheVGLC/TheVGLC

Compare with Autoencoder approach from Togelius' group

**Comment by schrum2** [comment]
This is an issue we talked about doing a long time ago. It will take a lot of work to get it up and running, but the raw VGLC data is already available, which is a step in the right direction. The first step will be turning the raw VGLC data into a json file with training data representing all of the levels.

For comparison, training data files used for Mario and Zelda are in the directory ```src\main\python\GAN```. If you open these json files in a text editor, you can see how they are structured.

**Comment by kdsteckel** [comment]
I am getting a weird indexOutOfBoundsException  that I am not sure how to handle. 
All values are correct and it is still giving an exception. 
@schrum2

**Comment by kdsteckel** [comment]
Still need to tweak the JSON output because it is not displaying all the rows.

**Comment by kdsteckel** [comment]
It now converts all 150 levels from the VGLC data in the MM_NEAT directory to JSON form. 
The tiles are broken up into 4 categories right now: passable points are 0, impassable points which are the ground are 1, enemies are 2, and ladders and ropes are 3. 
Might want to refactor later but it is working right now. 
@schrum2

**Comment by schrum2** [comment]
passable, impassable, ground, etc are tile attributes, not tile types. The GAN should have a separate category for each unique tile type ... at least, that is the approach that currently makes the most sense to me. We may adjust things down the line, but I suspect you will need to reconfigure the json training data and train the GAN again.

**Comment by kdsteckel** [comment]
First training of GAN on LodeRunner data complete. 
May need to refactor.
@schrum2

**Comment by kdsteckel** [comment]
Updated mapping to include all 8 tile types

**Comment by kdsteckel** [comment]
You could make a new data set that only contains 5 levels (give the json file a different file name that makes it clear what is contained in it) and train on that. It should be easy for the GAN to overfit to such a small training set, and we should get a lot of results that look exactly like the input levels
#394 @schrum2

**Comment by kdsteckel** [comment]
There is a problem with adding the row List of integers to the complete list of list of integers. 
@schrum2

**Comment by kdsteckel** [comment]
Conversion to JSON now working @schrum2

**Comment by schrum2** [comment]
The next step of this process is to edit `src\main\python\GAN\generator_ws.py` so that if the `z_dims` is a certain size it assumes you are using Lode Runner and sets the `out_height` and `out_width` accordingly.

If you can get `generator_ws.py` to successfully generate output at the command line this way, then you should modify the Java code to have cases for initializing the Lode Runner GAN and sending the Python output to the Lode Runner renderer: #470

**Comment by kdsteckel** [comment]
Added a parameter to get the model of the GAN that we trained on Lode Runner.
Added a case to allow for lode runer levels to be rendered from the GAN.
Updated generator_ws.py to default to lode runner when it is 8 tiles.
Added a class called LodeRunnerGANUtil to help control the rendering of levels from the GAN.
@schrum2

**Comment by kdsteckel** [comment]
First thing to try is to retrain with 10,000 iterations instead of 5,000.
Evolve levels from latent space, try if longer training doesn't work. 
Right now gonna try retraining. 
@schrum2

**Comment by kdsteckel** [comment]
![Capture2](https://user-images.githubusercontent.com/50111166/82455632-c5974680-9a78-11ea-8483-d0d7efcdf9e8.PNG)
Example of a level generated by the new GAN model.
Multiple spawn points, ladders that run into the floor, and unreachable gold. 
@schrum2

**Comment by kdsteckel** [comment]
Next thing to try if the current training does not work is removing the spawn point in the mapping, if the current GAN model doesn't improve things.

**Comment by kdsteckel** [comment]
![Capture3](https://user-images.githubusercontent.com/50111166/82475402-123b4b80-9a92-11ea-9b8f-3d94807e6743.PNG)
Example of a level generated by the GAN with an input of size 20, with 10,000 iterations.

**Comment by kdsteckel** [comment]
Tomorrow, test the new model to see if it improves the levels that are generated. 
Will need to update parameter with the new model name.

**Comment by kdsteckel** [comment]
Having 6 tiles may be problematic because the zelda levels are defaulted in the generator_ws.py class when there are 6 levels and I kepe getiing an index out of bounds exception @schrum2

**Comment by kdsteckel** [comment]
![error](https://user-images.githubusercontent.com/50111166/82569569-0ad57a00-9b46-11ea-8e0d-ae4ea5d212c7.PNG)

**Comment by kdsteckel** [comment]
![LevelBreeder](https://user-images.githubusercontent.com/50111166/82578962-b8e72100-9b52-11ea-87e9-234a5f0caccf.png)
Generalized Lode Runner generation to allow for the new model from the new mapping to work. 
@schrum2

**Comment by schrum2** [comment]
> new data set that only contains 5 levels (give the json file a different file name that makes it clear what is contained in it) and train on that. It should be easy for the GAN to overfit to such a small training set, and we should get a lot o

Let's increase the priority of doing this

**Comment by kdsteckel** [comment]
Renamed models to end with  "iterations_latentvectorsize_number of tiles" to make them be able to be parsed in the LevelBreeder. @schrum2

**Comment by kdsteckel** [comment]
Keep training models with an increasing number of levels. Do it with 20, 50 to see if more levels help with making more diverse levels.

**Comment by kdsteckel** [comment]
![Capture](https://user-images.githubusercontent.com/50111166/82698715-e904f180-9c30-11ea-8358-20a8691eeb5e.PNG)
This image of the level breeder is trained on the first 50 levels, in 10,000 iterations, and using hte 6 tile mapping. It does not look good, think it may need more iterations. 
For the model for the first 50 levels using the 7 tile mapping I am  going to try to train it for 20,000 iterations to see if that improves the levels that are generated. 
@schrum2

**Comment by kdsteckel** [comment]
LAst commit should have been tagged with #472

**Comment by schrum2** [comment]
Train models with more and more iterations using the 100 level training set until something decent is produced. Then move on to 150 levels.

**Comment by schrum2** [comment]
The models trained on 100 levels really don't make beatable levels yet. Still, need to move one. Train the following models:

- All tile types, 100 levels, 10 latent inputs, double the number of iterations of the previous model
- All tile types, 150 levels (all), 10 latent inputs, niter = same as previous

**Comment by kdsteckel** [comment]
python main.py --niter 200000 --nz 10 --json LodeRunnerFirstHundredAllTilesNoSpawn.json --experiment LodeRunnerFirstHundredAllTilesNoSpawn200000_10_7 --tiles 7 --cuda
@schrum2

**Comment by schrum2** [comment]
Model on 100 levels finished. About to push:
![fake_samples_200000](https://user-images.githubusercontent.com/8397236/84431369-cee77f00-abf0-11ea-822f-5ecd24518c1b.png)

Next I'll train on all 150:
`python main.py --niter 200000 --nz 10 --json LodeRunnerAllLevelsNoSpawn.json --experiment LodeRunnerAllLevelsAllTilesNoSpawn200000_10_7 --tiles 7`

**Comment by schrum2** [comment]
This issue is basically done, but there are still more Lode Runner models to train in issue #525
