### ISSUE TITLE
No debugging map for study

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#398]
Just launched the study batch file and an image of the whole map popped up. This is useful for us when troubleshooting, but we need to remove it before the launching the study.

Of course, since we are still debugging, we might want to leave this in for a while more, but we need to remember to remove it eventually, and soon.

**Comment by schrum2** [comment]
I've checked all of the levels at this point. As long as the Tower levels match the ones I've been seeing, we won't need to look at the maps for troubleshooting any more, so you can fix this issue.

**Comment by jakeryang** [comment]
Fixed in a latest commit. It will only show when a DEBUG constant is true. Closing.
