### ISSUE TITLE
Ms Pac Man full screen (visualizer or controller?)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#4]
From MM-NEATv2: https://github.com/schrum2/MM-NEATv2/issues/242

Even though I want to move on to the new PO pacman code, I'll probably use a facade interface to make all of my old code work with it, so this issue is still worth some attention

**Comment by schrum2** [comment]
@DevonFulcher The work you are doing in Tetris with CNNs will likely also be applied to Ms. Pac-Man as well, but although I have great results in Ms. Pac-Man using intelligent features, I haven't really worked out all the kinks of applying HyperNEAT to Ms. Pac-Man with low-level features. So, if you get sick of the Tetris CNN code or stuck, you can also look at this issue a bit.

Running some of the features in MsPacMan-HyperNEAT is a good place to start ... I'm not sure all of them run.

Note: although there is a dev_mspacman branch, that should be reserved for the work @Squillyprice01 is doing with PO Pac-Man #21 for now. You can play with this issue in the dev branch for now.

**Comment by schrum2** [comment]
Ms Pac-Man alerady supports HyperNEAT, and there are some batch files that launch this controller. I think that one is a test batch file that immediately shows a visualization, and this is where the problem is. Basically, the input-output mapping for this version of the game is not great yet. It needs more work, and we should also try to do it with convolutional networks instead of fully connected networks. Go ahead and look at this today if you are interested @Squillyprice01 though we probably won't be able to really dive into working on it until next week.

**Comment by DevonFulcher** [comment]
It appears that once the activations reach the end of the network they are very saturated. Tanh produces outputs that are very close to 0 or 1 with very little or no variation in between time steps. ReLU is also ineffective with all activations showing little variation. Normalized nodes with ReLU produces all 0.0 outputs. Normalized Nodes with Tanh produces varied outputs.

**Comment by DevonFulcher** [comment]
This is not a problem with the visualization but rather the output becoming very saturated. Follow up on saturated output is here #270
