### ISSUE TITLE
Heart Drop Rate Parameter (Reduce)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#406]
The enemies are dropping hearts too often. First, the drop rate should be a command line parameter if it isn't already. Second, the rate should be smaller ... probably needs some tuning, but my initial inclination would be to set it at 20%

**Comment by jakeryang** [comment]
To make this configurable. I'll add a better way of handling drops. Instead of hard coded drop chances, a class will be used

**Comment by jakeryang** [comment]
Just added cmd line values for `healthDropRate` and `bombDropRate`, being 20% and 40% respectively. I've been playing through the levels with these options and it seems like these values are fine. They allow for a lot of backtracking for bombs and being careful due to the lack of heart drops. For comparison, before it was a 90% chance for a drop, _then_ 50/50 for either a heart or a bomb (So 45% overall for both, right?)

**Comment by schrum2** [comment]
I like it, but worry that it is too hard now. Set the default heart drop rate to 30%, and also make the following changes:

The first time the subject plays a level, make the drop rate 30% and give them 4 hearts.
If the subject dies, change the settings in the next play through to 60% drop and 6 hearts.
If they die again, make it 90% drop and 8 hearts.

If they die yet again, then make them invincible. I would like all subjects to beat each level.

**Comment by jakeryang** [comment]
This has been implemented. However, making the player invincible is tricky and would require a lot of small changes in a lot of places. On the final "try", they get 20 hearts and a 90% drop on hearts. I found that when you die the first time (so now 60%, 6 hearts). Is really doable and they shouldn't get on the last try. If they do it still shouldn't be a problem.

**Comment by schrum2** [comment]
I'll try it out and let you know what I think, but this sounds reasonable. I'm wondering if the instructions we give to the participant should encourage them to talk to us and ask for help each time they die. For example, we can give them tips on how to move to avoid getting killed/hit (back up to draw them in, then attack).

I'll figure out an instruction script. In any case, after I give these new settings a test run I'll close this issue myself.
