### ISSUE TITLE
Extensive Logging for Zelda Experiment

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#408]
I'm aware that we currently log information to file during the play sessions for the Zelda experiments. However, I have a list of information that I want to make sure we track. In fact, we might want to track some of this information separately from the extensive low-level log, and have some kind of text file report that provides us with summary information, since this will be much easier for us to process when we look at the final results and put the information in a paper.

Here is the information we need to have easy access to regarding each level played:

- How many actions performed
- How many keys collected
- How many enemies killed
- How much damage received
- How many hearts collected
- How many bombs collected
- How many bombs used
- How many deaths/attempts until success
- Number of distinct rooms visited/not visited

The idea is to track anything that could potentially be useful. For example, we could track number of actions performed and damage received as measures of difficulty. It would also be useful to know if the dungeons can be beaten without certain rooms being visited.

Naturally, if you can think of anything else worth tracking in this report, then add it too.

Also, note that we should still keep the low-level logs and do the screen recordings, in case we later realize that there is something we want to check for that we forgot to log specifically. It will just be much more tedious to look through that raw data than to have the program summarize it as we collect it.

**Comment by jakeryang** [comment]
What do you think about putting the information in CSV files? We could have 3 different CSV files for each of the different level types. With the original type having an extra column for the specific number. This is so we can import it to R, Excel, etc., and not have to do a lot of post editing of the data files.

**Comment by schrum2** [comment]
That would be great, though any text format should be easy for us to process. I think that the amount of info needed from one level of one user is a single column of information, so CSV might be overkill. Still, the more structured the data is the better. Do whatever you think works best ... just be sure to output all of the needed information.

**Comment by jakeryang** [comment]
Just made a way to save a class to a CSV file, checkout `ParticipantData.java` to see if there's any more values you would like to keep track

**Comment by schrum2** [comment]
I think we should also track some information about the dungeons being played, but I think I need to have a better understanding of the graph grammar first. Basically, do we generally expect all dungeons from a given grammar to have the same number of rooms? Perhaps give or take a room or two since it might be impossible to place a room sometimes?

Basically, I think we should log the number of rooms in the dungeon. This will get repetitive for the original levels, but we should track that info the same way.

We should also track some information about the connectivity of the dungeons. Such as:

- Number of rooms with only one entrance/exit
- Number of rooms with exactly two entrances/exits
- Number of rooms with exactly three entrances/exists
- Number of rooms with exactly four entrances/exits

Note that in the above counts, any kind of entrance/exit counts, whether a bombable wall, locked door, block puzzle, etc.

Then we should also count the number of rooms with 1, 2, 3 bombable walls, since I think people can really get lost/stuck because of these.

I'm not sure how useful it will be to track information about all of the other entrance/exit types.

**Comment by jakeryang** [comment]
I think the difference between the min and max number of rooms is around 4. The graph grammar might add a room off to the side or not. Place one more room in between or not. We added a way to backtrack room placement in the event that a room couldn't be placed so that's not an issue. Getting these other values shouldn't be too hard. I'll work on getting the other values tracked throughout the code and then add the additional values.

**Comment by jakeryang** [comment]
>     * How many actions performed

What exactly is an action? Is it every time the player moves and/or attacks?

**Comment by schrum2** [comment]
I thought that this concept was defined in the rough-like somehow. I guess it is every time the player presses a button, which is mostly an arrow key, but the bomb button also counts

**Comment by schrum2** [comment]
The files produced for this should be saved in the Subject-X subdirs produced when running ZeldaStudy.bat

**Comment by jakeryang** [comment]
There's only three CSV files that will be produced throughout the study since it's by the generation type and loader. So could we save it in the study directory but under ParticipantData or something?

**Comment by schrum2** [comment]
Make it be a subdir within the root dir since that won't change (the name of the dir containing the batch files might)

**Comment by schrum2** [comment]
Name the directory `ZeldaStudy2019`

**Comment by schrum2** [comment]
Log in both this ZeldaStudy2019 directory but also in the individual subject's directory for redundancy, as we discussed.

**Comment by jakeryang** [comment]
Just added data about the number of exits and bombs in the dungeon to be outputted in the CSV file

**Comment by schrum2** [comment]
If the player dies and replays the level, I think we need a way of separating out the information from the distinct plays. Since each row contains the player ID number, I think it is ok and preferable to simply log a separate row in the output for each play though the level. All of the level-specific information will be duplicated, but the action count and enemies killed, etc will be reset. The number of deaths will be different on each row ... I guess this column could actually be interpreted as the attempt number, and then the number of rows with the same ID will actually correspond to the number of lives used.

**Comment by jakeryang** [comment]
Just implemented this. Also made sure to save the backup data as separate files on death.

**Comment by schrum2** [comment]
I'm satisfied with this.
