### ISSUE TITLE
More intuitive and helpful interface for Zelda rogue

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#409]
We can't assume that all users will find the game as intuitive as we do. We also can't assume that if we provide instructions, they will actually remember all that we say (though we will try just in case). So, I would like for there to be permanent instructions on the screen in one of the side margins (wherever it fits). These instructions should be short descriptions of each type of object in the game, and should also be color coded. Something like the following:

@ This is you. Move with arrows.
e Enemy: Move toward to attack. They fight back!
(green door) Go through these to reach new rooms
(blue door) Kill all e in room to open
(red door) Find a k to open
(yellow door) Push a block to open
k Keys sometimes appear when all e are dead
b Bomb: Press b to use. Bomb certain walls to find secret doors. Kill e to find more
(triforce) Find this to win!

**Comment by schrum2** [comment]
Also the following:
(water) Enemies can fly over but you can't cross
# Bridge: Rare item for crossing water

**Comment by jakeryang** [comment]
I like this idea. But I think that's too much information when it's in the side margin. We could make a separate screen and when they press H or something where all of that info will pop up and pressing H again will resume the game.

**Comment by schrum2** [comment]
Are you sure? There is a lot of empty space on the margins, and while I agree that this info is a bit distracting for a real game, I think it would really help for it to simply be readily visible for the sake of the study. As with most things, we probably want to be able to enable/disable it with a command line parameter.

Try displaying it this way, and if it seems too busy, we can try putting it in a help screen instead.

**Comment by jakeryang** [comment]
It might seem like a lot of space, but characters take up a lot of space on the screen. I'll try to fit all of it in the left side and see what it looks like.

**Comment by schrum2** [comment]
It might also work on the bottom of the screen (beneath the log) if you make the window larger. Currently, it does not fill the whole screen, but it could.

**Comment by jakeryang** [comment]
![Untitled](https://user-images.githubusercontent.com/6686189/64071842-b05b5d00-cc48-11e9-8d48-8e3593b93014.png)

This is what the screen is like when its on the side. The width of the screen is 85 characters.
I suppose we could go to the bottom and extend it.

**Comment by schrum2** [comment]
How much can we abbreviate that text?

@: You. Move with arrows.
(red e): Enemy. Move toward to attack.
(green): Use to reach new rooms.
(blue): Kill all (red e) to open.
(red): Find (yellow k) to open.
(orange): Push a block to open.
(yellow k): Key. Dropped by (red e)
b: Bomb. b to use on walls. Find secret doors.
(water): Enemies can cross, but you can't.
\#: Cross water
(trifoce): Find to win!

Changing it's placement could also make it look better. We definitely don't want it intruding on the game content. Of course, The game content could be moved to the right a bit ... there is blank space there.

**Comment by jakeryang** [comment]
I was messing around with it and increased the screen height. Even with the abbreviated text it was still going over into the play area. I would like to keep the play area in the center.
![Untitled](https://user-images.githubusercontent.com/6686189/64072066-2910e800-cc4e-11e9-870d-d9ade3bcc174.png)

Also, doing colored text within a sentence is very tricky and painful. I think it'll be fine if we don't have the colored text in the description.

**Comment by schrum2** [comment]
If we can't color code the text, then we should use complete words. Kill all enemies ... Find a key to open. Overall, this looks really good though and I think it will help the users.

Close after making the final tweaks I suggested.

**Comment by jakeryang** [comment]
Tweaks added. Closing.
