### ISSUE TITLE
Impossible Block Puzzle

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#410]
I was playing a GAN generated room with seed 4, and found this room:

![image](https://user-images.githubusercontent.com/8397236/64069275-f940f080-cc0b-11e9-8649-f53af244f177.png)

This room has a puzzle-locked door, but none of the blocks in the room can be pushed. I don't know if one of them is meant to be pushable, or if even that was left out somehow.

**Comment by jakeryang** [comment]
I tried with the parameter `randomSeed` set to 4 and I got a completely different level, with expected behavior of puzzle blocks. Do you have the latest commit?

**Comment by schrum2** [comment]
I checked again, and its actually the graph level with rooms from the original, not the GAN rooms.

**Comment by jakeryang** [comment]
I'm still getting a different layout. (Params: `zeldaType:generated randomSeed:4 zeldaLevelLoader:edu.southwestern.tasks.gvgai.zelda.level.OriginalLoader`)

**Comment by schrum2** [comment]
I launched it in sequence using this Zelda Study batch file. Not sure why
that would make a difference but it is the use case that matters more.
Ultimately I think we're going to need to play all 30 I'd numbers/seeds in
advance to make sure all are ok. Another reason that resolving those final
issues and freezing the code soon will be helpful

**Comment by schrum2** [comment]
This is still an issue, but I also found another dungeon with the same issue. When I launch Zelda study with a seed/ID of 28, the third dungeon (which I think is GAN generated) has an impossible block puzzle:

![image](https://user-images.githubusercontent.com/8397236/64081635-5b136000-ccc9-11e9-8b5b-f4189bc0c3af.png)

**Comment by jakeryang** [comment]
I got a different level again. I'll change the color of the movable blocks so we can see exactly where they are getting placed.

**Comment by schrum2** [comment]
According to the new code, the pushable block simply isn't being placed. The image still looks like this:
![image](https://user-images.githubusercontent.com/8397236/64087098-1f948800-cd01-11e9-8352-ae5750725e91.png)

I played a different level with a push block to confirm that the bright green coloring works, and indeed it does. So, in the case of this level (and presumably the other) a pushable block simply isn't being placed.

**Comment by jakeryang** [comment]
I've been trying to find a level where there's no puzzle block in a puzzle-locked room and I can't find one. However, I've been seeing levels where there are two puzzle blocks in the same room and one dungeon that got caught in an infinite loop. I think we're going to need to cherry pick levels when we get this setup on the Tower of Power

**Comment by schrum2** [comment]
I just played levels with random seed 4 on my office machine, and got the exact same levels. The fact that I'm getting the same levels on two different machines leads me to think that something is odd with your system that is preventing you from seeing these levels. Are you sure that you don't have some txt files whose changes are not tracked that might be affecting things? 

The only other issue I can think of that might affect things it your Python version (for GAN levels at least), but the seed 4 level above is not a GAN level. Maybe you should delete your personal repo and do a fresh checkout from GitHub. In any case, we'll need to test the levels that are generated on the test machine in the lab, but I suspect they will be the same as what I'm seeing. Given that this is the case, I could like to fix the block puzzle issue.

No matter what, we will need to play though all levels before we start the study.

**Comment by jakeryang** [comment]
I'm getting the exact same levels from before I refreshed the repo. Could it be a difference between 32-bit and 64-bit Java? I'm running 64-bit.

**Comment by schrum2** [comment]
The Tower of Power now runs the code, and it produces the exact same problem levels I'm seeing. You'll need to troubleshoot this problem on that machine if you can't produce them on yours.

**Comment by schrum2** [comment]
For what it's worth, I confirmed that the result of running the level from inside Eclipse is different than the result of running the batch file with the jar file. This makes no sense, but we'll either need to troubleshoot the Maven jar (tedious) or find the source of the difference.

**Comment by schrum2** [comment]
I made a recent commit that completely changed the way certain random numbers are generated. It probably shouldn't have fixed this problem, but I haven't found evidence of it yet (played ID numbers 0 through 18). I'll keep playing and see what happens.

**Comment by schrum2** [comment]
So, this commit seems to have actually fixed this issue:
https://github.com/schrum2/MM-NEAT/commit/6d65c7f6585a9481ca760ae1fb4d7c445c999e78

I'm not entirely sure why, but I checked all 30 random seeds we'll be using for the experiment, and all worked. The only level left with a problem is #412 

So, this issue can be closed, AFTER you switch the color of the pushable blocks back to the standard block color (which will make finding the blocks much harder)

**Comment by jakeryang** [comment]
Changed push block back to the color of walls, closing.
