### ISSUE TITLE
Must remove blocks under starting position of avatar

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#412]
If the avatar's initial placement is on a block, then that block should be changed to floor.

Other than looking better, I found a level where this really matters. I found that a GAN level with random seed 18 has a starting room with a problem. It looks like this:
![image](https://user-images.githubusercontent.com/8397236/64400088-8a5eff80-d030-11e9-8ffb-7976de6c3d46.png)

The position under the avatar is a block. If the player moves right, I end up getting stuck in an unbeatable level after I explore everything. The only way to beat the level is to move down with that first step.

**Comment by jakeryang** [comment]
Apparently I got the exact same starting room, but the layout is different. But the latest commit fixes this and makes the tile a floor tile. Closing.
