### ISSUE TITLE
Running out of bombs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#413]
Bombs are sometimes a bit scarce. However, this problem is magnified when playing the second or third time. The heart drop rate is increased, but this makes it really hard to get necessary bombs to progress. This is just a bit annoying. At the very least, I feel that if the player has full health, then bombs should be dropped instead of hearts, at least if the player has no bombs.

That's a lot of conditional logic, but I think it is justified.

**Comment by jakeryang** [comment]
Latest commit implements drop behavior where if the player is maxed on health and the drop system attempts to drop a heart, it will drop a bomb instead. I think this works for the most part.
