### ISSUE TITLE
Block Puzzles can make levels unbeatable

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#416]
I made a bunch of changes to the code, which changed the specific levels that are produced, but when testing on the Tower I still found an example of a level that becomes unbeatable.
![image](https://user-images.githubusercontent.com/8397236/64713793-2484d480-d483-11e9-92c4-771e3fcd6273.png)
On the Tower, this happens with a seed of 6 in a level with rooms from the original game, but generated with a graph.

I don't know if we can fix this without solving #415 first.

**Comment by schrum2** [comment]
Ok, so we believe we have fixed the non-determinism problem #415 . If that is true, then you should be able to reproduce the exact same levels I'm seeing. With the new code, using a random see of 1 when producing a GAN level results in a level with this room:

![image](https://user-images.githubusercontent.com/8397236/64749879-cb498f00-d4dc-11e9-9f47-94af1ae16ad4.png)

If you are able to reproduce this exact level/room, then figuring out a way to fix the level will be a lot easier. Note that having a raft would allow the player to beat this level #417 so that is one possible fix. However, this random seed does not correspond to original level 4, so finding another way to fix it might be a good idea too.

I'm really happy for either fix at this point.

**Comment by jakeryang** [comment]
It's kind of interesting that every time the puzzle block blocks the way,
you're able to get around it using a raft. But there could be a room where
you can't pass even with a raft. We'll see after I implement the raft.

**Comment by schrum2** [comment]
Ugh, just found a level that is unbeatable despite the raft and water fixes:
![image](https://user-images.githubusercontent.com/8397236/64896018-fd293580-d643-11e9-93e0-2b8b797fb39e.png)

I can step on the water, but then I'm trapped because I can't walk over two water places. This is seed 7 using the original rooms.

This specific problem could be fixed by expanding the area which is affected by the water, but I think I'm actually going to play more levels first. Let's see how many have a problem before trying a drastic solution.

**Comment by schrum2** [comment]
I did a hack to fix the level with seed 7 which is the only one that does not work out of the 30 we need for the study. I'm going to leave this issue open, but remove Need Soon since the hack to fix this one level will allow us to proceed with the study.

**Comment by schrum2** [comment]
I assume this is still an issue, but I recently removed the hack fix for random seed number 7 because some other code change (I'm not sure what, but it was caused by the GECCO papers) has changed the internal room layouts in Graph Only dungeons. Presumably, some change I made causes a different number of calls to the random number generator. The issue may also be related to a difference in how equality is defined between rooms.

In any case, random seed 7 no longer leads to a dungeon with an impassable room. However, I have not tested all 30 dungeons, and even ignoring that, an impassable room could still arise. It would actually be preferable to fix the code so that is still generates the original dungeons from the study, whose rooms can be seen at the website here:
https://people.southwestern.edu/~schrum2/SCOPE/zelda-graphgan.php
(look under "Human Subject Sessions in Graph Dungeons (Rooms From Original Game)")
Note that the dungeon layouts match the originals ... only the internal room contents are different.

However, without that fix, I would at least like to check the 30 new dungeons that are generated to see if any have the impassable room issue. Trying to find a way to fix this problem is only worthwhile if it is reproducible.

**Comment by schrum2** [comment]
At this point, I'm just assigning tons of issues in case you manage to maintain your current pace. This issue has a long history, but the first step to addressing it now is to reproduce the error: Use the human subject study launch class with different random seeds until you find a level that is unbeatable because of a puzzle block. Once you find that special case, make a note here of how to reproduce it. Then we'll worry about how to fix the issue.

**Comment by schrum2** [comment]
The "fix" of replacing walls with water around push blocks is a bit of an ugly hack. I would like the use of this hack to be controlled by a new command line parameter. This is something you should be able to address relatively soon @kdsteckel

**Comment by kdsteckel** [comment]
Added a parameter called zeldaAllowPuzzleDoorUglyHack that control whether the ugly hack is used for placing puzzle blocks. @schrum2

**Comment by schrum2** [comment]
There is not a command line parameter that turns the hack of surrounding the push block with water on and off. Whether it is used or not, it seems likely that it is still possible for levels to emerge that are unbeatable because of the push block. However, the current focus of this research is to let evolution simply create levels, and have fitness favor the better ones rather than making sure every level is repaired to work up front. Therefore, this issue is low priority.

**Comment by schrum2** [comment]
This was never definitively solved, but it also seems irrelevant now, so closing.
