### ISSUE TITLE
Comment Item classes in the me.jakerg.rougelike package

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#438]
The me.jakerg.rougelike package was made by Jake to support the Rogue-like engine used for Zelda levels. There are many files in this package in need of commenting, but this issue focuses only on the Item class, and other classes in this package that extend the Item class. The main priority is adding Javadoc comments, though other comments should be added as appropriate.

**Comment by schrum2** [comment]
This is not done. Focus on this part: "and other classes in this package that extend the Item class"

Lots of classes still need comments.

**Comment by schrum2** [comment]
While commenting, also add a ```public static final int INT_CODE constant = -6;``` to the ```Ladder``` class. This object is also known as the Raft. The Magic Number -6 is used in many places throughout the code ... I eventually want all of them to refer to ```Ladder.INT_CODE``` instead.

Both @cappsb and @kdsteckel will need to look out for this, but @kdsteckel will need to make and commit his change to the ```Ladder``` class first (since he'll be messing with these files for this issue anyway).

**Comment by schrum2** [comment]
Similar to the previous comment on this thread, I have found that the magic number 2 appears a lot in the code to represent enemies. Enemies are handled in part by the ```Creature``` class, though this class actually represents the player too. Add a ```public static final int ENEMY_INT_CODE = 2;``` to the ```Creature``` class and use this in place of the magic number 2 where appropriate.

**Comment by kdsteckel** [comment]
Commented Item class and all the classes that extend the item class.  Added constant variables to solve some magic number issues.
