### ISSUE TITLE
CPPN2GAN Zelda Level Breeder invalid doors

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#443]
Some of the generated levels have doors that can't be entered/used. Fix this

**Comment by schrum2** [comment]
This is your first "real" assignment and will likely require a lot of effort and exploration of the code. Ask me frequent questions to keep you on track, and log information about what you learn in this issue thread. Create a new branch dev_zeldadoorfix to store this work. Doing this issue will help you understand the Zelda code better.

Don't work on this issue until SCOPE officially starts.

**Comment by schrum2** [comment]
Start looking in ZeldaCPPNtoGANLevelBreederTask. Focus on the dungeonFromLevelGrid method. Also check ZeldaDungeon class.

**Comment by schrum2** [comment]
Look at the setLevels method in ZeldaDungeon and the setDoors method in ZeldaLevelUtil

**Comment by kdsteckel** [comment]
Issue solved. 
Removes the doors that the GAN produces and then the CPPN adds only valid doors.

**Comment by kdsteckel** [comment]
@schrum2
