### ISSUE TITLE
Commenting Zelda Graph Grammar Files

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#444]
Jake made a lot of files in the package edu.southwestern.tasks.gvgai.zelda.level that have to do with defining a dungeon via a graph grammar. Before attempting this issue, be sure to look closely at his paper: https://people.southwestern.edu/~schrum2/SCOPE/gutierrez.cec2020.pdf
Importantly, this extended version of the paper shows the graph grammar details at the end.

Start in the ZeldaGraphGrammar class and write comments for it that try to make sense of the grammar rules defined there. There should correspond to what is listed in the paper. In fact, a javadoc class comment should reference the paper with a complete citation.

After commenting this file, go about commenting others in this same package.

**Comment by cappsb** [comment]
Commented ZeldaGraphGrammar
