### ISSUE TITLE
ZeldaCPPNtoGAN: Too many keys

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#446]
The mechanism for adding keys to these rooms was way too simplistic. Basically, one key per locked door is added to every room with locked doors. This is boring ... the Graph Grammar approach does a much better job of setting up keys in advance for locked rooms later.

We need some way of having a more reasonable number of keys in the CPPN2GAN dungeons. This can be tested using ZeldaCPPNtoGANLevelBreederTask, but it affects evolution using ZeldaDungeonTask as well. I believe the relevant shared code is in ZeldaDungeon.java. Look at the call to ZeldaLevelUtil.placeRandomKey in the setLevels method.

**Comment by schrum2** [comment]
![image](https://user-images.githubusercontent.com/8397236/81737945-80fb2200-945e-11ea-9a3e-958e099295d6.png)

**Comment by kdsteckel** [comment]
Command line parameter that disables current behavior: Intelligent key?
Go through all the rooms and let the locked doors be placed
then separate code runs based on parameter to place the keys 
could use A* algorithm to track path 
Find all the points visited and count locked doors
Place the same amount of keys as locked doors on the path you visited

**Comment by kdsteckel** [comment]
Finds the shortest path through the level and hits every point if there is no path, go until you solve it or you hit every point you can without solving it. Then count the number of locked doors and change that number of points to keys. Then run it again,creating new sets of points every time and updating the number of keys from each new key if there are more locked doors found.

**Comment by kdsteckel** [comment]
I think that if I add the code to implement smart key placement under where I put the code to allow for rafts in the dungeonFromLevelGrid method because then the keys will already have been intelligently place when dungeonFromLevelGrid gets called in the gridDataToDungeon method.

**Comment by schrum2** [comment]
Make the following helper method that takes as input a Set of rooms (not sure if these should be in List<List> format, Node format, or something else), and returns an int count of the number of locked doors in those rooms

**Comment by kdsteckel** [comment]
Made two helper methods to help track the amount of locked doors. 
One in ZeldaLevelUtil called lockedDoorCOuntPerRooms.
One in ZeldaDungeon called totalLockedDoorCount that counts the total number of locked doors in the whole dungeon

**Comment by kdsteckel** [comment]
be aware of double counting doors

**Comment by kdsteckel** [comment]
Changed the process of adding intelligent keys.
It no longer adds random keys when intelligent key placements are being used.

**Comment by kdsteckel** [comment]
Found mulitple occurences where the keys were places in a straight line. 
Need to find a way to make them placed in a more interesting way

**Comment by schrum2** [comment]
Remaining: 

* Figure out why keys often appear in a line. Not random enough.
* Make key placement consistent: Instead of RandomNumbers.randomGenerator, create new Random instances based on auxiliaryInformation[0][0][0] (just picking an arbitrary piece of information spit out by the GAN ... may pick something different down the line ... might even fix the above issue, but probably not).
* Currently, keys are only provided for locked doors reachable from the start location. If there are additional locked doors that are behind other locked doors, then keys will not be provided for them. Some portion of the existing code needs to be put in a loop to make this possible.

**Comment by kdsteckel** [comment]
Made code in the level breeder task more readable by extracting the methods into smaller more manageable methods.  
Added Random object based on auxilaryinformation[0][0][0], but may change later

**Comment by kdsteckel** [comment]
I think that maybe looping hte code that we added inside of the intelligent keys if statement would help solve the issue of not having enough keys if you cant pass all the doors. 
Think of a good condition for this loop to be dependent on.

**Comment by kdsteckel** [comment]
Currently does not fail when I run it, but it stalls out before any levels are produced. 
Could this be because some levels are not necessarily solvable?
or maybe it is something with the way I am working with the sets in the loop?
@schrum2

**Comment by kdsteckel** [comment]
It tends to place all the keys needed in the same room which is boring. 
Can we place them in random rooms?

**Comment by kdsteckel** [comment]
I think even if you get it working, it will be computationally restrictive to use during evolution. 
We might shift to have the CPPN place the keys ... this will mean we don't always have enough keys, but evolution will favor the levels that are actually beatable, so maybe it doesn't matter.
Result is three levels and the rest are not generated. 
In the top left level, 6 keys are generated in the first room after killing all the enemies and 5 keys are place in the second room after killing all the enemies. This is problematic because only one key is needed to win the level. 
@schrum2

**Comment by schrum2** [comment]
This issue is resolved by settling for a simpler solution. Repeatedly using search to check if level is beatable costs too much time. Instead, just count all locked doors and scatter that many keys across the reachable rooms. If there are more locked doors than reachable rooms, then do a second pass in a different random order until the correct number of keys are placed.
