### ISSUE TITLE
ZeldaCPPNtoGAN: Include puzzle locked doors

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#447]
Expand the encoding to allow puzzle locked doors. The tricky part will be doing this in a way that maintains backwards compatibility with the previous encoding.

**Comment by schrum2** [comment]
Do after #443 and #446

**Comment by schrum2** [comment]
Look at setLevels method in ZeldaDungeon.java. encodedDoorType split up by fourths: 0-0.25, then 0.5, then 0.75

For puzzle locked door, place random puzzle block

**Comment by kdsteckel** [comment]
Created new boolean Parameter in the Parameters.java class to allow/disallow puzzle doors. 
Puzzle doors are present in dungeons and puzzle blocks are present to unlock the puzzle doors.

**Comment by kdsteckel** [comment]
Couldn't figure out how to implement randomness for puzzle block placement, look at tomorrow 
@kdsteckel  @schrum2

**Comment by schrum2** [comment]
For the randomness/consistency issue (tomorrow):
Look at ``placeRandomKey`` in ``ZeldaLevelUtil``. It accepts a ``Random`` instance as input.
In contrast, ``placePuzzle`` uses ``RandomNumbers``. However, you should modify this method to to what ``placeRandomKey`` does. In fact, there is already a ``Random`` instance defined in ``setLevels``. Move it up so that it can be used in the calls to both methods.

**Comment by kdsteckel** [comment]
Should be completed now. I tested it on a few levels and the puzzle blocks were consistent from what I could tell. @schrum2

**Comment by kdsteckel** [comment]
Done. Notes above.
