### ISSUE TITLE
ZeldaCPPNtoGAN: Include raft item

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#448]
This issue should be done in conjunction with #447 since it will also change the CPPN output encoding. As with #447, backwards compatibility must be maintained.

As for how the raft is placed, there can probably be an extra CPPN output, and whichever room has the highest raft output will be the one room that contains the raft. It may not be reachable, but if evolution favors backtracking (as in #434 ) then it might favor rooms where the raft can be reached and used to cross water.

**Comment by schrum2** [comment]
Do after #443 and #446

**Comment by kdsteckel** [comment]
More important to get the CPPN to produce a raft per level, but we want to try to get the DirectToGAN way to produce a raft for each level as well. 
@schrum2

**Comment by kdsteckel** [comment]
Added a Parameter for rafts to be placed in levels. 
Going to work on actually putting them in the level now. 
@schrum2

**Comment by kdsteckel** [comment]
Getting a Null Pointer Exception in the dungeonFromLevelGrid method in ZeldaCPPNtoGANLEvelBreederTask. 
Specifically in this line: raftNode.level.intLevel.get(p.y).set(p.x, Ladder.INT_CODE); (line 534)

Could be a problem in the method I added called pointForRandomRaft.

**Comment by kdsteckel** [comment]
Still not finished with the raft issue, still a null pointer exception. 
Working on moving the placeRandomRaft class into the ZeldaLevelUtil class.
Need to find a way to make the List<List<Integer>> parameter in placeRandomRaft be able to passed into the method in the dungeonFromLevelGrid method that is in the ZeldaCPPNtoGANLevelBreederTask.
Maybe there is something I am missing from going over the code that would help. 
Could try to do it with a node again also using the code snippet from SLACK that Dr. Schrum posted. 
@schrum2

**Comment by kdsteckel** [comment]
Got raft items to show up in the dungeons that are generated by the ZeldaCPPNtoGANLevelBreederTask. 
I only did a quick test to see if they are present, still need to check the randomness consistency. 
@schrum2
