### ISSUE TITLE
Graph grammar backbone should be a class parameter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#449]
The ZeldaGANLevelBreederTask makes dungeons when Dungeonize is clicked. this is done via the GraphDungeon class which defines a simple graph grammar backbone:
```		List<ZeldaGrammar> initialList = new LinkedList<>();
		initialList.add(ZeldaGrammar.START_S);
		initialList.add(ZeldaGrammar.ENEMY_S);
		initialList.add(ZeldaGrammar.KEY_S);
		initialList.add(ZeldaGrammar.LOCK_S);
		initialList.add(ZeldaGrammar.ENEMY_S);
		initialList.add(ZeldaGrammar.TREASURE);
```

I think that the backbone used here should be the same one used in the 2019 human subject study. However, I also don't want to duplicate code. What we need is a way of saving/specifying particular graph backbones using a class command line parameter. We can make the backbone above be ```SimpleDungeonBackbone``` and make the one from the subject study be ```HumanSubjectStudy2019Backbone``` and then define others very easily. Some of this work might need to happen before getting too deep on issue #445 .

**Comment by schrum2** [comment]
Just verified that the grammar above is not the same. The one from the study is defined in HumanSubjectStudy2019Zelda, and looks like:
```
			initialList.add(ZeldaGrammar.START_S);
			initialList.add(ZeldaGrammar.ENEMY_S);
			initialList.add(ZeldaGrammar.KEY_S);
			initialList.add(ZeldaGrammar.LOCK_S);
			initialList.add(ZeldaGrammar.ENEMY_S);
			initialList.add(ZeldaGrammar.KEY_S);
			initialList.add(ZeldaGrammar.PUZZLE_S);
			initialList.add(ZeldaGrammar.LOCK_S);
			initialList.add(ZeldaGrammar.ENEMY_S);
			initialList.add(ZeldaGrammar.TREASURE);
```
Of course, this makes the point that we need an easy way to encapsulate grammars.

As part of this issue, create a new package called ``edu.southwestern.tasks.gvgai.zelda.level.grammars`` that contains an interface ``ZeldaDungeonGrammar`` with a method ``getGrammar`` that returns a ``ZeldaGraphGrammar``. Then, you can make a bunch of classes that implement this interface to represent different dungeon grammars

**Comment by cappsb** [comment]
I put a command line parameter to use different backbones and it functions properly.
