### ISSUE TITLE
Make raft item be part of the graph grammar

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#452]
Currently, the raft item from Jake's original grammar is simply placed in the first room with a soft-locked door, but this is not great design. It would be preferable to support soft-locked doors without the raft, and to specifically intend to have the raft in a particular room specified by the graph grammar.

As usual, we want to maintain backwards compatibility, so there needs to be a boolean option "firstSoftLockedRoomHasRaft". Implementing this in isolation should be easy.

The next step is to make new grammar rules that specifically support the presence of a raft item in a room. This should be attempted as part of #445 

By the way, this issue is basically an extension of the now closed #417

**Comment by cappsb** [comment]
First I created ZeldaDungeonGraphBackBone interface to get any given backbone, with a corresponding parameter to call the specific class containing the combinations. Then, I created a parameter for the grammar rules (defaulting to the original ZeldaGraphGrammar now renamed to ZeldaHumanSubjectStudy2019GraphGrammar)

**Comment by cappsb** [comment]
There is a parameter called firstSoftLockedRoomHasRaft which tells whether or not you want to have the first soft-locked room to contain the raft. When set to false, the room is instead just a soft-locked room with enemies. I still need to create a RAFT_S symbol so that I can play with the graph grammar rules

**Comment by cappsb** [comment]
Raft item now appears in different places around the map
