### ISSUE TITLE
Javadoc and other comments for ZeldaLevelUtil

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#454]
This class seems to be tied to several issues you will be working on, but is poorly commented. I've started pointing out some relevant information. The class really needs some javadoc, but I'll admit that I'm even a bit confused about some of the parameters. Maybe you can bother Jake on Slack when you have a question. In any case, it is probably a good idea to understand (and comment) the code in this class before tackling issues that require you to modify this code.

**Comment by schrum2** [comment]
Add javadoc for placeReachableEnemiesAndRaft and then close this issue.

**Comment by cappsb** [comment]
Finished commenting ZeldaLevelUtil
