### ISSUE TITLE
Create ZeldaDungeonTask with direct encoding

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#457]
This will mainly be for testing out the back tracking fitness ( #434 ) but could have other uses. The idea is to create a class that extends ``ZeldaDungeonTask<List<List<Integer>>[][]>``. This directly represents a level as a 2D array of rooms, where each room is defined as a list of lists of ints, where each inner list is a row of tiles in a room, and each int is a code for a specific tile. The benefit of this is that it will be easy to specify a dungeon that requires backtracking to beat.

**Comment by schrum2** [comment]
I actually verified that backtracking fitness correctly scored a room that back-tracked through 5 rooms. That makes this particular issue very low priority now, but we'll keep it around for now.

**Comment by schrum2** [comment]
Turns out that anonymous extension to the Genotype interface I did was unnecessary. There actually is a Genotype called ContainerGenotype that could have been used here. This will be a bit cleaner, so switch the code to use it. @cappsb

**Comment by cappsb** [comment]
Originally what was wrong was that addAdjacencyIfAvailable changed tiles randomly. By adding a method encodedValueForDoorType to convert a tile type to an encoded value for a specific door type, it allows us to create dungeons with specified door connections. Backtracking room fitness works based on this model.
