### ISSUE TITLE
Apply GAN to MegaMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#464]
First get all of the raw data from https://github.com/TheVGLC/TheVGLC/tree/master/MegaMan and place it in the ``data\VGLC`` subdir. Then write some Java code that processes the raw data to create a json file in the ``src\main\python\GAN`` dir. This will be quite tricky for the following reason:

In Mario, levels only scrolled left to right, and what we did was sample using a sliding window across the level: https://suscholar.southwestern.edu/handle/11214/217

However, in MegaMan, the levels sometimes scroll vertically. I think we still want to define a sliding window, but it needs to zig-zag across the level. We also need to settle on a uniform height and width of the window.

Play around with it a bit and post ideas/issues in this thread.

**Comment by schrum2** [comment]
For this, try to reach a good stopping part with Zelda before launching into Mega Man. Also, put some effort into #473 before putting work into training a GAN

**Comment by schrum2** [comment]
Note that you should initially make separate training sets for handling horizontal and vertical portions of the levels.

**Comment by cappsb** [comment]
Train on horizontal first, make sure it works, then try vertical

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84043214-a3079780-a96b-11ea-9576-9094df776db8.png)
Took every horizontal screen in MegaMan's first level and converted it to a json file, then used  that for training.
python main.py --niter 5000 --nz 5 --json MegaManFirstLevel.json --experiment MegaManLevel1_5_Epoch5000.pth --tiles 13

**Comment by schrum2** [comment]
Train a model with these types:
```
0        "#" : ["solid","ground"],
1        "B" : ["solid","breakable"],
2        "H" : ["solid", "hazard"],
3        "|" : ["passable", "climbable"],
4        "M" : ["solid", "moving"],
5        "-" : ["passable", "empty"],
6        "C" : ["solid", "cannon"],
```
Then train a different model with these types
```
0        "#" : ["solid","ground"],
1        "B" : ["solid","breakable"],
2        "H" : ["solid", "hazard"],
3        "|" : ["passable", "climbable"],
4        "M" : ["solid", "moving"],
5        "-" : ["passable", "empty"],
6        "C" : ["solid", "cannon"],
7                 WATER
8,9,10,11,12         for different enemy types
```

**Comment by cappsb** [comment]
All levels (but 7) with 7 tiles is in the MegaManGAN folder

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84165881-d0bb1200-aa39-11ea-8518-6c6a352895d5.png)
Image of the newest model (see the previous comment)

**Comment by schrum2** [comment]
Train on a mix of horizontal and vertical segments, as described in #523 

Also, train on training sets derived from MMLV levels when you get he chance #502

**Comment by schrum2** [comment]
We will continue to train GAN models, but this issue is no longer needed to track this kind of progress.
