### ISSUE TITLE
Puzzle blocks unlock more than one Puzzle door

### ISSUE THREAD

**Issue by kdsteckel** [schrum2/MM-NEAT#465]
Associate a different puzzle block for each puzzle door, or restrict it to one puzzle block per room. 
We prefer to only have one puzzle block per puzzle door, right now it is placing one on each side of the puzzle door.  Can we find a way to pick the correct side.

**Comment by kdsteckel** [comment]
RIght now I am getting a ArrayOutOfBounds exception that I am not sure how to handle. 
It prevents levels with puzzle blocks from being generated at all. 
@schrum2

**Comment by kdsteckel** [comment]
This solve seems consistent with the features that we want. 
There is only one puzzle block placed in a room that has puzzle doors present, if there are more than one puzzle door it still only places one puzzle block and that puzzle block unlocks all the puzzle doors. 
@schrum2

**Comment by schrum2** [comment]
Though it is true that there is at most one puzzle block per room that unlocks all puzzle doors, we still have a problem where some rooms have a puzzle block that seemingly does not unlock anything. However, the reality is that we have puzzle blocks on both sides of a puzzle door. When the door is unlocked on one side, it remains unlocked on the other, leaving a useless puzzle block.

However, I know that in some old Zelda levels there were doors that would lock behind the player, and require them to find a puzzle block, so we should change the mechanics accordingly. Specifically: If the one puzzle block in a room is in the locked position, then the puzzle door exits to that room should remain locked. It will therefore be possible to enter through a puzzle door and have it lock behind the player.

**Comment by schrum2** [comment]
Resolved with previous commit
