### ISSUE TITLE
Render Lode Runner Levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#470]
If we are going to generate new levels for Lode Runner, we need a way of visualizing them. We should start by visualizing the existing levels.

We need a method that takes as input a List of Lists of Integers representation of a Lode Runner level and creates a graphical preview of the level. This will require you to have access to graphics files (pngs) of the individual tile types. I believe you will need to manually extract these yourself from the unprocessed level images in VGLC. Make sure they are all the same size. Save the resulting files in a subdir of the LodeRunner directory called "tiles".

Once you have extracted the tiles, you will need to load them into a visualizer based on a List of List of Integers. You will need to become familiar with the BufferedImage class. You might also look at the DungeonUtil.viewDungeon method for inspiration.

**Comment by kdsteckel** [comment]
We now have visualizations for the tiles in Lode Runner. 
@schrum2

**Comment by schrum2** [comment]
![image](https://user-images.githubusercontent.com/8397236/82087576-fca2dc00-96b5-11ea-934f-4f69471eadb1.png)

**Comment by kdsteckel** [comment]
Continued to work on getting the levels to render based on of the tile images in the subdir created earlier today. 
Still not done, but made progress
There is now a method called getBuffreredImage that should place display the rendered level.
Started on the method called setTilesForBufferedImage that will place the image tiles at the correct place based on the number code. 
Based my methods off of similar ones that I saw in the DungeonUntil class but will probably need to refactor. I think that the method for filling the image will probably be simpler than the method in DungeonUtil. 
@schrum2

**Comment by kdsteckel** [comment]
![grid](https://user-images.githubusercontent.com/50111166/82239749-e6d42780-98fe-11ea-82cd-c5fb93b59bae.PNG)

**Comment by kdsteckel** [comment]
![gridDiggableGround](https://user-images.githubusercontent.com/50111166/82245834-4b947f80-9909-11ea-8d9a-498fa9685039.PNG)
Grid is now filled with diggable ground tiles. @schrum2

**Comment by kdsteckel** [comment]
![fullyRenderedBadTiles](https://user-images.githubusercontent.com/50111166/82255855-fa8d8700-991a-11ea-9daf-bbfd751854d5.PNG)
@schrum2 
Grid is now fully rendered but the tiles look a little weird so I am going to look into improving those. 
Also need to add comments in LodeRunnerRenderUtil before I commit

**Comment by kdsteckel** [comment]
There might be a problem with loading in the PNG files for rendering the Lode Runner levels. 
Also the placement must be wrong so look into that as well.
There is more details on the PNG file on disk than in the loaded BufferedImage.
Look for an error in the creation of the BufferedImage. 
@schrum2

**Comment by kdsteckel** [comment]
![rendered](https://user-images.githubusercontent.com/50111166/82336479-43434f80-99b0-11ea-8b76-a4031ea84910.PNG)
@schrum2 
Improved scaling of render. 
In the creation stage the label was being made to be height/2 and width/2 so it was half the size it was supposed to be.

**Comment by kdsteckel** [comment]
The ladders look a little weird because of making the tiles 10x10 pixels, it was hard to get a tile for a ladder that would connect right with those dimensions. I don't think that this is a huge deal but worth fixing before closing this issue. @schrum2

**Comment by schrum2** [comment]
Problem with ladder tiles is that the tile image is of the bottom of the ladder, not the middle. Maybe grab a new version of the ladder that maintains a constant white line from top to bottom (take the tile from the middle of a ladder).

**Comment by kdsteckel** [comment]
![Capture](https://user-images.githubusercontent.com/50111166/82347675-8c4dd080-99bd-11ea-9469-d997aa0f7549.PNG)
Rendering looks almost exaclty like the level now that I changed the tile size back to 8x8 pixels.

**Comment by kdsteckel** [comment]
![Capture](https://user-images.githubusercontent.com/50111166/82380876-d3a08500-99ee-11ea-8c65-77d57cab1f69.PNG)
![Capture](https://user-images.githubusercontent.com/50111166/82380918-e61abe80-99ee-11ea-932f-063f07298e55.PNG)
![image](https://user-images.githubusercontent.com/50111166/82380944-fa5ebb80-99ee-11ea-9d4c-07dca5a56c0f.png)
Some example of the rendered levels from the GAN right now. 
@schrum2
