### ISSUE TITLE
Play Lode Runner Levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#472]
Though I still want to be able to render Lode Runner levels with the original graphics #470 , I also want us to be able to play them. Rather than try programming that from scratch, see if this code can be incorporated into our repo:
https://icecreamyou.github.io/LodeRunner/
https://github.com/IceCreamYou/LodeRunner

Basically, make a new package to contain all of these files ( icecreamyou.loadrunner ) and make sure you can run their code. Then, figure out a way to convert the VGLC format into their level format and play those levels.

**Comment by kdsteckel** [comment]
Still having trouble finding all of the places where I need to enter FILE_PATH for the player to work in our package. 
The Error: 
Error: reading the level file src/main/java/icecreamyou/LodeRunner/CAMPAIGN-1.txt did not complete. Can't read input file!...
Weird error message because it has the whole path, but it can't get the file? 
@schrum2

**Comment by kdsteckel** [comment]
Could be something in the getLayoutAsArray() method in the Layout.java class.
@schrum2

**Comment by kdsteckel** [comment]
I just pushed what I had at the end of the day, but I definitely have more work I need to do in this issue. @schrum2

**Comment by kdsteckel** [comment]
Solved the "Error: reading the level file src/main/java/icecreamyou/LodeRunner/CAMPAIGN-1.txt did not complete." error by removing an extra file path constant from the Level constructor.
The file path only needs to be in the getLayoutAsArray in the layout class becasue that method gets called in the constructor for Level. 
@schrum2

**Comment by kdsteckel** [comment]
![PlayLodeRunner1](https://user-images.githubusercontent.com/50111166/82460596-fe3a1e80-9a7e-11ea-85b4-4b3b8b27d134.PNG)

Made sample grey tiles be displayed on side of window. 
The Images are found the the constant DEFAULT_IMAGE_PATH so to get those images you just add the file path onto that constant. 
Still a lot of work to do, but the player and the door are displayed in the game window. 
@schrum2

**Comment by kdsteckel** [comment]
![PlayLodeRunnerDone](https://user-images.githubusercontent.com/50111166/82468561-8d97ff80-9a88-11ea-94d6-b7cce320f164.PNG)
Got the code to work to be able to play levels. SOlved by removing FILE_PATH from everywhere besides that was not creating a file. 
@schrum2

**Comment by kdsteckel** [comment]
Levels are playable after the last commit that removed FILE_PATH from all instances of images that were not reading from a file or creating a new file.
@schrum2

**Comment by schrum2** [comment]
Actually, there is still an unresolved component of this issue. You need to write code that accepts a Lode Runner level in the List of Lists if Integers format and then converts/plays the level in the YouIcecream  code.

By the way, even if we eventually don't train the GAN with the start/spawn point #394 , we clearly still need to have an integer encoding of the spawn point for the levels to be playable, so keep that in mind.

**Comment by kdsteckel** [comment]
There is now code that converts the VGLC levels into IceCreamYou format, but I now need to write a method to convert a List<List<Integer>> level into IceCreamYou format. @schrum2

**Comment by schrum2** [comment]
Can you show a picture of a level from VGLC in the IceCream format?

**Comment by kdsteckel** [comment]
I posted it in issue #482. 
@schrum2

**Comment by kdsteckel** [comment]
moved the converted Level1 file into the window to be played, but there is a big scaling issue where things are there but it is all bunched in the top corner of the game window and you get a null pointer exception when you try to play because they can't find a player. This is because we do not generate a spawn point for our levels. If the level name ends in "-level.txt" and is in the IceCreamYou.LodeRunner directory it will be loaded as an option to be played in the game. The IceCreamYou game panel is 600x600 so we could add a scalar to the conversion to try to fix the issue, gonna try to keep the IceCreamYou code as close to the original as possible. 
@schrum2

**Comment by kdsteckel** [comment]
Just putitng this here so I don;t forget right now, but I think theres a way to make a second "CAMPAIGN" of the VGLC/generated levels. 
@schrum2

**Comment by kdsteckel** [comment]
![image](https://user-images.githubusercontent.com/50111166/82936577-6b085980-9f54-11ea-983c-cf79da006e6f.png)
Scaling issue is pretty much fixed now. But now there is an issue with the placement of the enemies. They all get place in the ground so they can't move and can't attack the player. 
@schrum2

**Comment by kdsteckel** [comment]
![image](https://user-images.githubusercontent.com/50111166/82939648-42369300-9f59-11ea-924d-086a80422d9f.png)
Example of the enemies bad placement.

**Comment by kdsteckel** [comment]
Also we need to add a way to win the level because right now we are just collecting the gold and then are stuck in limbo. 
Need to work on vertical alignment and making the original levels work as well. 
@schrum2

**Comment by kdsteckel** [comment]
Players can now win the levels that we load in by collecting all of the coins instead of having to pass through a portal that were not present in the levels from the VGLC @schrum2

**Comment by kdsteckel** [comment]
The problem with the enemies is in the dropToSolid method in the Level class. 
Its purpose is to put the enemy on the ground because they can't fall but for some reason it is just putting them all on the ground.

**Comment by kdsteckel** [comment]
It is not updating the value of minY in dropToSolid so it is just placing them on the bottom of the map
@schrum2

**Comment by kdsteckel** [comment]
![enemy error](https://user-images.githubusercontent.com/50111166/82951791-76b44a00-9f6d-11ea-80d3-7dc82b6185a9.PNG)
Level one is now the only level that does not place the enemies correctly. 
@schrum2

**Comment by kdsteckel** [comment]
![enemy error](https://user-images.githubusercontent.com/50111166/82952271-45884980-9f6e-11ea-9271-3383be49113d.PNG)
Actually level 5 is also not placing enemies correctly either in some cases

**Comment by kdsteckel** [comment]
To Play levels that we pass in directly, not from a file, may need to make a GAN mode to simplify things. 
Also need to make a new cleanCopy method in the level class that gets it from the right constructor. 
Possibly other helper methods to be able to play levels that are not read from files

**Comment by kdsteckel** [comment]
Still some unresolved issues such as enemy placement when they start in the air, but this issue is probably pretty close to being able to be closed in my option. 
@schrum2

**Comment by kdsteckel** [comment]
Issues that still need to be addressed here are in no particular order: 
1. enemy placement
2. sometimes you cannot fall through dug holes
3. When you get hit by an enemy it clears the screen and resets the entire level when the play button is pressed. I need to look into it a little more to see if that is what usually happens, but I'm pretty sure it is supposed to go back to the screen it displays before hitting play initially. Where the ground, ropes ladders, and spawn point are displayed while everything else gets displayed when you hit play. It should hopefully be a fairly simple fix. 
@schrum2

**Comment by schrum2** [comment]
Player can now fall through holes properly. Enemies fall until they land on ground.

The third issue about the screen clearing after finishing the level is not a huge concern ... press play again and it works. I'm going to close this issue.
