### ISSUE TITLE
Simple Lode Runner Game Model to Apply A* to

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#474]
A* search is able to find a way to a goal (beat a level) by modelling the state transition dynamics of the game. For any state, there is a model that indicates what actions are available and what states each of those actions lead to. With such a model, you can apply A*.

However, actual games tend to have a lot of low-level interactions, and complex state spaces, which can make applying A* infeasible, or at least computationally expensive. For example, this amazing video shows A* being applied to Mario https://www.youtube.com/watch?v=DlkMs4ZHHr8 . The red paths are various action sequences the agent is considering, and every single action transitions to a new state that is just a tiny nudge forward along one of the red lines. This representation is highly accurate, but expensive.

In contrast, you can actually learn a lot about a level by using a simplified model. For example, if you look at Figure 4 of the CPPN2GAN paper ( https://arxiv.org/abs/2004.01703 ) you'll see how a simplified Mario was used to assess the beatability of Mario levels. In this representation, every X is a location you can move to with a single action. So, a RIGHT action moves you one entire tile length. If you are jumping and moving right, then you move UP-RIGHT to the diagonal tile. There is also a simple model of gravity that allows Mario to jump 4 tiles high before beginning to descend.

The code for this is launched in MarioLevelTask where the marioSimpleAStarDistance is calculated, though a lot of the necessary code is in the files MarioAction and MarioState.

So, the reason I'm telling you this is that I want you to make a simplified model for beating Lode Runner levels with A*. The model will involve moving one tile at a time, moving up ladders and across ropes, etc. You will need to track treasures too. You will need to play some version of the game and/or watch youtube videos of game play to get a sense for the game dynamics. 

Make a method in a utility class that returns the simplified action sequence for beating a level using this model. You'll need a new package for this and the other files you create (for the states and the actions).

**Comment by kdsteckel** [comment]
The paper on Lode Runner talks about two different steps that help to verify if a level is playable: 
Playablility to see if all of the gold can be reached to solve the level and Connectivity to see how many coordinate points in the level the player can reach and returns it as a percentage. The combination of these two techniques could be really useful for creating interesting levels.  For instance, is there a way to minimize the amount of tiles that the player can reach while still making a beatable level? 
I couldn't find anything in the paper about where the spawn point would be, in fact the examples of levels that there was not a spawn point. Maybe they hard coded it? 
@schrum2

**Comment by schrum2** [comment]
They show a level with certain locations circled to indicate an A* path at one point. I suppose the assumption is that the player starts at the lower left? I suppose we could pick pseudo-random start points ... eventually.

However, before worrying about that, just focus on verifying that the VGLC levels are beatable.

I suppose that we should provide some kind of command line option for the spawn point character to map to an int value of 7 in our code in some circumstances. Even if we are artificially defining the start point randomly, we need a way for that to be encoded in the level representation.

**Comment by schrum2** [comment]
Some clarifications here:
IF there is an int code for a spawn point present in a level, then it should be interpreted as such. However, the training data should not have spawn points (I don't think it does).

If a level has no spawn point, then one must be added. Pick a random empty space.

To apply A*, you will need to have a heuristic. Use Manhattan distance to the nearest treasure object.

**Comment by kdsteckel** [comment]
First pass of this when doing Astar treat enemies as being empty spaces to make it a little simpler to start off.

**Comment by kdsteckel** [comment]
First thing I need to do to in the LodeRunnerLevelTask is to define an A* Agent that will play the level with a parameter. Then start filling in the given methods and will have to add helper methods to fill the goldLeft set, get the level, and probably more. 
@schrum2

**Comment by schrum2** [comment]
My recommendation for testing this out is to create a main method in the appropriate class that loads Level-1 from the VGLC data, and then applies A* to it, and prints out the action sequence.

Eventually, you should write code that takes the image/rendering of the level and modifies it by marking the locations along the solution path.

**Comment by schrum2** [comment]
The `lodeRunnerLevelAgent` parameter is unnecessary and the `AStarAgent.class` you are using is unnecessary, and also specific to Mario anyway. Remove this parameter. @kdsteckel 

This is a bit confusing, but there are two types of A* applied to Mario. One is for full agents that actually play the game (you are not doing anything like that). The other is a simplified A* for a simplified level representation ... that's what you are emulating for Lode Runner

**Comment by kdsteckel** [comment]
write a method to search the vglc data to find the spawn point and it removes the spawn point while keeping a marking
make new constructors one with only level and one with level and point with start coordinates 
remove gold but mark it when creating the goldLeft set 
Fix the y coordinates 
Right now the code allows you to walk on air, if current position 
If there is no ground then your only option 
re write passable methods for vertical and horizontal 
Did I get everything we talked about? @schrum2

**Comment by kdsteckel** [comment]
For some reason, the newGoldLeft is never changing from goldLeft. might have something to do with the point. The size is staying the same too because I added an additional part of the toString() method to print the size in every State. 
Need to write the method to get the spawn point for levels from the VGLC data there is probably something in LodeRunnerVGLCUtil that already does something similar. 
We talked about changing the if statements in the getSuccessor method of the LodeRunnerState to switch case, so try to add that. 
Added the method headers for the two new constructors we needed, one from just the level and one from the level and the starting point. We might need to write a method to find the current amount of gold to pass into the constructors. 
Recheck the new passable methods because the action sequence is still always null. Might need to have individual ones for up and down as well because you can go down if the space below you is empty, but you cannot go up if the space above you does not have a ladder. So the cases are different I think.
Probably should update the isGoal() method to have something to do with the heuristic. Maybe when the largest Manhattan distance is 0?
Take care of the case where you are allowed to walk on the air. Check the square below you in right or left actions and fall until you hit the ground if it is empty. This needs to happen before newX is updated to avoid moving when you should not be allowed to.  
@schrum2

**Comment by schrum2** [comment]
> Probably should update the isGoal() method to have something to do with the heuristic. Maybe when the largest Manhattan distance is 0?

Do not do this. Just make isGoal depend on the size of the set of treasure points.

For moving left or right, check if there is ground under the current position first.

Basically, having the passable method only makes sense for left/right movement. But for up, you need to check if there is a ladder above. Since we will use the down action for going down ladders and for falling, it can probably use the passable method to check the tile below.

**Comment by kdsteckel** [comment]
From looking at the output of mostRecentVisited set in LodeRunnerState, I could tell that the search is only looking at the bottom 2 rows (row 20 and 21) when I gave A* 300 attempts. It successfully picks up and modifies the amount of gold in the level at point (20,20). The x values range from 15-21, so it getting stuck in a box at the bottom of the level for some reason. 
@schrum2

**Comment by kdsteckel** [comment]
After changing the conditions for automatic falling if there is no ground beneath them to be not equal to the ground or diggable ground, the range increased but only slightly.

**Comment by kdsteckel** [comment]
The search going from (15,20)-(20,20). 
At (15,20) the left is null when it should be fine to go left because it is an empty space. 
At (20,20) the right it null with the same circumstance.
The gold at (20,20) is successfully picked up and decreases the size of the gold set, maybe there is something stopping it from going any farther after picking up the gold. 
No idea why it is not going any farther left than 15 in the x-direction. 
Also, up and down are always null, which is what they are supposed to be given the circumstances but they have not been tested yet. 
@schrum2

**Comment by schrum2** [comment]
A* returns an action sequence now. Agent can move up/down ladders, fall, move left/right, and collect treasure.

Next, add support for traversing ropes, digging ground, and visualizing the final solution by getting all of the locations associated with an action sequence and placing X marks on the image to signify where the agent went.

**Comment by kdsteckel** [comment]
<img width="265" alt="SolutionPathLevel1" src="https://user-images.githubusercontent.com/50111166/83445860-60960600-a413-11ea-92a7-cc72d21f67ff.png">
Solution path for level 1. Red x's show the solution path, and white x's show the visited states not in the solution path.

**Comment by schrum2** [comment]
The issue with catching the rope while falling seems like it will require the least coding, so fix that first.

Since digging is definitely required, let's start by assuming (falsely) that dug up spaces stay open forever. In that case, track dug up locations with a HashSet (don't change the level format). This requires that whenever you check what a tile type at a location is, you also have to check the HashSet of locations that used to be diggable tiles

**Comment by schrum2** [comment]
Also, could you make is so that the final render displays the version of the level that still has the treasures in it?

**Comment by kdsteckel** [comment]
Next thing to work on for this is getting digging to work. 
Start with an empty set of points and then fill it with the points of the ground that has been dug.

**Comment by kdsteckel** [comment]
Updated code to take DIG_RIGHT and DIG_LEFT as options for move. 
Having trouble with updating the set, for some reason it never has more than one element in it from the current state if it chose to dig that move. 
Still working on ways to troubleshoot that. 
@schrum2

**Comment by schrum2** [comment]
We can beat Level 2 with A* now:
![image](https://user-images.githubusercontent.com/8397236/83573523-42063c80-a4f1-11ea-9125-c877bf3f7f14.png)
The trick was to remove the DIG actions and just give the agent the ability to directly move downward through diggable ground. I worry this might be a little bit too permissive, so we should keep an eye out for weird solution paths in other levels we check. Still, the solution path for Level 2 seems legit.

So, what is still required before this issue can be closed? 
Finish `LodeRunnerLevelTask`. In particular, make it evoke the A* search in the `oneEval` method and create a (scores,other scores) pair in which there is only one fitness score, which is the length of the A* path (longer/harder levels are better).

Also in the `oneEval` method, make it so that `if(CommonConstants.watch)` then the level rendering with the A* path will pop up and `MiscUtil` will wait for a key press. There is similar code in `MarioLevelTask` and `ZeldaDungeonTask` for doing this, so write similar code.

**Comment by schrum2** [comment]
LodeRunnerGANLevelTask and LodeRunnerLevelTask need javadoc on the methods as well as the class headers. In general, more comments are needed.

I haven't tested the code yet, but `LodeRunnerState start = new LodeRunnerState(level);` is going to fail to find a start state. You need to pick the start state here the same way you do for the interactively evolved levels. In fact, make sure that you are using the same code in each case ... may require moving things around.

The call to search should use the "aStarSearchBudget" parameter.

For debugging, add a bit right before the return that is inside `if(CommonConstants.watch)` and renders the visualization of the level with the A star path and visited states. Use a MiscUtil wait to pause, and have the option of entering `P` to play the level (in IceCreamYou). Compare with ZeldaDungeonTask.

To eventually test, you'll need a main method in LodeRunnerGANLevelTask that calls MMNEAT.main in the right way.

**Comment by kdsteckel** [comment]
Added Java docs on methods. 
Added a random spawn point so that the start state is valid for these levels. 
have it calling "aStarSearchBudget" parameter.
Added the main method that calls MMNEAT.main.

**Comment by kdsteckel** [comment]
Added the debugging code, I think I am done with this issue. Can you check it? @schrum2

**Comment by schrum2** [comment]
Once the debugging code for CommonConstants.watch successfully places the player in the level so you can actually play it, the issue will be done.

**Comment by kdsteckel** [comment]
Successfully places the player and the gold in the level in the correct places.
