### ISSUE TITLE
HybrID CPPN2GAN and Direct2GAN in Zelda

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#477]
At the end of the CPPN2GAN paper ( https://arxiv.org/abs/2004.01703 ) we propose in future work some ways of combining CPPNs and direct encodings that are similar to an algorithm called HybrID: https://journals.plos.org/plosone/article/comments?id=10.1371/journal.pone.0174635
Although there are variations, the first idea to try is that you start with the CPPN2GAN approach, but at some point you take the direct latent vectors spit out by the CPPN and evolve with them instead (Direct2GAN) from that point onward.

My version of HyperNEAT already supports HybrID, but that is based on neural networks, and I don't think it will work with MAP Elites as-is. In fact, I want to change how it works with MAP Elites. Instead of switching all CPPNs into direct vectors, I want to have a mutation that allows for a switch from CPPN to Direct form.

This will require several steps. First, in the edu.southwestern.evolution.genotypes package make a new Genotype that can be either a TWEANNGenotype (CPPN) or a BoundedRealValuedGenotype. I'll commit something soon to help you with this. These genotypes start as TWEANNGenotypes, and will generally be mutated as normal, but there is a small chance of a new type of mutation that transitions the TWEANNGenotype into a BoundedRealValuedGenotype.

**Comment by schrum2** [comment]
I just merged dev into your branch so that you have access to EitherOrGenotype. You should create CPPNOrDirectToGANGenotype as follows in the same package.
```public class CPPNOrDirectToGANGenotype extends EitherOrGenotype<TWEANN,ArrayList<Double>>```

This class will require a constructor with no parameters that calls the super constructor with a newly constructed TWEANNGenotype.

You will also need to override the mutate method in the following way:
Create a command line parameter called indirectToDirectTransitionRate that is a mutation rate. You will need to create a class that extends the Mutation class. In the overridden mutate method of the CPPNOrDirectToGANGenotype class, you need to use this class to mutate the genotype. It should use the CPPN to create a bunch of latent vectors, but then save them into an ArrayList that is used to initialize a new BoundedRealValuedGenotype, and transition the EitherOrGenotype to be the second form.

Once that all works, you can move to create a task extending the ZeldaDungeonTask that handles these CPPNOrDirectToGANGenotypes. You'll want to avoid duplicating code that is already present in the ZeldaGANDungeonTask. You might want to extract a static version of its getZeldaDungeonFromGenotype method so that you can call it externally.

**Comment by schrum2** [comment]
Some requests:

- Move CPPNOrDirectToGANGenotypeMutation to edu.southwestern.evolution.mutation.tweann
- Remove both constructors and replace with a single constructor with no parameters that is hard coded to act like your current CPPNOrDirectToGANGenotypeMutation(String rateName) constructor, but with the command line parameter specified.
- ADD JAVADOC COMMENTS!
- Refactor/Rename CPPNOrDirectToGANGenotypeMutation to ConvertCPPN2GANtoDirect2GANMutation

You also still need to create the task that uses this genotype, but before that you should make a unit test for the mutation: ConvertCPPN2GANtoDirect2GANMutationTest.

**Comment by schrum2** [comment]
Once the task works, make a batch file in batch\Experiments-2020-MoreCPPN2GAN that copies the settings of the existing files, but uses the new task and new genotype

**Comment by schrum2** [comment]
This seems to work. Close it once you have created the requested batch file

**Comment by cappsb** [comment]
Created batch file
