### ISSUE TITLE
Interactive GAN Evolution of Lode Runner Levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#478]
Although we don't quite have a working GAN for Lode Runner yet ( #394  ), we do at least have a GAN model that generates something. Therefore, you can start work on an interactive evolution interface for evolving Lode Runner levels, and eventually be able to play them #472 .

Make a ` edu.southwestern.tasks.interactive.loderunner` package and make a `LodeRunnerGANLevelBreederTask` within it. You can model this partly on the `MarioGANLevelBreederTask` which extends `InteractiveGANLevelEvolutionTask`. Since you are extending the `InteractiveGANLevelEvolutionTask` class, a lot of the work is done for you. Just tell Eclipse to add the unimplemented methods and fill in the blanks.

You should render the levels using your renderer #470 and (eventually) play them using the code we got from that YouIceCream repo #472 .

**Comment by kdsteckel** [comment]
Levels are now displayed in the window. Still need to update the model i the mornin gto the new model to see if there is improvement.
Prints each level in a different window just like the LodeRunnerGANUtil in addition to the levels in the buttons of the LevelBreeder.  Most likely a simple fix in the LodeRunnerGANUtil. java class or the LodeRunnerRenderUtil.java class.

**Comment by kdsteckel** [comment]
Removed the extra windows that are displayed by calling createBufferedImage instead of getBufferedImage in the getButtonImage method of LodeRunnerGANLevelBreederTask.java. 
getBufferedImage actually displays the level in a window from the createBufferedImage method that actually creates the level. @schrum2

**Comment by kdsteckel** [comment]
Added comments into this class. 
Javadocs on all the methods and for the class itself.
@schrum2

**Comment by kdsteckel** [comment]
try to put the play command in a new thread like Mario, I was getting a ton of errors even tho all of the curly braces matched up Will need to refactor a lot of stuff to make it be able to be playable, just turns to a white screen when you press play in the level breeder and then play in the game window. Before pressing play, the level from the level breeder is displayed correctly. 
<img width="1074" alt="Untitled 2" src="https://user-images.githubusercontent.com/50111166/83573705-a0cbb600-a4f1-11ea-9cf8-917c6bf961c8.png">
Start with this error. It may be something about how it start with CAMPAIGN-1 every time. Also, need to find where they place the level title and change it to something that is descriptive to the GANLevelBreeder level.

**Comment by schrum2** [comment]
Although you are still working to fix issues with playing the levels and the visualization, we are able to launch the game from the interactive interface. Therefore, closing this issue.
