### ISSUE TITLE
Specify output dimensions for generator_ws.py

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#480]
Currently, `generator_ws.py` tries to determine the size of the relevant output window based on the number of tile types (z_dims) for the domain. This was destined to be problematic as support for more games was added. The logic for this is in the following code:

```
    if z_dims == 4 : # Assume this is Zelda (4 tiles, currently)
        out_height = 16
        out_width = 11
    elif z_dims == 6 or z_dims == 3: # Fixed Zelda (rotated)
        # The fixed Zelda rotates the rooms to match the original game presentation
        out_height = 11
        out_width = 16
    elif z_dims == 8: #Lode Runner
        out_height = 22
        out_width = 32 
    else: # Assume this is Mario (10 or 13 tiles, depending)
        out_height = 14
        out_width = 28
```

Change the Python code so that `out_height` and `out_width` are directly specified as command line parameters to `generator_ws.py`. This change will also require you to move the logic from this Python code into the Java class GANProcess.

While you're at it, go ahead and remove the default constructor GANProcess() that defaults to Mario. Treat Mario like all of the other domains and move its initialization details into the place where the Zelda and Lode Runner details are specified.

This will hopefully fix #394 but be sure to test Zelda and Mario after making this change.

**Comment by kdsteckel** [comment]
![LevelBreeder](https://user-images.githubusercontent.com/50111166/82578962-b8e72100-9b52-11ea-87e9-234a5f0caccf.png)
Updated with new mapping as well. 
LodeRunner is now generalized. 
@schrum2

**Comment by kdsteckel** [comment]
The levels with 3 tile types now a have the correct width and height. Had to add a new condition parameter for selcting the height and width in the GANProcess.java file. 
I was putting the conditions in the wrong order, which is why it was not working before. 
@schrum2
