### ISSUE TITLE
ZeldaGANLevelBreederTask: remove doors from previewed rooms

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#481]
In this interactive evolution task, the doors are actually placed by the graph grammar when clicking Dungeonize, so it doesn't make sense for doors to show up in the visualization of the evolved rooms. Therefore, remove the doors from each rooms being displayed. 

Note that after clicking dungeonize, this preview is what the dungeon looks like after doors are placed by the graph grammar, so the doors should be visible in that interface.

**Comment by cappsb** [comment]
Fixed the display so that it no longer shows doors. Doors still show up after you click Dungeonize.
