### ISSUE TITLE
Convert VGLC Lode Runner level to IceCreamYou format

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#482]
Input text file in one format and output text file in other

**Comment by kdsteckel** [comment]
Consider making a new Util class to handle this? or does it fit in with one that is already there?

**Comment by kdsteckel** [comment]
Implemented a simple switch case to convert the levels from the VGLC data to the IceCreamYou format
@schrum2

**Comment by kdsteckel** [comment]
![VGLCtoIceCreamYouConversion](https://user-images.githubusercontent.com/50111166/82699092-9b3cb900-9c31-11ea-8fa3-f56381c2ef38.PNG)
Conversion of level 1 to IceCreamYou format. Does not display the whole thing because of space. @schrum2

**Comment by kdsteckel** [comment]
An issue that still need to be addressed is that the IceCreamYou levels have as the first line the next level that will be played, but I am not sure that is necessarily a problem we will have to deal with. 
For instance, this is the first line of the first level in the levels provided by IceCreamYou: "nextLevel:CAMPAIGN-2"
@schrum2

**Comment by schrum2** [comment]
What I want you to do is output that text to a file and try loading the file to show an in-game picture. Load and play the VGLC level 1 in IceCreamYou

**Comment by kdsteckel** [comment]
The next level is only set in CAMPAIGN and CHALLENGE because they are a whole string of levels, so I don't think that we will need to worry about that for our level conversions

**Comment by kdsteckel** [comment]
try to put the play command in a new thread like Mario, I was getting a ton of errors even tho all of the curly braces matched up Will need to refactor a lot of stuff to make it be able to be playable, just turns to a white screen when you press play in the level breeder and then play in the game window. Before pressing play, the level from the level breeder is displayed correctly. 
<img width="1074" alt="Untitled 2" src="https://user-images.githubusercontent.com/50111166/83573705-a0cbb600-a4f1-11ea-9cf8-917c6bf961c8.png">
Start with this error. It may be something about how it start with CAMPAIGN-1 every time. Also, need to find where they place the level title and change it to something that is descriptive to the GANLevelBreeder level.

**Comment by schrum2** [comment]
This particular issue is focused on converting the VGLC levels to the IceCreamYou format. I understand that there are still some issues with loading and playing these levels that are handled in issue #472 . However, I would like to get this issue closed. The last step required to close this issue is to run a loop that converts ALL of the VGLC Lode Runner levels into the IceCreamYou format (all 150) and add those text files to the repo (force add for text).

**Comment by kdsteckel** [comment]
force committed all 150 original lode runner levels into the IceCreamYou directory so we can play all the levels.
