### ISSUE TITLE
ZeldaCPPNtoGANLevelBreederTask: checkbox toggles zeldaCPPNtoGANAllowsRaft

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#487]
This will be slightly more complicated than #486 and #485 because it requires changing the number of CPPN outputs, which means the whole population has to be reset whenever it is selected. We may even want a dialog box to pop up warning the user that changing this setting will reset the evolved population. There is an option in the task to reset the population, so you can simply call that after changing the parameter, though there may be other settings you have to tweak (you may need to manually change the number of CPPN outputs, though I'm not sure). In any case, do this after the other interface issues for this task.

**Comment by cappsb** [comment]
Created checkbox that functions properly. When pressed, it sends a warning that it will reset the population, then it generates new map layouts with the proper number of CPPN inputs
