### ISSUE TITLE
Generalize CPPNOrDirectToGANGenotype for Mario

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#488]
The CPPNOrDirectToGANGenotype was originally designed for Zelda, but it should be possible to do something similar for Mario. However, ConvertCPPN2GANtoDirect2GANMutation seems to very specifically use code associated with Zelda.

Rename ConvertCPPN2GANtoDirect2GANMutation so that it has Zelda in the name, and also make a similar but distinct version for Mario. Then, in the mutate method of CPPNOrDirectToGANGenotype, have some cases that use the right operation based on the value of GANProcess.type.

In fact, put a case in there for LodeRunner too, but make it throw an UnsupportedOperationException

**Comment by schrum2** [comment]
Unit test the Mario version of the mutation. Do this by modifying ConvertCPPN2GANtoDirect2GANMutationTest. rename test to testZelda so that you can also define testMario. You will actually need to move all of the current setUp code into testZelda, since testMario will have to initialize the parameters in a completely different way.

**Comment by cappsb** [comment]
Batch file runs smoothly, the task works properly.
