### ISSUE TITLE
Log number of CPPN vs Direct genotypes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#490]
When you run the new ZeldaMAPElites-CPPNThenDirect.bat batch file, it creates logs called ZeldaDungeons-CPPNThenDirect2GAN0_Fill_log.txt (for counting the number of occupied bins) and ZeldaDungeons-CPPNThenDirect2GAN0_MAPElites_log.txt (for tracking the specific scores in each filled bin). These logs are also created when running the CPPN only or Direct only approaches.

In the CPPNThenDirect case specifically, I want an extra log file that counts the number of CPPN genotypes and the number of Direct genotypes, and for convenience also tracks the percentage between them.

 The currently used logs are created by instances of MMNEATLog initialized in the MAPElites class. The constructor of this class should use `instanceof` to see if the CPPN then Direct genotype is being used, and set up an additional log in this case. You might also need to change the Archive class.

**Comment by cappsb** [comment]
Created addition in log() to track the number of CPPNs or Directs. Basically loops through all of the genotypes and tracks which is which. Creates file accordingly
