### ISSUE TITLE
More Mario Models

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#496]
The trained GAN models for Mario are in the directory `src\main\python\GAN\MarioGAN`

I would like a few more models, and training these should actually provide a bit of practice for you. Basically, I want models with the following names:
`Mario1_Underground_5_Epoch5000.pth`
`Mario1and2_Overworld_5_Epoch5000.pth`

These are very similar to existing models in this directory, but the number `30` is replaced with `5`. The naming convention for these models means that this number is the input size ... in other words, the number of latent variable inputs. Basically, we have good models that take 30 inputs, but I want some good models that take just 5 inputs.

The json training files are in `src\main\python\GAN`. Use `underground.json` for the `Mario1_Underground_5_Epoch5000.pth` model, and `overworlds.json` for the `Mario1and2_Overworld_5_Epoch5000.pth`

(by the way, @kdsteckel was apparently accidentally training his models without using his GPU, and it didn't take too long. It's much faster now that he is using the GPU. Anyway, I just wanted to make the point that you don't necessarily need the GPU to train these models, but let us know how it goes)

**Comment by cappsb** [comment]
New models uploaded and trained
