### ISSUE TITLE
Enhance Lode Runner Enemy AI 

### ISSUE THREAD

**Issue by kdsteckel** [schrum2/MM-NEAT#498]
We might want to enhance the AI for the enemies in the levels because right now they are pretty lame. In the original game, they can move just as freely as the player, so eventually, we may want to implement that into our gameplay. 
https://www.youtube.com/watch?v=72k1ZYp83tc&t=345s
This video shows an example of the movement of the enemies in the original game. 
This is not super important, just would make things a lot more interesting if we have time.

**Comment by kdsteckel** [comment]
Anytime an enemy can move left, right, up, or fall. 
If you are falling then you keep falling. 
other wise, can you go up? if so then that is a valid action
check all actions, up only if there is a ladder
check Manhattan distance from each action to the player, choose the one with the lowest Manhattan distance (Greedy).  

Enemies don't use the ropes in the version we are working with.

**Comment by schrum2** [comment]
It occurs to me now that enemies can also voluntarily move down if they are on a ladder, so support that as well

**Comment by schrum2** [comment]
@kdsteckel I see that the enemy is following me, but it does not fall. It is able to float in the air. Also, it has access to a ladder, but does not go down the ladder.

![image](https://user-images.githubusercontent.com/8397236/87214135-c5d0f700-c2ef-11ea-8a0e-f4a5e13b943f.png)

**Comment by schrum2** [comment]
@kdsteckel More importantly, when I set smartLodeRunnerEnemies:false, the behavior is still screwed up. We need to have access to the original behavior as well. The current behavior is already too challenging, despite being a bit messed up

**Comment by schrum2** [comment]
Even though we're at a point where we can run experiments, I'm curious if there is any progress on this, or it has just stopped. At the very least, we need to make sure we have a way of using the original weak, but properly functioning AI behavior. Last I checked, AI behavior was a bit broken (agents floating between levels and other weird stuff). Use of the "smart" AI needs to be optional anyway.

**Comment by kdsteckel** [comment]
I am planning on getting to this issue but have been taking some time off. To enable the original enemy AI the parameter "smartLodeRunnerEnemies" just needs to be set to false and it will return to the normal AI functionality. 

@schrum2

**Comment by schrum2** [comment]
I should have checked this issue ages ago, but basically, it is not fixed. Have the smart enemy option set to false, but the enemies still track me down and float through the air in a glitchy way:
![image](https://user-images.githubusercontent.com/8397236/90535229-4b8e6080-e140-11ea-9146-83d7fdf67e97.png)

The easy way to test this is to use `postMAPElitesWatch.bat` (from the dev branch) on any of the results you've been evolving. `postMAPElitesWatch.bat` already sets `smartLodeRunnerEnemies:false` but I still got the behavior shown above.

Please fix this @kdsteckel . Make a new branch off of dev to work on this. All we want at this point is the ability to revert to the old boring behavior we had before. Also, there should be plenty of comments indicating that the "smart" behavior does not work yet.

**Comment by kdsteckel** [comment]
I will work on this later today. Thanks for reminding me about it!

Kirby

**Comment by schrum2** [comment]
Here is an issue you can play around with if you get through other, more important issues.

**Comment by schrum2** [comment]
Very low priority, but not closing this yet

**Comment by schrum2** [comment]
Giving up on this. Not important.
