### ISSUE TITLE
Connectivity fitness function for Lode Runner

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#508]
Some Lode Runner levels cannot be beaten, so we need a way of measuring performance when this is the case. The autoencoder paper mentioned two fitness functions: A* path length and connectivity. I don't think they got too far into the details of connectivity (but check and see if I'm wrong), however, I know that they are basically checking how many locations in the level are reachable.

Add a second fitness function to Lode Runner for connectivity. If the details are lacking in the autoencoder paper, then this is how I think you should define it:

After running A*, get the set of visited states. Then create a HashSet of Points. Loop through all states, extract the (x,y) coordinates into a Point, and add the Points to the set. Note that there could be multiple LodeRunnerStates that visit the same location (but the gold is different), but by adding just the points to a set (no duplicates) you'll see how much of the space is connected. The size of the visited set should be the value for the connectivity fitness.

**Comment by kdsteckel** [comment]
I believe I am done with this issue after the last commit. Can you check it? @schrum2

**Comment by schrum2** [comment]
For both this connectivity fitness and the original A* fitness, add command line parameters (use detailed names ... compare with Mario and Zelda). Basically, each fitness function has a boolean parameter indicating whether to actually use it ... you should compute the values regardless. In fact, no matter what the values of these boolean parameters are, both scores should show up as "other scores" (even if it also shows up as fitness). However, in the end, only add scores to fitness whose corresponding boolean parameter it true.

**Comment by kdsteckel** [comment]
I think this issue is done or close to being done. Can you check it? @schrum2

**Comment by schrum2** [comment]
The parameters work, so I'm closing this
