### ISSUE TITLE
Lode Runner: interactive interface: A* budget control

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#510]
Add an element to the Lode Runner GAN Level Breeder interface that allows the user to change what the A star budget used for search is. Changing this value will directly modify the corresponding command line Parameter.

I want this option to be controlled by direct text input, and when the user presses enter after changing the value is when the levels will update. There isn't an example of a text field input on any of the existing interactive evolution interfaces. However, when you choose to ExploreLatentSpace a new window pops up that does have a JTextField that you can use as an example. In particular, look at the code for `vectorInput.addKeyListener` in the `InteractiveGANLevelEvolutionTask` class.

First, note that this text field will NOT be tied to a JSlider, so your code will be a bit simpler. Also, this code accepts negative and positive double values ... your code will only accept positive ints. So, change `if(!typed.matches("-*\\d+(\\.\\d*)?"))` to `if(!typed.matches("\\d+"))` (I believe that will work)

**Comment by kdsteckel** [comment]
I think I am done with this issue. Can you check it?
@schrum2
