### ISSUE TITLE
Be able to render portions of MegaMan levels in Java

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#511]
In order to evolve MegaMan level segments, we'll need to be able to render them in Java. So, create a class MegaManRenderUtil that has code to allow you to render a portion of a MegaMan level (same size as what you send to the GAN for training). You will need to add png files of individual tile types in the data subdir so you can load them for the visualization.

@kdsteckel made a Lode Runner render class that you can compare with.

**Comment by schrum2** [comment]
Generalize to handle either individual frames or whole levels

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84162166-aff0bd80-aa35-11ea-801a-0b396f5746b4.png)
Currently coded for testing of A*, will allow for individual screens at a later date (will not be hard)

**Comment by schrum2** [comment]
Are hazards (spikes) being visualized? I thought they were part of this level too

**Comment by cappsb** [comment]
The should be rendered, but some things are not properly represented because it is so zoomed out? I'm not sure. It's in the code as the rest of the level that's rendered.

**Comment by schrum2** [comment]
I'm still not convinced that the hazards/spikes are showing up. Also, I looked at level 5, and I would like the tile/viz for moving platforms to be distinct from solid ground (maybe that is the problem with the hazards too ... are they just shown as ground tiles?).  Could also visualize water in level 6.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84196681-2efdea00-aa66-11ea-91f5-a807ee0764c6.png)
The problem was that the level is too large and was only rendering the upper-left-hand corner of the PNG file (which has a blue background), thus not rendering the moving platforms and spikes properly. Water now added to the representation.
