### ISSUE TITLE
Interactive GAN evolution of MegaMan level segments

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#512]
Given a GAN model, you can extend the InteractiveGANLevelEvolutionTask to evolve level segments for MegaMan using a GAN. There are various examples for Lode Runner, Mario, etc. that you can look to for inspiration. However, you can't complete this until #511 is done.

**Comment by schrum2** [comment]
I've been monitoring this thread:
https://megamanmaker.com/forum/viewtopic.php?f=8&t=10703&p=98455#p98455
They indicate that launching the level is not possible, but support may be added later. However, if you go to this page:
https://megamanmaker.com/?page=explore
It actually is possible to simply click a link and have it open up the game to play a specific level. This is exactly what we want, except for levels stored on our personal machine rather than levels stored on the internet. You should ask about this specific feature on the forum ... is it possible to launch a level this way even if it hasn't been uploaded/shared with the MMM community?

**Comment by schrum2** [comment]
Regardless of how that forum post turns out (you need to ask the follow-up question there still by the way @cappsb ), we're still going to want to have a way of saving evolved levels in MMLV format directly to the MMM level directory. Here is how to do it.

First, put a text file `MegaManMakerLevelPath.txt` in the top `MMNEAT` directory. This file will NOT be part of the repo (txt should be ignored automatically) because each person with the code will need to put custom content into this file. It will basically contain the file path (within App ... Local, etc) for the MMM levels.

However, in the interactive evolution interface, add a button `SaveMMLV` which will save the currently selected levels directly to the MMM level directory (using information from `MegaManMakerLevelPath.txt`). A text pop-up should ask the user what filename prefix they want to use (it is a prefix rather than a filename because ALL selected levels will be saved, using the format `<prefix><id>.mmlv`). 

If the `MegaManMakerLevelPath.txt` file does not exist or is empty, or contains an invalid path, then a pop-up should tell the user to create the file and fill it with appropriate information. This is a gentle error message instead of crashing with an exception.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84543678-687e6180-acc1-11ea-88b7-59f7d3ac0565.png)

![image](https://user-images.githubusercontent.com/63438571/84543541-2a813d80-acc1-11ea-8bc0-e05471dd9615.png)
MegaMan level snippets can now be saved. 

**NOTE** 
when saving the levels, they will render here:
![image](https://user-images.githubusercontent.com/63438571/84543621-4f75b080-acc1-11ea-8869-6c714f55c101.png)
So if you save and go back to check if it worked, then make sure you traverse to the upper left corner of the map.

**Comment by schrum2** [comment]
This does indeed work.
