### ISSUE TITLE
Apply MAP Elites to the LodeRunnerLevelTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#513]
Apply MAP Elites to the evolution of individual Lode Runner Levels (single GAN output). Code will go in LodeRunnerLevelTask.

Bin dimensions will be defined in a separate class, but all bin dimension scores will be computed in LodeRunnerLevelTask and also act as "other scores". Here are possibly useful other scores:

- Percentage of ladders (ladder tile count / total tile count)
- Percentage of ground ( (solid + diggable) / total tile count)
- Percentage of rope (rope tile count / total tile count)
- Number of treasures
- Number of enemies
- Percent connected (connectivity / total tile count)

**Comment by schrum2** [comment]
When implementing MAP Elites, try these bin dimensions first:
- Percent connected
- Percent ladders
- Percent ground
And the fitness would be A* Path distance

**Comment by kdsteckel** [comment]
The largest bin for percent ladders was 20%-30% of the level being ladders. We may want to redo our bin dimensions to avoid unnecessary empty bins.

**Comment by kdsteckel** [comment]
Ground and ladders are broke up into bins of 4, [0-4][4-8][8-12]...[36-40]

**Comment by kdsteckel** [comment]
I think that I have fixed the binning to be like we discussed where it is in steps of 4 up to 40, instead of steps of 10 up to 100. 
Can you check it? @schrum2

**Comment by schrum2** [comment]
I'm pretty sure this part of the code is wrong:
```
			int connectedIndex = (int)Math.min(percentConnected*BINS_PER_DIMENSION, BINS_PER_DIMENSION-1); 
			int groundIndex = (int)Math.min(percentGround*BINS_PER_DIMENSION, BINS_PER_DIMENSION-1);
			int laddersIndex = (int)Math.min(percentLadders*BINS_PER_DIMENSION, BINS_PER_DIMENSION-1);
```
To check, I recommend using the MiscUtil wait and printing out things like `percentGround` and `groundIndex`. Under the new scheme, if `percentGround` is between 0.0 and 0.04 you should have `groundIndex` of 0. If it is between 0.04 and 0,08 you have a `groundIndex` of 1 and so on.

Check whether or not this is true and fix it if it is not. Do this before moving on to #521

**Comment by kdsteckel** [comment]
The original binning scheme is working correctly now. 0.0-0.04 has a ground and ladder index of 0, 0.04-0.08 has a ground and ladder index of 1, and so on. 
@schrum2

**Comment by schrum2** [comment]
Can't test this because of this error when running `LodeRunnerGAN-MAPElitesConnectedGroundLadders.bat`

```
Caused by: java.lang.RuntimeException: A Valid Binning Scheme For Lode Runner Was Not Specified
        at edu.southwestern.tasks.loderunner.LodeRunnerLevelTask.evaluateOneLevel(LodeRunnerLevelTask.java:288)
        at edu.southwestern.tasks.loderunner.LodeRunnerLevelTask.oneEval(LodeRunnerLevelTask.java:120)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.evolution.mapelites.MAPElites.initialize(MAPElites.java:178)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:26)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:21)
```

I don't know if the problem is just with the batch file or the code, but you need to test by Maven compiling and running it. @kdsteckel
