### ISSUE TITLE
Evolve Lode Runner Level sequences

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#515]
Make `LodeRunnerLevelSequenceTask` extend `LodeRunnerLevelTask` and work the following way.

Override `oneEval` so that it calls a new abstract method that returns an array of `List<List<Integer>>` (of levels). Then call `super.oneEval' on each level in the array to get all of the results. Combine those results to create a single fitness result for the sequence.

There are many different ways of doing this, and we will need command line parameters to choose between different options. Eventually, we will ad interesting types of fitness scores for the level sequence, but for now, have the following commandline params:
`lodeRunnerLevelSequenceAverages`: if this is true, then the level sequence fitness scores (and other scores) are simply the averages across the scores in the individual levels.
`lodeRunnerLevelSequenceIndividual`: if this is true, then each set of scores from every single level are completely separate fitness functions in the fitness result for the sequence.

**Comment by schrum2** [comment]
By the way, the `LodeRunnerLevelSequenceTask` task is abstract, so something will need to extend if before you can test anything. Specifically, start with a `LodeRunnerGANLevelSequenceTask` where instead of evolving one vector the length of the GAN input, there is a parameter defining how many levels are in the sequence, so that the vector you evolve is that many times as large (e.g. 5 level * 20 latent variables per level = 100 latent variables)

**Comment by kdsteckel** [comment]
Can you look at this? I still think I am doing something wrong somewhere. 
Also, I still need to implement the averaging or individual scores. 
@schrum2

**Comment by kdsteckel** [comment]
![Screen Shot 2020-06-12 at 3 36 12 PM](https://user-images.githubusercontent.com/50111166/84544231-7b456600-acc2-11ea-8a1f-377e67187826.png)

There is a problem in the code where it is not reading the levels correctly out of the sequence. It is probably the way it is being constructed. Tried switching to an ArrayList<List<List<Integer>>> instead of a List<List<Integer>>[] to see if that would help but it did not. Although I am not getting a null pointer exception anymore, so that good. Gonna come back to this on Monday. 
@schrum2

**Comment by schrum2** [comment]
I think the problem is the constructor:
```
	public LodeRunnerLevelSequenceTask() {
		super();
	}
```

Currently, the fitness functions for the Level task are being registered, but the Level sequence task needs a different set of fitness functions. I'll make a commit in a moment that sets you up to work on this.

**Comment by schrum2** [comment]
I know that work stopped on this somewhat abruptly, but where does this issue stand? Does it seem to run? Do I need to test it out?

**Comment by kdsteckel** [comment]
The code for this runs, and there is a batch file that also runs. It is ready to be checked. @schrum2

**Comment by schrum2** [comment]
This is running, but I've noticed at least one issue. 

The Fitness and Other Score labels need to be more precise. When doing averaging, the name of the fitness function you register should say it is the average. When doing the individual scores, you should actually mention the level number: Level1AStarLength, Level2AStarLength, etc.

Also, refactor to avoid repetition of the other score registering.

I'll look more later. However, note that #528 is still more important ... you can focus on this issue later.

**Comment by schrum2** [comment]
In addition to the comments above, I've noticed more problems.
A post watch of the results revealed that the level sequence was just the same level over and over. This seems to be caused by the getLevelSequence method in LodeRunnerGANLevelSequenceTask. First,this class should not be using type T ... it should explicitly be the bounded real valued genotype. Then, in the getLevelSequence method, you need to break that genotype up into several separate latent vector sequences. For example, if the GAN input size is 20, then the first 20 values in the genotype generate level 1, and the next 20 generate level 2, etc.

This might explain the weird scores I was seeing, but I also think that there may be some issue with the fitness or other score calculations, but I could be wrong ... fix the above issues first.

**Comment by kdsteckel** [comment]
The levels in the sequence are all unique and there are exactly the amount of levels that are specified by the parameter. Before there were extra copies of each level. i.e. [level1,level2,level3,level1,level2,level3,level1,level2,level3].
Next thing to do with this issue is to work on the score labels and make sure that they are calculated properly.

**Comment by kdsteckel** [comment]
<img width="992" alt="Untitled" src="https://user-images.githubusercontent.com/50111166/86281704-901b6800-bba3-11ea-9430-35c57ac96061.png">
Got the same error as I did in the Level Anaylsis when I was testing the level sequence task to see if the labels were correct. @schrum2

**Comment by schrum2** [comment]
The LodeRunnerLevelTask currently catches IllegalStateException if the search fails. Add a catch for this OutOfMemoryError that does the same thing

**Comment by schrum2** [comment]
After the fixes in the last few commits, this works.
