### ISSUE TITLE
Maven build fails on Mac 

### ISSUE THREAD

**Issue by kdsteckel** [schrum2/MM-NEAT#516]
Failed tests:   test(edu.southwestern.evolution.mutation.tweann.MeltThenFreezePreferenceMutationTest): expected:<false> but was:<true>
  test(edu.southwestern.evolution.mutation.tweann.MeltThenFreezePolicyMutationTest): expected:<false> but was:<true>
  test_Upper_Boundary(edu.southwestern.evolution.crossover.network.TWEANNCrossoverTest)

**Comment by schrum2** [comment]
Fixes should help, though can't be certain. This is in the Simplified branch
