### ISSUE TITLE
Evolving Horizontal MegaMan Levels from multiple segments

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#517]
Mario GAN allows for evolution of long levels by combining multiple segments together. Add this option to the interactive interface #512 by adding a slider for deciding how many megaman chunks/segments to use in making up a level. In fact, you will need to add a command line parameter for this. 

You're basically copying the behavior of the MarioGANLevelBreederTask

Note that we'll eventually need to find a way to make this more complicated to support both vertical and horizontal segments, but for now we'll just do one at a time.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84422329-7d37f800-abe2-11ea-8580-009a66bad824.png)
Seems to work well. Levels stretch and can play with the latent space
