### ISSUE TITLE
Evolve Vertical Levels in Interactive Interface

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#520]
We need to train and evolve vertical levels in the interactive interface. We eventually need to train one model that is the complete level.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84528612-a3729c00-aca5-11ea-85dc-c4be3cc36746.png)
Vertical levels in interactive evolution

**Comment by schrum2** [comment]
Clearly works!
