### ISSUE TITLE
MegaMan levels with mix of horizontal and vertical

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#523]
This is tricky. There are lots of decisions to be made, but there are two broad approaches I can envision. 
- One involves training a single model for both horizontal and vertical segments, and interpreting its output in order to place the segments appropriately.
- The other involves using both a vertical and a horizontal model (two GANs) and switching back and forth depending on where vertical/horizontal segments are desired.

So, I guess the first thing to do is to train a model on all segments (vertical and horizontal) and once you have that, we can figure out what to do with it.

In the meantime, you can investigate how to use a combination of two GAN models to fill out the segments of a pre-specified level path. Right now, we are unclear where this path will come from (human specified or evolved) but the code should work either way.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84794690-2c4a4a00-afbc-11ea-8b9a-eee6954c98f8.png)
First attempt

**Comment by schrum2** [comment]
Yeah, we will undoubtedly produce many unbeatable levels with a single model trained on the horizontal and vertical segments. I'm curious to eventually use objective fitness functions on this model #529 , but in the meantime, I think it makes sense to move on to the combination of horizontal and vertical models.

To support this, we'll need several command line parameters, and corresponding interface buttons. A checkbox should indicate if one or two models are used. If two models are used, then the original MegaManGANModel parameter should be completely ignored, and two new/distinct parameters should be used instead: MegaManGANHorizontalModel and MegaManGANVerticalModel.

The other tricky issue here is that the code is very heavily biased toward only ever having one GAN model running at a time. There are all of these static methods in GANProcess and corresponding util classes that assume there will only ever be one GAN running. Therefore, a lot of code refactoring will be required. I might look at this issue a bit myself before passing it off to you.

**Comment by schrum2** [comment]
After looking at GANProcess, here is my proposed approach for working with two GANs simultaneously. You will have to refactor MegaManGANUtil a lot before you can really dive into this. Basically, every method in MegaManGANUtil that accesses static methods/data from GANProcess needs to be modified. I'll commit an example, and you will do the rest. Basically, there needs to be a version of each of these methods that accepts a GANProcess as a parameter. 

When working with two MegaMan models, you will need to call the GANProcess constructor directly from MegaManGANLevelBreederTask to set up two distinct models. Stay posted for a commit that starts chipping away at this issue.

**Comment by schrum2** [comment]
The message in the commit above gives you some guidance on what to do, but here are some more notes about the interface:

Whenever that checkbox is activated to use two models, you should destroy/deactivate the static GANProcess instance with `GANProcess.terminateGANProcess()` and then construct the horizontal and vertical models using the new command line parameters. I wonder if it would be possible to hide the SetGANModel button when the checkbox is selected, and reveal two new buttons: SetHorizontalGAN and SetVerticalGAN.

**Comment by schrum2** [comment]
This issue will stay open until the interface has been improved a bit. When UseBothGANs is clicked, the SetGANModel button should be hidden, and two new buttons should appear: SetHorizontalGAN and SetVerticalGAN.

**Comment by schrum2** [comment]
Although the details of this issue are sort of ongoing, they have been subsumed by issue #537, so I'm closing this one.
