### ISSUE TITLE
Show A* Paths in interactive interface for MegaMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#524]
@kdsteckel did this exact same thing in Lode Runner #503 so you can compare with his code. Basically, we want a checkbox tied to a command line parameter that turns visualization of the A* paths on and off. In addition to that, there should be a text box that allows the user to change the A* budget.

The extra wrench thrown in when working with MegaMan is that these evolved levels don't have start and end points, so you will need to add them in. We want to have a deterministic approach that places the start and end points appropriately according to whether the level is horizontal or vertical (or at least based on the types of the start and end segments). 

For horizontal, we want the leftmost patch of ground you can reach by dropping down onto from the ceiling to be the start point. Similarly, the end point should be the rightmost such place.

I'm less sure how the vertical endpoints should be placed, but fiddle around and see what does/doesn't work and report back in this issue thread.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84668677-862e0f80-aee9-11ea-9923-1bd949a7f2b9.png)
Horizontal levels have start/endpoints


Also works when stretching
![image](https://user-images.githubusercontent.com/63438571/84668791-a8279200-aee9-11ea-8d79-6d5196b68641.png)

**Comment by cappsb** [comment]
First attempt with vertical:
![image](https://user-images.githubusercontent.com/63438571/84669989-1c166a00-aeeb-11ea-8d8a-116978f1681b.png)


current placement scheme:
upper-right = orb, lower left = player

![image](https://user-images.githubusercontent.com/63438571/84670218-731c3f00-aeeb-11ea-81ff-5ee5fc986851.png)

**Comment by cappsb** [comment]
2nd attempt vertical:
Orb = tallest point:
![image](https://user-images.githubusercontent.com/63438571/84671050-82e85300-aeec-11ea-8808-552c1217b3d7.png)

**Comment by cappsb** [comment]
A* path:
![image](https://user-images.githubusercontent.com/63438571/84680630-9994a700-aef8-11ea-9fac-0e31737cec2c.png)

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84681808-50455700-aefa-11ea-8415-bec84b944cc6.png)
Thicker lines and update budget
