### ISSUE TITLE
Alternative Lode Runner visualization

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#527]
In the interactive Lode Runner interface, have a check box tied to a command line parameter that allows the visualization to switch between using the tiles from the original game, and using the tile visualizations from the IceCreamYou game. The 'png' and 'gif' files for this are located in `src\main\java\icecreamyou\LodeRunner`

**Comment by kdsteckel** [comment]
There may be some issues with doing this since the image files for IceCreamYou are 30x40 pixels and the normal rendered levels are 8x8. This might make it look weird in the level breeder. 
Also I need to get a white tile for the empty tiles because the background of the render is completely black which covered up the tiles like player, enemy, ladder, and maybe others. @schrum2

**Comment by schrum2** [comment]
I think the png files define certain pixels as uncolored or blank. However, a way around this might be to create the BufferedImage first, and then make every pixel in the image plain white before importing any of the tile images.

As for the scale ... let's just see what it looks like and go from there.

**Comment by kdsteckel** [comment]
The checkbox works now to change the visualization to ice cream you, but the visualizations look really strange because of the scaling. @schrum2 
<img width="1280" alt="Untitled" src="https://user-images.githubusercontent.com/50111166/85032060-013f3200-b145-11ea-859e-d2bb75514985.png">

**Comment by schrum2** [comment]
When I load it, I get pure black buttons. What is missing? In any case, I'm not fully convinced that this can't look better.

Lastly, you should keep the SolutionPath button and the AStarBudget bits close together ... in fact, in order to save space, you should stack them the way that @cappsb did in his recent reorganizing of the MegaMan interface: https://github.com/schrum2/MM-NEAT/issues/539

**Comment by kdsteckel** [comment]
Check boxes and the text field are not formatted and the ice cream you visualization is displayed on the button when the "PlayFormat" button is pressed. @schrum2
