### ISSUE TITLE
Objective A* Evolution using MegaMan A* path length

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#529]
Create a MegaManLevelTask which is abstract, and a MegaManGANLevelTask which extends the MegaManLevelTask to specifically evolve levels using latent vectors. You can find examples of this general scheme by looking at Mario, Zelda, and Lode Runner. 

Allow two possible fitness functions, each controlled by its own command line parameter. However, no matter which ones are used for fitness, both of the following should still be calculated an used as "other scores":
- A* Path length
- Connectivity

You can talk to @kdsteckel and look at the LodeRunnerLevelTask to get some insight here. Basically, connectivity is simply the portion of the level that is actually reachable. I think that in Lode Runner we actually count the tiles, but for Mega Man I would prefer the connectivity to be the percentage of passable tiles that have a white X on them after A*. The point of this second fitness is that sometimes A* fails, and if every level is unbeatable, it is hard to know which ones are worth evolving further. Connectivity helps with that since being able to reach a greater percentage of the passable tiles in the level means there are better odds of the A* path eventually working out.

**Comment by cappsb** [comment]
Beatable levels usint objective evolution
![image](https://user-images.githubusercontent.com/63438571/85145755-ae33b080-b212-11ea-90ae-940e00af3a30.png)

![image](https://user-images.githubusercontent.com/63438571/85146397-30bc7000-b213-11ea-8b78-1236590e6a68.png)

The same level is reproduced frequently (but only the beatable ones) there is some variation

**Comment by schrum2** [comment]
I'll test this once the Maven build passes, which requires fixing #544

**Comment by schrum2** [comment]
This seems to mostly work, but I think I encountered a problem with the post watch of results ... will double check on this later.

**Comment by schrum2** [comment]
The evolution part seems correct, but when I did a post watch it said
`Could not display image`
Why?
@cappsb

**Comment by schrum2** [comment]
Also, a different run froze when it tried to show a picture, and the level save is not working.

Whenever an MMLV is saved, a message should print the full file path of the saved file to the console

**Comment by schrum2** [comment]
Lastly, in the final cleanup method (this is something you can override ... not sure of exact name) you need to gracefully terminate the three GAN processes (if they are being used)

**Comment by schrum2** [comment]
Put a batch file in `batch\Experiments-2020-MegaMan` and then close this issue. The population size and number of generations should be the same as in the other batch files in this same directory. However, let's only make a batch file that uses both A* and connectivity ... no need to explore every single fitness combination.

The reason we want the CPPNtoGAN settings as similar to the plain GAN settings as possible is that we may want to compare these approaches.
