### ISSUE TITLE
GAN models that produce Mega Man enemies

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#532]
If you have a model that can generate enemies, then add the necessary code to display them and encode them in the saved MMLV levels from the interactive interface. Get to a point where we have a GAN model that can produce enemies in the interactive interface.

**Comment by cappsb** [comment]
```
python main.py --niter 5000 --nz 5 --json HORIZONTALONLYUniqueEnemiesMegaManAllLevelsBut7With30TileTypes.json --experiment HORIZONTALONLYUniqueEnemiesMegaManAllLevelsBut7With30TileTypes_5_Epoch5000.pth --tiles 30
python main.py --niter 5000 --nz 5 --json VERTICALONLYUPUniqueEnemiesMegaManAllLevelsBut7With30TileTypes.json --experiment VERTICALONLYUPUniqueEnemiesMegaManAllLevelsBut7With30TileTypes_5_Epoch5000.pth --tiles 16
python main.py --niter 5000 --nz 5 -- json VERTICALONLYDOWNUniqueEnemiesMegaManAllLevelsBut7With30TileTypes.json --experiment VERTICALONLYDOWNUniqueEnemiesMegaManAllLevelsBut7With30TileTypes_5_Epoch5000.pth --tiles 30
```

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85302938-6f4e6680-b46f-11ea-93c0-57cf26f6db18.png)

**Comment by schrum2** [comment]
This seems done, but I want one of the issue threads to track what we discussed about the different enemy types. Since there are clear distinctions between ground/air/wall enemies, we either want the GAN to have these generic categories, or simply encode every single enemy type as a unique entity.

I think that having each enemy be unique is what we are going to pursue first, so please give me a training commands for those json data sets when they are available.

**Comment by schrum2** [comment]
We'll just stick to unique enemy types ... having categories to too complicated.
