### ISSUE TITLE
Unusual edge transitions in MegaMan levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#536]
Here is a picture:
![image](https://user-images.githubusercontent.com/8397236/84848118-31d57d80-b018-11ea-8f75-a6c58f2f1c59.png)
The starting point is beneath the edge of the screen. Is there a way to fix this?

**Comment by cappsb** [comment]
Yes, but it involves removing the fast vertical scroll from this level. Basically, MegaMan is being spawned on top of the screen beneath him, so if you traverse right, you will drop down.

**Comment by cappsb** [comment]
I believe this is resolved. When using V+H, the json to mmlv does not have fast vertical transitions

**Comment by schrum2** [comment]
Seems good enough for now, though we'll need to keep an eye on it
