### ISSUE TITLE
MegaMan interactive Interface spacing

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#539]
This is a quick snippet of a Slack discussion with suggestions for tightening the interface:

> Look at how ThreeDimensionalAnimationBreederTask stacks the vertical and horizontal tilt sliders
> You can stack the MegaManMaker and SaveMMLV buttons in a similar way.
> You can probably also stack the checkboxes for AllowPlatformGun and AllowBlockBreaker since they are similar
> incidentally, I would like the UpdateAStarBudget to be placed close to the ShowSolutionPath box since they are related ... maybe place the budget input under the ShowSolutionPath checkbox too
> That should squeeze the space sufficiently, but also keep things appropriately located

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/84956924-c5ae5480-b0bf-11ea-8116-9f9ed25ec3db.png)

**Comment by schrum2** [comment]
To buy more space, put the "View" button in the same column as MegaManMaker and SaveMMLV (and center the buttons if possible). Also, make the label for "UpdateAStarBudget" appear above the textbox rather than to the left so it can stack more tightly under "ShowSolutionPath".

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85025340-e2d53880-b13c-11ea-840a-ba8e6b1dbe7b.png)

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85025704-58d99f80-b13d-11ea-9864-ede93724838c.png)

**Comment by schrum2** [comment]
This is done, though more buttons will need to be crammed in to accommodate selecting of different UP, DOWN, HORIZONTAL models: #537
