### ISSUE TITLE
Start/End locations for MegaMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#540]
Look at this:
![image](https://user-images.githubusercontent.com/8397236/85033733-e8d01700-b146-11ea-93c1-1bfdb5bd459e.png)

The start location of MegaMan is the red circle on the left, and the end location is on the right. These seem misplaced. The start location should be in the top left segment, and the end location (although unreachable) should be in the bottom right.

Incidentally, I believe that this example also reveals that the corner segment connecting a horizontal segment to a downward segment should probably be provided by the vertical/downward GAN model #537 . The same may also be true for moving up, though this example doesn't really show that need.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85049210-fc38ad80-b159-11ea-9b16-2bd7261f7dd4.png)

![image](https://user-images.githubusercontent.com/63438571/85049355-3013d300-b15a-11ea-8164-198dfa9bf157.png)

Changed the way the orb and spawn are placed:
While building the level, it places the spawn at the first screen it places. Then, just before it finishes, it places an orb in the last screen it will place.

**Comment by schrum2** [comment]
Sounds good.
