### ISSUE TITLE
Way to browse MAP Elites archive

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#541]
We need a way to play any arbitrary level in a MAP Elites archive resulting from an experiment. You are going to write some code and a batch file that is sort of similar to `postAllBestObjectiveWatch.bat`. This batch file loads all of the data from an experiment that was run with an objective fitness function, but replaces the `experiment` parameter with `experiment:edu.southwestern.experiment.post.ObjectiveBestNetworksExperiment`, which loads and displays/demos the champion of the previously executed/saved evolutionary run. All of the other parameters (more or less) come from the previously experiment's saved Parameter file.

So, you will make a batch file called `postMAPElitesWatch.bat`. It will figure out what data to load using the runNumber, base, log, and saveTo parameters just like `postAllBestObjectiveWatch.bat`. You should also set the trials parameter from the command line in the same way. In addition, you will need one more new String parameter which we'll call `mapElitesArchiveFile`.

However, the big change is that you will set `experiment` to a new class which you must write. Put it in the `edu.southwestern.experiment.post` package and call it `ExploreMAPElitesExperiment`. The `run` method of `ExploreMAPElitesExperiment` will load the specific xml file specified by `mapElitesArchiveFile`. However, this parameter will only be the final file name, not the full path. For example: `mapElitesArchiveFile:Connected[00-10]Ground[8-12]Ladders[4-8]-elite.xml`. The reason the rest of the path is not needed is that it will be derived from various parameters associated with the experiment. For example, `FileUtilities.getSaveDirectory()` will give you something like: `loderunnerlevels/MAPConnectedGroundLadders5`. Then you can append `/archive/` to this followed by the `mapElitesArchiveFile`.

Load the xml file with `Easy.load` and save it into a generic `Genotype`. Then call the `evaluateOne` method of the task (look at `ObjectiveBestNetworksExperiment`)

**Comment by kdsteckel** [comment]
![Connected 00-10 Ground 16-20 Ladders 12-16 __Direct--1 00000_133-LevelRender](https://user-images.githubusercontent.com/50111166/85140492-f058f400-b20a-11ea-998d-9b85aebce258.png)
Before moving on to this, after looking at the experiment I ran yesterday I noticed that there were 4 spawn points in every level. Just need to do a little refactoring in the evaluateOneLevel class to avoid calling performAStarSearch method 4 times. At least thats what I'm hoping 
@schrum2

**Comment by kdsteckel** [comment]
![Connected 00-10 Treasure 5-10 Enemies 0-2 __Direct--1 00000_40-LevelRender](https://user-images.githubusercontent.com/50111166/85141057-cce27900-b20b-11ea-9b8a-71ad529e6032.png)
Fixed by calling performAStarSearch once into a triple and then getting the values from the triple. Also made a separate method to calculate the simpleAStarDistance to avoid having too many things calculated in a single method. @schrum2

**Comment by kdsteckel** [comment]
This issue is done, or close to it. can you check to make sure?
@schrum2

**Comment by schrum2** [comment]
It actually didn't work with Mario and Zelda, but after some tweaks it now does.
