### ISSUE TITLE
Apply MAPElites to MegaMan

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#542]
Apply MAP Elites to the evolution of individual Mega Man Levels from MegaManLevelTask

Bin dimensions in another class, but calculation goes into the above task.

**Comment by schrum2** [comment]
Brain storm some possible MAP Elites bin dimensions in this issue thread before moving forward with code. I think that measuring variation in up, down, horizontal sections could be interesting.

**Comment by schrum2** [comment]
Define the following bin dimensions:
- Number of vertical segments (int bins scaled based on the total number of segments)
- Percent connectivity (percentage bins: 0-10,10-20,20-30,...,90-100)
- Number of distinct segments (int bins scales based on total number of segments)

For fitness, use the A* path distance.

The reason we only need to track vertical segments is that the horizontal count will always equal the total minus the vertical count.
