### ISSUE TITLE
Apply CPPN2GAN to MegaMan

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#543]
Apply the CPPN to Megaman using the tree-GAN approach. Places screens based on which GAN is being used (possibly based on the radial pattern?)

**Comment by schrum2** [comment]
How to encode coordinates and CPPN outputs.

CPPNs will have 3 additional outputs (besides the latent variables) for UP, DOWN, HORIZONTAL. Each output corresponds to one of these directions (label accordingly). At each step, CPPN checks which one of the three is largest: the largest output is the chosen GAN model and direction of the segment. But, one direction could be illegal, so if the maximum output is for an illegal direction, simply take the second biggest output.

First segment is placed at coordinates (0,0). Up is actually positive for y, and down is negative, and can lead to negative coordinates like (2,-3). Let's say the number of level segments/chunks is S. Scale Y from [-S,S] to [-1,1] and scale X from [0,S] to [0,1].

**Comment by cappsb** [comment]
I've made some significant progress on this. I have made a case for:
placing the first level (and which direction to place it)
placing all subsequent levels
Placing the next-best level after finding an illegal case

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85420192-8016df00-b538-11ea-97b3-220603e077d2.png)

![image](https://user-images.githubusercontent.com/63438571/85420090-66759780-b538-11ea-8858-0df6395a86c3.png)

**Comment by schrum2** [comment]
Now you can extend MegaManLevelTask to make MegaManCPPNtoGANLevelTask

**Comment by cappsb** [comment]
@schrum2  I believe this is done. The interactive evolution and objective evolution functions properly

**Comment by schrum2** [comment]
Even though we plan to move on to the conditional GAN #538 , there are some small fixes I want here. Specifically, the GAN model used to generate a particular segment should come from the CPPN when used on that particular segment. Here is an example of what I mean:

Start with input (0,0). The output is to use the UP model with vector V1. 
V1 is sent to the UP model.
Next input is (0,1). The output is to use the UP model with vector V2.
V2 is sent to the UP model.
Next input is (0,2). The output is to use the HORIZONTAL model with vector V3.
V3 is sent to HORIZONTAL model.
Next input is (1,2). The output is to use the DOWN model with vector V4.
V4 is sent to the DOWN model.
Next input is (1,1). The output is to use the DOWN model with vector V5.

The level would look like this:
```
_________
|   |   |
|V3 |V4 |
|___|___|
|   |   |
|V2 |V5 |
|___|___|
|   |
|V1 |
|___|
```

**Comment by cappsb** [comment]
Basically:
change how coordinates are updated

1. when placing Horizontal, the NEXT placement will be to the right
2. when placing up, the NEXT placement will be up
3. when placing down, the NEXT placement will be down


Currently, the code updates the coordinates just before it is placed:
When placing UP, make room for UP and then move UP and place from the GAN
the way it should be: How to place next gan? see previous placement. Based on previous placement, place current segment from CPPN then tell the next iteration to place in the appropriate direction

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85869787-cdda5400-b791-11ea-926a-d16550de6f7f.png)
Appears to work

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85872879-fcf2c480-b795-11ea-9609-7c3c560fa761.png)
first cppn2gan solution path

**Comment by schrum2** [comment]
Looks good to me.
