### ISSUE TITLE
CommonConstants.watch then play of Lode Runner lacks enemies

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#546]
The MAP Elites explorer worked for Lode Runner, except that when I played the loaded level the display image contained enemies that were not copied over to the IceCreamYou version for playing. This is probably a problem in LodeRunnerLevelTask

**Comment by kdsteckel** [comment]
I think that this is fixed now. Needed to add 
`for(WorldNode n : level.enemies) 
			contents += n.toString() + "\n";`
into the levelToString method in Layout.java in the IceCreamYou code. 
@schrum2

**Comment by schrum2** [comment]
Works!
