### ISSUE TITLE
Track other scores for Mega Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#547]
Several "other scores" should be tracked in the MegaManLevelTask.

First, A star distance and connectivity should be tracked as other scores, regardless of whether they are tracked as regular fitness or not. If they are a fitness score, then this means they will be repeated, but this is ok.

Additional things to track:
- Number of total enemies
- Number of flying enemies
- Number of ground enemies
- Number of wall enemies
- Number of pure horizontal segments
- Number of pure upward vertical segments
- Number of pure downward vertical segments
- Number of corner segments (that join a horizontal and vertical segment)

**Comment by schrum2** [comment]
I guess you already have A* and connectivity as other scores ... but please add the rest too

**Comment by cappsb** [comment]
Just for awareness' sake:
![image](https://user-images.githubusercontent.com/63438571/85873469-c9fd0080-b796-11ea-8044-f37c6d32179e.png)
this image is of a level with 9 Horizontal, 1 Down, and 1 corner (which is the down). However, it appears as though there is no corner. Corners are counted by changing direction and are not necessarily attached by two segments.


That being said, I believe this issue is resolved @scrhum2

**Comment by schrum2** [comment]
It would be easier to visually assess what a level looks like if we had less distortion from stretching. Is there a way to make the image displays maintain a uniform size?

**Comment by cappsb** [comment]
Yes, that's how rendering originally was. However, there were a couple of problems:
1. longer levels could not display on the screen properly
2. the "View" button in the interactive interface did not enlarge the images sufficiently for smaller levels

**Comment by schrum2** [comment]
Maybe at least make it an option? Leave it to the user to decide how to view it.

**Comment by cappsb** [comment]
Surely there's some scaling function that I can use... 
Basically we need the width of the image to be between 0 and 1600 based on the width of the level and 
The height of the image to be between 0 and 900 based on the height of the level

**Comment by cappsb** [comment]
Horizontal level
![image](https://user-images.githubusercontent.com/63438571/85880471-b2774500-b7a1-11ea-80fd-f4b8bbbaaa5f.png)


vertical level
![image](https://user-images.githubusercontent.com/63438571/85880506-c458e800-b7a1-11ea-8773-5f9b399c8532.png)

**Comment by schrum2** [comment]
These all seem to be tracked. Closing
