### ISSUE TITLE
Describe MMLV format

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#548]
In the `MM-NEAT\data\VGLC\MegaMan` directory, create a simple text file that describes the MMLV format. Specifically, describe each character type and all of the number codes you know.

**Comment by schrum2** [comment]
Please don't forget this.

**Comment by cappsb** [comment]
Description here (can be more detailed if needed):
https://docs.google.com/spreadsheets/d/1WEIZrFFfafY52HxukqsS3zxhxlTapwd5mWORqCHXAOI/edit?usp=sharing

**Comment by schrum2** [comment]
I changed the location of the file, but am otherwise happy with the details. closing
