### ISSUE TITLE
MMLV file save errors

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#549]
When using the interactive interface, I'm encountering problems when trying to save the MMLV file. It is either freezing, or simply failing to copy the level over to the MMM Levels directory (I do see it appear in the MM-NEAT repo though). 

Ultimately, the file copy/move/save should work, but even if it works there should be helpful text messages in the console explaining what is happening. And there should be even MORE helpful messages if anything goes wrong. Tell the user exactly where files have been saved.

However, the file should not be saved into the local MMNEAT dir ... only to the specified MMM Level dir.

**Comment by cappsb** [comment]
@schrum2 I changed the code quite a bit to perhaps help this issue. I still need to print proper statements when the GAN is not compatible with the code, but many of the shortcomings have been resolved

**Comment by schrum2** [comment]
Everything seems to save properly. GAN compatibility issue will be handled elsewhere
