### ISSUE TITLE
Conditional GAN training sets

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#550]
Ok, if we're going to commit to conditional GANs #538 then we need a training set for them first.

Create a cGAN training set in the following manner. Each level segment must be associated with a one-hot encoded version of its class label. The class labels are up, down, horizontal, bottom-right, bottom-left, top-right, top-left, in that order. This means each class can be designated as a vector:

up: [1,0,0,0,0,0,0]
down: [0,1,0,0,0,0,0] 
horizontal: [0,0,1,0,0,0,0]
bottom-right: [0,0,0,1,0,0,0]
bottom-left: [0,0,0,0,1,0,0]
top-right: [0,0,0,0,0,1,0]
top-left: [0,0,0,0,0,0,1]

Previously, each level segment was a json list of lists: segment = [[ ... ], ... , [ ... ]]

Now, each segment will be [ label, segment ]

For example, [ [0,0,1,0,0,0,0], [[ ... ], ... , [ ... ]] ] would be one training example.

And the json file would be a list of these:
[ [ [0,0,1,0,0,0,0], [[ ... ], ... , [ ... ]] ], [ [0,0,0,0,1,0,0], [[ ... ], ... , [ ... ]] ], ... , [ [0,0,0,0,0,0,1], [[ ... ], ... , [ ... ]] ]

**Comment by schrum2** [comment]
Actually, after looking at other code and thinking a bit, it seems to make more sense to have two separate training files. One that contains all of the levels segments as before (from all levels), and another that contains all of the class labels. The trick is that both files have to have the same order, so that (for example) the 50th segment in the segment file corresponds to the 50th label in the label file.

This approach is more flexible anyway. The data is probably easier to work with this way.

**Comment by cappsb** [comment]
Training sets for MMLV and VGLC are in

**Comment by schrum2** [comment]
Closing this ... remaining work related to this is in #556
