### ISSUE TITLE
Falling model for MegaMan A*

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#555]
Falling is currently very unrealistic. Maybe we should make it so that after falling for 4 consecutive tiles, sideways movement is no longer possible (only straight down). That may not be exactly what we want to do, but we should definitely do something to change the model.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86149359-7c97d080-bac1-11ea-9d99-374612d44ab1.png)
I believe it works the way we want it to

**Comment by schrum2** [comment]
Reopening this, because you need to redo the Unit Test: MegaManStateTest

**Comment by cappsb** [comment]
unit test passes
