### ISSUE TITLE
Integrate TSP solver

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#559]
Now that #528 is wrapping up, we need to integrate the TSP solver. 

The code needs to be able to do either regular A* or A*+TSP. In LodeRunnerLevelTask, keep A* path length as an option, but add a separate fitness with a separate boolean parameter for using TSP path length (user could conceivably use both). In interactive interface, have a checkbox (tied to a command line parameter) that decides between A* and TSP (only one can be used here).

Next, the code needs to be able to tolerate when TSP fails. Currently, code crashes with an exception. However, evolution is sure to make many unbeatable levels ... so if TSP fails, it just needs to return null to the evolution code, which can then interpret that as a fitness of -1 (same as when A* fails).

We need a way of controlling the computation budget for TSP. Here is how: In getTSPGreedyWithBackTrackingSolution, set a global variable to 0. In greedyTSPStep, increment that variable. This variable will track the number of calls to greedyTSPStep. If that number exceeds a budget, then greedyTSPStep should return null for search failure. A command line parameter should control that budget. The interactive interface should have a way of changing this budget. To get an idea of what this budget should be, run the TSP solver on some levels from the VGLC and print out that value of the global variable afterward (how many calls to greedyTSPStep)

**Comment by kdsteckel** [comment]
![image](https://user-images.githubusercontent.com/50111166/86278731-7b88a100-bb9e-11ea-9851-3a0620d552e6.png)
Displayed are the solution paths for the A* path,  but when I try to change to the TSP + A* path it does not do anything. 
This is confusing, I think it maybe be something with how I set the TSP budget or with how I am setting up the drop down menu. 
Can you take a look when you get a chance? @schrum2

**Comment by kdsteckel** [comment]
It worked up until the 6th one so I think it may be a budget issue now, I tried to set the budget but maybe I forgot to silence one of the stack traces somewhere or something.
![image](https://user-images.githubusercontent.com/50111166/86292249-117bf600-bbb6-11ea-8194-2c00c8657fa5.png)
@schrum2

**Comment by schrum2** [comment]
The TSP works now, but we should add a way to control the TSP search budget from the interface. This will be just like the A* budget. In fact, it should appear in the same place. Whenever TSP is selected, the A* option should be hidden and the TSP budget should appear. If A* is selected, then A* is shown and TSP is hidden. @cappsb can tell you how to hide/show interface elements (he used it in MegaMan's interactive interface).

**Comment by schrum2** [comment]
In addition to the above change, make the following fixes:
- Add support for solution paths in both tile sets ... not just original.
- In the drop down, move the words "Choose Path Type" outside and above the drop box, and make the box options be "None" followed by the two you already have

**Comment by kdsteckel** [comment]
I think I have done everything for this issue, but can you check it just to make sure? @schrum2

**Comment by schrum2** [comment]
This is fully integrated
