### ISSUE TITLE
Compute Novelty Score for Mario, Zelda, and MegaMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#560]
Might be better than "distinct" segments since segments can be very similar despite being distinct.

There is already a way of computing Novelty Scores for Zelda Dungeons. The code is here in the `DungeonNovelty` class. We only used that for analysis of the levels that were already made, but could also use it as a MAP Elites dimension or fitness.

Description of the calculation is in this paper: https://arxiv.org/pdf/2001.05065.pdf

Do Zelda first since this code is already written for Zelda. Then move on to MegaMan and Mario

**Comment by cappsb** [comment]
Parameterize STARTx STARTy and row/col
Run it using something, tally the score, then write a unit test. After that, radically change code to use command line parameters and run the test again to assure that it is still working properly. Then apply it to MegaMan and Mario in place of Distinct Rooms

**Comment by schrum2** [comment]
Notes from Slack convo

I'm looking at Jake's publication to get a sense for what the Dungeon Novelty score range was:
https://people.southwestern.edu/~schrum2/SCOPE/gutierrez.cec2020.pdf
Highest number there is about 0.606
So, let's assume that novelty scores for Zelda dungeons range from 0 to 0.7.
This means you can take any novelty score, multiply by 10 (number of bins), then divide by 0.7 (max of range), then cast to an int to get the bin index on that dimension. However, we have to assume that novelty scores higher than 0.7 are occasionally possible
which means you need to take the binIndex and calculate as Math.min(binIndex,9) or rather Math.min(binIndex, BINS_PER_DIMENSION - 1)
It will be important to look at the MAP Elites file names when testing to make sure that a full range of possible bins are selected in this index

**Comment by schrum2** [comment]
This seems to work for Zelda now ... please add appropriate batch files to the Experiments-2020-MoreCPPN2GAN subdir.

Next are Mario and MegaMan. However, I'm not sure if the DungeonNovelty class can be easily generalized to these domains. So, try the following ... make a new class called LevelNovelty and try to write it in a general enough fashion that it can apply to both Mario and MegaMan. I'll worry about whether it can be generalized to Zelda later.

**Comment by cappsb** [comment]
If you want to test what I've done so far, run MegaManLevelNovelty

**Comment by schrum2** [comment]
Ok, here is my interpretation of the output. Tell me if this makes sense:
```
VGLC Average: 0.33623499978867233
OneGAN Average: 0.42771726190476195
SevenGAN Average: 0.4111964285714286
```
This first bit of output shows the average novelty of the levels. So, the novelty of each segment with respect to the other segments in the level is calculated, that is averaged to get the level novelty, and those scores are averaged by type. So, within any given VGLC level, the segments are fairly uniform and less novel. The GAN approaches produce levels where there is greater segment variety in each level, which could be interpreted positively or negatively. On the one hard, we get more variety in each level, on the other, each level is less cohesive. That second point can actually be used as evidence for why we should use a method like CPPN2GAN in future work.

```
159
Average Set of Original Segments: 0.4349151254188633
178
Average All Original Segments: 0.4390132694284632
287
Average Set of OneGAN segments: 0.4636510485047253
300
Average All OneGAN segments: 0.4709229166666666
254
Average Set of SevenGAN Segments: 0.4483245573634005
300
Average All SevenGAN Segments: 0.45419652777777764
```
This second batch of data indicates that there are not that many repeated segments within the individual data sets for a given type of level. However, it does make sense that SevenGAN repeats segments more than OneGAN (smaller number of unique segments) because of the corners. **TODO for PAPER: Count the number of unique segments produced by each individual GAN of the SevenGAN**. This data also indicates that despite uniformity within levels, the diversity across the entire Mega Man game is higher, and both GAN approaches replicate that level of diversity in their outputs.

So, there are some conclusions to draw from this (go ahead and insert this into the Overleaf draft). However, I am still interested in knowing how many segments produced by a GAN directly replicate something from VGLC. In fact, none of this data demonstrates a calculation based on levels of different types. One type is used at a time, and the numbers are compared. It should be easy to loop through the collection of GAN segments and see if any are contained in the set of VGLC segments. Making sure we track which GAN produced each of those segments is a bit of extra work, but also important.

**Comment by schrum2** [comment]
@MBatt1 This is an issue that I think should have been closed a while ago. Ben definitely got the novelty calculation working for Mega Man, and I think it already worked for Zelda. However, I guess it hasn't been thoroughly testing on Mario or Lode Runner (Correct me if I'm wrong @cappsb).

In any case, I'm closing this, but if you run into trouble while working on #660 then you might look at this issue thread, or just keep in mind that the calculation hasn't been tested much on Mario and Lode Runner.

**Comment by cappsb** [comment]
You are correct, the novelty calculations have not been extensively tested in Mario or Lode Runner @schrum2, though they are confirmed to still work in Zelda and Mega Man.
