### ISSUE TITLE
Don't use ALLOW_WEIRD_SIDE_WAYS_MOVE_THROUGH_DIGGABLE by default

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#562]
In LodeRunnerState, ALLOW_WEIRD_SIDE_WAYS_MOVE_THROUGH_DIGGABLE should be changed into a constructor parameter instead of a final constant. In TSP, graph paths should be made with this as false, only resorting to true if the path fails (this is during graph construction).

Regular uses of A* in Lode Runner should depend on a command line parameter. Set:
```
	public LodeRunnerState(List<List<Integer>> level) {
		this(level, Parameters.parameters.booleanParameter("allowWeirdLodeRunnerActions"));
	}
```

You will also need to fix LodeRunnerStateTest which now fails. This is due to other changes to the A* model as well.

**Comment by kdsteckel** [comment]
JUnit test passes after updating the constructor and fixing the test. I think this is done @schrum2
