### ISSUE TITLE
Unified support for OneGAN and SevenGAN in MegaMan

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#565]
I tagged you on several commits talking about the need to support OneGAN, and the need to consolidate SevenGAN code. I think you should make a class called MegaManLevelGenerator and then extend it with subclasses like MegaManOneGANGenerator and MegaManSevenGANGenerator. This will allow you to simply pass around an instance of MegaManLevelGenerator in many method of the code without regard for whether you are using one or seven GANs (or a conditional GAN in the future). Also, the new MegaManSevenGANGenerator class can encapsulate all of the 7 GAN variables, as well as the initialization code, meaning you won't have to duplicate it. Doing this before continuing work on CPPN2GAN could make that cod easier to write.

**Comment by schrum2** [comment]
The commits above show the work I've been putting into this. It still doesn't work. I feel like there is a problem in the placement methods, but I could be wrong. Here is a summary of major changes.
- Methods no longer return unnecessary extra data
- The previous point starts out at null instead of equal to current, to indicate that the first segment is being placed.
- There is now an explicit case for placing the first segment (I suspect the first segment was simply being skipped before ... level was only 9 segments instead of 10: see Slack)
- Instead of passing around and returning SEGMENT_TYPE instances, the code simply tracks the previous and current Point in most places.
- There were missing cases in determinType and nextPoint, and some cases were ambiguous without access to the previous Point (previous SEGMENT_TYPE was not enough, but once the previous Point was available, the previous SEGMENT_TYPE was superfluous).

I think the current error is related to my inability to understand exactly how `placementPoint` is supposed to work.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86788879-43fd7700-c02c-11ea-93a2-8ef7627ac334.png)
![image](https://user-images.githubusercontent.com/63438571/86788950-60011880-c02c-11ea-9ccd-b1d304408896.png)
Still only using three GANs (corner cases never happen)

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86793292-ecadd580-c030-11ea-9439-fe746fd7e25e.png)
I believe I fixed it.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86814079-8c299300-c046-11ea-8b6e-a20ce2c5a4e9.png)
the GANGenerator is trying to place down and then up immediately after


![image](https://user-images.githubusercontent.com/63438571/86814148-9fd4f980-c046-11ea-9968-12a879f71c82.png)
As such Up wins out and MegaMan is not placed properly

**Comment by schrum2** [comment]
This is done. Conditional GAN does not work, but it should be easy to add support in the future if it every works
