### ISSUE TITLE
Broken MegaMan Levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#572]
I tried loading one of the newly evolved levels, and got this error:
![image](https://user-images.githubusercontent.com/8397236/87679370-b6173f80-c741-11ea-8dea-dccf08bf6045.png)

I'll attach the MMLV file so you can look at it and see what the problem is.

[secondtry.zip](https://github.com/schrum2/MM-NEAT/files/4931861/secondtry.zip)

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/87724867-c949ff80-c781-11ea-89da-b16a5eae384c.png)
Changed breakable blocks

**Comment by schrum2** [comment]
Seems fixed
