### ISSUE TITLE
Track QD Score in MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#582]
This should probably happen after #579 but not necessarily.

I was reading this paper ( https://arxiv.org/pdf/2007.05674.pdf ) which reminded me about QD score:

> QD-Score: The QD-Score metric was proposed by Pugh et al.
> (2015) as the sum of fitness values of all elites in the archive.
> The measure distills both the diversity and quality of elites in
> the archive into a single value.

This should be easy to include, and would be appropriate to calculate in future experiments.

**Comment by schrum2** [comment]
Some discussion is probably required to make sense of what this issue is. It should be noted that simply using the sum of all elite fitness values will not work if fitness can be negative, as is possible in some domains currently. Also, empty bins are assumed to have a fitness of negative infinity, which needs to be taken into account.

To handle the negative fitness issue, you need to know the minimum possible negative fitness, or have a guess at one that will definitely be lower than the negative by a bit. If you have that number, then you can add it to all bin fitness scores before computing the QD score.

**Comment by MBatt1** [comment]
Added a parameter and "calculateQDScore" method to MAPElites.java, which also has a set of JUnit tests to go with it. A log file outputs QD in the Fill log, and the fill log plot file now creates a plot of the QD scores.

**Comment by schrum2** [comment]
This issue is done, but now I need to go into batch files that use MAP Elites and make sure they have an appropriate base value being added, depending on the domain. Want to make sure I'm consistent with what I already calculated for the upcoming ToG submission.
