### ISSUE TITLE
Mega Man Level Orb Placement

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#593]
![AStarDistAndConnectivityOneGAN3](https://user-images.githubusercontent.com/63438571/95232023-91bf8200-07c9-11eb-850f-0f6e7b34e86f.PNG)
This image shows why there are so few 'left-facing' segments. This is relatively easy to fix. Change how the orb is placed based on the previous segment's orientation.

**Comment by schrum2** [comment]
Some more details on what exactly this issue is. The exit orb is currently always placed on the far right of whatever segment it appears in. However, if the segment was generated by moving from the right to the left, then the exit orb should be placed on the left side of the segment.

**Comment by MuellMark** [comment]
placeOrb was divided into two separate methods: placeOrbLeft and placeOrbRight. The only difference between them is the direction the first for loop goes in (left the right or vice versa). longVectorOrCPPNtoMegaManLevelAndVector was also edited to place the orb to the left if the last segment was placed to the left of the previous one, or to the right in all other cases.
