### ISSUE TITLE
Problems With Level Breeder Tasks Mega Man

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#595]
The problem is that MegaManTrackSegmentType segmentCount is not initialized, causing a null pointer exception in MegaManCPPNtoGANLevelBreederTask
![image](https://user-images.githubusercontent.com/63438571/96191772-6431b180-0f0a-11eb-85fe-56062912ba3f.png)
![image](https://user-images.githubusercontent.com/63438571/96191744-55e39580-0f0a-11eb-89ee-07ac3dce3345.png)

For MegaManGANLevelBreederTask, segmentCount is initialized, another problem is that when you initialize with one segment and use the slider to increase length, then it only copies in the direction it originally went.

![image](https://user-images.githubusercontent.com/63438571/96191910-afe45b00-0f0a-11eb-8f1e-e55db201d58d.png)

However, when initialized with multiple segments, there is no such problem
![image](https://user-images.githubusercontent.com/63438571/96191987-c985a280-0f0a-11eb-978d-d5d81c09cf0a.png)

**Comment by schrum2** [comment]
I think the default should be multiple segments. However, the behavior of duplicating the same segment over and over when you start with one segment and increase the slider is not a problem ... an easy way around it is to select levels and click randomize ... at least I think this should fix it.

**Comment by cappsb** [comment]
MegaManCPPNtoGANLevelBreeder and MegaManGANLevelBreeder work as intended now.
