### ISSUE TITLE
Render Mega Man Levels Without White X's

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#599]
For the paper, we need to render the levels with the solution path (red X's) but not the connectivity (white X's).

**Comment by cappsb** [comment]
All images (0-29 on OneGAN and SevenGAN) are in SCOPE Artifacts > SCOPE 2020 Mega Man > SevenGAN (Solution Path Only) and corresponding OneGAN folder as well.

**Comment by schrum2** [comment]
@cappsb Be sure to put the new images into the Overleaf draft too
