### ISSUE TITLE
Is Manhattan Distance admissible in Mega Man?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#607]
Since Mega Man can move diagonally as part of a jump, I think that the Manhattan Distance heuristic is technically not admissible. We might need to make a slightly different heuristic, after our paper submission.

**Comment by schrum2** [comment]
Basically, the issue here is that diagonal movements are allowed while jumping and falling. Therefore, a simple heuristic that would never be an overestimate would be the max(|xM-xG|,|yM-yG|). MegaMan is at (xM,yM) and the goal orb is at (xG,yG), so whichever distance is farther (horizontal or vertical) is simply the distance.

The potential problem with this is that it could be a gross underestimate. However, given that the search worked fine when we were accidentally using 0 as the heuristic, I think we'll be fine. As long as it is admissible, it will be better than the null heuristic.

**Comment by schrum2** [comment]
You'll need to watch my videos on A* search and brush up on what admissible means to make full sense of this, but ultimately you are just replacing one heuristic with another.

**Comment by schrum2** [comment]
You'll need to make some JUnit tests for this. This means you need to manually construct some simply levels out of list of lists of integers and double check that the calculated heuristic distance on these simple levels is exactly what you expect it to be.

A class `MegaManStateTest` already exists, and fortunately this new code change has not broken it. The test currently only checks that the correct optimal path is discovered. However, you need to add some tests that verify that certain heuristic calculations come out to exactly what they should be.

**Comment by MuellMark** [comment]
After fixing the original unit tests that were broken by adding the orbHeurisitc (#758), I added new test cases to ensure that the orb heuristic was calculated correctly.  I also Mavin built it to verify this.
