### ISSUE TITLE
Mario falls through the map in simulation

### ISSUE THREAD

**Issue by Flemoz** [schrum2/MM-NEAT#61]
Hi! 
I'm trying to run some Mario examples in the batch folder, but all of them leads to instances where Mario just falls through the map at the beginning of the simulations. There are no error messages, it just sees it as Mario dying and goes to the next network.
 
I am running this on Mac OS with Java version 1.8.0_112 and Maven version 3.5.2. 
I did have some problems with loading the "tiles.dat" file out of the box (it did not get packaged into the JAR file), which I have alleviated by moving the resources folder to src/main/ and calling `LevelScene.class.getClassLoader().getResourceAsStream("tiles.dat")`
inside the LevelScene class instead. I am not sure if that is causing the problems, although I can't see why.

Below image shows it running the Mario-Basic-HyperWatch example with showMarioInputs:true and the simulation running side by side. The ground seems to be recognized but Mario still falls right through. 

<img width="707" alt="screen shot 2017-12-05 at 14 46 53" src="https://user-images.githubusercontent.com/6792447/33611342-6075490e-d9ce-11e7-82e9-bb08a65056a7.png">

**Comment by Flemoz** [comment]
Ok, so it seems that cloning down the project anew and building the JAR file has made it work correctly. I am not sure why (and I could've sworn I tried that already...), but I could've made some changes before, which I haven't reverted that made the Mario engine break.

**Comment by schrum2** [comment]
I'm glad you were able to figure this out yourself so quickly. Please feel free to ask for follow-up help in the future.

Note that I am doing some work with Mario right now in the dev branch. The master branch should be fairly stable though.
