### ISSUE TITLE
Future Work From Zentangle Paper

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#611]
Some interesting ideas for future work from the Zentangle paper:

- Scale variation: CPPNs can easily draw things at arbitrary scale. Therefore, the scale of images that are composed into patterns should be parameterized to allow for mixing of images at various scales.
- Pattern orientation: It should be easy to mathematically rotate images using a rotation matrix. Just parameterize the degree of the rotation (or could this be a CPPN output?). Basically, some images should be rotated.
- Allow for more than three background patterns. Can be done by layering more images in the template and assigning different backgrounds to every combination of overlapping parts between templates.

**Comment by schrum2** [comment]
I believe the first two bullet points can be accomplished by emulating the approach of the `ShapeInnovationGenotype` class. Basically, the genotype for the pictures should consist of a CPPN and some real-valued parameters: one for scale (multiply each coordinate value by this before inputting to CPPN), one for the degrees of rotation (transform x/y coordinates with a rotation matrix before inputting into CPPN).

This will be a bit mathematically daunting, but talk to me about the task first and I'll walk you through how to do it.

**Comment by annazwicker** [comment]
https://collections.southwestern.edu/s/suscholar/item/216

**Comment by schrum2** [comment]
Here is some more guidance regarding scale variation and pattern orientation. For both of these changes, the key is in the `GraphicsUtil` class, in the `get2DObjectCPPNInputs` method. Basically, you need to add two parameters: one for scale, and one for rotation. This also means you have to modify pretty much every method that calls this one, as well as the methods that call those methods, etc all the way up to the `imageFromCPPN` method (though we may end up making a "default" version of that method that uses standardized parameters). Basically, if the scale is 1.0, and the rotation is 0 radians, then these methods will behave the same way they currently do. However, here is how they can change.

The `ILocated2D scaled` in the  `get2DObjectCPPNInputs` method is actually a `Tuple2D` so you can change its type. This will make it easier to modify.

Scale:  Replace the `scaled` variable with one where you use the `mult` method of the `Tuple2D to change the scale of the x/y coordinates.

Orientation: Similar, but use the `rotate` method

**Comment by schrum2** [comment]
By the way, a good place to work on modifying these aspects of CPPN images is the `PicbreederConstructor` class:
https://github.com/schrum2/MM-NEAT/blob/2df68fbd0afbbd261050d8bbde1748244f0cbe26/src/main/java/edu/southwestern/tasks/interactive/picbreeder/PicbreederConstructor.java

Start by just running it to see the output. Then, once you start adding the ability to change scale and rotation as described above, you can make sure that you are getting the same image, but scales and/or rotated.

**Comment by annazwicker** [comment]
Added the parameters for the get2DObjectCPPNNInputs method (scale and rotation).  Created new methods without the new parameters so other methods that call the methods with the new parameters can stay the same.  This has been tested and currently works.  Currently adding JavaDoc comments to the new methods and revising old JavaDoc to include all parameters.

**Comment by annazwicker** [comment]
JavaDoc has been added.

**Comment by schrum2** [comment]
Use the newly added `TWEANNPlusParametersGenotype` to evolve CPPNs whose images can be rotated and scaled. First, you will need to extend this `TWEANNPlusParametersGenotype` into a new genotype called `EnhancedCPPNPictureGenotype`. All that this genotype really has to do is specify that the type of the second phenotype is `ArrayList<Double>`, and have a constructor that creates a `TWEANNGenotype` and a `BoundedRealValuedGenotype`. 

The `BoundedRealValuedGenotype` will need to specify bounds for its values. Basically, the two numbers being tracked here are the scale and the rotation. The bounds for rotation should be `0` and `2*Math.PI`. As for scale, make the bounds `0.1` and `10` (these might be replaced with command line parameters later, but don't worry about this for now)

You should be able to add this new genotype without any syntax errors, so make a commit when you are done. The next step is integrating this into PicbreederTask. Basically, you will have to have checks in the code that use `instanceof` to see what the type of the class being manipulated is. Whenever `getPhenotype()` is called to get a `Network` you can use `instanceof` to see if the resulting `Network` is actually a `NetworkPlusParameters` instance. If this is the case, you can cast it to `NetworkPlusParameters` to access the additional parameters, and then use them in the call to generate the CPPN image so that the results will be scaled and rotated.

**Comment by annazwicker** [comment]
Of the original three issues, the first two have been completed.  Scale and rotation parameters have been added and can be seen in the output.  The third issue > * Allow for more than three background patterns. Can be done by layering more images in the template and assigning different backgrounds to every combination of overlapping parts between templates.  has not been completed yet.

**Comment by schrum2** [comment]
To handle the final part of this, start by looking at `GraphicsUtil`. There are different versions of the method `zentangleImages` and even one that isn't being used. You can make a version of the method that supports 4 patterns with 2 background images. Read the comment for the version with this method header
`public static BufferedImage zentangleImages(BufferedImage backgroundImage1, BufferedImage backgroundImage2, BufferedImage pattern1, BufferedImage pattern2, BufferedImage pattern3)`

You basically need to copy this method but add a `pattern4` and add a fourth case to the if/else if/else inside the loop. In fact, you'll notice that the second case involves an OR `||`, and all you really need to do is split that one case into two distinct `else if` cases where each part of the OR is a different case instead of two ways of activating the same case.

**Comment by annazwicker** [comment]
Adding the extra zentangleImages method with pattern4 has now been added, and the black + non-black case has been split into two separate cases (one using pattern2 and one using pattern4).

**Comment by schrum2** [comment]
In order to test this code out, you need to call your new version of the `zentangleImages` method in the appropriate place within `PicbreederTask`. Basically, there needs to be a case where `numSaved == 6` and this version of the method gets called. This will also require additional code above that senses when 6 images are selected and actually sets them up so you can pass them to your method.

Just to clarify how this code currently works: The Zentangles are created differently based on the number of images the user selects in the Picbreeder interface before clicking the Zentangle button. All of the images are saved, some as patterns created by WFC. The proper images then get re-loaded back into the code and combined with the call to `zentangleImages`. Some details on this are here: https://github.com/sarahkfriday/QuantumZentanglement

**Comment by annazwicker** [comment]
All of the original issues have now been attempted and completed.  Images can now be scaled and rotated, and zentangle images can now include four pattern images.
