### ISSUE TITLE
Relocate megamanlevels/textLevels directory

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#621]
I'm not exactly sure why these are here. I'm sure they were put here by @cappsb . I suspect that these are all the levels evolved for our 2021 GECCO paper, and that Ben put then into text before running the Novelty analysis on them. If that's the case, then we should still keep them in the repo, but I would prefer to have them moved into a sub-directory here:
https://github.com/schrum2/MM-NEAT/tree/master/data
However, I want to make sure this is done in a way that makes it possible to still run the Novelty analysis, or do whatever else was previously being done with these files.

**Comment by cappsb** [comment]
Yes, that folder is for the novelty calculations. To change it in the code, go to MegaManLevelNovelty.java on line 29:

final String basePath = "megamanlevels/textLevels/AStarDistAndConnectivity";

**Comment by schrum2** [comment]
This will be a task for you @MBatt1 . First, run `MegaManLevelNovelty` to see the proper output.

Then, move the text files in `megamanlevels/textLevels` into a new directory `data/EvolvedMegaManLevels2020`

Then change the `basePath` variable that Ben described.

Finally, run the code again and make sure that it produces the same output.
