### ISSUE TITLE
Mega Man Experiments using MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#625]
Ben's recent Mega Man paper used multiobjective evolution, but did not use MAP Elites. Therefore, we don't really have much of a sense yet for what sort of diversity of levels can be discovered in Mega Man. I think that @cappsb worked on some binning schemes for Mega Man to use MAP Elites, but I'm not sure. Look in the task for evolving Mega Man levels and see what it says about binning schemes, if anything. Even if binning schemes exist, we may need to make more/better ones. Ultimately, I want to have a batch file subdirectory full of files that can launch Mega Man experiments using MAP Elites.

This should be done before #557 , since CPPN2GAN and CPPNThenDirect2GAN are mainly interesting when combined with MAP Elites.

**Comment by MBatt1** [comment]
I think it is done, take a look at it.
There are 4 experiments, using singleGAN and multiGAN with CPPN2GAN and Direct2GAN. Output directories correspond to the amount of GANs used, and are added to gitignore

**Comment by schrum2** [comment]
@MBatt1 I never did get around to running this, so I'm going to ask you to try again.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120695719-51f08d80-c471-11eb-86da-b46f91655c04.png)
Results

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120705612-a8fc5f80-c47d-11eb-959d-71d9afbe3f62.png)
CPPN2GAN with MultiGAN results, **note: Scaling is not the same**
