### ISSUE TITLE
Basic Function Optimization Task for CMA-ES

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#627]
To have confidence that our use of CMA-ES actually works ( #313 ) I want you to create a new type of LonerTask that is specifically for FunctionOptimization. Confusingly, a task with that name already existed, but it was actually meant for MultipleFunctionOptimozation, so I'll be renaming it soon.

Make a new package: `edu.southwestern.tasks.functionoptimization`

Make a task (`FunctionOptimization`) that essentially evaluates a genotype (specifically a `BoundedRealValuedGenotype`) by using one of the test functions already included in the CMA-ES test examples, such as `Rosenbrock` and `Rastrigin` (see the class `FunctionCollector`)

Once this task works, you can apply CMA-ES to it and compare the results with the more straight-forward CMA-ES code examples

**Comment by MBatt1** [comment]
Test function in FunctionOptimizer matches CMAExample1, both using Rosenbrock
