### ISSUE TITLE
KL Divergence for MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#630]
An interesting thing that is done in the paper about Illuminating the space of Mario levels ( https://arxiv.org/pdf/2007.05674.pdf ) is that one of their MAP Elites binning schemes is based on KL Divergence. Basically, there are two specific Mario levels (technically scenes, which are parts of a level), and the binning dimensions are defined as the difference (measured by KL Divergence) with respect to these levels. I actually have the code for computing KL Divergence in MM-NEAT. There is an example of how to use it in `InteractiveGANLevelEvolutionTask`.

Specifically, this code is relevant:
```
		int[][] level1 = getArrayLevel(phenotype1);
		int[][] level2 = getArrayLevel(phenotype2);

		ConvNTuple c1 = KLDivTest.getConvNTuple(level1, Parameters.parameters.integerParameter("receptiveFieldWidth"), Parameters.parameters.integerParameter("receptiveFieldHeight"), Parameters.parameters.integerParameter("stride"));
		ConvNTuple c2 = KLDivTest.getConvNTuple(level2, Parameters.parameters.integerParameter("receptiveFieldWidth"), Parameters.parameters.integerParameter("receptiveFieldHeight"), Parameters.parameters.integerParameter("stride"));

		double klDiv = KLDiv.klDivSymmetric(c1.sampleDis, c2.sampleDis);
		String result = "Symmetric KL Div: " + genotype1.getId() + " to " + genotype2.getId() + ": " + String.format("%10.6f", klDiv);
		return result;
```

I would like you do define a MAP Elites binning scheme for Mario that uses KL Divergence in the manner of the above referenced paper.

The relevant calculations will need to happen in `MarioLevelTask`. Currently, this task assumes that any MAP Elites binning scheme will have three dimensions, but you'll need to generalize the `setBinsAndSaveMAPElitesImages` method to handle situations with just two bin dimensions. In fact, remove the parameters `dim1`, `dim2`, and `dim3` and replace them with a single `int[] dims` parameter which can have any length, to fully generalize it.

You'll also need to define a new MAP Elites binning scheme based on the KL Div scores. Look at `MarioMAPElitesDecorNSAndLeniencyBinLabels` for comparison.

Of course, the KL Div scores are defined with respect to specific reference levels. The way we will handle this is that we will have two String-type command line parameters that specify txt files containing the levels that are being compared against. I believe that these can refer to files located in the `data\VGLC\SuperMarioBrosNewEncoding` directory. There is some code somewhere that can read this text format, and convert it to an array of integers, which is exactly the format needed for KL Divergence.

**Comment by schrum2** [comment]
Note: If you do any work on this, try to define the binning scheme in a very general fashion that does not depend on Mario at all. I think that we should be able to extend this to any game with a tile-based encoding, so I want it to be written in a general fashion.

**Comment by MBatt1** [comment]
Currently has an implemented KL Divergence calculation static method. Bin labels are generated based on the amount of dimensions, and can be accessed with 1D indexes generated by the 1D index function. Values can be discretized into coordinates based on specified bins per dimension and overall dimensions. There is a temporary main function I was using to test discretizing and indexing functions. There is no behavior characteristic implemented, but the function is present, always returning null

**Comment by MBatt1** [comment]
KL divergence dimensions are levels to be compared to

**Comment by MBatt1** [comment]
KL Divergence for Mario is fully set up, but parameters corresponding to bins per dimension and the maximum value need to be set to proper values to actually have it work

**Comment by MBatt1** [comment]
Parameters have been set up and appears to produce valid output for the Mario test that can be run in MarioLevelTask

**Comment by schrum2** [comment]
Very curious to see how CMA-ME handles the KL-Div binning scheme in Mario since that is what was done in the paper by Fontaine et al. If CMA-ME doesn't outperform MAP Elites here, then we definitely have a problem (probably already do ... but this will be more supporting evidence).

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120367547-a14e8680-c2d6-11eb-89a7-93ab30dc6152.png)
Results from KL Divergence. We already know it's wrong but here's more evidence

**Comment by MBatt1** [comment]
needs batch files

**Comment by MBatt1** [comment]
Should be tested and needs batch files for Zelda and Lode Runner

**Comment by MBatt1** [comment]
For Zelda and Mega Man, we will need to do something different, since a level is not linear or a fixed size. We need some way to compare a dungeon to another dungeon with KL Divergence with both the layout and the rooms themselves somehow. Could just break up the dungeons into a list of the rooms and compare each one, but they would be in an arbitrary order.

**Comment by MBatt1** [comment]
As a product of KL Divergence being 2 dimensions, Lode Runner is no long hard-coded as 3 dimensional for MAP Elites

**Comment by MBatt1** [comment]
With KL Divergence, since there are spaces in the files paths and level file names needed to provide KL Divergence levels, they need to be provided like so: `data\\VGLC\\LODERU~1\\Processed\\<level name>`, where level name comes from doing `dir /x` in normal command prompt.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120813400-769d4180-c513-11eb-932a-65b1d995d5db.png)
Lode Runner results

**Comment by schrum2** [comment]
Try with 10 emitters, and then maybe even 15

**Comment by MBatt1** [comment]
Running 10 and 15 emitter tests, however we still need to figure out what to do with Zelda and MegaMan

**Comment by MBatt1** [comment]
Current state of KL Divergence is compatibility with Mario and Lode Runner levels. MegaMan and Zelda have several issues with how to apply KL Divergence- primarily the blanks spaces in different room layouts. 
Since KL Divergence is working for 2 games, batch files will be made and noted in the issue threads for #686 and #693
