### ISSUE TITLE
Log max fitness in MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#632]
MAP Elites should log the maximum fitness that it has encountered across all of its bins. Currently, it already logs the number of filled bins and the QD score. Add a column for the max fitness across occupied bins. Also need to update the gnuplot file that is generated so a plot of this new score can be generated.

**Comment by schrum2** [comment]
If you think this is done, then close the issue

**Comment by annazwicker** [comment]
#632 Added a plot for the maximum individual fitness score.  Appears to have the correct scale according to the results produced.
