### ISSUE TITLE
Create a MIDI file from code

### ISSUE THREAD

**Issue by annazwicker** [schrum2/MM-NEAT#634]
Look for a way to create a MIDI file from an array of numbers corresponding to notes.  Something to think about: how to code enharmonic notes (notes that are the same in frequency, but on paper they are written differently depending on the key of the piece.  For example: A# and Bb (A sharp and B flat) are identical in pitch but are written on different lines on a staff).  There are technically 12 different pitches but if you chose to include enharmonics it would be a lot more.  What might be easiest is to go through all 30 scales (some of these are the same scale but are enharmonics of each other, so technically there are only 24 different major and minor scales), and write down the individual notes of each one with accidentals (sharps, flats and naturals) to find every possible note used.  A place to start with creating a midi file from an array: find a way to code an entire scale inside an array, then try to make a scale that spans more than one octave.  Start with major and minor scales, see if there's a formula to be developed to switch between the two.  You could find a formula for converting to and from parallel and relative minor and major scales.

Something to keep in mind as a future task: there are two accidentals, the double sharp and double flat, that are also used in music, but they aren't used in any of the basic scales.  However, some composers do use them in their scores, so this is something to consider adding later.

Another future task to think about: How to code different modal scales.  I would need to do more research on this since this isn't something I've spent a lot of time covering in previous music classes.  However, the concept isn't incredible difficult, but since there are a few different ways of looking at it, there are a few different ways to code this.  
![modesspacing2](https://user-images.githubusercontent.com/82399865/118682900-7b00f500-b7c6-11eb-8aae-89a8330edf74.jpg)

@schrum2

**Comment by annazwicker** [comment]
Here's some things I think need to be done in order to tackle this (just some ideas):

- Figure out the frequency of every note in a given range (I think two octaves is decent, since this would allow for us to explore every possible scale, for example A4 has a frequency of 440).
- Create an integer ArrayList of pairs to pair each note with its given frequency or create a global variable for each note.
- Figure out how to calculate or store the duration and the speed of the playback.
- Create methods to tell the program when to play a certain note and when to stop playing a certain note (you would need this same method but for a rest too probably).
- Maybe reconfigure Isabella's version of the keyboard so that when you press a key, it corresponds to the actual note it plays (this might include putting a text box where users can input notes in a certain format (or create buttons, one for note name, one for accidentals, and one for octave number) and if they press another button or hit 'enter' the output will be played).
- Create a save method.

**Comment by schrum2** [comment]
It could still be nice to do this as a starting point for something bigger. You would need to rely on some tutorial online to get a basic prototype working, but ultimately this is a pretty low priority issue now.

**Comment by schrum2** [comment]
Dead/stale issue that is unlikely to develop further.
