### ISSUE TITLE
Parameter for Picbreeder Picture scale

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#636]
The new EnhancedCPPNPictureGenotype hard-codes the max picture scale to be 10. This should be a parameter in the `Parameters` class. Add this parameter, and set the default value to 5 instead of 10 (the images seemed too zoomed out when we looked at them)

**Comment by annazwicker** [comment]
Created a new parameter for EnhancedCPPNPictureGenotype to use rather than using a hard-coded value.
