### ISSUE TITLE
PictureTarget fitness troubleshoot

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#637]
In the `edu.southwestern.tasks.innovationengines` package make a class called `PictureTargetFitnessTroubleshoot` that has a main method. We can modify the contents of the code to specify the filenames of two jpg images ... at first, one would refer to the skull since that is where we are focusing our effort. The purpose of the class is to take these two images, compare them using the fitness function in `PictureTargetTask` and print out the fitness. Then, to go deeper, you would compute the `degreeOfDifference` for each pixel and store the results in a 2D array, which you could then turn into a heatmap image depicting the degree of disagreement between images at each pixel location.

**Comment by schrum2** [comment]
Use the DrawingPanel (like in PicbreederConstructor) to visualize

**Comment by schrum2** [comment]
If the individual error values are greater than 1, you will need to scale them. Find the maximum (Use StatisticsUtilities.maximum). Then, divide each error value by that maximum to scale it to the range 0 to 1.

**Comment by schrum2** [comment]
The new method for converting to a BufferedImage should be moved to the GraphicsUtil class.

The class currently displays an error image for the Woolley fitness. Make the code actually display/print the Woolley fitness as well, so we know that the calculation makes sense. Once that is done, create and display a second error image for the RMSE fitness ... the method will need to return a `Pair<BufferedImage,BufferedImage>`

**Comment by annazwicker** [comment]
PictureTargetFitnessTroubleshoot now runs and produces a Triple of BufferedImages.  The result from both the Woolley and RMSE fitness calculations are slightly off (likely due to a floating point error).  The three heatmaps show the Woolley fitness pixel difference, RMSE fitness pixel difference, and both fitness pixel differences.
