### ISSUE TITLE
Stark AnimationBreederTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#638]
The `AnimationBreederTask` is somewhat similar to the `PicbreederTask`. Both are examples of `InteractiveEvolutionTask`s, so they are coded in very similar fashion.

Currently, the animation breeder does not support start images, but this should be easy to add. Add a checkbox to the AnimationBreeder interface like the one in Picbreeder. Note that if you force the command line parameter "starkPicbreeder" to be true for the AnimationBreeder, it will already be able to make stark animations. The purpose of this issue is simply to add a checkbox to the interface that toggles the setting.

**Comment by annazwicker** [comment]
AnimationBreederTask now has a stark setting for the animations.  I added a new button to a new panel to do so (this code was taken from PicbreederTask).
