### ISSUE TITLE
Animations where the scale and rotation change

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#641]
For AnimationBreeder, it would be really awesome if the scale and rotation of the images could change during animation. I think I have a way of doing this.

Add two outputs to the CPPN: rotation and scale. However, these outputs are going to be a bit odd. Normally, you ask the CPPN for an output at each pixel, and in animation breeder you ask at each pixel and time frame. So, you input a bunch of information, and you use all of the output to set the color of one pixel. However, these new outputs are different.

At each time frame and for each pixel, you will still provide information as normal, and extract resulting information about the pixel color. There will be additional CPPN outputs for the scale and rotation, but you will completely ignore these when setting the pixel colors. So, when do they get used at all then?

Well, BEFORE generating any of the pixels for an image at a given time frame, you will query the CPPN once to get the scale and rotation. This requires some default values for the x, y and distance from center inputs, so just set them all to 0. The time input still varies as usual, so that the scale and rotation can change over time. Therefore, this special query happens once per time frame. When you query the CPPN in this way, it will produce outputs for HSB (the color), but they are ignored. This special query is the only time you pay attention to the scale and rotation outputs. Save the scale and rotation outputs from this special query, and then do the normal queries to produce the image on that time frame, except you use the scale and rotation that you produced earlier as parameters to the imageFromCPPN method so that the resulting images will be appropriately scaled and rotated.

**Comment by annazwicker** [comment]
The images produced by AnimationBreederTask now can rotate and scale as they move.  This involved adding a new parameter to the Parameters class, altering numCPPNOutputs and ouputLabels in AnimationBreederTask, and altering the imageFromCPPN method in AnimationUtil.
