### ISSUE TITLE
MAPElites Archive Heatmap Plot does not generate with an extreme amount of bins

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#644]
Running MAPElites with a large amount of bins (was failing with CMA-ME with 500x500 plots) fails to generate a Archive Heatmap Plot due to the large file size

**Comment by MBatt1** [comment]
It may be worth changing how -Infinity is represented, as the file sizes can get excessive with huge amounts of bins (>1GB)

**Comment by schrum2** [comment]
We found out that you can see the heatmap if you change the gnuplot terminal to standard (not pdf), so there is at least a way to see the results. However, it might be possible to see them in PDF if either a size or resolution setting is changed, but we're not sure.

**Comment by schrum2** [comment]
See what happens with large archives when you use other terminals, like PNG. See if any of them work with the really large number of bins

**Comment by schrum2** [comment]
Various terminal options here: http://www.bersch.net/gnuplot-doc/complete-list-of-terminals.html

Honestly, there are too many, but try out the common image types to find out if any work, noting that you may need to tweak size and other params as well

**Comment by schrum2** [comment]
Actually, let's make things simpler and also more useful. For non-MAP-Elites-based evolution, what I currently do is output plt files that use the default terminal AND plt files that use PDF. Do the same for MAP-Elites ... that way, the user can decide what to look at. In fact, just generating the plot instead of a PDF could actually be useful in a lot of situations.

**Comment by MBatt1** [comment]
Now, the original file is generated but has pdf in the name, for example: 
"MarioCompareBins-DecorateNSLeniency999_MAPElites_pdf_log.plt". 
The new file has the old name, and just generates an image and displays it, with no PDF
