### ISSUE TITLE
Different Behavior Characterization for MAP Elites + Picbreeder

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#647]
This is an issue related to #615 .

Let's assume our fitness calculation is ok (ignoring this #637), but that the problem is the MAP Elites binning scheme. However, we also want something simpler than the autoencoder (#642). Here is an idea:

Keep in mind that a 2D image is sort of like a 2D array of pixels. You can split the image into 4 quadrants. Within each quadrant, you can add up the pixel intensity values (brightness values). This gives us 4 numbers. We can use these 4 numbers as the 4 dimensions of a behavior characterization for MAP Elites. We just need to bin each dimension into a specific range.

Note: This is sort of like the 2D behavior characterization that @MBatt1 used for the Rastrigen function, but with 4 dimensions. You can ask him for help.

If an image is n x n pixels in size, then each quadrant is (n/2) x (n/2) pixels in size (let's assume n is even for simplicity). Also, a brightness value for 1 pixel is between 0 and 1. Therefore, the highest possible sum of pixel intensities is (n/2) x (n/2), and the lowest possible value is 0. We can have a command line parameter that sets the number of bins per dimension. It needs a good name, but for now let's just call it d. That means that when you discretize the behavior characterization, you get the index with the formula ((n/2) x (n/2) / d).

Once again, @MBatt1 did something very similar ... perhaps he can point to some of that code here.

This may not be a great behavior characterization, but it is something different that is worth trying. In particular, it is actually based on the image contents and not just the network structure, which should create more variety in the images we see in the archive.

**Comment by annazwicker** [comment]
https://github.com/schrum2/MM-NEAT/blob/dev_maxx/src/main/java/edu/southwestern/tasks/functionoptimization/FunctionOptimizationRastriginBinLabels.java

**Comment by annazwicker** [comment]
Testing for PictureFourQuadrantBrightnessBinLabels has been completed and PictureFourQuadrantBrightnessBinLabels works well.  Currently running PictureTargetTask to see if different results will be produced.

**Comment by annazwicker** [comment]
Currently running using the new binning scheme, but the results aren't much different so far.  The class functions correctly and the testing also functions properly (thorough cases were tested).

**Comment by annazwicker** [comment]
The images produced varied more (rather than having a series of almost uniform images, more variety can be seen), but the images still aren't anywhere close to the skull image.  Need to try with a simpler image to make sure the algorithm is correct (perhaps the skull is just too complicated for the code we have?).

**Comment by schrum2** [comment]
@annazwicker Put some picture examples in this issue thread so that we get a sense for what "diversity" means
