### ISSUE TITLE
Zentangles: Different Scaled Tiles

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#650]
Currently, all Zentangle tiles in a WFC pattern are the same size. This should be allowed to vary.

We will keep the "zentangleTileDim" parameter, and interpret it as the minimum tile size (don't change anything ... just change how you think about it). Think of the "zentanglePatternDim" parameter as the number of tiles you can have in a row if they all have the minimum tile size of "zentangleTileDim". This means that if you want tiles that are twice as big, you halve the number of tiles in a row. You could also quadruple the tile size to halve the number of tiles in a row again. Restrict things to powers of 2 like this.

The `SimpleTiledZentangle.simpleTiledZentangle` method is currently improperly hard-coded to assume that there will be 30 times in each row and 30 tiles in each column. Change the method signature for `SimpleTiledZentangle.simpleTiledZentangle` to accept a single parameter that is the `int patternDim`, but have this one parameter replace both occurrences of 30 in `SimpleTiledZentangle.simpleTiledZentangle`.

This will change the number of tiles in WFC patterns. However, we still want all images to be the same size, so when we save the tiles we need to save them with the right sizes. Let's limit ourselves to double size, quadruple size, and octuple size: 2, 4, or 8. Use `RandomNumbers.randomGenerator.nextInt(4)` to get a random number 0, 1, 2, or 3. In the loop that makes the call to `saveSingle` have a line at the start that sets a `tempTileSize` equal to 2 raised to the power of your random number (use `Math.pow`). Then replace all uses of `tileSize` in a call to `saveSingle` with `tempTileSize`.

You will also have to remember what power of two was used for each tile so that you now how to adjust the `patternDim` in each call to `SimpleTiledZentangle.simpleTiledZentangle` later. You can save the values in an array every time you save a tile, and then on every call to `SimpleTiledZentangle.simpleTiledZentangle` you can divide the standard "zentanglePatternDim" by the power of two to get the right size for each image.

**Comment by annazwicker** [comment]
The Zentangle images now include patterns with tiles scaled to varying powers of 2.  This involved storing the power in an array in order to get the right size for each image.  Images are 3200x3200 pixels in order to accommodate the power of 2 scaling.
