### ISSUE TITLE
Log More information in MAP Elites (as well as CMA-ME)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#651]
Currently, the log tracks how many bins are filled. I would also like to track how many generated offspring are discarded. Being able to plot this could be helpful. Basically, adding the number of discarded to the number of filled should always add up to the total generated so far, which would be a straight line. Still, it would be nice to track at what point we are discarding more than we add.

Anything you add to the log in this way should work for CMA-ME as well.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/119536590-de52d000-bd4e-11eb-93a4-b78d21ef2d86.png)
Discarded is plotted and when summed, shows a straight diagonal line, which it should be.
