### ISSUE TITLE
Troubleshoot CMA-ME FAILURE_VALUE

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#653]
Do some quick tests with the Sphere and Rastrigen functions to see if CMA-ME performance is impacted by the value of `FAILURE_VALUE`. Try both `Double.MAX_VALUE` and `0`. Don't bother making this a command line parameter ... just hard code the different options so we can figure out if they make a difference.

**Comment by MBatt1** [comment]
After some testing with Rastrigin for #622, it is apparent that *at least in the case of Rastrigin* Double.MAX_VALUE is a better choice for FAILURE_VALUE in CMA-ME, however more functions and tasks should be tested

**Comment by schrum2** [comment]
We recently realized that there should not even be a FAILURE_VALUE. Rather, every offspring gets a fitness, even if it is not a new elite for the archive.
