### ISSUE TITLE
Experiment with CMA-ME Mu value

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#654]
I'm not sure we want to be setting mu = lambda in CMA-ME emitters:
```
		optEmitter.parameters.setMu(lambda);
		optEmitter.parameters.setPopulationSize(lambda);
```
Fiddle with the value of Mu a bit just to get a sense for what happens (report here). What if it is smaller than lambda? Can it be bigger? What if it is 1? Summarize answers here.

**Comment by MBatt1** [comment]
If lambda is 1, it seems to perform much worse
Cannot be bigger than lambda, or CMA-ES crashes

see #622 results for plots comparing things

**Comment by schrum2** [comment]
It sounds like we could have this version of Mu be its own parameter, but the default Mu that CMA-ME should use is lambda / 2
