### ISSUE TITLE
Lode Runner with NSGA2 and CMA-ES

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#658]
In issue #598 I point out how it is simply hard to find Lode Runner levels that are beatable, but I wonder if that is true. The evidence there indicates that it is hard to find beatable levels using MAP Elites. However, I wonder if plain objective search could succeed where MAP Elites fails.

Create a new directory for batch files associated with objective-evolution in Lode Runner. Ultimately, I want to have a batch file that uses each of the GANs that were used in the experiments of the `Experiments-2021-GECCO-LodeRunner` directory. For each GAN, have one batch file that evolves in Lode Runner using CMA-ES with A* path length as the objective (but using connectivity if the level cannot be beaten). Then, have another batch file for each GAN using NSGA2 (which is the default). With NSGA2 there should be two objectives: path length and connectivity.

**Comment by MBatt1** [comment]
CMA-ES results are lower than NSGA2's

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120672605-13020e00-c458-11eb-8cb6-6f678787c992.png)

**Comment by schrum2** [comment]
Try doing some NSGA2 runs using the On150 and WordsPresent GANs, and log results here. The On20 results you have provided reach a fitness value comparable to the best On20 results Kirby obtained, but it was harder to find long solution paths with the other GANs.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121540050-c5435380-c9cb-11eb-9933-088ce67ddc1f.png)
NSGA2 | CMAES
On150 results, strange that CMAES found good aStar ones then had horrible aStar ones the rest of the time

**Comment by schrum2** [comment]
It's good to note that there is apparently some weird issue with A* in CMA-ES, but it's not important enough to spend a lot of work tracking down at the moment. However, could you go ahead and put a comment in the batch file indicating that it produces these weird results (Use `REM` to comment a line in a batch file). Go ahead and mention the name of the problem batch file in this thread as well.

**Comment by MBatt1** [comment]
Broken CMA-ES batch files are:
batch\LodeRunnerObjectiveEvolution\LodeRunnerGAN-CMAES-AStarDistConnectivityCombo-On150Levels.bat
batch\LodeRunnerObjectiveEvolution\LodeRunnerGAN-CMAES-AStarDistConnectivityCombo-WordsPresent.bat
