### ISSUE TITLE
Generalized GAN latent vector binning scheme

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#659]
It should be possible to make a binning scheme for GAN latent vector evolution similar to what you did for the sphere and rastrigen functions. Basically, you split the latent vector up, add up the components, and divide into some number of bins.

Since this is similar to what you already did for KL Div #630 , you should make a generalized **abstract** binning scheme (put it in the mapelites package or a subpackage of that one) that handles some number of dimensions that are divided according to some max values. Refactor KL Div to use this new abstract binning scheme, and also make a new binning scheme based on the idea above that uses the abstract binning scheme as well.

**Comment by MBatt1** [comment]
The class is set up and can be given several parameters:
binsPerDimension, The bins in each dimension, currently all the same
minPossibleValue, The lowest value for bins, basically the lower bound
maxPossibleValue, The highest value for bins, basically the upper bound
numDimensions, Number of dimensions in the archive
vectorLength, The length of the vector being evolved

**Comment by MBatt1** [comment]
Given that (from what I saw in the incomplete runs before I had to leave) Rastrigin seemed to be working, and we will have KL Divergence results soon, I think this issue can be closed, the class is complete and has javadoc / needed comments, as well thorough JUnit tests

**Comment by schrum2** [comment]
Still need to make a generalized GAN latent vector binning scheme that just chops up the latent vector and adds up subranges to get the behavior characteristic.

**Comment by MBatt1** [comment]
Added chopping binning scheme as `MultiDimensionalRealValuedSlicedBinLabels`

**Comment by MBatt1** [comment]
Generalized GAN chopping scheme is `LatentVariablePartitionSumBinLabels`, configured to work with all 4 games

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121369545-8fd23380-c901-11eb-8883-c34473d95f2a.png)
Generalized binning scheme with Mario

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121369814-ce67ee00-c901-11eb-9617-84bca32fe6da.png)
Generalized binning scheme with MegaMan

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121370078-0838f480-c902-11eb-90aa-e0721cd692ec.png)
Generalized binning scheme with Lode Runner

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121370390-4fbf8080-c902-11eb-8c37-f779fb09443f.png)
Generalized binning scheme with Zelda

**Comment by schrum2** [comment]
A lot of these plots are (hopefully) mislabeled as using other binning schemes. I just want to make sure that was an oversight in the command line parameter, and not an indication of testing with the wrong binning scheme. Otherwise, you can close the issue. Though it is interesting how the Lode Runner levels are low quality (consistent with previous work). I'm also shocked at how little coverage the Zelda dungeons have, but maybe that makes sense too ... there isn't much diversity in the training set, and the overall novelty scores we got for our dungeons were pretty low

**Comment by schrum2** [comment]
It looks like a lot of the thorough testing you did for this issue was invalidated by an error that was later fixed. Are we ready to test things again? Do we want to add binning schemes related to this to #686 and #693 ?

**Comment by MBatt1** [comment]
Currently testing all 4 games, Mario has been running and appears to be far more broad than it was previously, so hopefully the others will be the same

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122132260-20c47580-ce00-11eb-855b-7f8c666c53d5.png)
New Mario results- more bins filled, much higher QD, but a lower maximum, possibly a result of filling more bins instead of focusing on a small group of bins?

2D archive visualization:
![image](https://user-images.githubusercontent.com/53229958/122132348-494c6f80-ce00-11eb-9a3d-67727a6b34a5.png)

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122233885-07fca400-ce82-11eb-9b4e-0a9b95dc4bb2.png)
Better MegaMan results for every chart

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122234327-6b86d180-ce82-11eb-9527-195c5697b2d7.png)
New Lode Runner results, more bins filled but lower QD, maximum, and about equal beatable

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122234909-ddf7b180-ce82-11eb-8469-5f0a44ad7b21.png)
New Zelda results

**Comment by schrum2** [comment]
Is this issue complete? It sounds like it might be. If not, please give an update.

**Comment by MBatt1** [comment]
Since the results improved and appear to be capable of actually fully filling the archive to the intended size, I believe the issue is done. This binning scheme will be applied to #686 in each game, all with the latent vector divided in 2
