### ISSUE TITLE
Try evolving a simpler image

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#662]
We keep failing to recreate the skull, but the skull is hard to reproduce. We should start trying to evolve a much simpler image.

Use `PicbreederConstructor` to produce a super simple image. In particular, comment out a lot of the code so that the complexity of the neural network making the image is very low ... just one or two neurons and a few links. Save it as a png instead of a jpeg, and make it fairly small. Also, make sure you are using the default scale of 1 and rotation of 0 (currently, the code is not doing this). You will also need to set it to black and white.

Once you make and save the image, put it where the other images are stored (subdir of data) and force commit it to the repo. Then, set up PictureTargetTask to attempt evolving that image.

**Comment by annazwicker** [comment]
The algorithm works for a less complicated image (dot.png), but consistently failed when trying to recreate a slightly more complicated image.  Examples can be seen below:
Target: dot.png
![dot](https://user-images.githubusercontent.com/82399865/120345559-32663300-c2c0-11eb-95c6-f5bcea394248.png)
Images produced (attempting to recreate the dot):
![0 82734(5,6,5,6)1727](https://user-images.githubusercontent.com/82399865/120345829-748f7480-c2c0-11eb-887a-dddeb2bbae25.jpg)
![0 94998(7,7,7,7)255](https://user-images.githubusercontent.com/82399865/120345830-748f7480-c2c0-11eb-8956-3c3ae99475f4.jpg)
![0 95973(7,7,7,7)2707](https://user-images.githubusercontent.com/82399865/120345831-75280b00-c2c0-11eb-9254-c96226da189a.jpg)
Target: comet.png
![comet](https://user-images.githubusercontent.com/82399865/120345861-7d804600-c2c0-11eb-9952-d59a12f3559f.png)
Images produced (attempting to recreate the comet):
![0 75621(9,8,8,5)1400](https://user-images.githubusercontent.com/82399865/120346001-9983e780-c2c0-11eb-823c-42abb546c804.jpg)
![0 77444(8,9,7,3)2726](https://user-images.githubusercontent.com/82399865/120346002-9a1c7e00-c2c0-11eb-91fb-87a9b8963c70.jpg)
![0 78311(7,8,6,4)2276](https://user-images.githubusercontent.com/82399865/120346003-9a1c7e00-c2c0-11eb-8199-68b8a727e3cf.jpg)
Target: failedskull.jpg
![failedskull](https://user-images.githubusercontent.com/82399865/120346100-ae607b00-c2c0-11eb-855e-69f6d6656aa6.jpg)
Images produced (attempting to recreate the failed skull):
![0 72826(4,3,6,4)8908](https://user-images.githubusercontent.com/82399865/120346454-fed7d880-c2c0-11eb-99ab-3dbfe30f7a98.jpg)
![0 73145(4,4,4,4)6728](https://user-images.githubusercontent.com/82399865/120346455-ff706f00-c2c0-11eb-8318-99ba1389d30f.jpg)
![0 73721(3,3,5,5)5529](https://user-images.githubusercontent.com/82399865/120346456-ff706f00-c2c0-11eb-8f6b-b33136113172.jpg)

**Comment by schrum2** [comment]
What fitness function was used with these? RMSE or Woolley?

In any case, I'm interesting in a bit more work here. Let's use the RMSE fitness, and evolve for a very long time using the failed skull as the target. Try with both the neurons/links binning scheme and the 4-quadrant binning scheme. I want to see a comparison of these results, and try to get a sense for if the 4-quadrant scheme is actually better at all.

**Comment by annazwicker** [comment]
Assuming nothing has been changed in PictureTargetTask, I believe the images above were done using RMSE fitness, but I'm not completely sure.  Currently running the program twice, both using RMSE fitness but one using the neurons/links binning scheme and one using the 4-quadrant binning scheme.  Thus far, it appears to run much quicker using the neurons/links binning scheme.

**Comment by annazwicker** [comment]
Terminated the previous runs.  Both binning schemes were able to successfully replicate the failed skull image.  Currently doing two new runs, both using the RMSE fitness calculation, one using the neurons/links binning scheme, the other using the 4-quadrant binning scheme.  Since we saw success with the failed skull as the target image, these two runs are using skull64.jpg as their target image.
