### ISSUE TITLE
New Fitness for ImageMatchTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#663]
The `ImageMatchTask` was sort of our attempt to recreate the experiment of the Brian Woolley paper a long time ago. It isn't surprising that it doesn't work, but given the results in the Woolley paper, it seems like our results should at least be better. Therefore, I want you to try understanding this code better, and also add the option to use some different fitness functions.

Currently, the `ImageMatchTask` calls `super.evaluate(individual)`, which uses the fitness function in `MatchDataTask`. However, I want you to add the option to use different fitness functions, like the woolley fitness and the RMSE like we use in the PictureTargetTask. You can copy something like the code in the `fitness` method of the `PictureTargetTask`, except that the default option is to call `super.evaluate(individual)` as is already done in `ImageMatchTask`.

Note that once you get the fitness score, you store it in the `Score` instance differently than when you are using MAP-Elites

**Comment by annazwicker** [comment]
Results from ImageMatchTask
![ImageMatchTaskNeither](https://user-images.githubusercontent.com/82399865/120376318-5d14b380-c2e1-11eb-958b-162a1c5917b4.jpg)
![ImageMatchTaskNeithernetwork](https://user-images.githubusercontent.com/82399865/120376321-5dad4a00-c2e1-11eb-90bd-9cf7a20b26e7.jpg)
![ImageMatchTaskRMSETrue](https://user-images.githubusercontent.com/82399865/120376322-5dad4a00-c2e1-11eb-9b3f-e865557a64ca.jpg)
![ImageMatchTaskRMSETruenetwork](https://user-images.githubusercontent.com/82399865/120376323-5dad4a00-c2e1-11eb-8c2c-bdb6c7f66ef0.jpg)
![ImageMatchTaskWoolleyTrue](https://user-images.githubusercontent.com/82399865/120376325-5dad4a00-c2e1-11eb-9190-e3b5e2611443.jpg)
![ImageMatchTaskWoolleyTruenetwork](https://user-images.githubusercontent.com/82399865/120376326-5e45e080-c2e1-11eb-9f31-9e2c306f4745.jpg)

**Comment by schrum2** [comment]
The RMSE fitness is definitely measuring things correctly. It successfully recreates the failed skull in the objective-based ImageMatchTask:
![image](https://user-images.githubusercontent.com/8397236/120423646-6bd68700-c330-11eb-95fd-6215fe7bedab.png)
Images in the top right are the original image and the evolved image. The network and champion fitness plot are also shown. Note that although the fitness is high, it is not a perfect value yet, because the image is just good, but not perfect.

**Comment by schrum2** [comment]
The Woolley fitness seems to work too:
![image](https://user-images.githubusercontent.com/8397236/120423903-f4edbe00-c330-11eb-8156-d9eddad17ccc.png)
The result from this particular run was not quite as good as the result from RMSE, though that could be chance. Still, the result is clearly approaching being like the failed skull, and the fitness is high but not perfect in a way that seems appropriate.

**Comment by schrum2** [comment]
Even the standard fitness seems to work, but there are some issues:
![image](https://user-images.githubusercontent.com/8397236/120424452-fe2b5a80-c331-11eb-9758-42e17af3ccfb.png)
Note that the fitness plot here is zoomed in to ignore the starting fitness that was very low. The fitness that is actually achieved here is really high, but I think this is because the ImageMatchTask is generalized to handle color images. This means that for black-and-white images, the Hue and Saturation are always 0, which is easy to match. This results in a very high overall average error energy because at least 2/3 of the terms in the average have an error of 0, meaning that a smaller total amount is subtracted from 0.

There is an unrelated issue though ... this run generated several networks that ended up with infinity or NaN values in their activation functions. I don't think this is actually a direct error with this task. I think that sometimes, with CPPNs especially, a result of infinity is actually possible ... that is a bigger issue I should fix, but it is pretty rare.

Closing this issue.
