### ISSUE TITLE
Carefully compare pyribs CMA-ME to our version

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#664]
Our version of CMA-ME #622 still does not work, so you are going to have to actually download and run the pyribs version (https://pyribs.org/). In particular, you will need to get the source code, because you are going to want to edit it by adding some print statements throughout to track what is going on. Run the original code in a simple case on some basic function optimization task using just one improvement emitter. See how pyribs performs, try to understand what is going on, and then closely compare what it does with what our version does.

To track what is going on, you might consider making the lambda value very small, and also making other parameters small/simple so that it is possible to trace the behavior.

Track any insights you glean in this issue thread.

**Comment by MBatt1** [comment]
1 emitter run had the following error:
`CMA-ES error: an eigenvalue has become negative
Exception in thread "main" fr.inria.optimization.cmaes.CMAEvolutionStrategy$CMAException:  CMA-ES error: an eigenvalue has become negative
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.error(CMAEvolutionStrategy.java:873)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.eigendecomposition(CMAEvolutionStrategy.java:1109)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.samplePopulation(CMAEvolutionStrategy.java:1478)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.samplePopulation(Emitter.java:135)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.resetSample(Emitter.java:149)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.sampleSingle(Emitter.java:162)
        at edu.southwestern.evolution.mapelites.CMAME.newIndividual(CMAME.java:90)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.run(SteadyStateExperiment.java:40)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:778)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:999)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:959)`

This needs to either be resolved, or CMA-ES needs to restart, otherwise it terminates

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120495618-7e79ac00-c382-11eb-99f9-7963cdd0008d.png)
Results comparing 15 emitter runs

**Comment by MBatt1** [comment]
The equation for how many generations we should be running is (# emitters) * (lambda) * (iterations).
In their code the 15 emitters with 37 lambda running 4500 times is approx. 2.5 million (15*37*4500), which is how many generations we run our 15 emitter code for. for the single emitter, it should only be 1*37*4500, or 166500 generations. Likely the cause of the error we had before is due to CMAES fully leveling out, and then 0 becoming slightly negative due to imprecision

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120503001-86d4e580-c388-11eb-87ba-7e7e6d2bb0f9.png)
1 emitter comparison

**Comment by schrum2** [comment]
@MBatt1 Just to be thorough, go ahead and compare pyribs to MM-NEAT on Rastrigen too. Put the plots here when one to confirm

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120815098-2626e380-c515-11eb-8bc1-01ba8c93f90b.png)
15 emitter MAP Elites result

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121036981-b3b43e80-c774-11eb-860f-b5405d9621f7.png)
New data after changing the function optimization task

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121042384-3f2fce80-c779-11eb-9302-a87850a83985.png)
Comparing percentage filled before and after change. 
Before the negative sign change it was almost identical, and it is also strange that MAP-Elites almost didn't change at all

**Comment by schrum2** [comment]
You're going to need to put in some additional effort into understanding how QD is scaled in the Pyribs code for the sphere and rastrigen functions. Since we are uncertain about how we are handling fitness, that is the thing we have to take the closest look at.

Might also want to look at the C# implementation of CMA-ME: https://github.com/tehqin/QualDivBenchmark

**Comment by schrum2** [comment]
I talked to Amy a bit about how the objective score and QD score are computed for the Sphere function in pyribs. You can probably find the code, but here are the relevant parts.

```
    # Shift the Sphere function so that the optimal value is at x_i = 2.048.
    sphere_shift = 5.12 * 0.4
 
    # Normalize the objective to the range [0, 100] where 100 is optimal.
    best_obj = 0.0
    worst_obj = (-5.12 - sphere_shift)**2 * dim
    raw_obj = np.sum(np.square(sol - sphere_shift), axis=1)
    objs = (raw_obj - worst_obj) / (best_obj - worst_obj) * 100
```

There area some important issues going on here that we should talk about. The default sphere function assumes the solution is at the 0 vector, but this one shifts the location of the solution. Not sure we want to incorporate that idea into our code, but it is worth considering.

I also have the code for the behavior characterization for comparison as well:

```
    # Calculate BCs.
    clipped = sol.copy()
    clip_indices = np.where(np.logical_or(clipped > 5.12, clipped < -5.12))
    clipped[clip_indices] = 5.12 / clipped[clip_indices]
    bcs = np.concatenate(
        (
            np.sum(clipped[:, :dim // 2], axis=1, keepdims=True),
            np.sum(clipped[:, dim // 2:], axis=1, keepdims=True),
        ),
        axis=1,
    )
```

**Comment by MBatt1** [comment]
Because the HeatMap looks strange;
![image](https://user-images.githubusercontent.com/53229958/121745463-f144fe80-cac9-11eb-8d8a-b05c6e35d4f2.png)

I'm going to write some code to plot a 2D version of the archive to see what ranges/areas we actually are filling

**Comment by schrum2** [comment]
Try some unit tests that start with the solution vector itself, or even a Bounded Real Valued Genotype. See if you can map a solution to the extreme edges of the space

**Comment by schrum2** [comment]
By the way, was this result with plain MAP-Elites or CMA-ME?

**Comment by MBatt1** [comment]
This is plain MAP Elites

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/121926413-8da61580-cd03-11eb-8f2f-11e77c76defc.png)
CMA-ME results

**Comment by schrum2** [comment]
As far as binning schemes go, **plain** MAP-Elites seems to work fine on **Rastrigen**. Here are my results from over night.
![image](https://user-images.githubusercontent.com/8397236/122056082-e088d700-cdae-11eb-9146-57379bcf5ffe.png)

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122071676-8e4eb280-cdbc-11eb-90d2-a30ddf7be2bc.png)
I also did a run, almost identical

**Comment by schrum2** [comment]
I also did just short of 2.5 mil evals using CMA-ME with 1 improvement emitter on Rastrigen and got these results
![image](https://user-images.githubusercontent.com/8397236/122148619-698c2680-ce20-11eb-84de-a181017f531e.png)
And this last one is the number of filled bins:
![image](https://user-images.githubusercontent.com/8397236/122148702-8e809980-ce20-11eb-8895-689a530f305b.png)
It doesn't seem clearly better, but it is not obviously worse either. There is also a legit question of it it would improve with more time ... plain MAP-Elites (above) seemed to be leveling out. Interestingly, it reaches some parts of the archive that plain MAP-Elites does not, but also fails to reach regions it did reach. Although there is no clear boundary, it does seem as though the search roughly fills out a square area before presumably resetting and restarting elsewhere, which gives me a new idea I'll mention in another issue.

I am interesting in seeing what results you get from your runs @MBatt1 , but I also think it is once again worth doing some runs with more emitters. I'll start some now, and maybe I'll have you do some tomorrow too.

**Comment by schrum2** [comment]
Here is a zoomed in view of just the 2D archive from the previous post (CMA-ME with 1 Improvement Emitter on Rastrigen)
![image](https://user-images.githubusercontent.com/8397236/122149627-ff748100-ce21-11eb-9558-43e851c5bf0f.png)

I was hoping to run an experiment with 15 emitters, but ran into the error described in issue #696

**Comment by schrum2** [comment]
A 15 emitter run in Rastrigen is now duccessfully running using code in dev_maxx

**Comment by schrum2** [comment]
I did two runs of CMA-ME with 15 emitters on Rastrigen last night. Here are the final archives:
![image](https://user-images.githubusercontent.com/8397236/122224900-2ced1900-ce7a-11eb-8483-685e0feb6005.png)
and
![image](https://user-images.githubusercontent.com/8397236/122224969-3ecebc00-ce7a-11eb-9ba2-8c82f25ea96f.png)
and the fill counts:
![image](https://user-images.githubusercontent.com/8397236/122225236-80f7fd80-ce7a-11eb-9541-86d4a06ec88b.png)
This is disappointing. This is about the same level of performance as with 1 emitter, and maybe slightly worse. Certainly not a clear improvement over regular MAP-Elites.
It's also interesting how the max fitness stalls out, but perhaps this is an issue with regular MAP-Elites too:
![image](https://user-images.githubusercontent.com/8397236/122225687-e6e48500-ce7a-11eb-98f3-8f6af1ff8f6f.png)

**Comment by schrum2** [comment]
@MBatt1 Can you post some plots/data comparing MAP-Elites and CMA-ME in pyribs using Rastrigen? I want to see this data side by side. I assume that the actual pyribs code gets better results with CMA-ME than MAP-Elites, though I also remember you indicating that my version of MAP-Elites might be better?

For reference, here are the percentage of bins that were filled when I did various runs:

Rastrigen with CMA-ME and 15 emitters: 58% and 60%
Rastrigen with CMA-ME and 1 emitter: 61%
Rastrigen with MAP-Elites: 64%

Listing it out like this makes it even more clear that there is a problem.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122292210-58442800-cebb-11eb-83aa-74acfe91aace.png)
Pyribs MAP-Elites results: we fill ~160000 bins whereas pyribs fills only 140000

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122292716-e4564f80-cebb-11eb-8afc-772846bb0b51.png)
Pyribs CMA-ME 15 emitter results: We fill far fewer bins, ~150000, compared to Pyribs, which filled ~220000

**Comment by schrum2** [comment]
My run of Sphere function with 15 Improvement Emitters in CMA-ME finished. Here is how it compares to plain MAP-Elites.

CMA-ME actually does fill more bins, 201508 compared to 164313 for plain MAP-Elites. That's 80% vs 65%. CMA-ME also reaches higher maximum fitness.
![image](https://user-images.githubusercontent.com/8397236/122410466-90924780-cf49-11eb-88b5-84031ba50063.png)

Finally, here are the 2D archives:
![image](https://user-images.githubusercontent.com/8397236/122410761-d2bb8900-cf49-11eb-8221-1c70d33e82d5.png)

Conclusions: The issue with the Sphere function being bound to a certain range is fixed. Also, our version of CMA-ME is better than our version of MAP-Elites. This is good. However, I want to have you double check on HOW MUCH better CMA-ME should be than MAP-Elites for the Sphere function by comparing with Pyribs. Not above that our CMA-ME filled about 80% of the archive. You can also compare the 2D depictions visually.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122420981-ae63aa80-cf51-11eb-8ba1-a19e703724b7.png)
pyribs for comparison

**Comment by schrum2** [comment]
This basically confirms that pyribs is still better than us for CMA-ME, even on the Sphere. Maybe the animation issue can help #702

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-MAPElitesSphereFunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122438117-00abc800-cf60-11eb-9557-f2fc31ce2a1a.gif)
![mapelitesfunctionoptimization-CMAMESphere15ImprovementFunctionOptimization15_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122438131-043f4f00-cf60-11eb-86aa-fbb391010b37.gif)
Animations of both our archives filling

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-MAPElitesSphereFunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122438117-00abc800-cf60-11eb-9557-f2fc31ce2a1a.gif)
![mapelitesfunctionoptimization-CMAMESphere15ImprovementFunctionOptimization15_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122438356-3ea8ec00-cf60-11eb-9f03-6bf65a4841ad.gif)

Animations of both our archives filling

**Comment by MBatt1** [comment]
| MAP-Elites | CMA-ME |
| ![mapelitesfunctionoptimization-MAPElitesSphereFunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122455978-9d776100-cf72-11eb-89ca-18b77bcb81bf.gif) | ![mapelitesfunctionoptimization-CMAMESphere15ImprovementFunctionOptimization15_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122455996-a49e6f00-cf72-11eb-99d4-a791f1a75724.gif) |

Now scaled the same

**Comment by MBatt1** [comment]
MAP Elites vs CMAME Rastrigin fill results
![mapelitesfunctionoptimization-MAPElitesRastriginFunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122474557-0538a680-cf89-11eb-9e22-5f313a2cf49d.gif)
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementFunctionOptimization15_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122474567-08cc2d80-cf89-11eb-8a62-cf71131b92d2.gif)

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization999_MAPElites158](https://user-images.githubusercontent.com/53229958/122619536-46e35300-d056-11eb-854c-00c7412f0e8f.png)
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization999_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122619539-48148000-d056-11eb-84a6-5568e396dbbd.gif)
Current state of Rastrigin, and started the sphere one.

**Comment by MBatt1** [comment]
this is at generation ~800000 so we are still quite far from the end, and this is 5x slower than the other visualizations I made (10 vs 2)

**Comment by MBatt1** [comment]
Sphere function results with tracked emitters: 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53229958/122779251-4ecc0e80-d273-11eb-9905-100cc8dba4b7.gif)
![mapelitesfunctionoptimization-CMAMESphere15ImprovementDim500FunctionOptimization999999_MAPElites249](https://user-images.githubusercontent.com/53229958/122779266-5390c280-d273-11eb-9fd3-6ceb188fec4a.png)

**Comment by MBatt1** [comment]
Rastrigin function results with tracked emitters:
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization999_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122779759-cef27400-d273-11eb-9659-e54e15dd47a9.gif)
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization999_MAPElites495](https://user-images.githubusercontent.com/53229958/122779777-d3b72800-d273-11eb-9913-140526d73b7e.png)

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMERastrigin1ImprovementFunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/122785531-12031600-d279-11eb-85df-1c6aa485d23d.gif)
1 Emitter rastrigin GIF

**Comment by schrum2** [comment]
I believe I've finally found a major discrepancy between the correct CMA-ME implementation and our version. It seems odd that it would cause such a difference in performance, and this is frustrating since it might take quite a bit of work to make our version behave appropriately, but here is the issue.

The original CMA-ME paper states:
"If we have found parents that improved the map, we rank them [...] by concatenating two groups: first the group of parents that discovered new cells in the map, sorted by their fitness, and second the group of parents that improved existing cells, sorted by the increase in fitness over the previous solution that occupied that cell."

This is consistent with the pyribs source code for the Improvement Emitter (https://docs.pyribs.org/en/stable/_modules/ribs/emitters/_improvement_emitter.html#ImprovementEmitter). Specifically, this part is relevant:
```
        ranking_data = []
        new_sols = 0
        for i, (sol, obj, beh) in enumerate(
                zip(solutions, objective_values, behavior_values)):
            status, value = self._archive.add(sol, obj, beh)
            ranking_data.append((status, value, i))
            if status in (AddStatus.NEW, AddStatus.IMPROVE_EXISTING):
                new_sols += 1
        # New solutions sort ahead of improved ones, which sort ahead of ones
        # that were not added.
        ranking_data.sort(reverse=True)
```

We definitely do not do this yet. The consequence of this is that a solution that improves an existing cell by an amount more than the fitness of uncovering a new cell would be prioritized above the new cell. However, I feel that implementing this in our code may require mucking about inside the CMA-ES code, since currently we just send it an array of fitness values that it uses to make its decisions.

**Comment by schrum2** [comment]
According to the CMA-ES Wikipedia page (https://en.wikipedia.org/wiki/CMA-ES):
"This makes the algorithm insensitive to the specific f-values. More concisely, using the CDF estimator of f instead of f itself let the algorithm only depend on the ranking of f-values but not on their underlying distribution."

If this is true, I may have a way of fixing the sorting without mucking with CMA-ES code directly. In any case, we should try it.

**Comment by schrum2** [comment]
My last two commits are an attempt at implementing the proposed change. Basically, scores for improved bins and failed bins are artificially inflated with respect to the range of fitness values encountered, in a way that should rank the solutions based on solution type first and fitness second.

I'm running the code now to test, but I also want this code extensively unit tested as much as possible. I changed the type signature of the `calculateFitness` method, and I think that at least this method (for both emitter types) can be extensively unit tested (simply matter of right output for given inputs).

However, it would also be good if you could create an artificial archive (very small) where you call `addFitness` several times in a row and check the values in `deltaIFitnesses` after the point where it should be updated with new contents. That would be a reassuring test, and I think it is do-able.

**Comment by schrum2** [comment]
@MBatt1 This batch file doesn't seem to run long enough: `CMA-ME-Sphere-1Improvement-Dim500.bat`

**Comment by schrum2** [comment]
I thought I fixed this, but the following error came up when running Rastrigen with just 1 Improvement Emitter:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 37
        at edu.southwestern.evolution.mapelites.emitters.Emitter.addFitness(Emitter.java:140)
        at edu.southwestern.evolution.mapelites.CMAME.newIndividual(CMAME.java:121)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.run(SteadyStateExperiment.java:40)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:832)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1060)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1020)
```

**Comment by schrum2** [comment]
I believe the exception has been fixed (previous commit), and is being tested now.

**Comment by schrum2** [comment]
I did a Rastrigen run with just one emitter over night, and am annoyed that I did not change my power settings, so the computer slept and the run isn't finished. However, the incomplete results are still very telling.
![mapelitesfunctionoptimization-CMAMERastrigin1ImprovementFunctionOptimization5_MAPElites193](https://user-images.githubusercontent.com/8397236/122935697-29ec9f80-d336-11eb-928f-65b3715bdb6b.png)
We're definitely getting better coverage. In fact, this covers 98% of bins! With just one emitter!

It looks like the fitness suffers a bit though.
![image](https://user-images.githubusercontent.com/8397236/122936103-83ed6500-d336-11eb-9814-9020208725ab.png)
Max fitness stalled at -108 for a while, and just broke through to -92. Still, with so many bins filled, the only place left to go is to improve existing bins ... it might improve enough in time, and would certainly do better with 15 emitters.

Here are filled archives
![image](https://user-images.githubusercontent.com/8397236/122936718-fc542600-d336-11eb-96d6-d636175bde77.png)

and QD
![image](https://user-images.githubusercontent.com/8397236/122936797-0d9d3280-d337-11eb-9aa9-8b2ca7707494.png)

**Comment by schrum2** [comment]
Compare how pyribs sorts for the Optimizing Emitter in comparison with ours. I did the sorting for our Optimizing Emitter in a way similar to our Improvement Emitter, but I wonder if the Optimizing Emitter should actually favor improvements in existing bins over discovery of new bins. I guess it might also be in the paper, but they mainly focus on the Improvement Emitter, and I think it would be easier to check the pyribs code.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123005303-81f9c500-d37b-11eb-917d-834143dbb855.png)
Current standings of sphere/rastrigin

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMESphere15ImprovementDim500FunctionOptimization444_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123111709-bcf30b80-d402-11eb-8adf-c3d374b1e2f1.gif)
![mapelitesfunctionoptimization-CMAMESphere15ImprovementDim500FunctionOptimization444_MAPElites248](https://user-images.githubusercontent.com/53229958/123111741-c1b7bf80-d402-11eb-925f-a9e6599cd049.png)
Sphere function CMA-ME

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization444_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123111804-d1cf9f00-d402-11eb-8895-4c31c500cd10.gif)
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization444_MAPElites248](https://user-images.githubusercontent.com/53229958/123111821-d5632600-d402-11eb-9b6f-6acfc961ec9f.png)
Rastrigin function CMA-ME

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123112213-26731a00-d403-11eb-9581-83b3630679c9.png)
Actual graphs from above runs, done with new changes to CMA-ME improvement emitters.

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMESphere15ImprovementDim500FunctionOptimization6_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123275374-e32fae80-d4c9-11eb-833c-f88228c608c4.gif)
![mapelitesfunctionoptimization-CMAMESphere15ImprovementDim500FunctionOptimization6_MAPElites248](https://user-images.githubusercontent.com/53229958/123275398-e88cf900-d4c9-11eb-8e65-d7769d925d5b.png)
Correct sphere function results

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123275615-183c0100-d4ca-11eb-999f-5cf29d16741b.png)

**Comment by schrum2** [comment]
Lastest Rastrigen results. Coverage is still good ...
![image](https://user-images.githubusercontent.com/8397236/123283270-dbbfd380-d4d0-11eb-8c61-94e8d1d8b235.png)
... but max fitness is still poor.
![image](https://user-images.githubusercontent.com/8397236/123283441-0316a080-d4d1-11eb-9772-9859eb4b519f.png)

**Comment by MBatt1** [comment]
![cma_me_imp_20_heatmap_04500](https://user-images.githubusercontent.com/53229958/123290632-0ca30700-d4d7-11eb-909c-12e8f1a6a3c8.png)
Pyribs with raw scores plotted, pyribs appears to be able to get very close to 0

**Comment by MBatt1** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/53229958/123316578-9c09e380-d4f2-11eb-92f5-2cd81981eff2.gif)

**Comment by schrum2** [comment]
I believe we were concerned that our version of MAP-Elites was reaching a higher max fitness than our version of CMA-ME on the Rastrigen function, but I think we were mistaken. I couldn't find old results confirming this, and I just re-ran that comparison to get these results. I actually compare MAP-Elites, ME-Line, and CMA-ME on Rastrigen with 500 dimensions:
![image](https://user-images.githubusercontent.com/8397236/123422910-7b8a6980-d584-11eb-872c-f387c8820cf4.png)
As usual, CMA-ME has much better coverage. Reassuringly, ME-Line (though not finished) has better coverage than MAP-Elites. However, the all have comparable max fitness, with CMA-ME perhaps even being slightly better (at least for this run ... we know that there is variance).

Although there is perhaps still some improvement that can be made in the comparison with Rastrigen in pyribs, the fact that we are getting correct relative performance makes me want to look more closely at how we defined the Rastrigen function in pyribs to make sure it really is equivalent. I'm also curious to know how max fitness of MAP-Elites compares to max fitness of CMA-ME in pyribs ... how does their version of MAP-Elites do? Finally, I am still interested in how our experiment involving the unbounded genotype comes out.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123438766-a8477c80-d596-11eb-8615-1463670f75c2.png)

Unbounded Rastrigin vs Bounded Rastirigin, there does not appear to be a significant difference enough to make one better over the other, at least for rastrigin

**Comment by MBatt1** [comment]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/53229958/123483874-13ac4100-d5cd-11eb-9972-2bcd4af58672.gif)
Bounded vs Unbounded archives filling

**Comment by schrum2** [comment]
Probably worth combing through the code and comparing to this C Sharp implementation:
https://github.com/tehqin/QualDivBenchmark/tree/master/StrategySearch/src

**Comment by MBatt1** [comment]
The way that individuals were being evaluated caused bounded values to be evaluated and put into the archive, but the emitters were still receiving the unbounded values.
Most of our results for function optimization likely are still going to be the same, since they were bounded within the binning scheme, however they may have changed, and all other domains (games) need to be re-done

**Comment by schrum2** [comment]
Track any outcomes from running the fixed CMA-ME on game domains in issue #645 

Track results from re-running Rastrigen here in this issue.

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization446_MAPElites_archive](https://user-images.githubusercontent.com/53229958/124137821-aa548400-da4b-11eb-9d69-c0422d995851.gif)
With the new CMA-ME changes, the emitters appear to be more accurate, however the final bins, QD, maximum, etc are all pretty much the same

**Comment by schrum2** [comment]
Adding the resampleBadCMAMEGenomes trick seems to actually produce worse results for Rastrigen, which I suppose makes sense. The original Pyribs experiment for Rastrigen allows unbounded genotypes, so no resampling actually happened in that case. In fact, by discarding rather than clipping out of range values, I could see why we miss the extreme edges of the archive. Here is the final archive:
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500FunctionOptimization355_MAPElites](https://user-images.githubusercontent.com/8397236/124288099-69757180-db16-11eb-8a1b-48cd9c87a976.png)
It doesn't reach the edges.

Filled bins tops out at a lower value:
![image](https://user-images.githubusercontent.com/8397236/124288220-8d38b780-db16-11eb-9961-74f171217717.png)

And max fitness is still capped under -50.
![image](https://user-images.githubusercontent.com/8397236/124288285-a04b8780-db16-11eb-88ad-11dca9da55b1.png)

I'm going to return the resampling trick to be false by default.

**Comment by schrum2** [comment]
Before fully giving up and closing this issue, I'm going to run Rastrigen for even longer to see if the code eventually gets to the point it needs to be at.

**Comment by schrum2** [comment]
Ok, I think these results will be the final word on this issue. We may not perfectly be reproducing what pyribs does, but I don't think we have a glaring error. In any case, I ran CMA-ME (15 improvement emitters) and MAP-Elites on Rastrigen for 3 million individuals to see if things got better with a bit more time. Not that CMA-ME here is with genotypes bounded to [-5.12,5.12]. I actually re-ran the unbounded comparison as well, since I fixed a spot in the code where the vectors were being put into a bounded genotype, regardless of what the original intended type was (in other words, our previous unbounded results are probably invalid). However, I only allowed this run to go for the approx 2.5 million individuals.

In terms of bins, bounded CMA-ME does amazing, unbounded does worse, and MAP-Elites does far worse.
![CompareBins](https://user-images.githubusercontent.com/8397236/124373627-72bb2700-dc59-11eb-8c8f-b7271471c2f4.png)

However, in terms of max fitness, the unbounded CMA-ME does better! I'm not sure if this is as close to 0 as the pyribs results ... I think pyribs still does better, but it is interesting that an experiment closer to the original pyribs one (they were unbounded) gets better fitness. I'm not sure the drop in coverage makes up for it though.
![CompareMaxFit](https://user-images.githubusercontent.com/8397236/124373659-d5142780-dc59-11eb-87f1-7306c3949f04.png)

However, QD scores of unbounded and bounded are comparable, and both better than MAP-Elites, so maybe we are closer to the original pyribs results.
![CompareQD](https://user-images.githubusercontent.com/8397236/124373684-08ef4d00-dc5a-11eb-88e9-b35fc8796e7b.png)

Ultimately, I'm going to say that we are doing a good job recreating CMA-ME. So, I'm going to blame our frustrating results in the GAN level domains #645 on issues with those games and their binning schemes.

Last thing: here are the archives for each approach:

Bounded CMA-ME (long)
![mapelitesfunctionoptimization-LongCMAMERastrigin15ImprovementDim500FunctionOptimization0_MAPElites](https://user-images.githubusercontent.com/8397236/124373733-8adf7600-dc5a-11eb-956a-26ba4ff0e7c6.png)

Unbounded CMA-ME
![mapelitesfunctionoptimization-CMAMERastrigin15ImprovementDim500UnboundedFunctionOptimization0_MAPElites](https://user-images.githubusercontent.com/8397236/124373756-a9457180-dc5a-11eb-8462-28edcd69ecb5.png)

Plain MAP-Elites
![mapelitesfunctionoptimization-LongMAPElitesRastriginFunctionOptimization0_MAPElites](https://user-images.githubusercontent.com/8397236/124373761-b1051600-dc5a-11eb-9710-d068b2ff43ac.png)

Ok, actual last thing: The way I initialize unbounded genotypes might be limiting. Everything is close to the 0 vector since the vector values are between -1 and 1 (very small range). This is a small handicap at the start, and could be causing problems, but I'm not interested enough to re-run the experiment at this point. Like I said, I think our implementation basically works ... for the most part.
