### ISSUE TITLE
PictureTargetTask: Option to save whole image archive

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#667]
Currently, PictureTargetTask is set up to save an image whenever it passes a certain fitness threshold. Those images stick around on disk. Note that it is possible for an image that is no longer an elite to still be on the disk. For example, it could have passed the fitness threshold when it was created, but later it was replaced by a better elite. I want a different way of saving/tracking/organizing images from the archive.

The first step of this is to make a method in PictureTargetTask that creates a new sub-directory inside of the experiment directory, and then loops through the entire archive and saves the image produced by every elite. This will be especially useful when we start using the autoencoder #655 because the code we currently have loads a directory of images to find its training set. So, making this new method is a starting point.

**Comment by annazwicker** [comment]
Testing of the method saveAllArchiveImages was successful!

**Comment by schrum2** [comment]
Closing this issue in response to most recent commit
