### ISSUE TITLE
newCMAESInstance for emitters

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#668]
Is there any difference in the `newCMAESInstance` method for the improvement and optimizing emitters? If not, then the code should be put in `Emitter`. I think you mentioned that some other possible emitters really would be different, but the base `newCMAESInstance` method does not need to be `abstract` in order to be overridden. Just put the shared code into `Emitter`.

**Comment by MBatt1** [comment]
It was identical, and has been moved.
