### ISSUE TITLE
Comparing MAP-Elites binning schemes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#669]
It's hard to know if one MAP-Elites binning scheme is really "better" than another. You can't compare the number of bins filled, because different schemes simply have different numbers of bins. You can't compare QD scores for similar reasons. You can compare the maximum fitness values achieved, and perhaps the average values across the bins, but it is unclear if that means much, and it certainly doesn't say much about how diverse the archive is.

However, I think I may have a way of at least comparing two binning schemes. Evolve with each scheme, and then take all elites from the resulting archive and see what happens when you insert them into an archive with a different binning scheme. If one binning scheme really is catching a wide range of diversity, then when you put it into an archive with a different binning scheme, you should have pretty good coverage in that archive as well. However, I could also imagine having a bad binning scheme that is filled with elites it thinks are diverse, but when you insert them all into a different type of archive, everything gets clustered in a small portion of the archive.

So, the task for this issue is as follows: Write code that can take the saved archive from one experiment, but load all of the elites into a new archive with a different binning scheme, and then output something that allows the resulting archive to be analyzed. Things like the resulting number of occupied bins, QD score, as well as a representation of the whole archive that could be processed into a heat map.

When MAP-Elites experiments run, they save an archive of all the elite genomes. You've probably been focusing mainly on the pictures of the evolved levels, but you will notice that there are also .xml files in the archive directory. These are serialized representations of the evolved genomes that can be loaded back into Java. In fact, I think you'll find some code in vanilla MAP-Elites that tries to resume an aborted experiment by loading all of the xml elites back into the archive in memory. There might be an easy way to boot up an experiment, but simply change the binning scheme, which would result in this code loading these elites into a different archive.

**Comment by MBatt1** [comment]
Is functional, with an example batch file located in `batch\MAPElitesCompareTest`, able to compare a Mario run to the DistinctNSDecorate binning scheme. Should be provided the original directory location and run number, and automatically outputs a appropriately labeled folder and text files based on the binning scheme being compared

**Comment by schrum2** [comment]
I tested this on some data from previous experiments, and made an additional batch file to make the testing easier. I also deleted your old batch file ... use mine now instead. There are still one or two minor things that need to be fixed. I added a parameter logLock:true to make sure the log file for command line parameters would not be changed. However, during testing, I noticed that the plot file responsible for making the heatmap changed slightly: the xrange changed to correspond to the number of bins in the new scheme. In fact, all of the plt files seem to be overwritten, which should not happen.

I don't think any other files are modified, though I am certainly worried about that, and want the issue investigated thoroughly. Execute a run to completion (you can change the max gens so it is shorter). Then produce all of the PDF plots and back up all of the plt and txt log files. Then apply the bin comparison, and afterward extensively compare the files. For the text files, use diff or vimdiff. For the PDFs, just look closely.

Finally, do a comparison with yet another binning scheme on the same data to make sure that you really can do comparisons with multiple binning schemes, and everything will accumulate in a different directory without any problem.

One last thing: in the new `compareMAPElitesBinningScheme.bat` file you should probably add `io:false` and `netio:false` to really make sure nothing in the original archive will be changed, though you'll still want to write results for the other archive, essentially ignoring these settings with respect to the new archive you are making.

**Comment by schrum2** [comment]
In addition to the issues above, I think it might be easy to speed this experiment up using multi-threading, so talk to me about that when you get a chance.
