### ISSUE TITLE
Create batch files for SZ Tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#67]
Make some batch files for launching SZ Tetris with the best approaches from:
https://github.com/schrum2/MM-NEAT/tree/master/batch/Experiments-2018-NewTetris

Specifically, focus on Convolutional nets with shallow depth. The files 
Tetris-HyperNEAT-ConvolutionDepth1Width1Extra.bat	and
Tetris-HyperNEAT-ConvolutionDepth1Width4Extra.bat 

Make a new batch subdir for them, but change the batch files to run SZ Tetris.

**Comment by leg2015** [comment]
Added the batch files for SZ tetris and CNNs. Also ran some experiments with them but can't view the results because gnuplot is still broken on my mac.

**Comment by schrum2** [comment]
Now make batch files for CNN depths from 2 to 4 and check them too.

**Comment by schrum2** [comment]
Regarding gnuplot, try the following in a terminal:
First
brew uninstall gnuplot
Then
brew install gnuplot –with-x11 –with-pdflib-lite –with-cairo –with-wxmac

Once you do this, the built-in scripts that generate PDFs should work. This approach worked on the Mac I sometimes use.

**Comment by schrum2** [comment]
Also try batch files with weight sharing: convolutionWeightSharing parameter

**Comment by leg2015** [comment]
I added depths up to 4 for both widths of 1 and 4. I also created weight sharing batch files for D1W1 and D1W4. I can create more if need be too.

**Comment by schrum2** [comment]
Here are the plots from running your batch files with the TWEANNGenotype.smallerGenotypes = true; line in MuLambda commented out. First, for Convolution (finished):
[Tetris-HybrIDSZConvolutionDepth1Width1Extra0_parents-Game Score.pdf](https://github.com/schrum2/MM-NEAT/files/1797518/Tetris-HybrIDSZConvolutionDepth1Width1Extra0_parents-Game.Score.pdf)

And then for full HyperNEAT (still running, but past the HybrID switch point at 100 gens):
[Tetris-HybrIDSZHNeatExtra0_parents-Game Score.pdf](https://github.com/schrum2/MM-NEAT/files/1797520/Tetris-HybrIDSZHNeatExtra0_parents-Game.Score.pdf)

The score doesn't completely tank in either case, but there is a bit of a drop, and somehow I'm not entirely convinced that it works. Therefore, I actually would like you to do some testing and hopefully make some unit tests confirming that this whole HybrID switch thing actually works correctly. Hopefully our discussion yesterday will guide you in verifying this.

Something else that should in theory help you is a parameter deterministic. I will commit a batch file with deterministic:true in a moment, but this doesn't seem to work fully either, since it has to be defined in a special way for every domain we evolve in. It's purpose it to make evaluations deterministic, which in Tetris would mean that every agent uses the same series of "random" blocks, and would thus earn the same score on every evaluation. A consequence of this is that the fitness plot should only increase, which would remove the ups and downs (because selection is elitist). However, this does not happen. In any case, it might be a good idea to fix the deterministic setting for Tetris first.

**Comment by leg2015** [comment]
Finally got batch files to run on my mac. Had to hard code the runNumber and randomSeed to make it happy though, but not running large batches yet so that's okay for now. Could have been the same issue with the tower of power because the error was this weird trouble parsing parameter tokens error: 
java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at edu.southwestern.parameters.Parameters.getLogFilename(Parameters.java:998)
	at edu.southwestern.parameters.Parameters.initializeParameterCollections(Parameters.java:75)
	at edu.southwestern.MMNEAT.MMNEAT.<init>(MMNEAT.java:294)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:977)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:963)
Problem parsing parameter tokens

**Comment by schrum2** [comment]
For a Mac you need to change batch to bash by changing %1 to $1 etc. Still,
hard coded numbers are fine for now.

**Comment by leg2015** [comment]
I added those changes and it still had the weird error but it's not a big deal for now.

**Comment by schrum2** [comment]
This thread kind of went off in a different direction. The batch files do exist though, so I'm closing.
