### ISSUE TITLE
Comparing objective evolution to MAP-Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#670]
Somewhat similar to #669 , we need a way of comparing objective evolution to MAP-Elites. However, I don't think that this can be done after the completion of the run. This information has to be tracked during the objective based evolution. Basically, there needs to be a boolean parameter called "trackPseudoArchive" that when true, makes any objective evolution approach (NSGA-II or CMA-ES) store every solution that is produced in an archive using whatever binning scheme is defined for MAP-Elites. Whenever the next generation is produced, it tries to add all new offspring to the archive.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/120820487-37262380-c51a-11eb-8ef0-c71a43dd33b6.png)
Sphere function results for NSGA2 and MAP Elites on 200 NSGA2 generations

**Comment by MBatt1** [comment]
While I don't have more completed run results for comparison, I have created 8 batch files in `batch\ObjectiveEvolutionPseudoArchive` that have two files per game (Mario, MegaMan, Lode Runner, and Zelda), 1 for running NSGA2, and one for running CMA-ES. While the parameters are arbitrarily copied from other batch files to stay simple, I ran them all until I could see the maximum, QD, and filled bins increasing, and made sure all the archive output folders were appropriately being filled with images and xml/txt files.
