### ISSUE TITLE
Command line params for CPPNComplexityBinMapping's num neurons and links

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#675]
I've been running PictureTargetTask for a long time with CPPNComplexityBinMapping and the results are definitely interesting. I think it might be worth making the MAX_NUM_NEURONS and MAX_NUM_LINKS larger, so I think it's time to make these into command line parameters. 

Once that exists, you can launch really long runs that allow up to 50 neurons and 100 links

**Comment by annazwicker** [comment]
Added two command line parameters, maxNumNeurons and maxNumLinks, that will replace the hard coded values in CPPNComplexityBinMapping.  This required the addition of a constructor in CPPNComplexityBinMapping to initialize MAX_NUM_NEURONS and MAX_NUM_LINKS.  PictureTargetTask is currently running with the altered version of CPPNComplexityBinMapping.

**Comment by annazwicker** [comment]
From skull3:
![0 7869457274328053-Neurons 29 links 64](https://user-images.githubusercontent.com/82399865/121406968-68d92900-c924-11eb-95a9-7c692aeb6499.jpg)
![Uploading 0.7817342953996668-Neurons[32]links[53].jpg…]()

From skull 4:
![0 786092538133-Neurons 43 links 67](https://user-images.githubusercontent.com/82399865/121407067-8ad2ab80-c924-11eb-8811-63d606fb73c4.jpg)
![0 79162291438291-Neurons 37 links 81](https://user-images.githubusercontent.com/82399865/121407090-90c88c80-c924-11eb-87bf-09e483324c12.jpg)
![0 791917015376262-Neurons 49 links 91](https://user-images.githubusercontent.com/82399865/121407113-96be6d80-c924-11eb-85f4-984cd43769d2.jpg)

Conducting another run with maxGens set to 100,000,000
