### ISSUE TITLE
Use fitnessSaveThreshold for GAN level evolution in MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#677]
Currently, GAN level evolution saves images of all evolved levels. The PictureTargetTask uses a "fitnessSaveThreshold" parameter so that only sufficiently fit artifacts are saved. Make all of the GAN level evolution tasks use this as well (Zelda, Mario, Mega Man, Lode Runner). It could greatly reduce logging.

**Comment by MBatt1** [comment]
I tested it with various numbers on all 4 games and was able to limit the images generated to only be of a certain fitness. XML files and TXT files generate like normal still.
