### ISSUE TITLE
CMA-ME Line Mutation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#678]
This looks like it wouldn't be too complicated to implement

Add a command line parameter, "meLineMutationRate" with a default value of 0.0. Setting it to a positive value will make the line mutation possible, and setting it to 1.0 will mean that only line mutation is done instead of the standard MAP-Elites mutation.

The code you'll be changing is the `mutate` method in the `BoundedRealValuedGenotype` class. Currently, the code either always does `PolynomialMutation` or always does `PerturbMutation`. Whichever one of these is used will be treated as "normal" mutation. You'll add an `if`-check here that uses `perform()` method of a new mutation you make called `MAPElitesLineMutation`. 

`MAPElitesLineMutation` will extend `RealMutation` and can only work when MAP-Elites is being used, since it will have to grab access to the archive via the `ea` by casting it to an instance of `MAPElites`. The mutation operation uses the archive to randomly select some other occupied bin, so it can carry out this operation:
![image](https://user-images.githubusercontent.com/8397236/121072677-1fa79e80-c797-11eb-8116-94429c983e2c.png)

Note that whenever you compute N(0,1) in this code you can use `MMNEAT.weightPerturber.randomOutput()`. For the two sigma parameters, hard code `SIGMA1` and `SIGMA2` as public static final values in the new class with whatever default values they used in the paper. Note that the x - y in the code is vector subtraction, and this method returns a vector (a double array).

**Comment by MBatt1** [comment]
Look at pyribs code

**Comment by MBatt1** [comment]
ME-Line original paper: https://arxiv.org/pdf/1804.03906v1.pdf
Linked source code: https://github.com/resibots/vassiliades_2018_gecco

**Comment by MBatt1** [comment]
ME-Line is fully set-up I believe, but should be tested

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122066365-4e85cc00-cdb8-11eb-9e7a-1a484b25475d.png)
Sphere function optimization normal MAP Elites vs 1.0 ME-Line rate

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122067138-f13e4a80-cdb8-11eb-8b24-9c748cb4d534.png)
Lode Runner Connected, Ground, and Ladders on 20 Level GAN

**Comment by schrum2** [comment]
These results look great! Just to be sure, go ahead and run on Rastrigen too, then close.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122232981-4ba2de00-ce81-11eb-971c-10f2280ae10f.png)
Rastrigin function optimization, Normal MAP-Elites vs ME-Line
![image](https://user-images.githubusercontent.com/53229958/122233093-65442580-ce81-11eb-9383-094388d20abd.png)

**Comment by MBatt1** [comment]
Filled more bins, found a slightly higher maximum, but had roughly the same QD scores
