### ISSUE TITLE
Deep CNNs evolved like cascade correlation networks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#68]
HyperNEAT has trouble evolving deep CNNs, but perhaps it could be done incrementally.

Using MSS coordinates, we could add hidden layers to the CNN one step at a time via a mutation (or staged/planned progression) to gradually increase the depth and/or width. Since D1W1 networks already work well (in Tetris), we would be starting from a good place before building on the existing good performance.

In order to maintain established good performance, we should adopt the approach used in cascade correlation networks. Specifically, although there will be new connections through the net hidden layer that reach the final output, we should also maintain previous connections from previous hidden layers to the final output. This should prevent loss of performance when intermediate layers are added.

**Comment by DevonFulcher** [comment]
Could you point me in the right direction for this one?

**Comment by schrum2** [comment]
First, make getSubstrateInformation(HyperNEATTask hnTask) and getSubstrateConnectivity(HyperNEATTask hntask) methods in HyperNEATCPPNGenotype. Make the getSubstrateGenotype method in HyperNEATCPPNGenotype use these new methods instead of getting information from hnt directly.

Then make a new genotype class called HyperNEATCPPNAndSubstrateArchitectureGenotype that extends HyperNEATCPPNGenotype. Its constructor should require a substrate architecture (like the custom one you made previously (we may change this later). Then, in this new class, override the newly made getSubstrateInformation and getSubstrateConnectivity methods.

**Comment by DevonFulcher** [comment]
all of these MM-NEAT/src/test/java/edu/southwestern/networks/hyperneat/FlexibleSubstrateArchitectureTest.java pass individually but fail when run at the same time. Could this be a problem with the test or with the code?

**Comment by schrum2** [comment]
This usually means that something is not being properly reset between runs. Calling MMNEAT.clearClasses() at the end and then loadClasses() at the start each time is definitely needed, as it re-initializing the parameters. I suppose you may also need to run the following code:
```
EvolutionaryHistory.archetypes = null;
EvolutionaryHistory.setInnovation(0l); // reset
```
at the start, and then call the following after loadClasses

```
EvolutionaryHistory.initArchetype(0);
```

**Comment by DevonFulcher** [comment]
The HyperNEATCPPNAndSubstrateArchitectureGenotype class has now been tested and works at storing HyperNEAT hiddenArchitecture and allSubstrateConnectivity as a child of HyperNEATCPPNGenotype.

**Comment by DevonFulcher** [comment]
Now that we have untested methods that return a new HyperNEAT nn with an added layer, the next step is to make sure that these methods work with global coordinates. This will be done by hard coding a switch point and ensuring that the network looks as expected afterward. Later we can think about a way to define a more intelligent switch point and a way to allow for multiple switch points. Also, we will allow for cascade expansion with MSS.

**Comment by DevonFulcher** [comment]
The performance of HN with cascade correlations will be compared against standard HN with a definition that is equivalent to the HN network after the cascade correlations switch point. This custom definition is in a class called HiddenSkipsHidden

**Comment by DevonFulcher** [comment]
Next, we will allow for cascade expansion with MSS.

**Comment by schrum2** [comment]
Note that allowing MSS with changing architectures requires us to also change the CPPN's output neurons. The TWEANNGenotype has a method that adds output neurons, but only to the end of the output neuron list. What we really need is a way to insert output neurons between other output neurons, but this may actually be difficult given the sorting convention for the innovation number on output neurons.

**Comment by DevonFulcher** [comment]
The issue of SubstrateInformation being filled with null/0 values persists. Changing the data members to being non-final did not solve this issue.

**Comment by DevonFulcher** [comment]
After maven compiling it actually seems to work.

**Comment by DevonFulcher** [comment]
Now, we have to work on integrating MSS and think of an intelligent switch point.

**Comment by DevonFulcher** [comment]
I wrote a short unit test for cascade expansion with MSS in TWEANNGenotypeTest but all I could think to test is printing out the nodes list and visually inspecting it. I expanding with a 1 width layer then a 4 width layer with and without leo. I am confident that it works correctly. I left the commented out print statements in the test. I will start an evaluation and post watch after maven is finished installing.

**Comment by schrum2** [comment]
To test, loop through the nodes list and assertEquals that the innovation numbers and ntypes have the expected values

**Comment by DevonFulcher** [comment]
I don't think this currently works with MSS and extra HyperNEAT links. I will fix that.

**Comment by DevonFulcher** [comment]
Now that the visualization works there are three things that needed to be attended to before this issue is closed: the behavior must be tested, cascade must be fixed with extra/MSS, and intelligent switch points must be applied.

**Comment by DevonFulcher** [comment]
This issue is closed! Cascade with MSS or global coordinates. If using MSS numIncomingLinksForCascadeExpansion determines how many links are added to a new cppn output on cascade expansion.
