### ISSUE TITLE
Make new MegaMan training sets excluding the water level

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#681]
Will remove the water tunnel from generating

**Comment by MBatt1** [comment]
would be excluding level 9

**Comment by schrum2** [comment]
After making the training sets, I would also want you to train new GANs. This would mean training both a OneGAN and training 7 GANs for each segment type required by the MultiGAN. Of course, the MegaMan GAN folder is getting a bit crowded. Just make sure each of these files has a good prefix, like "NoWater9MegaMan"

**Comment by schrum2** [comment]
Make sure the training sets are actually "sets", meaning that duplicate segments are excluded.

**Comment by MBatt1** [comment]
@cappsb What's the process for getting a json version of a selection of levels? I'm a bit lost on where to actually convert them.

**Comment by cappsb** [comment]
Depends on what you mean exactly @MBatt1. Do you text-based (VGLC) --> list of lists? MMLV --> list of lists? Or do you mean taking text-based and performing the "sliding window" I talked about in my presentation? All of those are in MegaManVGLCUtil. All of them are accurately named except for the sliding window method, poorly named upAndDownTrainingData. Also, unused methods are labeled in the JavaDoc. It's pretty messy code because we wanted to preserve backward compatibility so feel free to message me on slack for details.

**Comment by MBatt1** [comment]
Accidentally made it output whole levels, need to extract the individual segments instead

**Comment by MBatt1** [comment]
In MegaManConvertMMLVToJSON, the main method allows for json files to be created based on a selection of levels

**Comment by MBatt1** [comment]
Currently files are generated properly, however the way that MegaManVGLCUtil.upAndDownTrainingData() appears to work puts all levels into the first json variable, not sorting them at all. This makes the oneGAN possible, but the sevenGANs cannot be properly generated yet. 

The current oneGAN was beofre removing the code that added duplicates, so it needs a new json and needs to be re-run.

**Comment by schrum2** [comment]
I need to help you wrap this issue up on Monday

**Comment by schrum2** [comment]
Definitely want this done before SCOPE ends

**Comment by MBatt1** [comment]
After removing duplicate corners from the jsons, there was still an issue with something in the training set throwing off the dimensions. This was due to some strange interaction with a timer in the mmlv reader class, which now appears to be resolved, and I am training a new OneGAN, then will attempt a SevenGAN if the OneGAN works

**Comment by MBatt1** [comment]
MegaManSevenGANDownNoWater9_5_Epoch5000.pth
and
MegaManSevenGANLowerRightCornerNoWater9_5_Epoch5000.pth
contain null space in generated levels

**Comment by MBatt1** [comment]
I have added some or checks to ensure that levels 1-10 are properly read, however these changes very likely will cause issues for parsing other levels in the future, and have comments noting why they are there.

GANs are being re-trained and hopefully will work properly

**Comment by MBatt1** [comment]
Seven GAN works perfectly, and the One GAN is being trained now but should not have any problems. Assuming that GAN works properly, this issue is done
