### ISSUE TITLE
Translate the center coordinate for Picbreeder images

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#682]
I've thought of another way to make Picbreeder images more diverse. We can translate the location of the center point. Basically, in `GraphicsUtil.get2DObjectCPPNInputs` you can add `deltaX` and `deltaY` parameters and simply add them to the x/y coordinates of `finalPoint`. However, this requires you to add additional parameters in a sequence of other methods leading back up to `imageFromCPPN`.

Basically, our current images are drawn as if the delatX and deltaY are both 0, so we are simply expanding the possibilities. Of course, the question is where should these delatX and deltaY values come from? We can modify the `EnhancedCPPNPictureGenotype` to include two additional numbers in the BoundedRealValuedGenotype, and make them correspond to these values. We would need to decide a scale, which would mean an additional command line parameter, called "imageCenterTranslationRange" which would be a positive number. Then, the range for both deltaX and deltaY would be negative imageCenterTranslationRange to positive imageCenterTranslationRange.

**Comment by annazwicker** [comment]
Picbreeder works when the parameters "picbreederImageTranslationX" and "picbreederImageTranslationY" are set to different values.  The images move horizontally and vertically accordingly.
