### ISSUE TITLE
PictureTargetTask with enhanced CPPNs genotype

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#683]
After completing #682 , try running `PictureTargetTask` with the setting:
`"genotype:edu.southwestern.evolution.genotypes.EnhancedCPPNPictureGenotype"`
(Note that this is still just using the `CPPNComplexityBinMapping`)

Basically, I want to see if being able to scale, rotate, and translate the image bounds makes it easier to find a skull-like image.

By the way, also change the `log` and `saveTo` parameters so that the name very distinctively clarifies which runs use the enhanced CPPN genotype.

**Comment by annazwicker** [comment]
Currently conducting a second run of PictureTargetTask using the enhancedCPPNPictureGenotype.  Need to post results when finished.

**Comment by schrum2** [comment]
I definitely want to see results from our preliminary run posted here after it has executed for longer. So far, I am not impressed, and I actually wonder if the code works the way it is supposed to, but we'll see if the results look better after the weekend.

**Comment by annazwicker** [comment]
Preliminary results are below from iteration 50000.  While PictureTargetTask with enhancedCPPNPictureGenotype ran over the weekend and saved the correct images, the images displayed were incorrect.  This error was fixed and PictureTargetTask is re-running.  The pictures below are from the new run of PictureTargetTask and appear to use scale, rotation, and translation.
![0 632468126550521-Neurons 15 links 46](https://user-images.githubusercontent.com/82399865/121946419-876f6380-cd1a-11eb-987f-c96ee659f92c.jpg)
![0 70401406464488-Neurons 19 links 51](https://user-images.githubusercontent.com/82399865/121946449-8fc79e80-cd1a-11eb-98bb-0088eece6924.jpg)
![0 6004442766200289-Neurons 22 links 60](https://user-images.githubusercontent.com/82399865/121946461-935b2580-cd1a-11eb-9b1c-bd8ae476b278.jpg)
![0 6466359407595441-Neurons 12 links 36](https://user-images.githubusercontent.com/82399865/121946472-95bd7f80-cd1a-11eb-9cc6-76274988e14e.jpg)
![0 6536441466397376-Neurons 12 links 35](https://user-images.githubusercontent.com/82399865/121946488-99e99d00-cd1a-11eb-91c3-87a0cb4df6c8.jpg)
![0 6603374005440015-Neurons 26 links 68](https://user-images.githubusercontent.com/82399865/121946503-9c4bf700-cd1a-11eb-85b0-1d63070b2ad4.jpg)
![0 6787628586486294-Neurons 9 links 22](https://user-images.githubusercontent.com/82399865/121946513-9fdf7e00-cd1a-11eb-88ef-b1e73025cfc1.jpg)

**Comment by annazwicker** [comment]
The following results are from iteration 100000.  
![0 70260869279134-Neurons 17 links 52](https://user-images.githubusercontent.com/82399865/122066941-c653f680-cdb8-11eb-9a88-94f72dec7e56.jpg)
![0 609457729623571-Neurons 31 links 76](https://user-images.githubusercontent.com/82399865/122066954-c9e77d80-cdb8-11eb-8b8f-af6d93e20d69.jpg)
![0 699110091404553-Neurons 40 links 83](https://user-images.githubusercontent.com/82399865/122066981-cf44c800-cdb8-11eb-942e-7fd9d9f674e6.jpg)
![0 701046669025744-Neurons 20 links 60](https://user-images.githubusercontent.com/82399865/122066999-d2d84f00-cdb8-11eb-93b1-ab3be92552cf.jpg)
![0 706738293401391-Neurons 12 links 29](https://user-images.githubusercontent.com/82399865/122067017-d66bd600-cdb8-11eb-92e0-ef7998b5ddf1.jpg)
![0 710104277981019-Neurons 17 links 40](https://user-images.githubusercontent.com/82399865/122067044-dbc92080-cdb8-11eb-8a37-3cdc68181d17.jpg)
![0 714635502108282-Neurons 15 links 42](https://user-images.githubusercontent.com/82399865/122067063-dff53e00-cdb8-11eb-91d9-fa85bf5dc524.jpg)
![0 6415073471363036-Neurons 27 links 81](https://user-images.githubusercontent.com/82399865/122067076-e2579800-cdb8-11eb-888f-a8c549b2a60f.jpg)
![0 6509310533414827-Neurons 38 links 86](https://user-images.githubusercontent.com/82399865/122067082-e4215b80-cdb8-11eb-8dce-1f1a37301094.jpg)
![0 6495598079112608-Neurons 31 links 81](https://user-images.githubusercontent.com/82399865/122067097-e7b4e280-cdb8-11eb-9bf3-8184196f68c5.jpg)
![0 6575620248982318-Neurons 49 links 99](https://user-images.githubusercontent.com/82399865/122067101-e8e60f80-cdb8-11eb-9de0-46e938c5fd64.jpg)
![0 6617506296090742-Neurons 24 links 75](https://user-images.githubusercontent.com/82399865/122067116-ebe10000-cdb8-11eb-857c-1e0b0be9051c.jpg)
![0 6663545697769366-Neurons 15 links 50](https://user-images.githubusercontent.com/82399865/122067128-ef748700-cdb8-11eb-98bc-29924cf5d2a1.jpg)
![0 6831755371034851-Neurons 16 links 51](https://user-images.githubusercontent.com/82399865/122067153-f56a6800-cdb8-11eb-8686-6c00b1f33ede.jpg)
![0 6912503970256163-Neurons 29 links 80](https://user-images.githubusercontent.com/82399865/122067172-fa2f1c00-cdb8-11eb-9862-927f3f0b22ad.jpg)
