### ISSUE TITLE
Evolved Animations with fixed or changing translation of the center point

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#684]
When working on the translation point issue #682 I did a quick fix for animations by just setting deltaX and deltaY to 0 so that animations do not allow center point translations. However, we should allow this ... both fixed values, and changing values. Do the following in `AnimationUtil`:

Add deltaX and deltaY parameters to this method:
`public static BufferedImage[] imagesFromCPPN(Network n, int imageWidth, int imageHeight, int startTime, int endTime, double[] inputMultiples, double scale, double rotation) `

Inside the method, when you call `images[i-startTime] = GraphicsUtil.imageFromCPPN`, use `deltaX` and `deltaY` instead of 0 and 0.

In `AnimationBreederTask`, in the method
`private BufferedImage[] imagesFromCPPN(T cppn, int width, int height, int startFrame, int endFrame, double[] inputMultipliers)`
Add the two new command line parameters for picbreeder image translation x/y, and sent them to the `imagesFromCPPN` call.

After all of this, there is still some work to be done, but I'll do that in the next post in this thread.

**Comment by schrum2** [comment]
Currently, in the `imagesFromCPPN` method of `AnimationUtil` there is a section:
`if(Parameters.parameters.booleanParameter("animateWithScaleAndRotation"))`

Change the name of that parameter to "animateWithScaleRotationTranslation" and change the body of the if statement as follows:
1. When you call `get2DObjectCPPNInputs`, the deltaX and deltaX are still 0 ... that is ok. In fact, remove the comment that makes a big deal about this.
2. After `scale` and `rotation` are changed at the end of the if, change `deltaX` and `deltaY` in a similar manner. You will need to define extra constants referring to indices in the output array: `CPPN_OUTPUT_INDEX_DELTA_X` and `CPPN_OUTPUT_INDEX_DELTA_Y`. Also, multiply by the parameter for image translation range.

You also need to make some additional changes to `AnimationBreederTask`:
1. In `outputLabels()`, add "deltaX" and "deltaY" in the appropriate case.
2. In `numCPPNOutputs()`, change the name of the command line parameter being used, and increase the number of outputs accordingly (add 4 instead of 2)

**Comment by annazwicker** [comment]
All changes have been made and AnimationBreederTask successfully runs and appears to translate the center coordinates as it animates.  Would it be possible to make zentangles with AnimationBreederTask (might be a bit much...)?
