### ISSUE TITLE
Make proper python requirements txt for easy setup

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#685]
We recently dealt with a bunch of hassles getting the right versions of various Python modules to install. This should not be so hard. Most GitHub projects out there have a `requirements.txt` file that makes sure the correct versions of all modules are installed. Read here: https://www.idkrtm.com/what-is-the-python-requirements-txt/

Please make a file like this for our project. This will mean having the pip installed version of PyTorch instead of the Anaconda install, but the rest should be straight forward. Here is a screenshot of the version numbers I have on my system, which is able to run the current code:

![image](https://user-images.githubusercontent.com/8397236/121709437-2cc9d380-ca9e-11eb-8d26-6394c5e2035e.png)

**Comment by schrum2** [comment]
Also, after making this, correct/update the version numbers in TUTORIAL.md and also put information there about how to run the pip install command with the requirements.txt file.

**Comment by MBatt1** [comment]
Is set up, but should be used on a fresh machine to make sure it actually works

**Comment by schrum2** [comment]
Add `opencv-python`
