### ISSUE TITLE
Experiments Comparing Binning Schemes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#686]
As part of 8aa9013c3603b2f07027be655b4743ca1d55737a you made a directory of batch files "Experiments-2021-CompareBinning" for comparing different MAP Elites binning schemes. Here is a list of all the things you should be testing in that file:

* Mario
  * DecorateNSLeniency
  * DistinctNSDecorate
  * KL Div (but on what levels? Wait until #630 is closed)
  * Novelty? but what to combine with?
* Zelda
  * DistinctBTRooms
  * WallWaterRooms
  * Novelty? but what to combine with?
* Lode Runner (all On20GAN)
  * GroundTreasureEnemies (PercentGroundNumGoldAndEnemies)
  * PercentConnectedGroundAndLadders
  * KL Div (but on what levels? Wait until #630 is closed)
* Mega Man (all MultiGAN)
  * DistinctVerticalAndConnectivity  
  * NoveltyVerticalAndConnectivity

Use the `launchMultiple.bat` batch file to run batches of 10 for each of these. As those batches of 10 complete, back up the results to Google Drive.

**Comment by MBatt1** [comment]
Adding two new KL Divergence binning schemes, one for Mario, and one for Lode Runner:
* Lode Runner level 2 and level 108:
![Level 2](https://user-images.githubusercontent.com/53229958/122106605-c3203100-cddf-11eb-9536-d787e6b0dd27.png)
![Level 108](https://user-images.githubusercontent.com/53229958/122106623-c74c4e80-cddf-11eb-9e41-e7d972fb6232.png)

* Mario level 2-1 and level 6-2
![image](https://user-images.githubusercontent.com/53229958/122106951-29a54f00-cde0-11eb-8483-48d605484811.png)
![image](https://user-images.githubusercontent.com/53229958/122107001-3629a780-cde0-11eb-8fcb-68653ec90af1.png)

**Comment by MBatt1** [comment]
Currently uploading more, but here are some of the current results from comparing what data we have in the google drive
![image](https://user-images.githubusercontent.com/53229958/122588123-53e74e80-d024-11eb-8b74-96d1762e02f5.png)

**Comment by schrum2** [comment]
It is definitely hard to remember what some of the numbers represent. Can you label parts of the sheet so it is clear what the source and target archives are? Also, clarify what is being divided by ... the total bins in the source archive or the target archive?

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122819015-7d5fde80-d29f-11eb-9311-a02f00a8f564.png)
This is the way things are compared, the top row is the original, the left column is what is being compared to

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122821124-11cb4080-d2a2-11eb-8479-6e6fb6d4659b.png)
Updated MAP Elites

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122821189-23144d00-d2a2-11eb-8ad7-5f0c91c153eb.png)
ME-Line

**Comment by MBatt1** [comment]
Since finishing the Latent partitioning scheme, all 4 domains now also have a 2-slice latent partitioning scheme

**Comment by schrum2** [comment]
Unfortunately, most of the comparison results are probably invalid. Need to re-run them all with "parallelEvaluations:false" since many tasks actually pass information around about archive indices via global variables. At the very least, I know that Lode Runner does this, and I suspect others do too.

Also, change the batch file to use parallelEvaluations:false, and also put both a comment and a warning in the `CompareMAPElitesBinningSchemeExperiment` that says parallel is risky if information is passed around via global variables.

**Comment by MBatt1** [comment]
A warning has been added, old results have a "prelim_" prefix in google drive, and I have cleared the computers of results and am re-running comparisons

**Comment by schrum2** [comment]
For your result comparing script:
```
>>> filepath = u'\\\\?\\G:\\My Drive\\Research\\SCOPE Artifacts\\SCOPE 2021 MAP-Elites Comparison\\megamanmultigancomparebins\\DistinctVerticalAndConnectivity0\MegaManMultiGANCompareBins-DistinctVerticalAndConnectivity0_comparedTo_MegaMa
>>>
>>> with open(filepath, "r") as opened_file:
...     print(opened_file.readlines())
...
['Occupied Bins: 148\n', 'Occupied Bins Percent: 6.727273% (148/2200)\n', 'Surviving Bins Percent: 45.820435% (148/323)\n', 'QD Score: 25660.0\n', 'Maximum Fitness: 260.0\n']
>>>
```
Basically, if you can get an absolute path to a file, then you can prepend "\\\\?\\" to be able to open it (this is the escaped version of "\\?\"). Also, you may need `u` in front, as in `u"\\\\?\\"`

**Comment by schrum2** [comment]
Also, more info on this in case it is needed:
https://bugs.python.org/issue18199

**Comment by schrum2** [comment]
You should be able to close this on Monday based on whatever results you have

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/124648913-71f2e280-de5d-11eb-8895-82310f161187.png)
![image](https://user-images.githubusercontent.com/53229958/124648969-833bef00-de5d-11eb-999e-c96556a22f4c.png)
![image](https://user-images.githubusercontent.com/53229958/124648983-8800a300-de5d-11eb-8806-89dfc1e0a760.png)

Results of compared binning schemes and the surviving bin percentages
