### ISSUE TITLE
Animations: Turn of rotations, scaling, and translation from interface

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#689]
Whenever "animateWithScaleRotationTranslation" is true, I want the AnimationBreederInterface to have a stack of four checkboxes in the top-right that are checked by default, but can be unchecked. They are for AnimateRotation, AnimateScale, AnimateDeltaX, and AnimateDeltaY.

As with all other interface features, each checkbox will be directly associated with a correspondingly named command line parameter. If a box is unchecked, then it means that in the `imagesFromCPPN` method of `AnimationUtil`, that corresponding value from the network will be ignored. This allows for components of the animation to be turned on and off.

**Comment by annazwicker** [comment]
New buttons have been added in AnimationBreeder which allow the user to turn on and off rotation, scale, deltaX, and deltaY.  They are stacked vertically alongside the stark button.  Buttons were added in AnimationBreeder, function changed in AnimationUtil.

**Comment by annazwicker** [comment]
The buttons for scale, rotation, deltaX, and deltaY are not displayed if animateWithScaleRotationTranslation is false.
