### ISSUE TITLE
Fair Starting Point for AutoEncoder and CPPN Complexity

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#690]
Currently, the `GaierAutoencoderPictureBinningScheme` and `CPPNComplexityBinMapping` both start at a weird place, because the initial population of generated networks can only go in one of the bins. For CPPNs, all initial networks will have the same number of links and neurons. For the AutoEncoder, we currently initialize the loss to 1.0 since the auto encoder doesn't exist year.

For `CPPNComplexityBinMapping`, we could probably allow for a bit more fairness by allowing a variable number of initial links. I thought that using the `fs` (feature selective) option might help with this, but that would just change the starting count for everyone, not create variety. Maybe some portion of networks in the initial archive need some random mutations?

For `GaierAutoencoderPictureBinningScheme` I need to look more closely at what Gaier did, but I think the solution is to generate 100 images, then train the autoencoders, and then add the 100 to the archive (though some may not qualify). That's a simple idea, but requires some special cases in the code, that will be a slight hassle to write.

**Comment by schrum2** [comment]
One way to diversify the starting population for any evolutionary algorithm, and not just MAP-Elites, is to randomly mutate the initial population a bit.

Make a command line parameter "randomInitialMutationChances" with a default value of 0 (which would correspond to what we currently do with no mutations). Then go to `PopulationUtil` and find the `initialPopulation`. The `else` case creates a new random population. It adds them all to the `parents` list, and then there is a chunk of code that randomizes activation functions `if(CommonConstants.netChangeActivationRate > 0)`.

AFTER THAT, loop "randomInitialMutationChances" times, and within that loop have an inner loop through each member of `parents` that calls mutate on each member of the population.

**Comment by schrum2** [comment]
`integerOptions.add("randomInitialMutationChances", 0, "No mutations intially.");`
The description portion of this is supposed to tell what the parameter does so that people will know how to set it. Change it.

Also, test if this works by setting randomInitialMutationChances to 10 with the `CPPNNeuronCountBinLabels` and launching the run. If it works, then the `iteration0` folder should have several images in it instead of just 1. If that works, then add this setting to ALL of the PictureTargetTask batch files #691

**Comment by annazwicker** [comment]
Set` randomInitialMutationChances` to 10 inside of `ScreamCPPNNeuronCountBinLabelsRegularGenotype.`  `Iteration0` inside of `snapshots` has 7 images rather than 1.  `randomInitialMutationChances` will be added to all batch files and initialized to 10.

**Comment by schrum2** [comment]
It looks like the randomInitialMutations isn't quite good enough in assuring a large-ish starting archive size. Therefore, I think we need to return to the earlier idea from the original post:

"For GaierAutoencoderPictureBinningScheme I need to look more closely at what Gaier did, but I think the solution is to generate 100 images, then train the autoencoders, and then add the 100 to the archive (though some may not qualify). That's a simple idea, but requires some special cases in the code, that will be a slight hassle to write."

I'm going to take a look at this first. I'll let you know if there is more to do afterward

**Comment by schrum2** [comment]
I added code to train the initial autoencoder, and that works. There is an archive of 100 starting images, and the autoencoder takes a while to train on them. However, after all of that, when the autoencoder places them in the archive they still all reduce to just one image! I guess the initial images are so boring that the variance in loss values is insignificant, resulting in them all being binned the same way. I feel that this warrants a little more investigation, but ultimately it is fairly disappointing. For now, this new  time-consuming start-up feature is disabled by setting trainInitialAutoEncoder:false by default.

**Comment by schrum2** [comment]
When using the autoencoder, iteration0 now actually has a lot of images in it, as intended. This works now.
