### ISSUE TITLE
Batch Files for PictureTargetTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#691]
Create a directory in the `batch` subdir called `Experiments-2021-PictureTarget` and add several batch files to it. Look at files in neighboring directories to get a sense of what is normal. You can right-click a batch file and open/edit in Notepad++. The launch command is similar to the list of command line params you see in the main method of PictureTargetTask, but you have to use the `cd` command first and launch `java` with the right `jar` file. Once again, compare with other batch files.

Ultimately, you need to make batch files for these cases. Note that the majority of the contents of these files should be the same (and taken from PictureTargetTask). Only change them enough to distinguish these 4 cases:

- `CPPNComplexityBinLabels` using regular genotype
- `CPPNComplexityBinLabels` using `EnhancedCPPNPictureGenotype`
- `GaierAutoencoderPictureBinLabels` using regular genotype
- `GaierAutoencoderPictureBinLabels` using `EnhancedCPPNPictureGenotype`

Be sure to set log and saveTo appropriately in all cases.

**Comment by annazwicker** [comment]
New directory, Experiments-2021-PictureTarget inside the batch directory.  Contains four new batch files, two using the CPPNComplexityBinLabels (one using the EnhancedCPPNPictureGenotype, one using the regular genotype) and two using the GaierAutoencoderPictureBinLabels (one using the EnhancedCPPNPictureGenotype, one using the regular genotype).  Log and saveTo are set to skullWithCPPNBinLabelsRegularGenotype, skullWithCPPNBinLabelsEnhancedCPPNGenotype, skullWithGaierBinLabelsRegularGenotype, skullWithGaierBinLabelsEnhancedCPPNGenotype.

**Comment by schrum2** [comment]
`GaierAutoencoderPictureBinLabelsEnhancedCPPNGenotype.bat` is empty, so need to fix this.

Also, the need to be fixed to work with the renamed BinLabel classes. Basically, you need to verify they work by first Maven installing to create the batch file, and then attempting to actually run it.

Finally, you need to also add two more batch files for the new `CPPNNeuronCountBinLabels`

**Comment by annazwicker** [comment]
Conducting two runs using the new batch files.  Both runs are using the neuron binning scheme, one using the EnhancedCPPNGenotype and the other using the regular genotype, neither training/using the autoencoder.

**Comment by schrum2** [comment]
`ColorCPPNComplexityBinLabelsEnhancedCPPNGenotype.bat`
Gives this error:
`Exception in thread "main" java.lang.IllegalArgumentException: string of log must equal string after hypen in saveTo`

`ColorCPPNComplexityBinLabelsRegularGenotype.bat`
Gives this error:
`Could not load image: PicbreederRainbow.jpg`

At this point I stopped checking, but you should attempt launching ALL of these batch files (even ones you have already checked) just to make sure that they actually run.

**Comment by annazwicker** [comment]
All batch files run successfully!  Missing parameters were added where needed and the parameter `randomInitialMutationChances` was added and set to 10 in every batch file.  Six batch files exist for the skull64 using the `GaierAutoencoderPictureBinLabels `binning scheme, `CPPNComplexityBinLabels`, and `CPPNNeuronCountBinLabels `(each binning scheme has two batch files, one using the `EnhancedCPPNPictureGenotype `and the other using the regular genotype.  Two batch files also exist for theScream256, both of them using the `CPPNNeuronCountBinLabels`, one using the `EnhancedCPPNPictureGenotype `and the other using the regular genotype.  Four batch files exist for a colored image, PicbreederRainbow (generated by Picbreeder), using the `CPPNComplexityBinLabels` and `CPPNNeuronCountBinLabels` binning schemes (each binning scheme has one batch file using the `EnhancedCPPNPictureGenotype `and one using the regular genotype).
