### ISSUE TITLE
Verify Correct Polynomial Mutation

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#692]
Reference this paper:
https://www.iitk.ac.in/kangal/papers/k2012016.pdf

But also try to seek source code written by others for comparison.

**Comment by schrum2** [comment]
I'm pretty sure this code from jmetal is where mine comes from:
https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/operator/mutation/impl/PolynomialMutation.java
