### ISSUE TITLE
CMA-ME: Log the mean locations of each emitter

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#697]
Something that would be cool to see on the 2D plot of the archives would be a visual representation of where the mean points of each emitter are after each update, and how they move through the archive space. There could be a different color for each emitter, and lines could connect sequential mean values, but there could be a break in the line (or maybe a dotted line?) whenever the emitter has to reset.

I feel like this has potential to help us with new insights in troubleshooting, and it would probably look cool too.

**Comment by schrum2** [comment]
After chatting with you, I realized that actually logging the means themselves didn't make much sense, at least not for the sake of visualization. The idea was to visualize where the mean point was in the archive, but that only makes sense if you log the bin coordinates that the mean point would be located in.

Note that visualizing in this way probably only makes sense for binning schemes based on slicing up the solution vector, since nearby bins in the archive are also nearby in solution space. However, these results could end up very weird in some domains where bins that are far away in the archive are close in solution space. 

Still, let's figure out how to plot this stuff anyways ... could be useful.

**Comment by MBatt1** [comment]
Would be nice to track the path and have older segments become more transparent

**Comment by MBatt1** [comment]
Path is tracked, might want to use a more drastic fading effect on the trails. Would be nice to track restarts to prevent lines from being drawn when one occurs, however that would require extra logging

**Comment by MBatt1** [comment]
Also something to note is that the means aren't actually placed in the spot that would appear to be the mean, since discarded bins are a factor, and the displayed mean is only the mean of the last generation in the current logging cycle. It may be possible to track the mean at every point and then log the average of that though.

**Comment by MBatt1** [comment]
Since this is pretty much completely set up, besides what could be done in #708, it should be fine to close this. Instructions on how to use the scripts are at the top of each corresponding script
