### ISSUE TITLE
Simple Binning: Just Number of Neurons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#698]
I'm pretty sure that at one point I had a bug that effectively reduced the entire archive to relying only on the neuron count for binning. This was caused because the other dimension was always the same for every genome. However, it seemed to work well!

So, make some bin labels called `CPPNNeuronCountBinLabels` that depends ONLY on the number of nodes/neurons in the CPPN.

This is of course for the PictureTargetTask

**Comment by annazwicker** [comment]
The new class `CPPNNeuronCountBinLabels` also needs to be tested before conducting new runs of PictureTargetTask.

**Comment by annazwicker** [comment]
Testing runs successfully for `oneDimensionalIndex`

**Comment by annazwicker** [comment]
Conducting runs of PictureTargetTask using the new binning scheme `CPPNNeuronCountBinLabels`, one using the EnhancedCPPNPictureGenotype and the other using the regular genotype.
