### ISSUE TITLE
Multimodal CPPNs with global coordinates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#70]
MSS coordinates give better performance because the weight encoding can be different for each pair of layers, but this doesn't scale to deep architectures because it requires too many CPPN outputs nodes. Having CPPNs with multiple output modules using preference neurons might be a good tradeoff. Specifically, I can use global coordinates, and although these might not generalize across many layers, the number of distinct encoding styles might not need to be the maximum (effectively provided by MSS). In other words, let evolution decide which weight encoding module (of the CPPN) to use for each layer pairing, or even for each individual link in the substrate network.

Try with a fixed number of output modules first, then try with Module Mutation.

I think that Verbancsics may have already implemented something like this, based on a conversation I had with him, but I think it was only ever "published" as a poster with extended abstract at GECCO. I need to seek that abstract out, and follow up if necessary.

**Comment by schrum2** [comment]
Might be as easy as setting startingModes:2 (would create CPPNs with two neurons containing preference neurons ... maybe?)

**Comment by DevonFulcher** [comment]
I tested this MM-NEAT\batch\RLGlue-Tetris-Experiments\testingGlobalCoordinatesWithModules.bat batch file as derived from this MM-NEAT\batch\Experiments-2018-GECCO-Tetris\Tetris-HyperNEAT-SubCoordsConvolutionDepth4Width4None.bat batch file. Post watched and it seemed to work:
![screenshot 3](https://user-images.githubusercontent.com/24593113/40581798-05305648-6127-11e8-919b-27029f8164a9.png) Numerous of those grey coordinate boxes popped up in rapid succession. I assume this is an intentional parameter setting in the batch file but I do not know for sure if it is an error or not.

**Comment by schrum2** [comment]
The CPPN network looks correct. The weight visualization in the upper left looks incomplete, but I assume you took the picture while it was still animating. Maybe this works already?

You can leave an evolutionary run going for a while to test, but I recommend making the population a bit smaller (half of what was used in the CNN-HyperNEAT paper).

However, while that is running, I also want you to make a JUnit test and some kind of visualization mechanism to confirm correct functioning. For example, you could make an additional weight visualization panel that, instead of indicating the link weight, had distinct colors indicating which CPPN module encoded the weight.

**Comment by schrum2** [comment]
Note: The JUnit test will be tricky ... we should discuss on Tuesday.

**Comment by DevonFulcher** [comment]
Yes, I took the picture while it was still animating. Could you give a little more guidance? I am not sure what to test with JUnit and I do not know which class the visualization is in.

**Comment by DevonFulcher** [comment]
Oh, nevermind about JUnit until Tuesday then.

**Comment by schrum2** [comment]
The weight visualization is in HyperNEATUtil. Look at the drawWeight method.

**Comment by DevonFulcher** [comment]
Where can I find information about which which CPPN encoded a weight? I couldn't find any such method in HyperNEATTask, or Substrate.

**Comment by schrum2** [comment]
First, note that it is in CommonTaskUtil.getDrawingPanels that HyperNEATUtil.drawWeight gets called. If you make a new method in HyperNEATUtil for indicating which module creates each weight, you would need to call it from here.

The code in HyperNEATUtil  is a bit of a mess. It really bothers me how much it relies on static global variables. A good place to start might be to refactor it so that after the initial call to HyperNEATUtil.drawWeight, all the variables are passes as parameters instead of saved into global variables. Even before that, it might be nice to refactor/rename a lot of the methods, whose names are a bit confusing in my opinion.

However, to actually implement the coloring, you basically just need to have a way to get the module source in drawNodeWeight. Specifically, this bit of code is relevant:

```
if(link != null) {
	double weight = link.weight;
	c = regularVisualization(ActivationFunctions.activation(ActivationFunctions.FTYPE_TANH, weight));
}
```

If only it were possible to as the link how it was created, this would be trivially easy. We can add a variable that stores this information. In FullLinkGene in TWEANNGenotype add a protected in moduleSource as well as getters/setters for it. If you assume this int stores useful information, then link.moduleSource can be sent to CombinatoricUtilities.colorFromInt to assign a unique color to each module.

In order to actually store information in moduleSource, you will need to change HyperNEATCPPNGenotype.conditionalLinkAdd.  Note that after cppn.process(inputs) is called, you can call cppn.lastModule() to get the module that was used. You might want to add parameters to the newLinkGene method.

**Comment by DevonFulcher** [comment]
Implemented visualization. JUnit test is on hold. This commit: https://github.com/schrum2/MM-NEAT/commit/e2a85a97284185bb5305d3849befa378bd73a662

**Comment by schrum2** [comment]
Create a new, separate issue for the JUnit test that refers to this one by its tag, and then close this issue.

**Comment by JoeRoybal** [comment]
Here is the issue #147
