### ISSUE TITLE
Fix GaierAutoencoderPictureBinningSchemeTest

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#700]
Need to rename to `GaierAutoencoderPictureBinLabelsTest` and also add `trainingAutoEncoder:true` to the parameters initialized in `setUp`

**Comment by annazwicker** [comment]
`GaierAutoencoderPictureBinMappingTest` has been renamed to `GaierAutoencoderPictureBinLabelsTest`.  The parameter `trainingAutoEncoder` was added and set to `true`.
