### ISSUE TITLE
PictureTargetTask using EnhancedCPPNPictureGenotype without the Autoencoder is incredibly slow

### ISSUE THREAD

**Issue by annazwicker** [schrum2/MM-NEAT#701]
I conducted a run of `PictureTargetTask` using the `EnhancedCPPNPictureGenotype` without using the autoencoder, and for some reason, it runs incredible slow (it actually seems to get slower the longer you let it run).  Not sure as to why but probably just some minor changes to the code to fix something else.  When I ran `PictureTargetTask` using both the `EnhancedCPPNPictureGenotype` and the autoencoder it runs at a relatively fast speed (slower than when using the regular genotype and the autoencoder, but faster than when running it without the autoencoder).

**Comment by schrum2** [comment]
@annazwicker Please do some benchmarking on this. What I mean is, try setting the maxGens to a much smaller value so that the process will finish reasonably quickly, use the simple CPPN Neuron Count bin labels, and then actually time the execution time of runs both with and without the enhanced genotype.

**Comment by schrum2** [comment]
Benchmark the new code. Compare enhanced to regular to see if it is still really slow.

**Comment by schrum2** [comment]
Specifically, run `ScreamNeuronCountEnhanced.bat` and `ScreamNeuronCountRegular.bat` and compare run times.

**Comment by schrum2** [comment]
Actually, compare `SkullNeuronCountEnhanced.bat` and `SkullNeuronCountRegular.bat` instead to see what execution time is like.

**Comment by schrum2** [comment]
Enhanced is slightly slower, but not unreasonably so
