### ISSUE TITLE
PictureTargetTask with color images!

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#703]
Recreating the skull is all well and good, but we should really try reproducing some other images, and in particular some color images. As a starting point that should be simpler, you can save an image from Picbreeder (in color, but turn off "stark"), rescale to 64x64 and put it in the imagematch directory.

See what happens when you try to match this using just the neurons and also the neurons+links as the bin labels. Be sure to turn off the black/white Picbreeder option so that the evolved images actually have color.

After some trials with this, we should try to see what the system does when given some kind of real image, like a photo. This would clearly be much harder, but potentially much cooler too ... we'll essentially be trying to evolve an abstract art recreation of a real image.

Note that you should NOT use the auto encoder with this issue. It will require some changes to work on color images first. So, set the train autoencoder option to false.

**Comment by schrum2** [comment]
Need to create batch file to try evolving a simple color image that was produced by Picbreeder (so we know it is possible to recreate). Just use the neurons binning with the regular genotype.

**Comment by annazwicker** [comment]
A new batch file, SimpleColorImageCPPNNeuronCountBinLabelsRegularGenotype, has been created to try and recreate a simple color image generated by Picbreeder.  Currently running.

**Comment by annazwicker** [comment]
Current results from PictureTargetTask (using the SimpleColorImageCPPNneuronCountBinLabelsRegularGenotype batch file).
Target:
![pinkStripe](https://user-images.githubusercontent.com/82399865/123158140-04908c00-d431-11eb-849b-c53216e61579.jpg)
Imitations:
![0 7032868741613525-Neurons7](https://user-images.githubusercontent.com/82399865/123158165-0eb28a80-d431-11eb-8435-ee9b33c7906b.jpg)
![0 7622327854749962-Neurons13](https://user-images.githubusercontent.com/82399865/123158166-0eb28a80-d431-11eb-94c0-6d3d54275f29.jpg)
![0 7732489501181306-Neurons27](https://user-images.githubusercontent.com/82399865/123158167-0f4b2100-d431-11eb-8b03-12223936613b.jpg)

**Comment by annazwicker** [comment]
This runs successfully,
