### ISSUE TITLE
PictureTargetTask Using The Scream 

### ISSUE THREAD

**Issue by annazwicker** [schrum2/MM-NEAT#705]
Trying out PictureTargetTask using The Scream (256x256 pixels, black and white image).  Since PictureTargetTask seems to be able to replicate the skull successfully, we should try it with a more complex image.  Batch files need to be made to test this (using the neuron binning scheme, not using the autoencoder).  When running, one batch file should run using the EnhancedCPPNPictureGenotype and the other run using the regular genotype.

**Comment by schrum2** [comment]
Results at iteration3650000 using 10 fixed loss bin ranges:
![0 6249058010032109-Neurons 33](https://user-images.githubusercontent.com/8397236/122966100-88257c80-d34e-11eb-9de9-67ab4cd91026.jpg)
![0 6264624789650795-Neurons 48](https://user-images.githubusercontent.com/8397236/122966103-88be1300-d34e-11eb-948e-4d1156f4baeb.jpg)
![0 612248612401497-Neurons 12](https://user-images.githubusercontent.com/8397236/122966104-88be1300-d34e-11eb-9d15-3b71eaac0c7e.jpg)
![0 625447584916972-Neurons 19](https://user-images.githubusercontent.com/8397236/122966105-88be1300-d34e-11eb-9198-beb2d86a86b5.jpg)
![0 6245361762095409-Neurons 29](https://user-images.githubusercontent.com/8397236/122966106-88be1300-d34e-11eb-9360-20273f8235bc.jpg)
![0 6247964622109113-Neurons 31](https://user-images.githubusercontent.com/8397236/122966107-88be1300-d34e-11eb-89cf-e4f39a32cd60.jpg)

**Comment by schrum2** [comment]
There isn't really more work to do on this. The prelim run I was doing terminated ... we should run one for longer, but I think we already see that the results aren't great.
