### ISSUE TITLE
Bin based on rotation, scale, and translation too

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#706]
Make two new types of BinLabels that only work for Enhanced Genotypes.

One is the same as the one with just the CPPN neuron count, but ALSO adds binning based scale, rotation, deltaX, and deltaY. Have a new parameter that decides how many slices to divide each possible value by. The scale and delta values are already constrained between min and max values based on command line params. The rotation is inherently constrained based on the number of degrees in a circle (is the rotation in degrees or radians?)

Then, make another binning scheme that is the same as the Gaier one (which also counts the num neurons), but add scale, rotation, deltaX and deltaY to that too in the same way. However, test the first one out a bit before trying this second one.

**Comment by annazwicker** [comment]
The new binning scheme, CPPNNeuronScaleRotationDeltaXDeltaYBinLabels has been created and tested (runs successfully).  The other binning scheme, GaierAutoencoderNeruonLossScaleRotationDeltaXDeltaYBinLabels has been created and tested (doesn't run successfully yet).  Both methods have been added to the if else inside PictureTargetTask that determines which binning scheme to use.  However, the bodies of the statements need to be filled out.

**Comment by schrum2** [comment]
Make batch files for any new schemes and attempt running after Maven building. Make sure the saved file names make sense and that no crashes occur.

**Comment by annazwicker** [comment]
Testing for `oneDimensionalIndex` inside `GaierAutoencoderNeuronLossScaleRotationDeltaXDeltaYBinLabels` doesn't run due to a memory error.  The calculations for the `scale`, `rotation`, `deltaX `and `deltaY `have been added in `PictureTargetTask` for both `CPPNNeuronScaleRotationDeltaXDeltaYBinLabels` and `GaierAutoencoderNeuronLossScaleRotationDeltaXDeltaYBinLabels`.

**Comment by schrum2** [comment]
Part of why this takes up so much memory might be because of the lengthy string names. 
`"Neurons" + allNeuronValues[i]+ "-loss" + labelEnds[i] +"-scale" + allScaleValues[i] + "-rotation" + allRotationValues[i] + "-deltaX" + allDeltaXValues[i] +  "-deltaY" + allDeltaYValues[i]`

Try shortening to something like
`"N" + allNeuronValues[i]+ "L" + labelEnds[i] +"S" + allScaleValues[i] + "R" + allRotationValues[i] + "X" + allDeltaXValues[i] +  "Y" + allDeltaYValues[i]`

**Comment by annazwicker** [comment]
Testing for both new binning schemes is successful.  I believe all that's left do is run the associated batch files.
