### ISSUE TITLE
Dynamic Gaier BinLabels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#707]
I've talked with Adam Gaier a bit more in email and found out that he dynamically scaled the intervals for how reconstruction loss was discretized in his binning scheme. Here is how it works.

First, he is splitting reconstruction loss into 32 intervals, which is way more than the 10 we are using, so simply making that small change could be useful to us. **Set numReconstructionLossBins:32 in all of the current Gaier batch files.**

However, the real interesting thing he did was he rescaled the minimum loss and maximum loss for defining the intervals based on the range of loss values encountered when training the autoencoder. Here is how we can do this.

In `MAPElites`, after `oldOccupied` is assigned but before `this.archive` gets reinitialized, have an if statement for a new command line parameter called "dynamicAutoencoderIntervals". If dynamicAutoencoderIntervals is true, then there needs to be a loop that goes through all occupied bins in the current archive, uses task.evaluate on each individual, extracts the reconstruction loss from the resulting Score instance, and keeps track of what the min and max reconstruction loss across the whole archive was. Once every member has been checked, two more command line parameters need to have their values reassigned: "minAutoencoderLoss" and "maxAutoencoderLoss". The default values for these should be 0 and 1 respectively. If dynamicAutoencoderIntervals is false then they will never change. 

`GaierAutoencoderPictureBinLabels` needs to be updated to bin according to "minAutoencoderLoss" and "maxAutoencoderLoss". Once again, if these values are set to 0 and 1 then it should behave as normal ... the way it already does. However, if these values are different, it means we'll be slicing up a smaller range of values. This could allow us to focus more on where the meaningful diversity in the archive population is.

**Comment by annazwicker** [comment]
Currently running the batch file DynamicGaierAutoencoderPictureBinLabelsRegularGenotype to test the new binning scheme.

**Comment by annazwicker** [comment]
The batch file DynamicGaierAutoencoderPictureBinLabelsRegularGenotype runs successfully (uses the skull as the target image, dynamic Gaier bin labels, and the regular genotype).  
Results:
![0 8173704422236-Neurons46loss0](https://user-images.githubusercontent.com/82399865/123323592-54d42080-d4fb-11eb-8778-be517bf47f9e.jpg)
![0 810297700509669-Neurons29loss0](https://user-images.githubusercontent.com/82399865/123323593-54d42080-d4fb-11eb-89ed-5e55173e661a.jpg)
![0 7911044932390566-Neurons14loss0](https://user-images.githubusercontent.com/82399865/123323594-54d42080-d4fb-11eb-9002-8ab184c42262.jpg)
![0 7981291029099349-Neurons17loss0](https://user-images.githubusercontent.com/82399865/123323595-556cb700-d4fb-11eb-94fc-5b96fa60e82d.jpg)
Close this issue?
