### ISSUE TITLE
Troubleshoot standard deviation in CMA-ME

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#709]
Because CMA-ME seems restricted, it could be due to our standard deviation being too small, and different values should be investigated

**Comment by MBatt1** [comment]
Pyribs uses 0.5, however we should still try other values because it is likely our CMA-ME or CMA-ES works differently

**Comment by schrum2** [comment]
I'm also curious about how the covariance matrix changes over time. It is supposed to update into ovoid shapes to fit the distribution, but there might be a setting that is restricting it to a spheroid instead.

**Comment by schrum2** [comment]
If our latest fixes to CMA-ME described in issue #664 work and give comparable results to pyribs, then close this issue about standard deviation

**Comment by schrum2** [comment]
Although we're still concerned about the maximum fitness attained by our version of CMA-ME, I think it's safe to close this sigma issue.
