### ISSUE TITLE
Delete `iteration` directories as we go

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#711]
We're filling up hard drives too fast to run experiments. Also, most of what we produce is not needed in the long run. Add a new parameter `deleteOldArchives`, and if it is true, then delete each iteration directory after the next one is made. We should probably launch this deletion routine in its own thread, but let's just get the delete working first

**Comment by annazwicker** [comment]
PictureTargetTask now deletes directories as it runs.  Need to also set up something similar to delete the .pth files.

**Comment by annazwicker** [comment]
PictureTargetTask deletes directories and the associated .pth files as it runs.
