### ISSUE TITLE
Shifted Sphere

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#712]
We seem to finally be getting the results we should be getting with CMA-ME. Therefore, I want to more properly test it for comparison. Note that the version of Sphere tested by pyribs has the solution point shifted off diagonally a bit. This makes the function slightly harder. Go ahead and make a version of the Sphere function called `ShiftedSphere` that does the same thing so we can compare CMA-ME to it.

**Comment by MBatt1** [comment]
Added under the same location as the current functions with the name ShiftedSphereFunction

**Comment by schrum2** [comment]
I think the save directory for the batch file is wrong

**Comment by MBatt1** [comment]
![cma_me_imp_20_heatmap_04500](https://user-images.githubusercontent.com/53229958/123110680-ec554880-d401-11eb-9f68-e7a6433d1b75.png)
Pyribs results scaled 0-100

**Comment by schrum2** [comment]
![image](https://user-images.githubusercontent.com/8397236/123110655-e6f7fe00-d401-11eb-99cc-ecf4c3e196b8.png)
Shifted Sphere seems to work!
Even max fitness is great!
![image](https://user-images.githubusercontent.com/8397236/123110772-02fb9f80-d402-11eb-8e24-3f61a8a6635c.png)

**Comment by MBatt1** [comment]
![mapelitesfunctionoptimization-CMAMEShiftedSphere15ImprovementDim500FunctionOptimization0_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123114027-9e8e0f80-d404-11eb-81bf-96e5d3ec7b82.gif)
Animation of Shifted Sphere

**Comment by schrum2** [comment]
Very cool the way that the emitter means jump to the upper-right where the solution is right away.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123154226-33f0ca00-d42c-11eb-8975-4661fc993650.png)
Compared to pyribs with actual values
