### ISSUE TITLE
Python Archive Scripts: Problems with Rectangular Archives

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#713]
I think that your Python scripts aren't working quite right for rectangular archives @MBatt1 . Here is an archive image produced in @annazwicker 's `PictureTargetTask` using `GaierAutoencoderPictureBinLabels`.

![TargetImage-skullDynamicGaierAutoencoderPictureBinLabelsRegularGenotype20_MAPElites](https://user-images.githubusercontent.com/8397236/123104096-43f0b580-d3fc-11eb-9f49-71ba3ed2e856.png)

I've checked the saved output and verified that results with larger numbers of neurons exist, so I assume the issue is with your script. Something weird to note here: 0 on the Neurons axis actually refers to save files with "Neurons7" in the name, since this is the minimum number of neurons a network can have. The max refers to "Neurons50"

Try solving this in your branch first @MBatt1 , but you may not have up-to-date code in your branch for testing this task. You can either get me to test it in my branch, or you can test in `dev_schrum`, but implement the change in your branch first since we currently don't want any merges moving into your branch.

**Comment by MBatt1** [comment]
![TargetImage-skullDynamicGaierAutoencoderPictureBinLabelsRegularGenotype50_MAPElites](https://user-images.githubusercontent.com/53229958/123129634-b6b85b80-d411-11eb-9a30-767bb11ea2a9.png)
I had switched the x and y axes of the plot, but not how they were plotted, so all previous results are accurate, but the axis labels should be switched. This is now resolved with the image generator and animation generator

**Comment by MBatt1** [comment]
I don't know how this binning scheme works exactly, but the lowest part is not filled, which would be neurons=5 or neurons=6, but this archive image matches the results in archive/
