### ISSUE TITLE
Generalize MAP Elites BC specification

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#714]
The BinLabels approach to MAP Elites is problematic, since it requires lots of code associated with each possible binning scheme to be stored in each task rather than in the BinLabels classes themselves. I'm trying to fix that with a new scheme in which the task just passes the BinLabels a HashMap full of information, and the BinLabels can pick whatever information is relevant in calculating the index in the archive.

**Comment by schrum2** [comment]
@annazwicker I've made some massive changes to how MAP Elites works, which also affects PictureTargetTask. Everything should be fine, but please Maven install and then attempt running each of your batch files just long enough to make sure they don't crash or have any obvious problems. Reply to this issue thread after you have checked.

**Comment by schrum2** [comment]
@MBatt1 I've refactored how MAP Elites works a lot, using the HashMap approach I told you about. I've tested all of the old binning schemes I used to use for my old papers. However, I would like you to make sure that your KL Div and generalized latent vector approaches still work. You will have to check this in dev_schrum. Just run the examples you already have long enough to make sure they don't crash and can create some data in the plot files. Respond to this issue thread after you do the checks.

Note: I haven't changed how MAP Elites works with function optimization yet, so I might need to do that eventually too.

**Comment by annazwicker** [comment]
`GaierAutoencoderNeuronLossScaleRotationDeltaXDeltaYRegularGenotype`, `ColorCPPNComplexityBinLabelsEnhancedCPPNGenotype`, and `CPPNNeuronScaleRotationDeltaXDeltaYRegularGenotype `don't work.  All other batch files run successfully.  Not sure why the color batch file won't run, the other two are likely due to other errors in the code not associated with MAP-Elites (they hadn't been tested before).

**Comment by schrum2** [comment]
@annazwicker 
The batch file `GaierAutoencoderNeuronLossScaleRotationDeltaXDeltaYBinLabelsRegularGenotype.bat` does not make sense. You cannot ask for rotation, scale, etc. when using the regular genotype. These can only be accessed when using the Enhanced Genotype. Replace this batch file with one that uses the Enhanced Genotype.

`CPPNNeuronScaleRotationDeltaXDeltaYBinLabelsRegularGenotype.bat` has the same problem and should be changed in a similar way.

`ColorCPPNComplexityBinLabelsEnhancedCPPNGenotype.bat` fails because it cannot find `PicbreederRainbow.jpg`. Make sure this file exists in the repo.

**Comment by annazwicker** [comment]
`CPPNNeuronScaleRotationDeltaXDeltaYBinLabelsEnhancedCPPNGenotype` and `ColorCPPNComplexityBinLabelsEnhancedCPPNGenotype` both run.  `GaierAutoencoderNeuronlossScaleRotationDeltaXDeltaYBinLabelsEnhancedCPPNGenotype` doesn't run for unknown reasons.

**Comment by schrum2** [comment]
@annazwicker can be done with this issue, though I still need verification from @MBatt1

**Comment by MBatt1** [comment]
Confirmed working for KL Div, Latent vector
