### ISSUE TITLE
Log min and max loss ranges

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#715]
Every time the minAutoEncoderLoss and maxAutoEncoderLoss are updated, the current iteration, along with the updated values, should be written to a special log for this purpose that only exists if using the autoencoder with dynamic loss range. This logging would happen in `MAPElites`. Ask @MBatt1 for help with logging, as he has handled several issues like this.

**Comment by annazwicker** [comment]
When PictureTargetTask runs, an additional plot is now created for the min and max loss ranges.
