### ISSUE TITLE
2D Mario BinLabels with just leniency and decoration

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#717]
I'm trying to think of ways to make more sense out of the performance of CMA-ME. I wonder if we could make a Mario binning scheme that is simpler to analyze in that it makes a 2D archive based on just decoration sum and leniency sum. In fact, we could test it in a simple scenario with just 1 level chunk (segment) to really simplify things. We could do a quick check with MAP-Elites and CMA-ME to see if there is a performance difference, and maybe gradually increase the number of chunks to see what happens. We could also visualize the emitters in 2D. We could also play with the number of bin intervals per dimension, since I have a feeling that CMA-ME requires a larger number of bins in order to show an advantage.

Do all of this work in the dev_schrum, as my recent changes to how tasks deal with binning schemes (via a HashMap) should make it very easy to define the new BinLabels.

**Comment by MBatt1** [comment]
Added the binning scheme originally with the same set-up as other binning schemes, however because of the way the calculations were set up, it is not feasible to just change the number of segments.

I am re-writing this to separate the number of segments from the bins, and allow for any amount of segments, averaging the results.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/123707983-3db16d80-d830-11eb-8f82-84610bcf2707.png)
Results with the new binning scheme, mu=37, lambda=100, 1 GAN level chunk
Sadly CMA-ME is worse than MAP-Elites, but they are comparable

**Comment by schrum2** [comment]
Can you divide each dimension into 200 bins instead of 50? Try that out and post the results, then close the issue either way.

**Comment by MBatt1** [comment]
In trying to plot emitters, it appears that the emitters x and y values are swapped, flipped over the x/y diagonal
![MarioLevelsDecorateLeniency-CMAME5Improvement7_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123866900-4454e900-d8f3-11eb-9860-446b995a3663.gif)

Flipping the values manually shows that they do indeed line up properly
![MarioLevelsDecorateLeniency-CMAME5Improvement7_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123866943-52a30500-d8f3-11eb-8469-58f6ee5e18eb.gif)

**Comment by schrum2** [comment]
I'm curious if the same weird pause-jump behavior of the emitters would occur if you did a shorter run with a much higher logging frequency.
