### ISSUE TITLE
Exclude corners from moving up/sideways sliding window

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#718]
When reading the levels, the sliding window copies corners into the movement set that is currently being done, IE: when scanning right and hitting a corner, the last slide taken from the level before changing direction is the corner itself, which shouldn't be included in the right moving horizontal set

**Comment by schrum2** [comment]
This should be done before SCOPE ends, and needs to be done before #681

**Comment by MBatt1** [comment]
Output jsons appear to be jagged, the changes made here may be at fault, thus I am reopening until I verify what's wrong

**Comment by MBatt1** [comment]
It was an unrelated problem.
