### ISSUE TITLE
Updating Emitter Mean Logging for the new HashMap Behavior Approach

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#719]
Make sure it still works with function optimization and adjust to work with Mario and others too

**Comment by MBatt1** [comment]
The means appear to be accurate for my binning schemes, (Function opt, KL Div, Latent vector partition), however in the Mario 2D domain the x and y are flipped

**Comment by MBatt1** [comment]
The indices were flipped for my binning schemes, I am running some tests to make sure it does what I want, and then assuming they match up, I will change the python scripts to flip x/y, and that part of this issue will be resolved

The strange logging every 5 steps is still a potential issue however.

**Comment by MBatt1** [comment]
2D binning schemes once again plot correctly, however we may still want to investigate why the MarioMAPElitesDecorAndLeniencyBinLabels binning scheme only moves the emitters every 5 steps

**Comment by schrum2** [comment]
Is this still causing problems?

**Comment by MBatt1** [comment]
Besides the weird moving every 5 steps issue, it is fully functional, however we may want to increase the image resolution so we don't have the issue with not being able to see certain bins that you were having

**Comment by schrum2** [comment]
Do try to fix the resolution issue, but this should be lower priority than several other outstanding issues.

Not sure we know how to fix the "every 5 step" issue but thanks for clarifying.

**Comment by MBatt1** [comment]
Images (not animations) are now 10x bigger to make them much higher quality, and pdfs are exported along side the pngs to allow for easier insertion into publications
