### ISSUE TITLE
Add UT2004 MirrorBot

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#72]
If I ever get the UT2004 code running again ( #1 ) then I should also incorporate MirrorBot into this code. It is available at: https://bitbucket.org/polceanum/mirrorbot

I might also want to incorporate my own UT^2 bot ( http://nn.cs.utexas.edu/?ut2 ) but maybe only as a jar file. The UT^2 codebase is a bit complicated, and maybe not easily compatible with standard Pogamut.

**Comment by schrum2** [comment]
This should not be undertaken until we get UT2004 working again.

MirrorBot was the other bot that won BotPrize the same year my UT^2 bot won. See http://eldar.mathstat.uoguelph.ca/dashlock/CIG2013/papers/paper_3.pdf

It could be useful to have both MirrorBot and UT^2 on hand as opponents to evolve against, or agents to play against in post-evals against human players, etc.

**Comment by friedmaa** [comment]
UT^2 bot added, will read the paper for MirrorBot before adding it in

**Comment by schrum2** [comment]
This issue not focuses exclusively on MirrorBot. Details relating to UT^2 are now handled in #124 .

This particular issue can be closed once MirrorBot is included in MM-NEAT

**Comment by schrum2** [comment]
MirrorBot works! Of course, now we need to make sure that the changes didn't break it. I'll be giving you an issue on this soon.
