### ISSUE TITLE
Use original pyribs, but with our Java task code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#721]
I've made a jar file that runs Lode Runner with a particular binning scheme in Java. It accepts json level descriptions from the console and prints MAP Elites multidimensional bin indices along with the bin score. This should be enough to use the Python pyribs code for CMA-ME with our actual Java version of the task. I'll share the jar file separately from the repo since it is so massive.

If the results in this one Lode Runner task are promising, then I'll look into other game domains.

**Comment by schrum2** [comment]
Note that the Python code interacting with this will need to have a loop that discards lines of output from Java until the line "READY" is encountered.

**Comment by schrum2** [comment]
I updated the Lode Runner code on the java side and creates a new jar file which I've shared in Google Drive. This new version still prints the multidimensional bin indices, though you might be able to ignore that. Afterward, it loops through the HashMap and prints each value in the format
`<key> = <value>`
This is a tiny bit harder to parse than just printing out specific values in a fixed order, but I think it will be less error prone and also more generalizable in the future if we need to. You should parse this on the Python side using a loop and a dictionary (don't assume the key/value pairs will come out in a specific order, since they may not). The way you know that the HashMap is done printing is because the line 
`MAP DONE`
will be printed.

Note that because all of the HashMap contents are printed, you could conceivably use this for other LodeRunner binning schemes too ... at least some of them.

**Comment by MBatt1** [comment]
It currently outputs images to "loderunner_output" in the MMNEAT root directory, but for some reason the images all appear to be 0, and I'm not 100% sure the bins are even distributed properly, or what needs to be given to pyribs, but several things are probably wrong.
file can be found here: https://github.com/schrum2/MM-NEAT/blob/dev_schrum/src/main/python/Pyribs/LodeRunnerGAN-MAPElitesGroundTreasureEnemiesCAFit-On100Levels.py

**Comment by schrum2** [comment]
Here are some ideas.

1. First, clean up the code a bit. I think that much more of the code actually should go inside the `if __name__ == '__main__':` portion. Try moving the majority of it there.
2. Second: It occurs to me that although we are used to having 3D archives, a good starting point just to get things running would be a 2D archive ... just pick two of the aspects of the 2D archive, such as percent ground and treasure count and ignore the enemies. See if that works.

If this doesn't solve the problem, then we'll scrutinize it more closely together.

**Comment by schrum2** [comment]
I'm going to try making a Java class that can launch any of the GAN level generators in a way that will be compatible with pyribs. I just need to make all of those tasks implement an interface that accepts a level as a list of list of integers.

**Comment by schrum2** [comment]
If you export a jar of `ExternalLevelGenerationExecutor` called `ExternalLevelGenerator.jar` then there are now some batch files in the root MM-NEAT directory for launching Mario, Lode Runner, and Mega Man. These are in theory set up to accept jsons of full levels, but keep in mind that the GAN script is set up to only generate one segment of a time. Also, Mega Man can't really be used right now because one of the important behavior characteristics is an object whose information doesn't really display when printed. Mario has a similar problem with its arrays of stats, though I fixed that display issue ... except you would still need to manually sum or calculate based on the raw stats on the Python end.

So, although this "works" it is not really practical.

I'm thinking of making a more general Java class to help with this.

Finally, note that Zelda still doesn't work with this.

**Comment by schrum2** [comment]
Ok, committed `ExternalRealValuedGenotypeExecutor` which should be better. It can work with any task that uses real-valued genotypes (including bounded ones). It accepts the array as input at the console. This seems to work with Lode Runner and Mario.

Mega Man still has the problem with the Object in its behaviors, and Zelda is not tested yet.

**Comment by schrum2** [comment]
I definitely want lots of attention given to this with what little time you have remaining @MBatt1

**Comment by MBatt1** [comment]
Located in `src\main\python\Pyribs` there is a python script `MarioLatentPartition2SlicesTEST.py` that runs pyribs with the a 2D Mario latent vector partition

**Comment by schrum2** [comment]
The test Mario script works with "mapelites" but the code crashes with "cma_me_imp"

```
Traceback (most recent call last):
  File ".\src\main\python\Pyribs\MarioLatentPartition2SlicesTEST.py", line 221, in <module>
    fire.Fire(pyribs_main) # Run with progress bar
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File ".\src\main\python\Pyribs\MarioLatentPartition2SlicesTEST.py", line 156, in pyribs_main
    optimizer = create_optimizer(algorithm, dim, None) # Make optimizer with contained archive
  File ".\src\main\python\Pyribs\MarioLatentPartition2SlicesTEST.py", line 99, in create_optimizer
    seed=s) for s in emitter_seeds
  File ".\src\main\python\Pyribs\MarioLatentPartition2SlicesTEST.py", line 99, in <listcomp>
    seed=s) for s in emitter_seeds
  File "C:\Users\he_de.000\AppData\Roaming\Python\Python37\site-packages\ribs\emitters\_improvement_emitter.py", line 85, in __init__
    self._archive.dtype)
  File "C:\Users\he_de.000\AppData\Roaming\Python\Python37\site-packages\ribs\emitters\opt\_cma_es.py", line 110, in __init__
    self.weight_rule)
ZeroDivisionError: division by zero
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.util.Scanner.nextLine(Scanner.java:1540)
        at edu.southwestern.tasks.export.ExternalRealValuedGenotypeExecutor.main(ExternalRealValuedGenotypeExecutor.java:42)
Traceback (most recent call last):
  File ".\src\main\python\GAN\generator_ws.py", line 145, in <module>
    lv = numpy.array(json.loads(line))
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 

I think the division by zero is the original error, happening in `_cma_es.py`. This is probably caused by a bad setting, since the script is still configured for MAP Elites and not for CMA-ME, though I'm not sure what you change.

Any suggestions @MBatt1 ?

**Comment by schrum2** [comment]
I think the problem was that the batch size was just 1 and there was only 1 emitter, so I increased both of these values, but this led to another error:
```
Exception in thread "main" java.lang.IllegalStateException: 5.613322943815662 exceeds maximum value specified (5.0)
        at edu.southwestern.evolution.mapelites.generalmappings.MultiDimensionalRealValuedBinLabels.discretize(MultiDimensionalRealValuedBinLabels.java:125)
        at edu.southwestern.evolution.mapelites.generalmappings.MultiDimensionalRealValuedSlicedBinLabels.multiDimensionalIndices(MultiDimensionalRealValuedSlicedBinLabels.java:86)
        at edu.southwestern.evolution.mapelites.BaseBinLabels.oneDimensionalIndex(BaseBinLabels.java:16)
        at edu.southwestern.tasks.mario.MarioLevelTask.evaluateOneLevel(MarioLevelTask.java:502)
        at edu.southwestern.tasks.mario.MarioLevelTask.oneEval(MarioLevelTask.java:253)
        at edu.southwestern.tasks.export.ExternalRealValuedGenotypeExecutor.main(ExternalRealValuedGenotypeExecutor.java:47)
```

Is this value actually inappropriate, or do I just need to change the expected bounds?

**Comment by schrum2** [comment]
Note: The above out of bounds issue does not appear to occur when running plain MAP Elites, though I would have though this error was not related to the algorithm. Then again, I guess MAP Elites doesn't search the space as well.

**Comment by schrum2** [comment]
Finally, a success for CMA-ME in our of our GAN level domains @MBatt1 @volnam . When using the original Python CMA-ME in pyribs with calls to a Java jar file to evaluate the Mario levels, the pyribs version of CMA-ME does better than the pyribs version of MAP-Elites (probably need to compare with our Java MAP-Elites just to be sure). This is promising though.

The specific behavior characterization was based on splitting the latent vector into two and summing the values, as with the function optimization benchmarks. Interestingly, CMA-ME loves to generate values outside of the [-1,1] bound used for in the solution vectors, so the Java side actually clips these values. Therefore, when you look at the pyribs archive, you see tons of values outside these bounds, but I guess that doesn't matter?

Anyway, for a quick preliminary test, MAP-Elites gets these final results:
`Iteration 5000 | Archive Coverage: 28.380% QD Score: 243151.000`
CMA-ME with 5 improvement emitters gets this final result:
`Iteration 5000 | Archive Coverage: 35.230% QD Score: 311979.000`

Here are images of the archives:
MAP-Elites:
![map_elites_10_heatmap_05000](https://user-images.githubusercontent.com/8397236/125200452-dda7c780-e230-11eb-86c0-00b4ab661c7b.png)
CMA-ME:
![cma_me_imp_10_heatmap_05000](https://user-images.githubusercontent.com/8397236/125200458-e6000280-e230-11eb-8d03-39f1ea3cc216.png)

Note that CMA-ME fills out the edges a lot better, though this is at least in part due to the clipping described above. These were short runs. I think if I run them just a little but longer, I could fill a lot more of the archive, so more tests are needed. Still, this is promising.

Of course, the possible implication here is that there is still some kind of bug/problem with our Java CMA-ME implementation, which is incredibly frustrating. However, since we can use the Python code now, maybe this doesn't matter.

**Comment by schrum2** [comment]
@volnam @MBatt1 Confirmed that Pyribs can handle this simply Mario behavior characteristic based on splitting the latent vector with longer runs. Data below:
![mariolatentpartition2slices_Coverage](https://user-images.githubusercontent.com/8397236/125210470-9f78cb00-e265-11eb-949b-a241facbbac1.png)
![mariolatentpartition2slices_QD](https://user-images.githubusercontent.com/8397236/125210471-a1428e80-e265-11eb-865c-7948ce48d017.png)

Final MAP-Elites archive:
![map_elites_10_heatmap_30000](https://user-images.githubusercontent.com/8397236/125210477-abfd2380-e265-11eb-99d1-c60c3b7f63e1.png)
Final CMA-ME archive:
![cma_me_imp_10_heatmap_30000](https://user-images.githubusercontent.com/8397236/125210485-bae3d600-e265-11eb-8213-83c228b1905d.png)

**Comment by schrum2** [comment]
I re-ran CMA-ME when I realized that BCs were being computed with unclipped values. That seemed unfair, but even if you clip the values you get similar results. Note that the solution vectors are still unclipped ... they are simply clipped before computing BCs.

![cma_me_imp_10_archive_coverage](https://user-images.githubusercontent.com/8397236/125214195-474cc380-e27b-11eb-8e3b-37853baf0c21.png)
![cma_me_imp_10_qd_score](https://user-images.githubusercontent.com/8397236/125214198-4ae04a80-e27b-11eb-8a8c-00774b0319cd.png)

**Comment by schrum2** [comment]
The previous results might have some problems because it turns out that only one level of each batch was being evaluated. However, this only affects the fitness and not the coverage, since coverage was calculated with respect to the solution vectors only.

In any case, I'm not worried about that because I moved on to testing pyribs in the Mario binning scheme from my recent ToG submission. Here are the results from that paper:
![image](https://user-images.githubusercontent.com/8397236/125389415-c79c2300-e366-11eb-8eed-a74151d56bdc.png)
Direct2GAN proved inferior to CPPN2GAN, and there is not much coverage. This line plot compares coverage:
![image](https://user-images.githubusercontent.com/8397236/125389608-1c3f9e00-e367-11eb-9585-9fe22edf86b8.png)
My Java version of MAP-Elites filled just over 200 bins on average.

Here is a comparison of pyribs MAP-Elites and CMA-ME:
![coverage](https://user-images.githubusercontent.com/8397236/125389707-46915b80-e367-11eb-96da-feaebeaa5c80.png)
The Pyribs version of MAP-Elites does a bit worse, somewhere between 150 and 200 (though this is just one run). CMA-ME clearly does better at over 300. Here are what the archives look like.

Note that the trick I used here was that I mapped the 3D archives of this domain to 2D archives in a way that displays the heatmap organized the way my results above are organized (but not clearly labelled).

Pyribs MAP-Elites:
![map_elites_50_heatmap_00541](https://user-images.githubusercontent.com/8397236/125389951-a4be3e80-e367-11eb-8c05-b8dc619eab45.png)
This single run is actually pretty comparable to the average of 30 runs shown in my previous Java results. Here is CMA-ME:
![cma_me_imp_50_heatmap_00541](https://user-images.githubusercontent.com/8397236/125390018-c4edfd80-e367-11eb-978c-a1dfce866fcc.png)

Not only does CMA-ME discover more successful (high quality) levels (very little black/purple), but it also discovers several levels consisting of only 4 or 5 distinct segments (Pyribs MAP-Elites was incapable of this).

These results are a success. Time to test some other Mario binning schemes and also Lode Runner, and so on.

**Comment by schrum2** [comment]
Results in Lode Runner indicate no improvement for CMA-ME, but the results are at least consistent with my previous Java results. I only tested this with the Lode Runner GAN trained on 100 levels. Here is the previous final archive from Java experiments:
![image](https://user-images.githubusercontent.com/8397236/125678323-339b2208-3dc6-4aa8-b4bd-4c996e1f3860.png)
Here is the comparable MAP-Elites result from Pyribs:
![map_elites_10_heatmap_00271](https://user-images.githubusercontent.com/8397236/125678368-d3ed6aba-9727-4098-8852-8d5fbbffda6b.png)
And the final CMA-ME archive:
![cma_me_imp_10_heatmap_00271](https://user-images.githubusercontent.com/8397236/125678399-47452b51-9a60-4867-9774-26f7f352645b.png)
Finally, here are the coverage and QD comparisons, which are basically right on top of each other:
![qd](https://user-images.githubusercontent.com/8397236/125678446-bd630831-fc67-425b-95ba-c7b14e8ad25e.png)
![coverage](https://user-images.githubusercontent.com/8397236/125678449-187c5977-2f22-4848-bea5-a76baa4887ac.png)

So, at least we didn't do any worse than the previous results. This Lode Runner domain is hard, and I think the GAN is not great in the first place. This might be the best that is possible.

Some final notes: Lode Runner evaluations take a long time, and the Java code consumes a lot of memory. I guess that is to be expected for the A* algorithm given how complex the levels are, but I might look to see if I can consume less memory. Also, on the Python script side, the computation of Archive Coverage percentage is off by a decimal place ... need to fix.

**Comment by schrum2** [comment]
CMA-ME also seems to produce better results in Zelda using the Wall/Water/Rooms bin scheme. Here are the original results from my ToG submission:
![image](https://user-images.githubusercontent.com/8397236/125788117-8e5a4041-172c-4278-861f-b28f194366ef.png)
Here are MAP-Elites results from pyribs for a single run:
![map_elites_425_heatmap_00541](https://user-images.githubusercontent.com/8397236/125788189-763ddafe-0778-46cf-8211-41d7bea525fa.png)
These seem comparable. Here are CMA-ME results:
![cma_me_imp_425_heatmap_00541](https://user-images.githubusercontent.com/8397236/125788292-568a3301-84ce-4417-aa58-52781e2cf2ed.png)
Coverage seems comparable, but quality is slightly better. This is confirmed by these plots:
![coverage](https://user-images.githubusercontent.com/8397236/125788415-4f8d99f8-fe5d-4332-9953-76edf7ce4059.png)
![qd](https://user-images.githubusercontent.com/8397236/125788418-5d1e19ea-28c8-45bb-aff6-3a3573c0400d.png)
(Note that I actually did two runs of each)

So, I think this is another success.

**Comment by schrum2** [comment]
I did two runs each of the Mario bin scheme that I'm calling Sum DSL in the new ToG submission. These are the Mario labels used in the original CPPN2GAN paper as well. CMA-ME does NOT show a clear benefit with this binning scheme. Here is the original average archive heatmap from the latest ToG paper (very similar to the CPPN2GAN paper):
![image](https://user-images.githubusercontent.com/8397236/125832405-46eddef5-0d41-4dc6-abd7-d2966c0c63c1.png)
Here is MAP-Elites using pyribs:
![map_elites_50_heatmap_00541](https://user-images.githubusercontent.com/8397236/125832453-55247757-53a1-4d7f-9b4d-818fe66ee35c.png)
and CMA-ME using pyribs:
![cma_me_imp_50_heatmap_00541](https://user-images.githubusercontent.com/8397236/125832481-62207f37-b13d-417b-9d15-339907708848.png)

Notice that the original Java results generated a few levels in leniency bin 1 (this is the second column of the second row), but neither of the pyribs algorithms accomplished this. This result is more evidence that the version of MAP-Elites I'm using in Java is a bit better than the version of MAP-Elites in pyribs. As a reminder, this could either be due to the use of crossover, or the use of polynomial mutation, which are the two main differences in implementation I am aware of. Still, the difference is rather small. Here is a plot of archive coverage from the ToG submission:

![image](https://user-images.githubusercontent.com/8397236/125832850-20e72fe3-0d19-43f7-b5d0-044ffb9e42aa.png)
For the sake of this comparison, only the red line matters, which goes slightly above 300. In contrast, here are results from pyribs:
![coverage](https://user-images.githubusercontent.com/8397236/125832939-29578f64-a861-4450-8973-af0df47dfa7d.png)
And QD as well:
![qd](https://user-images.githubusercontent.com/8397236/125832951-cf5bf600-07ba-414b-b94c-f63fea9f740a.png)
I did two runs of each, and in one case CMA-ME is a bit better than MAP-Elites, but in general it looks like, for this binning scheme, CMA-ME is not better than MAP-Elites in pyribs, and neither of the pyribs algorithms are even better than my Java version of MAP-Elites.

We were sort of seeing this result earlier with our Java version of CMA-ME. Results like this make me wonder if our CMA-ME implementation is fine after all. However, there are still some examples in this thread of CMA-ME slightly outperforming MAP-Elites, so maybe not.

Only things left to test are the other Zelda binning scheme and Mega Man.

**Comment by schrum2** [comment]
Some interesting results using the Zelda Distinct BTR scheme. Basically, CMA-ME has a clear advantage over MAP-Elites in pyribs, but the difference between pyribs MAP-Elites and my Java MAP-Elites is also much larger, putting it right in the center of the two. Here are my previous Java results (once again, focus only on the red line):
![image](https://user-images.githubusercontent.com/8397236/125957407-a5b9f6e1-d011-4744-88ad-5258bb6ebe15.png)
It tops out around 2500 bins.

Here is the comparison of MAP-Elites to CMA-ME in pyribs:
![coverage](https://user-images.githubusercontent.com/8397236/125957503-8be419de-d397-46bb-81e3-827b7f2651bc.png)
MAP-Elites here maxes out around 1000, and CMA-ME maxes out around 3500.

Also, here is QD:
![qd](https://user-images.githubusercontent.com/8397236/125957526-78e3b4e0-04f4-4f6a-bc7b-986bcc5e5f9d.png)
(note that fitness scores range from 0 to 1, which is why QD is actually less than the number of filled bins here).

Here is what the final archives look like. First, my Java results:
![image](https://user-images.githubusercontent.com/8397236/125957793-426977f2-6328-428a-a6dc-9410d56f6833.png)

Now MAP-Elites in pyribs:
![map_elites_425_heatmap_00541](https://user-images.githubusercontent.com/8397236/125958035-6b17920b-d8a2-4959-95de-60b41952772d.png)
And finally CMA-ME
![cma_me_imp_425_heatmap_00541](https://user-images.githubusercontent.com/8397236/125958078-d2db22c4-adc7-45f7-b4b4-0d7d612ae0b8.png)

It's interesting that this one CMA-ME run (I'm running another by the way) can't fill that lower-right grid (25 reachable rooms), but still filled more bins over all. It seems to fill out the lower section of each sub-grid a bit better (corresponding to fewer distinct rooms, as in more copies).

This is still a success for CMA-ME, but brings up more concerns about the MAP-Elites implementation used. Last major domain to check is Mega Man.

**Comment by schrum2** [comment]
Problem with Mega Man: the process execution string for the GAN process is printed out after task initialization, so it is being caught by the pyribs code attempting to communicate via the console. Will need to add special handling of this.

**Comment by schrum2** [comment]
Did a second run of Zelda Distinct BTR with CMA-ME and it got slightly worse coverage. Bit disappointing. Still better than my Java plain MAP-Elites results though.
![coverage](https://user-images.githubusercontent.com/8397236/126021713-0e8a279c-a828-4317-ba71-39beb58b2544.png)

**Comment by schrum2** [comment]
I did an experiment with Mega Man too. My only previously published Mega Man results did not use MAP Elites, so I don't have Java results to compare against ... presumably, my Java version of "plain" MAP-Elites would do better. However, what I have to present are results comparing MAP-Elites to CMA-ME in Pyribs. Here are the plots first.

Archive coverage:
![coverage](https://user-images.githubusercontent.com/8397236/126021779-f762b783-853a-4dc8-b81a-ee3b8dfb2f73.png)
CMA-ME is way better! That's nice, but we would have to see how well Java MAP-Elites does before getting too excited.

QD:
![qd](https://user-images.githubusercontent.com/8397236/126021802-76c3eacc-6372-4870-9751-b008d64ad70a.png)
Very odd! One Mega Man run did terribly in terms of quality. Here are the heat maps of the final archives from the two CMA-ME runs.
![cma_me_imp_90_heatmap_00600](https://user-images.githubusercontent.com/8397236/126021818-34738ae1-4229-4363-aa2b-87053a0c1d90.png)
![cma_me_imp_90_heatmap_00600](https://user-images.githubusercontent.com/8397236/126021823-a5feb6a7-af14-44bc-acd0-df9037893043.png)

This fitness function (quality measure) might be a bit too harsh. If the level is unbeatable, then the fitness is 0 ... probably need to allow some incremental improvement. In Lode Runner, we took the max of the A* path length and the connectivity as a ration from 0 to 1. That meant that even unbeatable levels had a fitness gradient.

In any case, here is one of the MAP-Elites archives (they look similar, so seeing one is enough):
![map_elites_90_heatmap_00600](https://user-images.githubusercontent.com/8397236/126021870-749ccc5f-e332-4127-ba8b-971465611644.png)

**Comment by schrum2** [comment]
I changed the Mega Man fitness to be the max of connectivity and path length. I only did one run of each, but it looks like the great CMA-ME run with the previous fitness was the fluke ... the fitness here is comparable to the lesser of the two fitness scores above. Archives don't seem to be as filled. Here is the data.

![qd](https://user-images.githubusercontent.com/8397236/126026787-34c54bdd-ba1a-41a9-a535-9c49b176b0b6.png)
![coverage](https://user-images.githubusercontent.com/8397236/126026791-5bac9b65-5f5a-45df-8582-09341e1ecc42.png)

MAP-Elites archive:
![map_elites_90_heatmap_00600](https://user-images.githubusercontent.com/8397236/126026798-6282be32-8a41-4605-8987-9a489a1c015b.png)
CMA-ME archive:
![cma_me_imp_90_heatmap_00600](https://user-images.githubusercontent.com/8397236/126026801-784b2735-9314-4622-87aa-99a223ce787d.png)

**Comment by schrum2** [comment]
Ok, this all works. However, since most of this does not rely on a lot of MM-NEAT code, I've extracted the relevant parts out into this repo:
https://github.com/schrum2/PyribsForGameGAN

Closing this issue, but any further work with pyribs can continue there.
