### ISSUE TITLE
Percent matching pixels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#723]
Make a method in GraphicsUtil called `percentMatchingPixels` that takes two BufferedImages and loops through all the x/y coordinates and returns the percentage of pixels that match exactly in the two images. Two pixels can be considered matching if the int values returned by the `getRGB` method are identical.

We will use this to assess how good our final results actually are.

**Comment by schrum2** [comment]
I guess this works, but it seems odd that we are getting such worse numbers than Gaier given what the images look like. I think that this comparison should maybe be performed on the 28 by 28 pixel version of the skull.

In the troubleshoot class that does the heatmap comparison, see if you can scale both images to 28 by 28 before comparing.

**Comment by annazwicker** [comment]
`PictureTargetFitnessTroubleshoot` now scales the images to be 28x28 pixels when `shrink` is set to true.  The percentage of matching pixels is slightly higher when the images are scaled down.
