### ISSUE TITLE
Segment Swap Mutation and Segment Duplicate Mutation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#731]
When evolving with Direct2GAN, subsequences of the solution vector directly correspond to level segments. Therefore, if you wanted to swap two level segments, you could do so by swapping two subsequences in the solution vector of the appropriate length. This would allow for higher-level manipulation of evolved levels, and might also allow Direct2GAN to compete better with CPPN2GAN.

So, make a new mutation operator that knows where the segment boundaries are (a new parameter), and swaps two randomly chosen subsequences.

Related to this, have another new mutation operator that copies an existing segment to another place in the level, so that there are then two copies of it.

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/135324235-bc271238-c9f9-40ed-92d4-ed8fc9aa4efc.png)
Decorate NS Leniency results: Copy+Swap on top, normal on bottom.

![image](https://user-images.githubusercontent.com/53229958/135324473-d09dfb5f-ec01-4a16-9097-8346e7a9825a.png)
Distinct NS Decorate results: Copy+Swap on top, normal on bottom.

Decorate NS Leniency Copy+Swap does a bit worse than just normal Direct2GAN, however Distinct NS Decorate does a significant amount better in both QD and filled bins

**Comment by MBatt1** [comment]
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GAN0_MAPElites](https://user-images.githubusercontent.com/53229958/135324987-6c9af59c-e7ae-409b-93ce-e4cff81a1960.png)
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GANCopyAndSwap5_MAPElites](https://user-images.githubusercontent.com/53229958/135324994-4420d8ef-e0aa-4527-8498-25995860390a.png)
Distinct NS Decorate archives

**Comment by schrum2** [comment]
Would definitely be nice to have both lines plotted in the same figure next time. Still, the basic summary of results seems to be the following:
- Copy+Swap gives no advantage in Decorate NS Leniency (aka Sum DSL)
- Copy+Swap DOES have an advantage in Distinct NS Decorate (aka Distinct ASAD)
- However, Copy+Swap in Distinct NS Decorate (aka Distinct ASAD) should do better

Next steps:
- Run Distinct NS Decorate (aka Distinct ASAD) with Copy mutation rate of 0.7, 0.9, 1.0 to compare all (other settings the same)
- Run Distinct NS Decorate (aka Distinct ASAD) with Copy mutation at 1.0 and other mutation rates at 0.0 (sanity check)

**Comment by schrum2** [comment]
Important update for both @MBatt1 and @cappsb . I figured out why Maxx's runs are not actually logging the swap/copy mutations ... simply put, they are not happening at all. But why? Well, at some point over the summer after SCOPE but before you started on this code, I modified the batch files for the experiments to use `RealValuedGenotype` instead of `BoundedRealValuedGenotype`. However, the new mutation code that Maxx wrong is only in the `BoundedRealValuedGenotype` class. This means that if you evolve with `RealValuedGenotype`, as happens in our new batch files, the new mutations will never happen.

So Maxx: please put the mutation code into the `RealValuedGenotype`, but refactor it in a way so that `BoundedRealValuedGenotype` can also use the new mutations, but try to avoid code repetition.

**Comment by schrum2** [comment]
We'll need to wait for @cappsb to fix that unit test, but in the meantime, see if you can successfully build and run the code without running the unit tests. See details here:
https://stackoverflow.com/questions/8923002/how-to-configure-maven-install-to-skip-tests-in-eclipse
Hopefully it will compile, and you can run an experiment to see what happens with the swap and copy mutations are actually applied @MBatt1

**Comment by MBatt1** [comment]
wholeVectorMutateRate parameter is needed to be able to change rate of whole mutation, rather than only per-index mutation rate

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/138153573-6d6306f5-c5ab-445e-a5d5-8c91003744b7.png)
comparisons of results after fixes
ALL FOR DISTINCT NS DECORATE

**Comment by MBatt1** [comment]
Copy mutation by itself can repeat segments successfully with just 1 or 2 distinct segments
![ExtendedMarioLevelsDistinctNSDecorate-Direct2GANCopyNoMutation0_MAPElites](https://user-images.githubusercontent.com/53229958/140168641-4d693d19-5f1c-4942-b890-d00f3587e40b.png)
Final archive for 100% copy chance, no other mutations

**Comment by MBatt1** [comment]
Next: run mario ones with new rate in new directory
setup for zelda copy mutation

**Comment by cappsb** [comment]
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GANSwapOnly1_MAPElites](https://user-images.githubusercontent.com/63438571/142260152-b315844c-aa09-4c89-9c83-347866bc9f85.png
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GANCopyAndSwap1_MAPElites](https://user-images.githubusercontent.com/63438571/142260239-17af8b1f-45ff-4d29-9fdd-f606662b60dd.png)
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GANCopyOnly1_MAPElites](https://user-images.githubusercontent.com/63438571/142260347-e9df07e6-41e9-48c8-8bd0-65b1dd6099e5.png)
![ExtendedMarioLevelsDecorateNSLeniency-Direct2GAN1_MAPElites](https://user-images.githubusercontent.com/63438571/142260411-eba4413b-a662-43ab-b77e-b8e6d583e8a8.png)
![ExtendedMarioLevelsDecorateNSLeniency-CPPN2GAN1_MAPElites](https://user-images.githubusercontent.com/63438571/142260459-43e3a38f-e327-4fdd-92b4-8caa1404c6bf.png)
)

**Comment by cappsb** [comment]
![ExtendedMarioLevelsDistinctNSDecorate-Direct2GANCopyAndSwap1_MAPElites](https://user-images.githubusercontent.com/63438571/142260575-a9bef98c-c4ec-4f2c-8485-dd8906e21d75.png)
![ExtendedMarioLevelsDistinctNSDecorate-Direct2GANSwapOnly1_MAPElites](https://user-images.githubusercontent.com/63438571/142260636-ee5a31f1-08ee-492c-890b-ccb357503252.png)
![ExtendedMarioLevelsDistinctNSDecorate-Direct2GANCopyOnly1_MAPElites](https://user-images.githubusercontent.com/63438571/142260752-d38d5649-42f5-48f2-b4b0-232ca3ceefcc.png)
![ExtendedMarioLevelsDistinctNSDecorate-Direct2GAN1_MAPElites](https://user-images.githubusercontent.com/63438571/142260814-77dcac56-dab3-4509-8e0b-7c5f98ca574f.png)
![ExtendedMarioLevelsDistinctNSDecorate-CPPN2GAN1_MAPElites](https://user-images.githubusercontent.com/63438571/142260890-a0f50875-f3b7-4b66-adf6-6d66066652c3.png)

**Comment by MBatt1** [comment]
So far, Mario works completely, and has several batch files allowing runs with each option on/off in different combinations, to compare with CPPN and regular Direct to GAN, and can be found in the `Experiments-2022-Direct2GANExtensions` folder, with more batch files in `Direct2GANExtensionsPrelim`. The results above (for Mario) show that swapping alone is not very good, while swap-copy and copy only have fairly good results, beating out regular Direct to GAN, but not able to have as many duplicate segments or get as high values compared to CPPN to GAN. The next step is to set up swapping/copying settings to allow whole segments (auxiliary variables included) to be swapped with Zelda.

**Comment by schrum2** [comment]
I believe we have confirmed that Swap mutation and Copy mutation work. We're disappointed in the results, but they do work. I think that means we can close this issue.
