### ISSUE TITLE
Segment Swap and Segment Copy in Mega Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#736]
Please tag future commits related to this issue with this issue number. This is basically a Mega Man focused version of issue #731 . Beyond simply testing the mutation operations in Mega Man, we also want to see what happens if we specialize the mutation to only swap the portion of the segment associated with the latent variable inputs (keeping the auxiliary direction variables the same).

However, from what I understand, we first need to resolve some kind of array bounds exception associated with a unit test. Please keep me up to date on the details of troubleshooting that in this issue thread.

**Comment by cappsb** [comment]
![MegamanCopySwap-OneGANCopySwap1_MAPElites](https://user-images.githubusercontent.com/63438571/142261202-d316ecbb-2108-4d91-92f4-f7ec9f779f47.png)
![MegaManCopy-OneGANCopy1_MAPElites](https://user-images.githubusercontent.com/63438571/142261249-e2743e17-0af0-4567-8118-059a23fce648.png)
![MegaManSingleGAN-MegaManDirect2GAN1_MAPElites](https://user-images.githubusercontent.com/63438571/142261302-57030b6e-b7ff-4932-94bc-991ee2346cbb.png)

**Comment by cappsb** [comment]
Update in Mega Man as of now:

segment / swap works trivially. That is, it swaps the entire segment (including auxiliary variables). No work has been done to split up the aux / latent variables. Both copy and copy/swap perform better at fewer diverse segments, likely due to the ability to repeat segments.

**Comment by schrum2** [comment]
These results indicate that CPPN2GAN is still dominant, but there are still interesting observations to be made here.

Go ahead and make batch files for variants of CPPNThenDirect2GAN that use Swap and Copy after the Direct switch. Once all needed batch files are made, close the issue.

**Comment by schrum2** [comment]
@cappsb Do these batch files exist? If so, where are they located?

**Comment by schrum2** [comment]
I made the batch file `MegaManMAPElites-DistinctVerticalAndConnectivity-CPPNThen2OneGAN.bat` but it was non trivial. It turns out I needed to make some new classes. I started work on this and it kept getting more complicated, so I've now made a separate issue instead: #751 

Once that issue is completed, then a new batch file based off of `MegaManMAPElites-DistinctVerticalAndConnectivity-CPPNThen2OneGAN.bat` can be made that also incorporates the swap and copy segment mutations.

**Comment by MuellMark** [comment]
By utilizing similar code from previous Mario and MegaMan files, the batch file MegaManMAPElites-DistinctVerticalAndConnectivity-CPPNThenDirect2OneGANNoAuxCopySwap was created to test #751 with Segment Swap and Segment Copy. There weren't any issues after running it on PowerShell.
