### ISSUE TITLE
Fix Issues with Enhanced Picbreeder Genotype

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#739]
Evolved Picbreeder images have problems. When we evolve normal CPPN images with random fitness, we get reasonably good results with some diversity. When we use the enhanced genotype, we get a lot of solid green, solid red, etc images. I think the problem is related to how the activation functions saturate as you move outside of the narrow range around [-1,1].

First step in diagnosing this is to see which activation functions have problems. @annazwicker is playing with the PictureEvolutionTask in her branch to investigate this. Any observations on this matter should be posted to this thread.

**Comment by annazwicker** [comment]
These images had the following parameters: "includeFullSigmoidFunction:true",
					"includeFullGaussFunction:true", "includeCosineFunction:true", "includeGaussFunction:false",
					"includeIdFunction:true", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false",

![image4](https://user-images.githubusercontent.com/82399865/152728712-a8be2a9c-5ba8-4c9c-bd46-037c1bb61371.jpg)
![image5](https://user-images.githubusercontent.com/82399865/152728715-4ea86985-0da9-4f8b-b060-2302118e0ea0.jpg)
![image6](https://user-images.githubusercontent.com/82399865/152728716-3f670d7f-8e6b-4149-afb7-8e4590cd4ff7.jpg)
![image7](https://user-images.githubusercontent.com/82399865/152728717-e82b9dd0-99d6-4afc-81fd-8dba32743aef.jpg)
![image8](https://user-images.githubusercontent.com/82399865/152728718-65513003-f999-46b9-a915-6a328fa5fe35.jpg)
![image9](https://user-images.githubusercontent.com/82399865/152728719-08761e68-0750-40ee-8bab-43676439e7cb.jpg)
![image1](https://user-images.githubusercontent.com/82399865/152728721-fa5d7cca-f3c7-4c60-a5d1-7ae7c239b50a.jpg)
![image3](https://user-images.githubusercontent.com/82399865/152728722-fbf686a8-87c6-411d-a3f3-24f55c20980e.jpg)
,

**Comment by annazwicker** [comment]
(Run 2)
These images have the following parameters:"includeFullSigmoidFunction:true",
					"includeFullGaussFunction:false", "includeCosineFunction:true", "includeGaussFunction:false",
					"includeIdFunction:true", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false"
![image2-5](https://user-images.githubusercontent.com/82399865/152729407-e9c15670-2760-499e-a1f6-41ce7d3b818a.jpg)
![image2-6](https://user-images.githubusercontent.com/82399865/152729408-ef3843b4-e536-408c-9349-b90cb67f3c47.jpg)
![image2-7](https://user-images.githubusercontent.com/82399865/152729410-b553391e-27bf-401a-8121-0a76b987b1e3.jpg)
![image2-8](https://user-images.githubusercontent.com/82399865/152729411-3be4a883-29c3-4939-85bb-f5514eebda22.jpg)
![image2-1](https://user-images.githubusercontent.com/82399865/152729412-4c5f5b69-6c52-4891-81e4-b20ecaa0ed11.jpg)
![image2-2](https://user-images.githubusercontent.com/82399865/152729413-f4ae75f4-db8d-4969-b0b7-c9b9b274f0be.jpg)
![image2-3](https://user-images.githubusercontent.com/82399865/152729415-1e1d43b5-ab98-427d-8759-fb93c69f987d.jpg)
![image2-4](https://user-images.githubusercontent.com/82399865/152729416-78284b2e-d0fa-4da5-88a3-5dda3a7a29a4.jpg)
,

**Comment by annazwicker** [comment]
(Run 3)
"includeFullSigmoidFunction:false"
These images have the following parameters:"includeFullSigmoidFunction:false",
					"includeFullGaussFunction:true", "includeCosineFunction:true", "includeGaussFunction:false",
					"includeIdFunction:true", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false"
![image3-5](https://user-images.githubusercontent.com/82399865/152730482-56e4a99d-d407-45b1-aae3-2bfd34248ab6.jpg)
![image3-6](https://user-images.githubusercontent.com/82399865/152730484-a2b8f2ca-2bcf-4309-bb1e-68de9c1e8b26.jpg)
![image3-7](https://user-images.githubusercontent.com/82399865/152730485-140144dc-e97c-412a-bf40-fcda5865dd8c.jpg)
![image3-8](https://user-images.githubusercontent.com/82399865/152730486-8b682ffc-17b0-44bd-822f-1e2b58e64b3a.jpg)
![image3-1](https://user-images.githubusercontent.com/82399865/152730487-d241c11d-b1d0-438c-9f05-880f4419e861.jpg)
![image3-2](https://user-images.githubusercontent.com/82399865/152730488-c78e7fe4-88f3-4386-8679-62927e2d2098.jpg)
![image3-3](https://user-images.githubusercontent.com/82399865/152730489-07745012-262d-4e94-a765-61a01d948bb9.jpg)
![image3-4](https://user-images.githubusercontent.com/82399865/152730490-84416519-5c2b-4481-9a7f-d0dbbdb07a3e.jpg)
,

**Comment by annazwicker** [comment]
(Run 4)
"includeCosineFunction:false"
These images have the following images: "includeFullSigmoidFunction:true",
					"includeFullGaussFunction:true", "includeCosineFunction:false", "includeGaussFunction:false",
					"includeIdFunction:true", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false",
![image4-6](https://user-images.githubusercontent.com/82399865/152731167-871f087b-8aee-4496-9b45-5df850c90980.jpg)
![image4-7](https://user-images.githubusercontent.com/82399865/152731171-0314a87e-f53a-41d4-ac55-648c2b341a57.jpg)
![image4-8](https://user-images.githubusercontent.com/82399865/152731173-dab4a8f6-e754-4481-9a66-4c8019a30331.jpg)
![image4-1](https://user-images.githubusercontent.com/82399865/152731175-4babf8dd-cb3e-460b-a170-2f286ea97269.jpg)
![image4-2](https://user-images.githubusercontent.com/82399865/152731179-27917d24-4337-49b9-a576-db259945d6a6.jpg)
![image4-3](https://user-images.githubusercontent.com/82399865/152731180-9fc4d0fd-ddf2-4216-b6f4-be951e50e5a4.jpg)
![image4-4](https://user-images.githubusercontent.com/82399865/152731181-c622156a-c6c0-466e-850b-7ca65fb2d3e3.jpg)
![image4-5](https://user-images.githubusercontent.com/82399865/152731182-887731ec-5874-4d6e-83e3-d644027e8b43.jpg)

**Comment by annazwicker** [comment]
(Run 5)
"includeIdFunction:false"
These images have the following parameters:"includeFullSigmoidFunction:true",
					"includeFullGaussFunction:true", "includeCosineFunction:true", "includeGaussFunction:false",
					"includeIdFunction:false", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false",
![image5-6](https://user-images.githubusercontent.com/82399865/152732071-b16fd8d7-6d37-461c-a213-21804da93311.jpg)
![image5-7](https://user-images.githubusercontent.com/82399865/152732074-1e6872cc-bc5c-427d-8cb3-47193600fc11.jpg)
![image5-8](https://user-images.githubusercontent.com/82399865/152732075-955c2d8b-ae17-445d-a788-23ccd31d0f74.jpg)
![image5-1](https://user-images.githubusercontent.com/82399865/152732076-d1a94b04-ed7d-43d5-b180-867160355ac0.jpg)
![image5-2](https://user-images.githubusercontent.com/82399865/152732077-71cdf01c-d82a-4a54-bf30-0d2b40c2c930.jpg)
![image5-3](https://user-images.githubusercontent.com/82399865/152732078-d86589e8-e2ae-4e89-84a7-e2bac6665cba.jpg)
![image5-4](https://user-images.githubusercontent.com/82399865/152732080-2155574b-90a8-432d-923b-8a798292ad06.jpg)
![image5-5](https://user-images.githubusercontent.com/82399865/152732081-36872f58-8a0c-43ce-a284-5585166633b1.jpg)

**Comment by annazwicker** [comment]
(Run 6)
Based off of the previous functions turned to false, the seems that the images produced when includeIdFunction and includeCosineFunction were set to false were the most dull.  This test turns those two functions to true, but turns the other functions in the thread above to false (this includes includeFullSigmoidFunction and includeFullGaussFunction are set to false).
This created some images that were incredibly boring, but also some that had interesting patterns.
These images have the following parameters:"includeFullSigmoidFunction:false",
					"includeFullGaussFunction:false", "includeCosineFunction:true", "includeGaussFunction:false",
					"includeIdFunction:true", "includeTriangleWaveFunction:false", "includeSquareWaveFunction:false",
					"includeFullSawtoothFunction:false", "includeSigmoidFunction:false", "includeAbsValFunction:false",
					"includeSawtoothFunction:false",
![image6-7](https://user-images.githubusercontent.com/82399865/152733845-26209ccb-d6d7-4923-b301-20e5ab5c279a.jpg)
![image6-8](https://user-images.githubusercontent.com/82399865/152733846-6973ed67-3cfe-4082-aa23-4803d91a82c4.jpg)
![image6-9](https://user-images.githubusercontent.com/82399865/152733847-ac459e59-25f7-4268-af49-897dfd947b8e.jpg)
![image6-1](https://user-images.githubusercontent.com/82399865/152733849-ec2deb8e-b631-4b86-8677-444f76b2f472.jpg)
![image6-2](https://user-images.githubusercontent.com/82399865/152733851-24af90ed-6896-423d-b3b5-f2867d505d96.jpg)
![image6-3](https://user-images.githubusercontent.com/82399865/152733853-6d3a9455-5a15-4464-b0a7-436dfab5f4d2.jpg)
![image6-4](https://user-images.githubusercontent.com/82399865/152733854-3704b607-9de9-4811-b854-d17f17384a35.jpg)
![image6-5](https://user-images.githubusercontent.com/82399865/152733855-c04c0b8a-8b8d-4cfe-8dc7-c85386b57a0c.jpg)
![image6-6](https://user-images.githubusercontent.com/82399865/152733856-e1af9ecd-8f96-4174-98d7-964417b08510.jpg)

**Comment by schrum2** [comment]
Some are better than others, but none are perfect. However, seeing these results makes me think that we can solve the problem via the fitness function. All of these use the random fitness function, correct?

I think we could make a set of three fitness functions: RedRange, BlueRange, GreenRange. For each one, you loop through the whole picture and get the pixel value for the corresponding color (RGB), and you calculate both the min and the max across all of the pixels. The fitness score is the max - min. This approach would assign a fitness of 0 to any picture that only had the same color everywhere.

**Comment by schrum2** [comment]
Looks like the new color range fitness helps, but it gives us nothing but rainbows. We want to have color diversity but without only getting rainbows everywhere. We're revisiting the color fitness from the Zentangle paper to see if that helps. I think we're getting close to a solution

**Comment by schrum2** [comment]
@annazwicker Next step: make a new fitness set that combines the three color ranges and the three color sums.

**Comment by annazwicker** [comment]
These are the images produced with the normal set of parameters in PictureEvolutionTask, using the new ColorRangeAndSumFitness and using the random number generator.
![randomSumAndRange3](https://user-images.githubusercontent.com/82399865/153886805-0e293dc7-cd67-4df1-9d36-89973e276746.jpg)
![randomSumAndRange4](https://user-images.githubusercontent.com/82399865/153886807-6e335be4-4a5c-4390-8657-1fb5c504f4ce.jpg)
![randomSumAndRange5](https://user-images.githubusercontent.com/82399865/153886808-cce5d275-9804-4c4d-950e-cb85a3474c80.jpg)
![randomSumAndRange6](https://user-images.githubusercontent.com/82399865/153886809-13e38656-483c-4100-a669-7a0460a20772.jpg)
![randomSumAndRange7](https://user-images.githubusercontent.com/82399865/153886810-eff9ab7e-166f-4a05-94c5-241a07509fa7.jpg)
![randomSumAndRange8](https://user-images.githubusercontent.com/82399865/153886812-81a6d3f8-e3e2-4f96-9130-26fb98fd9fb5.jpg)
![randomSumAndRange1](https://user-images.githubusercontent.com/82399865/153886817-2cee7c9f-5f6c-4371-a454-5625ad426841.jpg)
![randomSumAndRange2](https://user-images.githubusercontent.com/82399865/153886818-cea06bf1-a099-44fa-85c3-60326b0b558d.jpg)

**Comment by schrum2** [comment]
@annazwicker In the PicbreederTask (the interactive one) I think we need a button that toggles the scaling back and forth between using the value in the EnhancedGenotype and using some pre-set value like 1 or maybe even 10.

**Comment by schrum2** [comment]
I'm going to close this specific issue, but the analysis of the enhanced CPPN genotypes will continue in other ways. In particular, I'm making a new issue about adding interface elements to the PicbreederTask for changing the scale, rotation, and translation: #752
