### ISSUE TITLE
Segment Swap and Segment Copy in Zelda

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#740]
Same as #736 but for Zelda

**Comment by schrum2** [comment]
Although our focus is on Mega Man now, does this work in theory? I would like to get a quick test done to see that the mutations can happen, and then we can close this.

**Comment by schrum2** [comment]
@cappsb Any final word on this? I know that we're basically going to stop work in this moving forward, but if you could clarify whether this works, or what still needs to be done to make it work, that would be appreciated. Naming any specific relevant class files could be very helpful.

**Comment by schrum2** [comment]
I've added the missing information regarding the start and end index of auxiliary variables. I think this is done, but I made a follow up issue to refactor the code a bit: #746
