### ISSUE TITLE
Comment ch.idsia.ai.MLP

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#747]
In the package `ch.idsia.ai` is a class called `MLP` which stands for Multi-Layer Perceptron. This is a fairly standard type of neural network which you can get a crash course in by watching this video:
https://youtu.be/s8pDf2Pt9sc

The point of this issue is to simply create properly formatted Java Doc style comments for each method and constructor of this class. This code was not written by me or one of my students, but it is fairly clean. It's not really heavily used in the code, so the main purpose of this issue is just to get practice with commenting, GitHub, and neural networks (there are other neural network models in the codebase that are extensively used).

If you're not sure what a method is doing, ask questions. Just remember that JavaDoc comments only need to explain how to use the method like a black box ... only input/output really matters. The comment doesn't need to over-describe the implementation.

**Comment by alejmedinajr** [comment]
Created java doc comments for every method and constructor in this class.
