### ISSUE TITLE
Comment edu.southwestern.tasks.interactive.megaman.MegaManGANLevelBreederTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#748]
This is a class that I think was mostly made by Ben Capps.

To start, open the class and run its main method to get a sense for what it does. It lets you interactively evolve Mega Man levels. It is even possible to play them with a separate program called Mega Man Maker (https://megamanmaker.com/) but setting that up takes a bit of extra work.

At a bare minimum, every method of this class needs a clear Java Doc style comment. However, I think there are other areas that can use commenting too.

The point of this task is for you to start learning how different components of MM-NEAT work, so I expect you to have questions. Please ask as you go along.

**Comment by MuellMark** [comment]
Everything has been commented
