### ISSUE TITLE
Comment ch.idsia.ai.agents.human.HumanKeyboardAgent

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#749]
This class is for allowing a human player to control Mario via the keyboard in the Mario AI code included in this project.

First, run the class `ch.idsia.scenarios.Play`. This will allow you to play Mario.

Once you've tried it out, take a shot at commenting the `HumanKeyboardAgent` class. Specifically, give every method a JavaDoc comment.

**Comment by richeyme** [comment]
I have added all the comments to the methods
