### ISSUE TITLE
Refactor OriginalPicBreederGenomeLoader to generate each image in sequence

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#750]
Look at the class `edu.southwestern.tasks.interactive.picbreeder.OriginalPicBreederGenomeLoader`. Run it and see what happens. You should see a very complicated looking neural network, and an image of a pink apple. The apple is supposed to look like this:
https://pbs.twimg.com/media/Dccx9ySVAAAzTwO?format=jpg&name=360x360
However, solving that problem is a separate issue #741 

What I want you to do is simply refactor this code a little bit. As you can see, there are many different Files named inputFile. Basically, you need to comment out one and uncomment another to try loading the CPPN image from that neural network. What I would prefer to have is a method `render` that takes the `String` of a filename (like `"5736_ShinyRedApple.xml"`) and then renders the image, since this would allow the main method to consist of a bunch of calls to `render` one after another.

Highlight the code beneath the part where the `File inputFile` comments end, and use the Refactor -> Extract Method feature of Eclipse to pull that code out into its own method.

Be sure to provide a JavaDoc comment for your new method, and also for the existing `getFType` method which needs JavaDoc as well.

**Comment by richeyme** [comment]
I have refactored the render method and left javadoc comments on both render and getFType

**Comment by schrum2** [comment]
This needs to be refactored differently, as we discussed, so I'm reopening the issue.

**Comment by richeyme** [comment]
I refactored the render method the right way this time and made it so that the user could loop through all the image files. I also left java doc comments on all the methods in the class.
