### ISSUE TITLE
Allow CPPNOrDirectToGANGenotype for Mega Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#751]
The `CPPNOrDirectToGANGenotype` requires a specialized mutation that converts from CPPN to Direct genotypes for each domain where it is applied. This already exists in Mario and Zelda via `ConvertMarioCPPN2GANtoDirect2GANMutation` and `ConvertZeldaCPPN2GANtoDirect2GANMutation`. I want one to be made for Mega Man now.

In the `edu.southwestern.evolution.mutation.tweann` package create a class `ConvertMegaManCPPN2GANtoDirect2GANMutation` 

It's purpose is to switch the form of the genotype from using a CPPN (TWEANN) to using a RealValuedGenotype.

It will probably require a lot of discussion to make sense of this.

**Comment by schrum2** [comment]
A lot of refactoring of the Mega Man code is required before this will be possible. Specifically, any "Task" (meaning a class that extends `Task` or any of the subclasses of `Task`) that contains a global non-static variable of type `MegaManGANGenerator` should have that variable removed. Instead of letting each task have its own generator, there only needs to be one central generator, meaning that it should be a global `static` variable. 

Place this global `static` variable in `MegaManGANUtil`. For any task class that formerly initialized a `MegaManGANGenerator`, it should instead initialize the new global variable in  `MegaManGANUtil` instead. All of this refactoring should be implemented and tested before returning to the issue of making the `ConvertMegaManCPPN2GANtoDirect2GANMutation`

**Comment by MuellMark** [comment]
All of the file were refactored, however, it would not run on my machine when trying to use SevenGAN. However, when run on a different machine, there weren't any issues. This is most likely an issue with PyTorch.

**Comment by MuellMark** [comment]
After refactoring several file, mostly MegaManGANUtil, we were able to get the MegaMan conversion to run without repeating code. From there, we were able to verify this by creating a new batch file (MegaManMAPElitesSingleGAN-CPPNThenDirect2GAN) to test this out. This leads us to issue #736
