### ISSUE TITLE
Picbreeder: Interface to change scale, rotation, translation interactively

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#752]
Run the class `PicbreederTask` and you'll see lots of images you can evolve. By default, "enhanced" genotypes are enabled. These are something we developed last summer but have not published on yet. Basically, the CPPN normally creates an image within a fixed window that is drawn in the interval [-1,1]x[-1,1]. However, the enhanced genotypes can zoom in or out of this window, can rotate it, and can shift (translate) it along the x and/or y axes. Basically, each evolved CPPN also has some set of numbers evolved alongside it that represent the scale, rotation, x translation, and y translation.

I want to have a way to easily modify these 4 "enhanced" parameters freely. What I envision is a button on the interface that opens up a new window with options for editing the most recently selected image. There will be text fields containing the current values, and they can be changed by the user.

To get some inspiration on how to make a separate GUI interface like this, look at `MarioGANLevelBreederTask` and run that. Notice that if you click a level and thin click the "ExploreLatentSpace" button, it opens up a window that allows you to edit that specific level. The interface you add for Picbreeder should be similar.

**Comment by richeyme** [comment]
I have made the interface that allows the user to select an image and edit it by either scaling, rotating, or translating it on the x and y axis.

**Comment by schrum2** [comment]
There is actually another component to this, and also a few small fixes needed on the current version. First, the small fixes:
![image](https://user-images.githubusercontent.com/8397236/168386937-e206edf5-44f3-40ff-9ca0-73baa7725b8b.png)
I put red boxes around the parts that need to change. 

We found out during testing that x and y are apparently mislabeled. Rather than try to fix this everywhere in the code, just change the text on the display of the interface by swapping the x and y (but also make comments that clearly point out that the labels are wrong).

Also, notice that the max values for two of the sliders are not the max values, and are not placed where they should be. Please adjust that.

I'll make more extensive feature requests in the next post of this thread.

**Comment by schrum2** [comment]
Look at line 789 of `PicbreederTask`. This is part of the code where the program is launched with a bunch of command line parameters, and the specific one being used here is:
`"genotype:edu.southwestern.evolution.genotypes.EnhancedCPPNPictureGenotype",`
This is the CPPN that is combined with the rotation, scale, and translation values. If you comment that out, then the code defaults to using plain CPPNs, which makes the images a bit more uniformly sized and centered. However, when enhanced CPPN genotypes are not being used (which each have their own scale, rotation, etc) then it is possible to have a single bunch of settings for these parameters that apply to ALL of the images. These parameters are also set a few lines below:

```
					"picbreederImageScale:10.0", "picbreederImageRotation:0.0", // <- Not relevant when EnhancedCPPNPictureGenotype is used
					"picbreederImageTranslationX:0.0", "picbreederImageTranslationY:0.0"});  // <- Not relevant when EnhancedCPPNPictureGenotype is used
```

Remember in the picture editing interface all those UnsupportedOperationExceptions that are thrown when not using an enhanced CPPN genotype? Well, it's time to replace that code. Now, if you manipulate the rotation, scale or translation of one image in this interface, it should directly change the values of the associated command line parameters and update ALL images in the population accordingly.

**Comment by schrum2** [comment]
In addition to the outstanding issues above, make it so that if a number is directly entered into the text fields and enter is pressed, then the value will be changed and the slider will be moved to that correct spot to match

**Comment by schrum2** [comment]
TODO:

- The x and y translation sliders and text fields do nothing when using plain CPPN genotypes.
- When using plain CPPN genotypes, instead of resetting just the image that is being edited, ALL images in the population need to be reset because the scale, rotation, etc values being modified apply to the whole population and not just one individual.
- In the Edit-Pic GUI, the image is rectangular instead of square, but only when using plain CPPN genotypes, which is really weird.
- Methods for the anonymous ActionListener that controls the picture editing need Java doc comments

**Comment by schrum2** [comment]
Following up specifically on the squeezed image problem. It turns out the Enhanced images are too wide and the regular images are too thin. This is because the height and width were incorrectly swapped in a call to `GraphicsUtil.imageFromCPPN` for one but not the other. Swapping the parameters there makes both enhanced and regular incorrect in the SAME way instead of in different ways. The images should be squares though. So, I changed various calls everywhere to use imageSize instead of separate height and width

**Comment by schrum2** [comment]
It turns out that x/y translation were NOT mislabeled. Rather, the direction of translation also depends on rotation, so things only seemed to be moving the wrong way because they were rotated somewhere close to 90 degrees or 270. Therefore, I changed the names of these labels in the picture editing interface back

**Comment by schrum2** [comment]
Remaining TODO items:
- The x and y translation sliders and text fields do nothing when using plain CPPN genotypes.
- When using plain CPPN genotypes, instead of resetting just the image that is being edited, ALL images in the population need to be reset because the scale, rotation, etc values being modified apply to the whole population and not just one individual.
- Methods for the anonymous ActionListener that controls the picture editing need Java doc comments

**Comment by richeyme** [comment]
The x and y translation sliders and text fields work properly for plain CPPN genotypes, all the images get updated when an edit is made to one image through the resetAllButtons method, and java doc comments have been made to all the action listeners that were used for the sliders and text fields

**Comment by schrum2** [comment]
When using the plain CPPN genotypes and trying to update all images at once, it is way too slow. I'm removing this feature, and will instead just make it update the images once the Edit-Pic window is closed. Also, it should not be putting a blue selection outline around everything. Need to fix that. Looks like there is still a problem with image caching as well.

**Comment by schrum2** [comment]
I tidied this up a bit and am ready to close it now. The background images in the grid no longer update as the image in the Edit-Pic Window is updating, but that's fine ... they update when the window closes. This also makes editing much faster/smoother.
