### ISSUE TITLE
edu.southwestern.tasks.megaman.astar.MegaManStateTest broken

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#758]
Something that you changed recently seems to have broken this unit test:
`edu.southwestern.tasks.megaman.astar.MegaManStateTest`
In fact, this is the test you need to work with anyway for issue #607 

I don't know how I missed this earlier. It is possible that the change from Manhattan is what broke this, but it's also possible that the exit orb placement could have messed something up.

**Comment by MuellMark** [comment]
The Maven build was a success, so there weren't any issues with the altered MegaManStateTest file
