### ISSUE TITLE
Confine the snakes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#766]
Similar to Python, have command line parameters for "redirectConfinedSnakes" and "stopConfinedSnakes" (don't need to have an additional parameter for simply using confinement ... that will be inferred by one of these being true). As before, "redirectConfinedSnakes" forces an alternate direction to be chosen when going out of bounds, and "stopConfinedSnakes" stops the generation prematurely when the snake goes out of bounds.

**Comment by richeyme** [comment]
I was running this just now and this is the graph I got from it. It seems to be way better than the python version
![image](https://user-images.githubusercontent.com/94399708/171458998-7496dbbb-1e92-46d6-a3b4-7a4b90cf7238.png)

**Comment by schrum2** [comment]
Also, it's useful to remember that we're comparing against this:
https://github.com/schrum2/EvoCraft-SCOPE/issues/46

**Comment by richeyme** [comment]
Both redirect and stop confined snakes work

**Comment by schrum2** [comment]
Definitely able to evolve long snakes:
![image](https://user-images.githubusercontent.com/8397236/171492639-90d589e0-96cf-4658-8f80-e7205ba0e50a.png)
Still, it's weird that the fitness fluctuates, and even seems to go above 100. I think this is caused by pistons, but can not 100% certain.
