### ISSUE TITLE
Block Diversity Fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#768]
Extend `CheckBlocksInSpaceFitness` to make `BlockDiversityFitness`. The point is to reward structures that feature a lot of blocks adjacent to blocks of different types. Specifically:

Go through each block X.
If the block X is not AIR, check the 6 neighbors of X.
Each of those neighbors whose type is different from the type of X adds a point to a tally (including AIR blocks)

In order to do this, you will need to have a way of easily looking up the neighbors of any given block, but the input is simply a `List` of `Block` objects where each `Block` contains its position. Therefore, the first thing you should do is create a 3D array of `int` and fill every index with the value of `BlockType.AIR.ordinal()`. Next, loop through the list of blocks and place the type of each block at the appropriate place within the 3D array (you will need to subtract out the corner coordinates to get relative coordinates for the 3D array). 

A clever thing you can do is make the 3D array 2 units larger in each dimension. This provides a buffer of AIR around the shape, so you won't have to check for array index out of bounds errors, but you will need to offset your coordinated by 1 to make this work.

**Comment by richeyme** [comment]
Did a successful run for the first time and we're getting really high fitness scores
![image](https://user-images.githubusercontent.com/94399708/171506193-a5ace49a-3519-40d1-99fc-a7672994486f.png)

This is what the structures ended up looking like:
![2022-06-01_16 38 07](https://user-images.githubusercontent.com/94399708/171506283-a21e4a01-bc86-4889-ab1b-22cc49ebd431.png)

**Comment by richeyme** [comment]
Here are what the redirect confined snakes looked like when they finished
![2022-06-03_14 42 11](https://user-images.githubusercontent.com/94399708/171938765-cd9dccb1-9d7a-4ee6-b3d0-3a394e147934.png)

**Comment by richeyme** [comment]
Here are what stop confined snakes looked like when they finished 
![2022-06-03_14 50 27](https://user-images.githubusercontent.com/94399708/171940140-331c6127-b491-4f82-87ec-20fc000d8551.png)

**Comment by richeyme** [comment]
To me it seems like it is a lot easier for the large cubic like structures to have a lot more variety but I can definitely tell that the snakes are also way more diverse than they would be regularly
