### ISSUE TITLE
HybrID style Minecraft Shape Generation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#775]
Once issue #773 is resolved, we could set up an approach where shapes are first evolved using CPPNs, but then transition to being evolved directly. However, I would want to explore the VectorToVolume approach thoroughly on its own first before trying this extra step

**Comment by schrum2** [comment]
I think there are two tricks to implementing this.

First, make a new genotype: `CPPNOrBlockVectorGenotype`. This will be somewhat similar to the `CPPNOrDirectToGANGenotype`, except the `mutate` method will be changed, and will require use of a new `ConvertMinecraftCPPNtoBlockVectorMutation`.

You will also need to make a new shape generator: `CPPNOrVectorToVolumeGenerator`. This class will contain internal instances of both the `ThreeDimensionalVolumeGenerator` and `VectorToVolumeGenerator`. It uses one or the other based on the type/form of the `CPPNOrBlockVectorGenotype`.

**Comment by alejmedinajr** [comment]
I think the `ConvertMinecraftCPPNtoBlockVectorMutation `class is close to done. However, I need to change the way the counter is being incremented becasue I did not like the way I did it. Additionally, I still need to finish up the `mutate ` method in `CPPNOrBlockVectorGenotype`. I am not entirely sure what needs to be added to it.

**Comment by alejmedinajr** [comment]
There is an issue with the `ConvertMinecraftCPPNtoBlockVectorMutation ` class. Specifically, when the genotype switches to its second form (vector), there are negative values in the `VectorToVolumeGenerator ` array. This should not be happening.

**Comment by alejmedinajr** [comment]
The problem with the negative values was caused casting to the wrong genotype. It seems to be fixed after changing the type to a bounded type. This required the creation of the new `BoundedVectorGenerator` , which bounds appropriately.

**Comment by schrum2** [comment]
Go ahead and make a batch file to test over the weekend. If it runs for long enough without crashing, close the issue.

**Comment by alejmedinajr** [comment]
The following batch files have been made: `MinecraftAccumulate-CPPNToVectorCount.bat`, `MinecraftAccumulate-CPPNToVectorDirectionalMovement.bat`, `MinecraftAccumulate-CPPNToVectorPistonOrientationCount.bat`, `MinecraftAccumulate-CPPNToVectorRedstoneVSPiston.bat`, `MinecraftAccumulate-CPPNToVectorWHD.bat`.
