### ISSUE TITLE
Snaking back in on itself

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#776]
The SnakeGenerator is capable of revisiting a given location multiple times. This can create block lists where multiple blocks have the same coordinates. We should prevent this. As soon as `(xi,yi,zi)` refers to the coordinated of a block that are already in the `List<Block> snake` the loop should set `done = true` (this can happen at the end of the loop like the `yi < 0` check).

In order to track this efficiently, put every value of `(xi,yi,zi)` in a `HashSet` as a `MinecraftCoordinates`, and simply check if each "new" set of coordinates encountered is already in the set.

**Comment by schrum2** [comment]
I think that a unit test can be written that does not require the use of the Minecraft server at all, so I would like to attempt this. The trick is that the behavior depends on a CPPN, and it is hard to make one do what you want. However, I may have a programming trick that will get us around that. We'll talk tomorrow.

**Comment by richeyme** [comment]
This was resolved in #779 that I just closed
