### ISSUE TITLE
Create Stable Block Set

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#782]
Have a new "Stable" block set in the same package as the Undroppable, Machine, etc.

The idea behind the "Stable" set is that it will consist only of blocks that stay in place without any changes. So, this excluded lava and water which spread out and flow. It also excludes gravel and sand which can fall. It's basically a subset of the Undroppable set. It should also exclude both types of pistons, since they also move. Exclude TNT as well.

There could be others I'm not thinking of.

**Comment by richeyme** [comment]
Removed: Flowing water, water, flowing lava, lava, piston, sticky piston, sand, frosted ice, ice, TNT, concrete powder, gravel, anvil, snow, snow layer
