### ISSUE TITLE
TWEAN Genotype that evolves its own block list

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#783]
We did this in Python (https://github.com/schrum2/EvoCraft-SCOPE/issues/6), but never did it in Java.

Currently, when a list of possible blocks is defined, the CPPN has to have a separate output for each one. This is a bit extreme. What we did in Python was allow the CPPN to have a fixed number of block outputs, but evolve which blocks were represented by each of those possibilities.

I think we can implement something like this by using the `ShapeInnovationGenotype` as inspiration. It is a combination of a CPPN and a  `BoundedRealValuedGenotype`. However, what we need here is a combination of a CPPN and a `BoundedIntegerValuedGenotype` where each int represents the index of a block in the available block set.

The new genotype can be called `MinecraftCustomBlocksGenotype`, but I worry that lots of changes have to be made to the existing code to handle it.  Each time a regular TWEANNGenotype is expected, we may need a special case to handle this new possibility instead.

**Comment by richeyme** [comment]
Looks like the lists of blocks evolves now. Here's what two separate generations looked like:
First:
![2022-06-10_15 52 04](https://user-images.githubusercontent.com/94399708/173148786-9b17ecf2-ce34-4852-86d0-38726b7e7590.png)

Second:
![2022-06-10_15 52 06](https://user-images.githubusercontent.com/94399708/173148845-bf3d2491-f1fa-41ef-9f41-b73bbcd6917d.png)
