### ISSUE TITLE
Different Approaches for Vector to Volume

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#786]
Before you start on this, change the way vector to volume works. Currently, the individual numbers range from 0 up to  (blocklist.length + 1). Change the range to simply be 0 to 1. When decoding the genome to create blocks, first multiple the number by  (blocklist.length + 1) before rounding down to determine the specific block. This will make the genome more tidy: everything ranging from 0 to 1. This will be the standard way that vector to volume works, but you will add an additional option. Test this before moving on.

Next:

Have a boolean command line parameter: "vectorPresenceThresholdForEachBlock"

If this is true, then instead of having (xrange*yrange*zrange) values in the vector you would have 2*(xrange*yrange*zrange) values.

Instead of looping through each index of the array and converting each one to a block, you would loop in increments of 2, where the first number of each pair is compared to the presence threshold to determine if the block is placed, and the second number determines the block (but only selecting from the block list ... no longer an extra option for AIR at the end). Since AIR is no longer an option, the second num of each pair would just be multiplied by blocklist.length instead of (blocklist.length + 1)

**Comment by schrum2** [comment]
By the way, when working on all of these, try using the ChangeCenterOfMassFitness on fairly small shapes (2 by 2 by 5). We need to work more towards evolving flying machines

**Comment by alejmedinajr** [comment]
So I think both approaches for vector to volume seem to work, and I tested both and they do not seem to break or interfere with each other.

**Comment by schrum2** [comment]
This could use more comments. Also, for any class you make, be sure to include a class-level javadoc comment that both explains the class, and mentions you as the author. Take credit for your work!

**Comment by schrum2** [comment]
I also found and fixed some bugs, but I think it works now. Still needs comments though.

**Comment by alejmedinajr** [comment]
Put more comments and a class-level javadoc comment.
