### ISSUE TITLE
Bedrock test chambers

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#795]
This is a new command line parameter that can be turned on and off.

With the change in center of mass fitness #794 #790 #792 it is in theory possible that a shape could leave the confines of the empty reserved area, despite the extra space between shapes. We previously discussed defining the change in center of mass fitness in a way that awarded the maximum score if the evaluated blocks went from being present to absent, since this would imply they had moved away a lot. However, a shape that leaves its space could interfere with neighboring shapes. I don't think this is happening yet, but we should be aware of the possibility.

So, this new option would do the following: encase each shape being evaluated completely in bedrock. I'm mainly thinking of this in the context of MAP Elites, since the shapes could be evaluated in one area inside these bedrock test chambers, before being transferred to the archive location in the world. Now, the shape could still fly away from the archive, but at least there we will eventually have the new regenerate option to help us #791

**Comment by schrum2** [comment]
Work together on this once all the Change in Center of Mass issues are complete

**Comment by schrum2** [comment]
Get all unit tests working before the bedrock test chambers, since the bedrock chambers have a chance of breaking the test results. We want to have some confidence that what we have works before complicating with the bedrock, which will probably require new tests (since the distance traversed will be different if shapes hit a bedrock wall)

**Comment by richeyme** [comment]
Issue #806 fixes this in a way that doesn't complicate the fitness. We shall consider this resolved
