### ISSUE TITLE
Support for evolved orientation in Vector to Volume Generator

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#797]
The "minecraftEvolveOrientation" Parameter already exists, and when it is true (as it default) then vector to volume should also evolve orientations. There are different ways to do this, but let's start with the easiest.

When this is set, each block has yet another number associated with it (therefore, if there is a separate presence number #786 then you could actually have three numbers per block, otherwise just two). This number is the orientation. It should be in the range [0,1] but you can multiply it by the number of orientations (6) and round down to get the index for the appropriate orientation.

**Comment by alejmedinajr** [comment]
Now evolve orientation is a possible parameter that can change the number of numbers associated with each block.
