### ISSUE TITLE
Minecraft CPPN that simply has one output to define the block ORIENTATION

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#800]
Very similar to #784 , but applied to the orientations instead of the block types.

**Comment by alejmedinajr** [comment]
Made a new command line parameter, `"oneOutputLabelForBlockOrientationCPPN" `. When this parameter is true, the CPPN will use only one output label for orientation as opposed to 6 output labels. This means that when this parameter and the other one made for #784 are both true, the CPPN will only have 3 output labels (presence, blocktype, and orientation).

I went ahead and tested this to verify and the number of output labels does match the expected number of output labels. Also the shapes generated still seem to have a good mix of differently oriented blocks.
