### ISSUE TITLE
Reduced set of possible orientations

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#801]
Let's have an option to only evolve with North and South as valid orientations for the blocks. This approach could be used with either the multiple outputs or the individual outputs, but we want to generalize as much as possible. This can be done by adding a single static method in the MinecraftUtilClass that gets the array of valid orientation directions. When using this new setting, it returns just North and South. Otherwise it returns every option, as usual.

**Comment by alejmedinajr** [comment]
I made the new `MinecraftUtilClass  `as described above, and it is now being used in `VectorToVolumeGenerator`. After running and testing it, it seems to work (as intended) both when the new command line parameter, `"minecraftNorthSouthOnly"` , is true or false.
