### ISSUE TITLE
ChangeCenterOfMassFitness needs higher max fitness if change accumulates

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#804]
In `ChangeCenterOfMassFitness`, when `minecraftAccumulateChangeInCenterOfMass` is true, the `maxFitness` needs to be higher. 

`minecraftMandatoryWaitTime / shortTimeBetweenMinecraftReads` rounded UP (or rounded down then add 1) is either equal to of slightly more than the number of times a number is added to `totalChangeDistance`. So, multiply the number of times by newly added `overestimatedDistanceToEdge()` to determine the max fitness, but only when `minecraftAccumulateChangeInCenterOfMass` is true

**Comment by richeyme** [comment]
Also tested change in position for the flying machine and that is also awarded the right max fitness too. This seems to work now
