### ISSUE TITLE
Batch files for different shape sizes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#809]
So far, only the count-negative binning scheme has been successful in producing flying machines. However, these batch files also differ from the others in that they evolve slightly smaller machines (due to whatever restriction is causing the problems we see in #788). Change ALL currently existing Minecraft batch files that use the other binning schemes to have the same x/y/z range settings as the count-negative batch files.

Once this is done, it would be good to test out evolution of vectors with the WHD and Count binning schemes to see if being restricted to a smaller space helps.

**Comment by alejmedinajr** [comment]
I have gone through and changed the batch files and their ranges. I will run the tests suggested in the issue thread when the current tests that I am running are complete.

**Comment by alejmedinajr** [comment]
The new batch files mentioned earlier in this issue thread are currently being run with the new x/y/z ranges (both without NorthSouth orientation restrictions).

**Comment by alejmedinajr** [comment]
The run for vector count produced flying machines and ended up causing a traffic jam. The fitness plot looks like this: 
![vectorCount21fitnesslog](https://user-images.githubusercontent.com/100097809/175329179-c4a60086-07ad-43ea-84a8-ff6a9b00575b.png)

**Comment by alejmedinajr** [comment]
The run for vector whd did not produce flying machines and also did not produce anything interesting or diverse. In fact, the fitness was nearly the same all the time. Here is the fitness plot and an image of what type of shape was being produced.
![VectorWHD21](https://user-images.githubusercontent.com/100097809/175329701-f24de7f0-eb99-498a-8f4b-2ca23c4c17da.png)
![VectorWHD21fitnessplot](https://user-images.githubusercontent.com/100097809/175329706-6dc35655-779c-4797-bff0-6b7ffbacee6a.png)

**Comment by alejmedinajr** [comment]
Both of these runs were with the new x/y/z ranges. They also did not restrict the orientation.
