### ISSUE TITLE
Comment ThreeDimensionalObjectBreederTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#81]
After completing #80 repeat the process for ThreeDimensionalObjectBreederTask.

**Comment by schrum2** [comment]
I just reassigned this to @DevonFulcher since he will need to look at this code anyway in order to generate 3D shapes in the Infinite Art Gallery. If you are going to be looking at the code anyway, please comment it. Go ahead and do this in the dev_neatcreative branch (not really in use, but this is the most appropriate place for that code)

**Comment by schrum2** [comment]
Here is your first issue. As you can see, it has been around a while and changed hands a bit. Start by executing ThreeDimensionalObjectBreederTask. Once you have read the animation breeder paper by Isabel, this should make more sense. Go through attempting to comment it, and feel free to communicate with me frequently on Slack about any uncertainty regarding what parts of the code do. Create a NEW branch off of dev for addressing this issue

**Comment by DevonFulcher** [comment]
It's exciting to see more work on this codebase! Good luck @cappsb!
