### ISSUE TITLE
Directional Binning Scheme

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#812]
We want flying machines to fly in all directions. Therefore, our binning scheme should encourage this.

First, changes to `ChangeCenterOfMassFitness` will be required. Basically, when we measure the change in center of mass, are can also measure the movement in the individual x, y, z directions. For example, to get the movement in the x direction, you just compare the initial average x value to the average x value after movement. This is already being calculated, but the details get discarded to calculate the change in the center of mass.

I'm going to need to think a bit about the best way to retrieve this information while only evaluating the flying shape once.

However, this will eventually lead to a 3D binning scheme that categorizes shapes differently based on whether they move up/down/left/right/forward/back

**Comment by schrum2** [comment]
We'll probably need to work together on this. I'm not sure of the best way to go about it yet

**Comment by schrum2** [comment]
Step in the right direction, but not fully working yet. See this:
![image](https://user-images.githubusercontent.com/8397236/176225745-d7c18d25-6e4f-4369-8547-a5d65461d07a.png)
The extreme edges should only be reserved for shapes that move a lot, not a slight piston nudge. In fact, I'm not fully convinced that the shapes in the given locations exhibit displacement in the correct dimension.

**Comment by schrum2** [comment]
More progress made. Needs unit tests now. Try to avoid actual Minecraft simulation.

**Comment by richeyme** [comment]
Batch file runs without crashing. Also, the tests that I have made so far pass.

**Comment by richeyme** [comment]
Checked the experiments that ran overnight and none created flying machines. There is a lot of dynamic movement within each machine but no flying

**Comment by schrum2** [comment]
I was running this binning scheme and noticed some oddities. First, only a core 3 by 3 block worth of bins in the archive ever seem to get filled. Adjusting the binning rules could change this, but perhaps the problem is that evolution simply wasn't producing anything that really belonged in the outer bins. However, even though the binning was fairly localized, several shapes that were not flying were being awarded the max fitness. This might indicate more problems with the change in center of mass fitness (which just went through some changes after all), but I'm hoping the problem was actually the result of a server that was already crowded with blocks that were not properly eliminated. I started a new server and am re-running the experiment now to see what happens.

**Comment by schrum2** [comment]
Quickly stopped the new runs as soon as it was apparent that change in center of mass is the problem, so I made this issue #827 .

Once that issue is resolved, can return to evaluate this binning scheme.

**Comment by schrum2** [comment]
Although the change in center of mass seems to be fixed, I've sort of given up on this binning scheme in favor of #822 . However, a test run of this did produce some flying machines, even though the specifics of how the shapes were binned seemed questionable. Going to close this.
