### ISSUE TITLE
Minecraft Instructions

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#821]
Make a file Minecraft.md in the root project directory that contains instructions for interacting with the Minecraft server via EvoCraft. Explain that the needed files are in the `data` subdir, and how to copy from the backup to the standard directory and launch the first time, then fill out the eula, etc.

Then, mention that shapes can be evolved in Minecraft with MAP Elites and mention one of the batch files that can do this. Then, explain that the shapes are evaluated in one region out of sight but placed in the archive in a different region and organized according to location in the archive. Then explain what the diamond, emerald, obsidian, and gold blocks are for.

**Comment by MuellMark** [comment]
I typed up all of the instructions and then ran them through google docs to check for spelling ang grammar. I tried to go into as much detail as possible to avoid confusion, but I'd be happy to make any edits as needed, closing for now, but can be reopened for alterations

**Comment by schrum2** [comment]
For text representing code, console commands, or other "compter-y" content, surround the text with backquotes to format, like `this`

**Comment by MuellMark** [comment]
Changed all of the computer-y content to have the` control e back quotes thing`. Also made a few minor adjustments. Closing for now but will reopen for any other edits to the markdown file

**Comment by schrum2** [comment]
Let's make the copying from backup to the regular server easier by creating a new batch file. In fact, @richeyme already made one that mostly does the job:
https://github.com/schrum2/MM-NEAT/blob/dev/batch/Experiments-2022-MinecraftFlyingMachines/ResetServerWorld.bat
Make a batch file similar to this in the directory EvoCraft-py that copies over content from the backup. This will allow you to change the instructions to simply running this batch file (but still explain that what it does is copy stuff from the backup dir).

Note that in a fresh install, the eula file will not be there until the server has been launched once, so launch once with the batch file, then change the eula, then launch again.

Also, the rcon message mentioning C:\schrum2MM-NEAT is clearly specific to your machine, so this should not be in the readme. Find a way to be more general in the instructions.

Put a link in here somewhere to the original EvoCraft-py GitHub repo for people that want more info.

You also need to say that Python is required, and that the my_python_path.txt file has to be set up as explained in 
https://github.com/schrum2/MM-NEAT/blob/master/TUTORIAL.md

Lastly, within TUTORIAL.md itself, under OTHER DOMAINS, mention Minecraft and link from there to this document (while looking at TUTORIAL.md, check to make sure it all makes sense)

**Comment by MuellMark** [comment]
I've added all of the things specified above to both of the markdown files and then ran them each through google docs for spellchecking. I've also added the new batch file that resets the world, but not the player's settings, making it very fast and convenient to reset the world. Closing for now, but can be opened for any other additions or edits that need to be made
