### ISSUE TITLE
Change in Center of Mass: Make sure flying machines get best fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#823]
An experiment I ran last night reveals that shapes that oscillate a lot can receive a higher fitness than ones that fly away, but leave a significant number of blocks behind (more than the leftoverMinecraftBlocksAllowed). This seems wrong. So, here is a new idea:

I think this approach will involve deleting the leftoverMinecraftBlocksAllowed parameter. What we do it track the change in center of mass as usual, but we also track the number of blocks at each point where we read the cubes. If the total number of cubes being read decreases then we assume that at least part of the shape has flown away (more on this in a moment) and award the maximum fitness, but to encourage all of the shape to fly away we also subtract from the fitness the number of remaining blocks.

This means that flying machines will be better than all non-flying machines, but that it is still possible for some flying machines to be better than others.

Also, simply checking for a decrease in the number of blocks might not apply to only flying machines. For example, some machines might be able to statically push 1 or 2 blocks outside of the read area without actually flying, so we should probably have a minimum requirement for the number of blocks that need to disappear before we count a machine as flying. So, although we are deleting the leftoverMinecraftBlocksAllowed parameter, we are adding something new ... call it minecraftFewerBlocksBeforeConsideredFlying

**Comment by richeyme** [comment]
The new changes work and should properly punishing flying machines that leave blocks behind
