### ISSUE TITLE
Batch file to reset server from backup

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#826]
`EvoCraft-py-Backup` never changes and `EvoCraft-py` is the Minecraft world that does change. The user is meant to copy over files from `EvoCraft-py-Backup` to `EvoCraft-py` to reset the server if needed. This process should be made as easy as double-clicking on a batch file. I want the file to be located in `batch\Experiments-2022-MinecraftFlyingMachines`. Note that the `EvoCraft-py` dir should not be deleted. Simply copy the files from `EvoCraft-py-Backup` into it, overwriting files with the same name.

**Comment by richeyme** [comment]
The batch file works in resetting the world
