### ISSUE TITLE
JUnit tests for GraphicsUtil

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#83]
This is an important class with a lot of static utility methods used by Picbreeder, among other things. I'm not really sure how practical it would be to unit test the methods in this class. Proper tests for certain methods may be infeasible, but it should be possible to write tests for at least some of the methods. 

Create a test file and test what you can, and also make comments regarding methods that seem improper/impossible to test. In these cases, talk to me to see if we can think of a way to write tests between the two of us.

Also, important note: GraphicsUtil is in the edu.southwestern.util.graphics package under src/main/java. However, Maven stores JUnit tests in the same package, but a different subdirectory: src/test/java. Make sure you place the test file in the right location.

**Comment by schrum2** [comment]
Move the `rotateBackgroundImage` image method into the `GraphicsUtil` class and unit test it as well. However, it also needs a more descriptive name ... perhaps `extractCenterOfDoubledRotatedImage`

**Comment by schrum2** [comment]
@annazwicker So, after looking more carefully at this, I understood what you were asking better. The `imageFromINDArray` method is in the `GraphicsUtil` class. The reason that `testImageFromINDArray` is in the `GraphicsUtilTest` class is because the test class was autogenerated to have a test method for each method in the `GraphicsUtil` class.

Note that `INDArray` is not actually an array, so you cannot use `assertArrayEquals`. However, the point of the test is to create an `INDArray` and use the `imageFromINDArray` method to create a `BufferedImage`, and then use `assertEquals` to compare it to the expected `BufferedImage`.

**Comment by annazwicker** [comment]
The methods requiring a CPPN (all of the imageFromCPPN methods, zentangle methods), saveImage, imageFromIND array, and remixed image from CPPN.  The other methods are done (17 total currently).  The images inside the tests need to be saved, reloaded, and then compared.  Also need to force commit the images produced by the CPPN.

**Comment by schrum2** [comment]
@annazwicker In general don't commit things in a state where the unit tests fail. Comment those tests out before committing so that the code will still Maven compile

**Comment by annazwicker** [comment]
All methods we can reasonably test in GraphicsUtil run successfully!!!

**Comment by schrum2** [comment]
There is a unit test that needs fixing.

**Comment by annazwicker** [comment]
Fixed the FlatFeatureArrayFromBufferedImage test and Maven Install was a success.
