### ISSUE TITLE
Create Minecraft Shape Based on Block List

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#832]
Minecraft with MAP Elites outputs text files formatted like this
```
[STICKY_PISTON at (29,34,29) oriented NORTH, OBSERVER at (29,34,31) oriented DOWN, STICKY_PISTON at (29,34,32) oriented UP, OBSERVER at (29,35,31) oriented EAST, PISTON at (29,36,31) oriented NORTH, SLIME at (29,36,32) oriented EAST, QUARTZ_BLOCK at (29,37,29) oriented NORTH, PISTON at (29,37,30) oriented DOWN, REDSTONE_BLOCK at (30,34,31) oriented NORTH, SLIME at (30,34,32) oriented SOUTH, SLIME at (30,35,29) oriented EAST, QUARTZ_BLOCK at (30,35,30) oriented SOUTH, STICKY_PISTON at (30,35,31) oriented NORTH, PISTON at (30,36,29) oriented EAST, STICKY_PISTON at (30,36,30) oriented UP, OBSERVER at (30,36,31) oriented NORTH, REDSTONE_BLOCK at (30,36,32) oriented DOWN, OBSERVER at (30,37,29) oriented WEST, OBSERVER at (30,37,30) oriented DOWN, STICKY_PISTON at (30,37,31) oriented DOWN, OBSERVER at (30,37,32) oriented WEST, QUARTZ_BLOCK at (31,34,31) oriented UP, SLIME at (31,34,32) oriented WEST, STICKY_PISTON at (31,35,32) oriented DOWN, QUARTZ_BLOCK at (31,36,31) oriented EAST, OBSERVER at (32,36,30) oriented WEST, OBSERVER at (32,36,32) oriented UP, STICKY_PISTON at (32,37,29) oriented EAST, STICKY_PISTON at (32,37,31) oriented UP]
```

Currently, there is a post eval experiment that will load a particular evolved Minecraft shape, but it does this by loading the genome and the simulation params, etc. I want something simpler.

Write code that just takes a text file that looks like what we have above, and parses it to figure out all of the blocks, and converts it to a spawnBlocks command that places blocks in the world.

We'll talk about the details of making an experiment class to handle this from the command line later. For now, make a method in the MinecraftUtilClass that takes the name of such a text file, and then loads and scans it (with a Scanner) to decipher all the blocks to send to spawnBlocks.

**Comment by schrum2** [comment]
In the package `edu.southwestern.experiment.post` create `MinecraftBlockRenderExperiment`.

It needs to implement `Experiment`.

There needs to be a brand new command line parameter "minecraftBlockListTextFile" that is associated with this. Its default value is the empty string "" but it can be set to the path of a file to load blocks from.

Once this exists, you can test it by running a main method that launches it via a call to the MMNEAT main method. Once that works, then you can make a batch file

**Comment by alejmedinajr** [comment]
The method in the util class that parses a file to get blocks has been created, and seems to work, however this is without testing with spawning the actual blocks. I have created the new experiment class, `MinecraftBlockRenderExperiment`, but the methods are currently empty. I will work on this tomorrow.

**Comment by alejmedinajr** [comment]
I created a batch file that spawns the blocks, it is in the minecraft experiment directory (where the reset world batch file is). It successfully spawns the blocks in the world that matches what the output file has.

**Comment by schrum2** [comment]
Please modify this so that the only parameter that needs to be passed is the `minecraftBlockListTextFile`. Basically, the batch file will be hard-coded to use the `MinecraftBlockRenderExperiment`.

I want the user to be able to launch the code with a command like this:
```
SpawnMinecraftBlocks.bat minecraftaccumulate/MEVectorPistonOrientation0/archive/NS0EW0UD1_0.56279_10384.txt
```

It's possible MM-NEAT will complain about the lack of a task being specified, but there are ways around this. I want to avoid having to specify the base, log, saveTo, etc.

Also, please place the batch file in the root MM-NEAT dir and rename to "postSpawnMinecraftBlocks.bat"

**Comment by alejmedinajr** [comment]
I moved the batch file in the root of MM-NEAT, and I renamed it to `postSpawnMinecraftBlocks.bat` as well. Also, now only one parameter needs to be sent for this to successfully work.
