### ISSUE TITLE
Comment RTSFitnessFunction

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#84]
Before getting too deep into StartCraft, I want you to look at and comment some of the code Alice wrote for microRTS, a simplified RTS domain. I think a reasonably easy file to start with is: RTSFitnessFunction.

Look through the code and try to provide sensible comments. If you are unsure what something does, then provide a comment (with your name) indicating why you are confused, and what needs to be clarified. You can also ask me for help.

Always when looking at the MM-NEAT code, keep an eye out for interesting code tricks you can use elsewhere.

**Comment by Squillyprice01** [comment]
I added comments to this file.
