### ISSUE TITLE
Comment MinecraftShapeTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#847]
Find `edu.southwestern.tasks.evocraft.MinecraftShapeTask` and comment parts that need it, and also fix or suppress warnings as appropriate.

Remove un-needed imports.
Add a JavaDoc header to the class itself (do a best guess and describing its purpose ... it is for evolving populations of shapes in Minecraft). 
Add/fix JavaDoc for methods that need it (feel free to ask me questions!)
Note that methods with an `@Override` don't need JavaDoc, but some methods might need the `@Override` added, and methods that are overridden might still need some body comments.

Try to understand all of the code, ask me about what doesn't make sense, and ad body comments to explain the parts that did not initially make sense.

**Comment by TjRaffert** [comment]
Added comments that were needed to MinecraftShapeTask
