### ISSUE TITLE
Comment MinecraftLonerShapeTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#848]
Find `edu.southwestern.tasks.evocraft.MinecraftLonerShapeTask` and add additional comments where needed.

Any method that does not have a `@Override` needs JavaDoc, though there might be some methods that should have an `@Override` but are missing it. Also, any inner classes need JavaDoc headers too. The code is already fairly well commented, but if things don't make sense to you, ask me about them and then add comments that clarify, so that a future reader of the code would not have the same questions you had.

**Comment by JoannaBlatt** [comment]
Commented on several classes and fixed typos. Added overrides when needed.
