### ISSUE TITLE
Comment rest of files in edu.southwestern.tasks.microrts.fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#85]
After completing #84 go ahead and move on to the rest of the files in the edu.southwestern.tasks.microrts.fitness package. These will give you some ideas of how we tried to assign/track fitness in an RTS domain. We may use some of these ideas in StarCraft, though we may also do something different.

Regardless, comment the code and try to make sense of it.

Note: to better make sense of these fitness functions, you may want to run some of the microRTS batch files and look at the fitness plots. In fact, I definitely recommend running these batch files and doing post evolution observation of the behavior just to get more familiarity with the MM-NEAT code.

Look in batch\MicroRTS and batch\MicroRTS-Experiments

**Comment by schrum2** [comment]
Every issue that you work on should have an issue comment by the end of the day. Is this issue done or still in progress? If done, then you can close it. Also don't forget to use the issue number in associated commit messages.

**Comment by Squillyprice01** [comment]
The logic changes did passed testing.
