### ISSUE TITLE
Javadoc for all classes in edu.southwestern.tasks.evocraft.blocks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#851]
The classes in the `edu.southwestern.tasks.evocraft.blocks` package are all short and simple, and don't need much in the way of comments, but a few need to have some kind of simple class JavaDoc comment added, so make sure each one has this.

Also, this might spur you to think about other types of block sets that could be interesting to work with.

**Comment by TjRaffert** [comment]
#851 Added simple comments to block sets that needed it.
