### ISSUE TITLE
Comment PistonCountFitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#853]
Note that although this is called a fitness function, it is actually used as part of a behavior characterization in practice. Everything that is a "fitness" is just a way to assign a number to a shape, and behavior characterizations are mostly collections of such numbers.

This class has no comments, but it needs both JavaDoc and body comments to explain what it does.

**Comment by JoannaBlatt** [comment]
Finished adding JavaDoc comments
