### ISSUE TITLE
Make Expanded Machine BlockSet

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#855]
Make `ExpandedMachineBlockSet` that is the same as `MachineBlockSet` except that it adds both the Honey and Leaf blocks

**Comment by schrum2** [comment]
We just realized that Honey was not added to Minecraft until version 1.15, but the EvoCraft API functions on version 1.12, so Honey is not available.

Since the new block set will only have the Leaf block added, just call it `LeafMachineBlockSet` instead. However, since there are both `LEAVES` and `LEAVES2`, we need to see what these actually are first to decide which one to add, or possibly to add both. You can boot up a server and use the send and receive script to just add these blocks to a game world and take a look at them

**Comment by TjRaffert** [comment]
Going with LEAVES (119) instead of LEAVES2 (120) only cosmetic differences. Let's add a log because leaves don't persist without something attached with the log tag. There were two options for the logs LOG(oak 131) and LOG2 (Acacia 132). Me and Joanna think LOG2 looks better. Let's call it natureMachineBlockSet.

**Comment by TjRaffert** [comment]
Issue #855 created block set natureMachineBlockSet which is machineBlockSet with a leaf block and log block added.

**Comment by TjRaffert** [comment]
@schrum2 when I committed, I had commit all changes that affected two other files. Can you just accept the new file natureMachineBlockSet.java and not the others? Or do I have to figure out how to decommit all the changes?

**Comment by TjRaffert** [comment]
There will be commit irregularities in .classpath and MinecraftClient.java.
