### ISSUE TITLE
Reward Speed in ChangeCenterOfMassFitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#856]
Currently, `ChangeCenterOfMassFitness` doesn't care about the speed of the machine. It does penalize flying machines for the number of blocks left behind. However, we could find a way to either punish machines for being slow, or reward them for being fast.

Any changes made to this class should maintain backwards compatibility with the experiments conducted previously, so the use of speed in the fitness should be an option that can be turned on and off. Therefore, start by adding a boolean parameter to `Parameters.java` called "rewardFastFlyingMachines" whose default value is false.

If this parameter is true, then the following line from `ChangeCenterOfMassFitness` should be changed. Specifically, change:
```
totalChangeDistance += lastCenterOfMass.distance(nextCenterOfMass);
```
so that instead of adding the distance between the next center of mass and the last center of mass, it adds the distance between the next center of mass and the starting, original center of mass. Remember to only do this if "rewardFastFlyingMachines" is true and use the old method otherwise. The reason for this change is that it rewards getting farther away from the starting point sooner. Since the reward accumulates, shapes that move faster will add up a series of values that are larger than those of a slow moving shape.

Note that when "rewardFastFlyingMachines" is true, the maximum fitness also needs to be calculated differently, in a way that takes the shape into account (not just a flat max fitness for any flying machine). This new setting should also discourage the leaving behind of blocks, since left over blocks will hurt the center of mass calculation, meaning it won't be favored.

**Comment by JoannaBlatt** [comment]
Changed variable name to minecraftRewardFastFlyingMachines
added if statement modified totalChangeDistance
added tests cases to test current functionality of speed reward and finished commenting changes

**Comment by schrum2** [comment]
I want this batch file to run for a while before closing the issue. I worry that we'll still get a situation where, once machines start flying, they'll all have the same max fitness value. So, it's possible that we'll have to modify the batch file slightly to increase the size of the evaluation area, so that flying machines are unlikely to escape it.

**Comment by schrum2** [comment]
By running this over night, we discovered that shapes are still hitting the edge of the evaluation area and getting the max fitness rather than exhibiting a range of scores based on their movement speed.

Change the batch file used for this to have double the value of `spaceBetweenMinecraftShapes` and run that to see if it results in a difference.

**Comment by schrum2** [comment]
Currently testing a value of `spaceBetweenMinecraftShapes` = 30. Tried smaller but still got flat max fitness for flying machines. We need to keep increasing until the machines differentiate themselves in terms of fitness.

**Comment by JoannaBlatt** [comment]
Has not successfully evolved a flying machines yet

**Comment by schrum2** [comment]
It seems like it was close though. Technically, we got some flying machines when the spaceBetweenMinecraftShapes was smaller, but this maxed out the fitness. Right now, we're trying a longer evolution time along with the larger value of spaceBetweenMinecraftShapes. We want to see flying machines that do not escape the evaluation area, but that also means we need a way of noticing the existence of these machines without depending on the fitness score to tell us.

**Comment by schrum2** [comment]
These "fast machine" runs hit the fitness ceiling again. We could keep increasing the space between shapes, and that is what we are focusing on.

However, I did see this code in the change center of mass fitness function:
```
if(shortWaitTimeUpdate.isEmpty()) { // If list is empty now (but was not before) then shape has flown completely away
	if(CommonConstants.watch) System.out.println(System.currentTimeMillis()+": Shape empty now: max fitness! Last center of mass = "+lastCenterOfMass);
	return new Triple<>(initialCenterOfMass, lastCenterOfMass, maxFitness());
}
```

If the latest fast run with a space between of 50 doesn't give us the result we want, then we should change this code. If the setting for rewarding speedy/fast machines is on, then instead of returning a `Triple` with the max fitness, we should add the `overestimatedDistanceToEdge()` to the `totalChangeDistance` and skip over the rest of the code in the loop. This will allow fast machines to differentiate themselves from others even if they leave the evaluation area.

However, if we add this setting, we will also have to increase the `maxFitness` in the case where the fast fitness function is being used.

**Comment by schrum2** [comment]
Actually, running with a space between of 50 crashed the server pretty much immediately, so we're using a space between of 40 instead. The code is running, but it may hit the max fitness barrier, which means we'll have to attempt the proposed solution above. However, Some of the guidance here is already changing because of the many refactoring changes happening due to #875

**Comment by schrum2** [comment]
The place to chance code for this now is inside of the `earlyEvaluationTerminationResult` method of `ChangeCenterOfMassFitness`, assuming that a cleared space of 40 is insufficient.

**Comment by schrum2** [comment]
Although we did get some differentiation in fitness, and some machines could fly without reaching max fitness, we still need to differentiate further. 

if "minecraftRewardFastFlyingMachines" is true, then `earlyEvaluationTerminationResult` should return false immediately.

However, you also need to change `calculateFinalScore` so that if "minecraftRewardFastFlyingMachines" is true, and in the loop either `history.get(i).t2` is empty or the center of mass is not changing and `checkCreditForDepartedBlocks` grants credit, then you add up the max fitness on each iteration of the loop

**Comment by schrum2** [comment]
Some comments are needed, and you also need to test this new fitness calculation out by running an experiment.

**Comment by JoannaBlatt** [comment]
We tested for speed fitness and got a range of scores. When testing a 75 fitness machine with a 236 fitness machine side by side there was no difference in speed. It seems to be hard to make slower machines, all fitness machines seem to go at the same speed. Lots of flying machines in lower score ranges after creating a larger extraspacebetweenshapes and upping the spacebetweenshapes. Does not seem capable of producing faster machines. Would have to find a way to produce slower machines.
