### ISSUE TITLE
Comment/Refactor MinecraftBlockRenderExperiment and MinecraftBlockEvaluateExperiment

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#861]
In `MinecraftBlockRenderExperiment`, provide better comments for `generateOneShapeFromFile` and make the method `static`. The `shiftBlocks` method should also be `static` and you should remove the `private` (don't make it `public`, just remove the `private`). Then give it a JavaDoc comment. Give body comments to the earlier code as well.

Then go to `MinecraftBlockEvaluateExperiment`. Remove `generateOneShapeFromFile` and `shiftBlocks` (you can call `MinecraftBlockRenderExperiment.shiftBlocks` when needed). Also, thoroughly comment the code. Fix any warnings by modifying the code (do not simply suppress them).

**Comment by schrum2** [comment]
So the commenting part of this first

**Comment by TjRaffert** [comment]
Finished commenting for MinecraftBlockRenderExperiment. Finished clean-up and code adjustments to MinecraftBlockEvaluateExperiment.
