### ISSUE TITLE
SPECIAL_CORNER is a stupid name

### ISSUE THREAD

**Issue by JoannaBlatt** [schrum2/MM-NEAT#872]
This is a terrible name and needs to be fixed. It's currently declared in minecraftClient and used in so many things

**Comment by schrum2** [comment]
Refactor/rename it to POST_EVALUATION_CORNER.

The purpose of this corner is that it is a place to put shapes that are being evaluated after a completed evolution experiment, typically by using a batch file whose name starts with "post"

**Comment by JoannaBlatt** [comment]
Finished refactoring these two variable names
