### ISSUE TITLE
Make Unit Test for the Water/Lava Fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#874]
I just made a file: `WaterLavaSecondaryCreationFitnessTest`. Note that this is within the test subdir rather than main.

Compare with `ChangeCenterOfMassFitnessTest`, then make some tests that generate basic shapes with Water and Lava that produce a known or approximately known number of cobblestone and/or obsidian blocks so that you can do an assertEquals on what the final fitness value should be.

**Comment by JoannaBlatt** [comment]
Maybe rename WaterLavaSecondaryCreationFitness to WaterLavaCobblestoneObsidionCreationFitness

**Comment by schrum2** [comment]
I mostly fixed this. There was an issue with running multiple servers, and also a problem with the clear area being too big. I fixed all but one of the tests, which is completely commented out. Fix that one test, verify that everything can Maven install, and then you can close the issue again.

**Comment by schrum2** [comment]
Seems to work!
