### ISSUE TITLE
Option to tweak POST_EVALUATION_CORNER

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#878]
The former SPECIAL_CORNER is now called POST_EVALUATION_CORNER and is defined in `MinecraftClient`. Make a parameter "minecraftPostCornerAdjustY" whose default value is 0. This is an int parameter whose value will be added to the y-coordinate of the POST_EVALUATION_CORNER, to make it easier to adjust where the special shape shows up.

**Comment by TjRaffert** [comment]
Fixed this issue and committed the changes.
