### ISSUE TITLE
Water/Lava Count Characterization

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#879]
Do a behavior characterization for Water/Lava experiments that creates a 2D archive:
number of water blocks vs number of lava blocks.
This would count the numbers of these blocks in the original shape, not the result after simulation.

Can model off of `MinecraftMAPElitesRedstoneVSPistonBinLabels`

**Comment by schrum2** [comment]
IF the new CMA-ME batch file from #876 is able to run without crashing right away, then also make a batch file for this Water vs Lava approach that uses CMA-ME instead of plain MAP Elites.

**Comment by schrum2** [comment]
CMA-ME did not result in great coverage, so running with SBX now

**Comment by schrum2** [comment]
SBX also not much better. To some extent, it makes sense that it's hard to cover the space, since Water and Lava are each just one block out of 7 or so, but we should be able to get more variety somehow.

So, try one more experiment (don't need a batch file, just a main method in some class) where you use the now fixed water/lava count characterization, but the fitness function is simply `NumLavaFitness`. This should at least drive evolution to fill out one axis of the 2D archive.

**Comment by TjRaffert** [comment]
![Screenshot 2023-06-05 154502](https://github.com/schrum2/MM-NEAT/assets/111467145/09a1bd49-f4fc-44d9-a4a7-e3746f9c3066)

**Comment by TjRaffert** [comment]
This is the final result. It should have been able to explore more lava blocks better.

**Comment by schrum2** [comment]
Try this with integer-based encoding ( #886 ) too

**Comment by TjRaffert** [comment]
![Screenshot 2023-06-05 163041](https://github.com/schrum2/MM-NEAT/assets/111467145/2f1fb0cf-b62f-405c-8556-0696a38e98ef)

**Comment by schrum2** [comment]
Try a similar experiment with a new block set that only has two possible blocks (one might already exist, but you can make one if needed) and use a fitness function that tries to maximize just one of those blocks with the type count fitness. This should have a better chance of succeeding.

**Comment by schrum2** [comment]
I had to produce 200000 individuals to get these results, and although they are better, they are still not great:

![Testing-TESTING90_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/681e07e6-28b6-410c-beef-1d09ce714124)

I'm going to change the mutation scheme

**Comment by schrum2** [comment]
Tried turning polynomial mutation off, but didn't get much better results

![Testing-TESTING99_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/b4f1d26e-1107-4c98-bf4b-aa27e07f77c1)

**Comment by schrum2** [comment]
The higher mutation rate basically had no effect

![Testing-TESTING99_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/f2ca04b3-1748-41a7-be28-2c1879921e25)

**Comment by schrum2** [comment]
The new theory is that if too many indices mutate at the same time, then it is hard to push the search in any one specific direction. So, the new `numVectorIndexMutations` option can limit the number of indices in a genotype that are modified by a single mutation. Applied to both real vectors and int vectors (with some code repetition unfortunately), and am testing with real now. Might work better with int encoding though

**Comment by schrum2** [comment]
Being restricted to just one index per mutation did not help with real-valued genotypes. Try integer based

![Testing-TESTING99_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/3366f8c3-9cda-436e-9240-43f05322c407)

**Comment by schrum2** [comment]
I think we're finally seeing a bit of improvement when we only allow a mutation to change one index of the genotype at a time.

![Testing-TESTING99_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/35d68160-ccef-457f-9bf6-667ee9efca72)

**Comment by schrum2** [comment]
This has inspired a new genotype encoding #899 

This issue can be closed.
