### ISSUE TITLE
Missile Batch files for above

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#880]
We already have batch files for the missile task where the target is below and to the side. Make one where the target is directly above the shape. That could post a challenge to destroy.

**Comment by TjRaffert** [comment]
Running this batch file right now will update and close the issue when finished.

**Comment by TjRaffert** [comment]
I ran it and it did pretty well. It was able to destroy half the shape in almost all the bins. I took a video of it and posted it.
