### ISSUE TITLE
Problem with call to clearAndVerify

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#882]
In `TimedEvaluationMinecraftFitnessFunction` there is a call to `clearAndVerify` that takes the wrong version of corner, but when it is corrected to the right version of corner it breaks some unit tests. However, the tests do not fail with a wrong value (at least, not yet), they simply crash because the clear command tries to clear a negative coordinate. The parameter to `clearAndVerify` should be changed as will be clarified in an upcoming commit, but this will also require fixes to some unit tests that have parameters set wrong.

**Comment by JoannaBlatt** [comment]
I think the problem is in `MinecraftClient` , often an evaluation corner is being passed to clearAroundCorner but it uses the shapes corner. This is part of clearAreaAroundSpecialCorner as well. It directly passes the evaluation corner.
