### ISSUE TITLE
Update the instructions in Minecraft.md

### ISSUE THREAD

**Issue by JoannaBlatt** [schrum2/MM-NEAT#889]
These instructions are old and out of date. It would be good to go through and update them.

**Comment by schrum2** [comment]
@JoannaBlatt Any progress on this?

**Comment by schrum2** [comment]
Your version of the file seems to have lost all formatting present in the original, which is here:
https://github.com/schrum2/MM-NEAT/blob/master/Minecraft.md
The .md extension stands for Markdown, and it allows for certain limited control over formatting. I want to retain that formatting in the document. See here for info on Markdown:
https://www.markdownguide.org/cheat-sheet/

**Comment by schrum2** [comment]
Also, the teleport command seems to be missing from the new version. Granted, it was incorrect in the old version (missing the <username>), but it should still be here (and corrected)

**Comment by schrum2** [comment]
I would like some more work on this before we wrap up. Here are some important notes to share in this file:

When evolving shapes, the best place to do (after entering creative mode) is actually -100 100 -100. The current recommendation to go to 10 10 10 was only true when we were storing the whole archive in the world, but the actual shape evaluations happen around -100 100 -100.

Also, mention how to use the batch files `postSpawnMinecraftBlocks.bat`, `postSpawnMinecraftEvaluateBlocksCenterOfMass.bat`, etc. Mention that these will spawn shapes at -500 100 500.
