### ISSUE TITLE
Clear space outside of eval area

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#896]
I think it is pretty clear that a big area is initially cleared, but only the evaluation area gets cleared before each evaluation. This creates a slight problem if a shape gets cut off with blocks right outside of the eval area before the next one is evaluated. So, it would be nice to have a bit of an extra buffer around the eval area being cleared. However, simply clearing bigger areas causes other problems, so this extra clearing should probably just be targeted to where we think excess blocks are likely to be.

**Comment by JoannaBlatt** [comment]
created a function, needs to be implemented in functions and visually confirmed before closing the issue

**Comment by schrum2** [comment]
I think this still needs some kind of confirmation. Although we've switched to not using glass clearing anymore, it might be easier to get visual confirmation on this if you turn that back on. However, save this issue for the final days when we're sort of running out of things to do.

**Comment by schrum2** [comment]
I think this works
