### ISSUE TITLE
Change Center of Mass Fitness Broken

### ISSUE THREAD

**Issue by TjRaffert** [schrum2/MM-NEAT#904]
Recent changes to the Center of Mass Fitness function have made it incorrectly assign max fitness to machines that are not flying. Here are two examples.

[ID108_.txt](https://github.com/schrum2/MM-NEAT/files/11707240/ID108_.txt)
[ID109_.txt](https://github.com/schrum2/MM-NEAT/files/11707241/ID109_.txt)

**Comment by schrum2** [comment]
Fixed by filtering out AIR blocks at the start of evaluation, but this indicates that the direct representation has a problem #899
