### ISSUE TITLE
BCs for Canons

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#906]
Make a binning scheme/behavior characterization for canons that is num Obsidian vs num TNT and then make a batch file for it and test it out.

**Comment by TjRaffert** [comment]
Seems to be working properly. I had to reduce the number of threads to three because TNT causes a lot of strain on the server.

**Comment by TjRaffert** [comment]
With the threads down to 3 it has slowed down the test. Both are only a fourth of the way done. They should be done by Tuesday when we get back.

**Comment by TjRaffert** [comment]
![image](https://github.com/schrum2/MM-NEAT/assets/111467145/79d5bc7c-f1c5-453a-b5a7-03ec7890dde6)

**Comment by TjRaffert** [comment]
![image](https://github.com/schrum2/MM-NEAT/assets/111467145/bfea0e6f-0243-418c-9d32-f0d6d739953c)
This is for the target to the side.

**Comment by TjRaffert** [comment]
I also think one thing to note for these cannons in general is that I think it is only possible because of how we are spawning them in. We are using loops to spawn them in, so every shape is spawned at a different time. This allows for the variation in activation of the TNT. If every block was somehow spawned at the exact same time they would probably all explode but not be able to push any of the other TNT.

**Comment by schrum2** [comment]
I don't think this is accurate. Although a look adds each block to a block list, the blocks themselves are spawned via a single API call to the spawnBlocks command in the MinecraftClient, which corresponds to a similar command on the Python side. So, all blocks should be spawned at the same time. However, the timing of the snapshots is definitely nondeterministic, and even though Minecraft itself is supposed to be deterministic, the fact that you could spawn the same shape in different places or at different times could easily be enough on its own to affect the random number generator, and thus lead to the exact same shape exhibiting different behavior across multiple evaluations.

Regardless, observation is needed to track the variation in scores.

**Comment by TjRaffert** [comment]
The two tests I am running are using the new bin labels so they can't use postSpawnMinecraftEvaluateBlocksMissile.bat. Should I run an old test so we can examine it tomorrow?
