### ISSUE TITLE
Clean up comments in org.rlcommunity.environments.tetris

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#91]
This package already has a lot of comments, but the style is sloppy/inconsistent and there are still methods lacking javadoc header comments. Make sure every class, constructor, and method as a complete javadoc comment with all params and returns labelled. This is also a good opportunity to understand how Tetris runs in Java.

This code is actually written by someone called Brian Tanner, and is the RL Glue implementation of Tetris. I and others have made small changes to the code, but for the most part we want to leave it alone. Still, if you see potential for improved style, make a comment about it.

If you don't understand something in the code, make a comment asking a question with your name. You can also post follow-up questions on this GitHub issue thread.

**Comment by DevonFulcher** [comment]
I am not sure if my comments are sufficient. Would like some feedback.
