### ISSUE TITLE
Restrict sub-pop size for MOME

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#910]
@JoannaBlatt asked: "should we have a control for the number of individuals in a bin's population?" with respect to MOME #891 

The original MOME paper did indeed impose a restriction of this sort, but they mainly did it for optimization purposes. I think that we can avoid doing this, at least in our first implementation. However, it could be useful in the long run to have this option.

So, complete MOME #891 first without any kind of restriction on the size of each sub-population. Then, after that seems to work, add a command line parameter for "maximumMOMESubPopulationSize" with a default value of -1. We will interpret -1 as there being no restriction, but if the value is a positive number, then there is a limit on the size of each Pareto front sub-population.

If we are limiting the size, and a given front/sub-pop is bigger than the size, then randomly remove individuals from the front until the size is in bounds.

**Comment by JoannaBlatt** [comment]
Subpop log is working, excess code needs to be hunted down and deleted

**Comment by JoannaBlatt** [comment]
Cleaned all the code I could find. Should now be consistent. Logging is successful.

**Comment by JoannaBlatt** [comment]
When running in console it correctly restricts the subpopulation size, but when running MinecraftAccumulate-MOME-Observer-FlyVsMissileDirectSmallPOCapped.bat it does not seem to restrict the sub population size.

This needs more observation to understand.

**Comment by schrum2** [comment]
I have a separate capped MOME run in my office where the populations are also not being capped, so I think there is definitely a problem. I'm skeptical that the console run actually worked, so this needs to be revisited. Extra assertions could help track the issue down.

**Comment by schrum2** [comment]
Problem not fixed yet. Adding even more debugging code. Investigating alarming possibility that the method to filter down the bin population to a Pareto front isn't even working

**Comment by schrum2** [comment]
After a night of running with none of the assertions tripping, and seeing the results so far on bin population size, I'm reasonably sure the issue has been fixed:
![image](https://github.com/schrum2/MM-NEAT/assets/8397236/fcdaa839-fc02-492a-bd01-80ebef591f39)

It was a synchronization issue, which makes sense in retrospect. We'll have to monitor execution speed in the meantime. For now, I'll close this issue, but I'm sure we'll notice if it breaks again.
