### ISSUE TITLE
Implement shapeIsWorthSaving for the Missile Fitness and Cannon Fitness

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#914]
See #913 to see what this is about. A simple implementation of this will give you a way to save some evolved canons to help with #906

**Comment by schrum2** [comment]
Implement this and base it directly on fitness. Say that if 90% of the target is destroyed, then save

**Comment by TjRaffert** [comment]
We are getting kicked out of the lab soon so I will test when we have enough time.

**Comment by schrum2** [comment]
Lost track of this because of how things ended. What is the state of this issue now?

**Comment by TjRaffert** [comment]
I am running it with the 90% and I confirmed it works when I manually blow it up. It ran all night and didn't save any shapes. I may rerun it with the setting turned down to 60% so we can look at some results.

**Comment by schrum2** [comment]
If you complete #911 then we can get results at the end of evolution even if they don't earn high fitness, though this may take too long to be realistic. Still, it is another issue that is important

**Comment by schrum2** [comment]
Make the percentage be a command line parameter

**Comment by TjRaffert** [comment]
Somehow the line in parameters got deleted but I added it back. I had already tested it and it works. You have to adjust it based on the test you are running because some target orientations are much harder than others. I got some video of some of the results.
