### ISSUE TITLE
TNT Shapes evaluate twice?

### ISSUE THREAD

**Issue by TjRaffert** [schrum2/MM-NEAT#915]
Some tests we're running seem to show TNT shapes evaluating twice in a row. Why is this?

**Comment by schrum2** [comment]
This was actually affecting all timed evaluation fitness functions. There was a problem with a static variable giving misleading information about the number of timed functions when it came time to assess "fitness" functions associated with behavior characterizations. This caused already evaluated shapes to briefly appear again. Fixed
