### ISSUE TITLE
MOME crashing 

### ISSUE THREAD

**Issue by TjRaffert** [schrum2/MM-NEAT#916]
![image](https://github.com/schrum2/MM-NEAT/assets/111467145/2753d062-3e01-4ee7-9b09-8c22dfb7889c)
Crashes with this stack trace shortly after running.

**Comment by schrum2** [comment]
The array out of bounds only makes sense if the contents of the list change after the array is constructed, which can only happen if the list is changed in a different thread. Therefore, access to the list has been synchronized.

**Comment by schrum2** [comment]
Seems fixed
