### ISSUE TITLE
create MOMELog class

### ISSUE THREAD

**Issue by JoannaBlatt** [schrum2/MM-NEAT#919]
Create and abstract MOMELog class inside edu.southwestern.log to handle all logging. This will make all logs have the same convenience class for logging. Extends MMNEATLog class.

Create separate MOME log for each file created. A single MOME log is a file with numbers and corresponding gnuplot textfile. 

Will take an array of length number of bin labels/bins and takes the pseudoGeneration int. It will handle plotting the array. Calculations will still be done in other MOME classes. This is just for outsourcing logging.

Between logs the file plot and file name are the only differences. Same range of x values based on number of bins and y value based on pseudoGeneration.

**Comment by schrum2** [comment]
This issue is on hold. It might not be needed in light of recent clean up work done with logging in the MOME class

**Comment by schrum2** [comment]
No MOME Log needed
