### ISSUE TITLE
Benchmark Minecraft Evolution Speed

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#922]
I have concerns the the speed of evolution has greatly decreased, and I want to benchmark runs with different settings. The trick to doing this is to have a subdir in the batch directory called `MinecraftBenchmark` (don't even include year or "Experiments") that explores a lot of options. Importantly, all of these should have a greatly reduced `mu` and `maxGens`. Use the settings `mu:10 maxGens:100` in all of these files. Otherwise, the first file you make should be a copy of the GECCO batch file `MinecraftAccumulate-ME-Observer-VectorPistonOrientation.bat`, but rename it to `Baseline-NoGlass.bat`. Even though clearing with glass is now set false by default, explicitly set `minecraftClearWithGlass:false` in this file. Then make another file with `minecraftClearWithGlass:true` called `Baseline-Glass.bat`.

Run these on separate machines and note the start times. I think the simulation will report the total run time at the end, but try to track it yourself as well. I'll propose more benchmarking in conjunction with other issues, but let's first get a sense for how much glass slows things down.

**Comment by TjRaffert** [comment]
With gens increased to 1000
Glass got done: 11.4648 minutes
and no glass got 10.2395

**Comment by schrum2** [comment]
Running without glass seems way faster
