### ISSUE TITLE
Save info to make Pareto fronts in MOME

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#925]
In the MOME finalCleanup method, save several text files.

Save one txt file for each occupied bin in the archive that contains one column per objective, and each row represents the scores from a member of the Pareto front in that bin. The name of each file can incorporate both "ParetoFront" and the bin label.

Then save a text file in the same format that contains the Pareto front of the whole archive.

**Comment by JoannaBlatt** [comment]
Saves info of pareto front and correctly logs it
