### ISSUE TITLE
MOQD Score

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#927]
The MOME paper (https://arxiv.org/pdf/2202.03057.pdf) defines MOQD Score, or Multi-Objective Quality Diversity score. Quite simply, it is the sum of the hypervolumes of all occupied bins. This is an additional score that should be logged and plotted with a line plot from MOME.

**Comment by JoannaBlatt** [comment]
I did create logging for the total hypervolume of all bins together. Is that what this is supposed to be?
