### ISSUE TITLE
Log overall global hypervolume of whole archive for MOME

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#928]
Description is pretty clear

**Comment by JoannaBlatt** [comment]
Logs total hypervolume in archive log with other hypervolume logging

**Comment by JoannaBlatt** [comment]
I think we should move the total hypervolume to it's own log, since it is scaled in such a way that it obscures the other hypervolume information.

**Comment by JoannaBlatt** [comment]
Synchronization issue between logging and add method was found. Currently fixed by having the whole archive locked for both of them.

**Comment by schrum2** [comment]
I think we need to have all of the following on one plot:
- global hypervolume (should be largest)
- max bin hypervolume (second largest or tied with global)
- average occupied bin hypervolume (only divide by num occupied bins)
- min occupied bin hypervolume (only min over occupied bins)
- average overall hypervolume (includes 0 entries for empty bins)

**Comment by JoannaBlatt** [comment]
finished logging all hypervolume data that we have thought about
all logging seems to function and looks appropriate so far
