### ISSUE TITLE
Don't allow multiple fitness functions with plain MAP Elites

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#930]
I've about to commit some code that throws an exception from MAP Elites when you try to run it with multiple fitness functions. Test this out to make sure the exception is thrown, and then to make sure that it is not thrown when just one objective is used. Also look for an exception when there are 0 objectives.

**Comment by TjRaffert** [comment]
Assertion errors were thrown when I had 0 or 2 fitness functions activated with MAPE elites. It also didn't throw any errors when just one was activated one.
