### ISSUE TITLE
Comment GameDataCollector

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#94]
This class is in the edu.southwestern.tasks.ut2004.bots package. It already has some comments, but they are incomplete. Make sure each method has a proper javadoc header comment, and try as best as possible to understand this code. You will probably see many odd Java features in this code that you are not familiar with ... that is good! You should ask me about these features so I can explain what they are and how they work. Understanding some of these advanced features will be important to working with Pogamut.

**Comment by friedmaa** [comment]
commented, not quite sure about a few methods, but I think most are correct
