### ISSUE TITLE
Change Center of Mass a bit too harsh

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#940]
It looks like we have some cases where we have a large shape where part of it flies away, but so many blocks are left behind that the center of mass does not change enough to register as a flying machine. They are not getting the flying machine fitness.

@TjRaffert is going to upload some example shapes that were scored in this way.

**Comment by TjRaffert** [comment]
[REDSTONE_BLOCK at (3,2,4) oriented WEST, REDSTONE_BLOCK at (2,1,3) oriented WEST, REDSTONE_BLOCK at (2,1,2) oriented EAST, REDSTONE_BLOCK at (2,1,1) oriented NORTH, PISTON at (2,1,0) oriented EAST, REDSTONE_BLOCK at (4,3,4) oriented NORTH, STICKY_PISTON at (3,2,3) oriented DOWN, REDSTONE_BLOCK at (3,2,2) oriented EAST, REDSTONE_BLOCK at (3,2,1) oriented WEST, SLIME at (3,2,0) oriented EAST, STICKY_PISTON at (4,3,3) oriented WEST, PISTON at (4,3,2) oriented UP, REDSTONE_BLOCK at (4,3,1) oriented EAST, STICKY_PISTON at (0,2,2) oriented UP, PISTON at (0,2,1) oriented UP, STICKY_PISTON at (0,2,4) oriented DOWN, OBSERVER at (4,0,4) oriented DOWN, SLIME at (4,0,3) oriented UP, STICKY_PISTON at (4,0,2) oriented SOUTH, QUARTZ_BLOCK at (4,0,1) oriented WEST, PISTON at (4,0,0) oriented UP, PISTON at (1,0,4) oriented WEST, QUARTZ_BLOCK at (2,1,4) oriented WEST, REDSTONE_BLOCK at (1,0,3) oriented DOWN, QUARTZ_BLOCK at (1,0,2) oriented SOUTH, PISTON at (1,0,1) oriented EAST, STICKY_PISTON at (1,0,0) oriented WEST, SLIME at (3,3,4) oriented SOUTH, SLIME at (3,3,3) oriented SOUTH, STICKY_PISTON at (3,3,2) oriented SOUTH, SLIME at (3,3,1) oriented DOWN, SLIME at (4,4,4) oriented WEST, SLIME at (4,4,3) oriented NORTH, REDSTONE_BLOCK at (4,4,2) oriented DOWN, PISTON at (4,4,1) oriented NORTH, SLIME at (0,3,3) oriented UP, SLIME at (0,3,2) oriented UP, SLIME at (0,3,1) oriented UP, QUARTZ_BLOCK at (0,3,0) oriented NORTH, STICKY_PISTON at (0,3,4) oriented NORTH, QUARTZ_BLOCK at (1,4,3) oriented WEST, SLIME at (1,4,2) oriented SOUTH, QUARTZ_BLOCK at (1,4,1) oriented NORTH, STICKY_PISTON at (1,4,0) oriented UP, STICKY_PISTON at (1,4,4) oriented WEST, STICKY_PISTON at (4,1,1) oriented SOUTH, SLIME at (4,1,0) oriented DOWN, REDSTONE_BLOCK at (0,0,0) oriented UP, REDSTONE_BLOCK at (0,0,2) oriented EAST, REDSTONE_BLOCK at (0,0,1) oriented SOUTH, QUARTZ_BLOCK at (1,1,4) oriented UP, STICKY_PISTON at (1,1,3) oriented WEST, REDSTONE_BLOCK at (1,1,2) oriented EAST, OBSERVER at (1,1,1) oriented NORTH, SLIME at (2,2,0) oriented SOUTH, OBSERVER at (2,2,3) oriented UP, PISTON at (2,2,2) oriented EAST, STICKY_PISTON at (2,2,1) oriented NORTH, REDSTONE_BLOCK at (0,4,4) oriented DOWN, REDSTONE_BLOCK at (0,4,3) oriented NORTH, STICKY_PISTON at (0,4,2) oriented DOWN, REDSTONE_BLOCK at (0,4,1) oriented DOWN, PISTON at (3,0,4) oriented EAST, STICKY_PISTON at (3,0,3) oriented EAST, SLIME at (3,0,2) oriented WEST, SLIME at (0,4,0) oriented WEST, REDSTONE_BLOCK at (4,1,4) oriented EAST, STICKY_PISTON at (4,1,3) oriented EAST, PISTON at (3,0,1) oriented SOUTH, STICKY_PISTON at (0,1,4) oriented WEST, QUARTZ_BLOCK at (0,1,2) oriented WEST, PISTON at (1,2,1) oriented SOUTH, REDSTONE_BLOCK at (1,2,0) oriented WEST, STICKY_PISTON at (1,2,4) oriented EAST, PISTON at (1,2,3) oriented NORTH, QUARTZ_BLOCK at (2,3,1) oriented SOUTH, OBSERVER at (2,3,4) oriented UP, REDSTONE_BLOCK at (2,3,3) oriented NORTH, STICKY_PISTON at (3,4,1) oriented NORTH, QUARTZ_BLOCK at (3,4,0) oriented UP, OBSERVER at (3,4,4) oriented DOWN, REDSTONE_BLOCK at (3,4,3) oriented DOWN, STICKY_PISTON at (3,4,2) oriented UP, OBSERVER at (2,0,4) oriented UP, OBSERVER at (2,0,3) oriented EAST, STICKY_PISTON at (3,1,4) oriented UP, OBSERVER at (2,0,2) oriented UP, SLIME at (2,0,1) oriented UP, PISTON at (2,0,0) oriented WEST, STICKY_PISTON at (4,2,4) oriented SOUTH, SLIME at (4,2,3) oriented EAST, PISTON at (3,1,2) oriented DOWN, OBSERVER at (3,1,0) oriented SOUTH, SLIME at (4,2,2) oriented NORTH, OBSERVER at (4,2,1) oriented EAST, SLIME at (4,2,0) oriented DOWN, OBSERVER at (1,3,2) oriented EAST, STICKY_PISTON at (1,3,1) oriented WEST, REDSTONE_BLOCK at (1,3,0) oriented EAST, PISTON at (1,3,3) oriented UP, PISTON at (2,4,2) oriented WEST, OBSERVER at (2,4,1) oriented DOWN, REDSTONE_BLOCK at (2,4,0) oriented WEST, SLIME at (2,4,4) oriented EAST, STICKY_PISTON at (2,4,3) oriented SOUTH]

**Comment by TjRaffert** [comment]
This had a score of 2.465075479555977 Fly, 215.0 Accumulate

**Comment by TjRaffert** [comment]
[59159_BC_105BlocksFITNESS_[2.465075479555977, 215.0].txt](https://github.com/schrum2/MM-NEAT/files/11984852/59159_BC_105BlocksFITNESS_.2.465075479555977.215.0.txt)

**Comment by TjRaffert** [comment]
[46544_BC_121BlocksFITNESS_[2.0011713827425455, 225.0].txt](https://github.com/schrum2/MM-NEAT/files/11984854/46544_BC_121BlocksFITNESS_.2.0011713827425455.225.0.txt)

**Comment by TjRaffert** [comment]
[43081_BC_121BlocksFITNESS_[2.888132561149057, 219.0].txt](https://github.com/schrum2/MM-NEAT/files/11984856/43081_BC_121BlocksFITNESS_.2.888132561149057.219.0.txt)

**Comment by TjRaffert** [comment]
[40768_BC_116BlocksFITNESS_[2.586152488426458, 209.0].txt](https://github.com/schrum2/MM-NEAT/files/11984860/40768_BC_116BlocksFITNESS_.2.586152488426458.209.0.txt)

**Comment by schrum2** [comment]
I may have fixed the issue, but a new unit test using the at least some of the additional shapes that Travis provided is needed.

@JoannaBlatt can work on this Monday

**Comment by schrum2** [comment]
@JoannaBlatt made a new unit test, and uncovered some other errors in existing unit tests.

The center of mass fitness now makes a decision about flying machines based solely on the farthest block, and not the distance that the center of mass travels, because some of these new big machines simply leave too many blocks behind to significantly shift the center of mass.
