### ISSUE TITLE
StarCraft AI from Java?

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#95]
Though creating a StarCraft bot directly in C++ certainly has a speed advantage, if you could create bots in Java, it would allow you to draw from all of my previous code. Therefore, you should investigate this:

https://github.com/JNIBWAPI/JNIBWAPI

This code supposedly makes it possible to interface with StarCraft via Java by mapping certain Java commands to C++ commands in the Brood War API. Try creating a stand-alone Java bot that can play StarCraft first, and if it works we will discuss how to integrate that code into the MM-NEAT repository.

**Comment by schrum2** [comment]
Take some time to make a simple as possible standalone bot in Java (there is probably an example bot you can use) that interacts with StarCraft via the BWAPI. See if you can get Java to successfully communicate with the latest version of BWAPI. If it simply doesn't work, and seems like it will be impossible to make work, then we will close this issue. However, it is worth taking some time to figure this out.

**Comment by Squillyprice01** [comment]
I do not believe that we will be able to develop a bot in Java, and even if we did manage to get something working it would be using an outdated version of BWAPI that isn't used in the competition. If we intend to just use SparCraft for some sort of project, we can use the standalone version.

**Comment by schrum2** [comment]
Because of annoying version issues, and general difficulty communicating between Java and C++, I'm closing this issue.
