### ISSUE TITLE
Comment ServerUtil and try running in parallel

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#96]
This is in the edu.southwestern.tasks.ut2004.server package.

This code is supposed to help run multiple instances of UCC.exe (the UT2004 server program) in parallel by assuring that each server uses different port numbers (Computer Systems was an important and relevant class!).

If this code works properly, then it should be possible to evolve UT agents in parallel. Just set the parallelEvaluations:true parameter and set the threads parameter to a positive number (default is 4). These setting changes can be done inside of the batch files in the batch\UT2004 directory.

You can tell if it is working in two ways. One is to watch the Task Manager and make sure that multiple instances of UCC.exe pop up when you run the evolution code (by the way, it is often necessary to forcibly exit these UCC.exe instances using the End Task option in the task manager when you are troubleshooting UT2004 code). The other way to verify that multiple servers are running is to go into the Server Browser of the UT2004 program itself (the user program, not the server program).

**Comment by friedmaa** [comment]
Commenting finished, will attempt running parallel tomorrow.
