### ISSUE TITLE
Thoroughly confirm correct functioning of HybrID

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#98]
I think that HybrID works fine when HyperNEAT creates standard fully connected networks, but I have my doubts. We need some unit tests to make sure it really works. Making this will be tricky. Mainly, we want to confirm that the network generated by a HyperNEAT CPPN before the switch is identical in behavior to the type of network saved after the switch. 

In think that in order to accomplish this, we will need to first refactor the code responsible for the HybrID switch. Specifically, HybrID is currently handled inside of MuLambda within edu.southwestern.evolution.mulambda. Instead, make a HybrIDUtil class inside of a new subpackage of edu.southwestern.evolution, and make the hybrID switch in MuLambda work by calling a static utility method of this new class. Basically, copy the code over into a method that takes the population of CPPNs and returns a population of NEAT networks (this is sort of already done for the special OffsetHybrID variant, but not for regular HybrID).

Once that new method exists (and is maybe also broken up into some additional helper methods) you can make JUnit tests for the new class. Keep in mind that Maven expects JUnit tests to be in a weird place. Although they will be in the same package as the class being testing, the file will exist in a separate file directory. This is why Maven projects split the src into src/main/java and src/test/java. The second directory is where you will find packages that should contain JUnit tests.

**Comment by schrum2** [comment]
Related to this. In our results Google Doc, I recently added this plot of using HybrID switch at 100 generations in Tetris:
![image](https://user-images.githubusercontent.com/8397236/40213768-d335f622-5a1c-11e8-86c3-8f13ce27be44.png)

From this, it is not completely clear that HybrID is not working, but I am very suspicious. The performance does seem to drop and stagnate in my opinion. However, the noisy evaluation of Tetris makes this difficult to confirm. This is why we need unit tests.

**Comment by schrum2** [comment]
Any issue that you work on should receive commentary that day. For example, you should have said something about how you ran the current version of HybrID twice with the same random seed to make sure that each run produced the exact same fitness plots.  This way, when you change the code, you will be able to compare and made sure the behavior is still the same.

**Comment by schrum2** [comment]
Note: After you complete and commit this to dev_tetris, you should submit a pull request to dev. This is easiest done with the old version of GitHub desktop ... ask me to show you how.

**Comment by DevonFulcher** [comment]
Tests passed for regular hybrid and it seems to be fine based on the performance. Dr. Schrum has skepticism about CNNs.
