### ISSUE TITLE
Question about Keep-Away Experiment

### ISSUE THREAD

**Issue by evolvingfridge** [schrum2/MM-NEAT#99]
I tried to search multiple times on google and in code implementation of MM-NEAT in keep-away experiment. My questions are: 
1. Why no one conducted such experiment ?
2. Will such experiment be of interest ?
3. May I ask more question here ? 

Thanks!

**Comment by schrum2** [comment]
I would love to see Keep-away soccer added to MM-NEAT as a possible domain. However, I believe most of the Keep-away code that is used is C++ based (I could be wrong). So, you would either need to find a Java implementation, write one yourself, or define a way for the Java code to communicate with C++ code (maybe via a JNI bridge?). In fact, something like this probably already exists for Keep-away.

If you can find/create a version of Keep-away that can be played by a Java agent, then I can help you interface with it using MM-NEAT. Please ask as many questions as you want, and if you get it working, submit a pull request.

Good luck!

**Comment by evolvingfridge** [comment]
Thank you !

Looking at this [thesis ](http://www.cs.put.poznan.pl/wjaskowski/pub/theses/mkurek_deep_learning_keepaway_soccer.pdf) and [implementation](https://github.com/mkurek/keepaway), seems like I just need to use JNI instead of python (doubt will be that simple). I think it is not only important for consistency to fallow as close as possible existing environment, but also would be interesting trying to train MM-NEAT for RoboCup 2D.

**Comment by evolvingfridge** [comment]
Sorry it took a bit longer then I expected, I was busy working on related project. I am now full time focused on keep-away, as of now starting implementation of MM-NEAT keep-away as a server with protobuf to which C++ existing client will connect. Expecting to start training MM-NEAT within a month may be two.

**Comment by schrum2** [comment]
Happy to hear that you are still interested. The master branch has changed a lot over the summer. Hopefully you can merge the changes without any significant problems with any code you have already changed. Please ask for detailed help if you need it.

It's worth pointing out that this code already contains several examples of the Java side launching other programs to communicate back and forth with. The code can launch Unreal Tournament 2004 servers and then run Java agents in threads that play on the server. There are also some domains that launch Python processes and communicate back and forth with them via the stdin and stdout. 

In light of that, I'm sure there should be a way to set up the necessary communications between MM-NEAT and a Keepaway server. Let me know if you have any problems.

**Comment by schrum2** [comment]
This issue has gone stale. I'm happy to help if you are still interested, but I'm going to close the issue for now. Feel free to re-open if you have questions.
